act_code: '24723'
requisite: Решение Атырауского областного маслихата 25 мая 2005 года № 227-III. Зарегистрировано Департаментом юстиции Атырауской области 23 июня 2005 года № 2433
title:
  rus: Программа профилактики правонарушений и борьбы с преступностью в Атырауской области на 2005-2007 годы
  kaz: Атырау облысында құқық бұзушылықтың алдын алу мен қылмысқа қарсы күрестің 2005-2007 жылдарға арналған бағдарламасы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2005-05-25
approved_by:
- '156000000002'
version_date:
  kaz: 2005-05-25
  rus: 2005-05-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/24723/kaz/25.05.2005
  rus: https://zan.gov.kz/client/#!/doc/24723/rus/25.05.2005
