act_code: '15515'
requisite: Решение Атырауского областного маслихата от 8 декабря 2001 года № 159-II. Зарегистрировано Управлением юстиции Атырауской области 26 февраля 2002 года № 803
title:
  rus: Об  утверждении постановления Атырауского областного акимата от 21 августа 2001 года № 21 по Региональной Программе «Охрана здоровья матери и ребенка в Атырауской области на 2001-2005 годы»
  kaz: Атырау облысы әкімиатының 2001 жылғы 21 тамыздағы № 21–ші «Атырау облысындағы ана мен бала денсаулығын қорғаудың 2001-2001 жылдарға арналған» аймақтық бағдарламасы бойынша қаулысын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2001-12-08
approved_by:
- '156000000002'
version_date:
  kaz: 2001-12-08
  rus: 2001-12-08
source:
  kaz: https://zan.gov.kz/client/#!/doc/15515/kaz/08.12.2001
  rus: https://zan.gov.kz/client/#!/doc/15515/rus/08.12.2001
