act_code: '56806'
requisite: Решение Кызылкогинского районного маслихата Атырауской области от 14 декабря 2010 года № XXIV-5. Зарегистрировано Департаментом юстиции Атырауской области 17 января 2011 года № 4-5-142
title:
  rus: 2011 жылғы бір жолғы талондардың құны мөлшерін белгілеу туралы
  kaz: 2011 жылғы бір жолғы талондардың құны мөлшерін белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-12-14
approved_by:
- '156007000002'
version_date:
  kaz: 2010-12-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/56806/kaz/14.12.2010
