act_code: '46351'
requisite: Атырау облысы Индер ауданы Өрлік селолық округі әкімінің 2009 жылғы 30 мамырдағы № 32 шешімі. Атырау облысының Әділет департаменті Индер ауданының Әділет басқармасында 2009 жылғы 5 маусымда № 4-6-82 тіркелді. Күші жойылды - Атырау облысы Индер ауданы Өрлік селолық округі әкімінің 2010 жылғы 27 қазандағы № 33 шешімімен
title:
  rus: Көшеге атау беру туралы
  kaz: Көшеге атау беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-05-30
approved_by:
- '156008004002'
version_date:
  kaz: 2009-05-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/46351/kaz/30.05.2009
