act_code: '117919'
requisite: Решение Кызылкогинского районного маслихата Атырауской области от 21 декабря 2017 года № XX-1. Зарегистрировано Департаментом юстиции Атырауской области 16 января 2018 года № 4045
title:
  rus: Об утверждении бюджетов сельских округов Кызылкогинского района  на 2018-2020 годы
  kaz: 2018-2020 жылдарға  арналған Қызылқоға ауданының ауылдық округтерінің бюджеттерін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2017-12-21
approved_by:
- '156007000002'
version_date:
  kaz: 2018-04-04
  rus: 2018-04-04
source:
  kaz: https://zan.gov.kz/client/#!/doc/117919/kaz/04.04.2018
  rus: https://zan.gov.kz/client/#!/doc/117919/rus/04.04.2018
caused_by:
  code: '120994'
  requisite: Решение Кызылкогинского районного маслихата Атырауской области от 4 апреля 2018 года № XXIII-1. Зарегистрировано Департаментом юстиции Атырауской области 20 апреля 2018 года № 4136
  title:
    rus: О внесении изменений и дополнения в решение Кызылкогинского районного маслихата от 21 декабря 2017 года № ХХ-1 «Об утверждении бюджетов сельских округов Кызылкогинского района на 2018-2020 годы»
    kaz: Қызылқоға аудандық мәслихатының 2017 жылғы 21 желтоқсандағы № ХХ-1 «2018-2020 жылдарға арналған Қызылқоға ауданының ауылдық округтерінің бюджеттерін бекіту туралы» шешіміне өзгерістер мен толықтыру енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/120994/rus
