act_code: '138483'
requisite: Решение Жылыойского районного маслихата Атырауской области от 25 декабря 2019 года № 42-1. Зарегистрировано Департаментом юстиции Атырауской области 14 января 2020 года № 4575
title:
  rus: О бюджетах города Кульсары, поселка Жана-Каратон, сельских округов Жем, Косчагиль, Кара-Арна, Майкумген и Аккиизтогай на 2020-2022 годы
  kaz: 2020-2022 жылдарға арналған Құлсары қаласының, Жаңа-Қаратон кентінің, Жем, Қосшағыл, Қара-Арна, Майкөмген және Ақкиізтоғай ауылдық округтерінің бюджеттері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-12-25
approved_by:
- '156009000002'
version_date:
  kaz: 2020-12-21
  rus: 2020-12-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/138483/kaz/21.12.2020
  rus: https://zan.gov.kz/client/#!/doc/138483/rus/21.12.2020
caused_by:
  code: '150946'
  requisite: Решение Жылыойского районного маслихата Атырауской области от 21 декабря 2020 года № 55-2. Зарегистрировано Департаментом юстиции Атырауской области 29 декабря 2020 года № 4852
  title:
    rus: О внесении изменений в решение Жылыойского районного маслихата от 25 декабря 2019 года № 42-1 «О бюджетах города Кульсары, поселка Жана-Каратон, сельских округов Жем, Косчагиль, Кара-Арна, Майкумген и Аккиизтогай на 2020-2022 годы»
    kaz: Жылыой аудандық мәслихатының 2019 жылғы 25 желтоқсандағы № 42-1 «2020-2022 жылдарға арналған Құлсары қаласының, Жаңа-Қаратон кентінің, Жем, Қосшағыл, Қара-Арна, Майкөмген және Ақкиізтоғай ауылдық округтерінің бюджеттері туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/150946/rus
