act_code: '211183'
requisite: Решение Курмангазинского районного маслихата Атырауской области от 4 июня 2025 года № 210-VIII
title:
  rus: Об утверждении программы по управлению коммунальными отходами по Курмангазинскому району на 2024-2028 годы
  kaz: Құрманғазы ауданы бойынша коммуналдық қалдықтарды басқару жөніндегі 2024-2028 жылдарға арналған бағдарламаны бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2025-06-04
approved_by:
- '156003000002'
version_date:
  kaz: 2025-06-04
  rus: 2025-06-04
source:
  kaz: https://zan.gov.kz/client/#!/doc/211183/kaz/04.06.2025
  rus: https://zan.gov.kz/client/#!/doc/211183/rus/04.06.2025
