act_code: '161791'
requisite: Решение Атырауского областного маслихата от 13 декабря 2021 года № 108-VII. Зарегистрировано в Министерстве юстиции Республики Казахстан 20 декабря 2021 года № 25831
title:
  rus: Об определении перечня социально значимых автомобильных сообщений по Атырауской области
  kaz: Атырау облысы бойынша әлеуметтік маңызы бар автомобиль қатынастарының тізбесін айқындау туралы
form: РЕШ
type_codes:
- ПРЧ
- РЕШ
approved_on: 2021-12-13
approved_by:
- '156000000002'
version_date:
  kaz: 2025-04-30
  rus: 2025-04-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/161791/kaz/30.04.2025
  rus: https://zan.gov.kz/client/#!/doc/161791/rus/30.04.2025
caused_by:
  code: '209793'
  requisite: Решение Атырауского областного маслихата от 30 апреля 2025 года № 168-VIII. Зарегистрировано в Департаменте юстиции Атырауской области 5 мая 2025 года № 5274-06
  title:
    rus: О внесении изменения и дополнений в решение Атырауского областного маслихата от 13 декабря 2021 года № 108-VII «Об определении перечня социально значимых автомобильных сообщений по Атырауской области»
    kaz: «Атырау облысы бойынша әлеуметтік маңызы бар автомобиль қатынастарының тізбесін айқындау туралы» Атырау облыстық мәслихатының 2021 жылғы 13 желтоқсандағы № 108-VII шешіміне өзгеріс пен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/209793/rus
