act_code: '52467'
requisite: Решение маслихата Макатского района Атырауской области от 14 апреля 2010 года № 204-IV . Зарегистрировано Управлением юстиции Макатского района Атырауской области 14 мая 2010 года № 4-7-116. Утратило силу решением Макатского районного маслихата Атырауской области от 18 июля 2012 года № 57-V
title:
  rus: '"Мақат ауданының құрметті азаматы" атағын беру ережесі туралы'
  kaz: '"Мақат ауданының құрметті азаматы" атағын беру ережесі туралы'
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-04-14
approved_by:
- '156006000002'
version_date:
  kaz: 2010-04-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/52467/kaz/14.04.2010
