act_code: '31695'
requisite: Атырау облысы Индер аудандық мәслихатының 2006 жылғы 9 желтоқсандағы № 207-III шешімі. Атырау облысы Индер аудандық Әділет басқармасында 2006 жылғы 23 желтоқсанда № 4-6-47 болып тіркелді
title:
  rus: Салық ставкаларын белгілеу туралы
  kaz: Салық ставкаларын белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2006-12-09
approved_by:
- '156008000002'
version_date:
  kaz: 2006-12-09
source:
  kaz: https://zan.gov.kz/client/#!/doc/31695/kaz/09.12.2006
