act_code: '107964'
requisite: Решение Атырауского областного маслихата от 28 октября 2016 года № 59-VI. Зарегистрировано Департаментом юстиции Атырауской области 5 декабря 2016 года № 3696. Утратило силу решением Атырауского областного маслихата от 15 марта 2021 года № 27-VІI (вводится в действие после дня его первого официального опубликования)
title:
  rus: Об утверждении Правил содержания животных на территории населенных пунктов Курмангазинского района
  kaz: Құрманғазы ауданының елді мекендерінің аумағында жануарларды асырау Қағидаларын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2016-10-28
approved_by:
- '156000000002'
version_date:
  kaz: 2016-10-28
  rus: 2016-10-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/107964/kaz/28.10.2016
  rus: https://zan.gov.kz/client/#!/doc/107964/rus/28.10.2016
