act_code: '175422'
requisite: Решение Исатайского районного маслихата Атырауской области от 12 декабря 2022 года № 174-VII. Зарегистрировано в Министерстве юстиции Республики Казахстан 14 декабря 2022 года № 31095
title:
  rus: Об утверждении ставок туристского взноса для иностранцев на 2022 год по Исатайскому району
  kaz: Исатай ауданы бойынша шетелдіктер үшін 2022 жылға арналған туристік жарна мөлшерлемелерін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-12-12
approved_by:
- '156005000002'
version_date:
  kaz: 2022-12-12
  rus: 2022-12-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/175422/kaz/12.12.2022
  rus: https://zan.gov.kz/client/#!/doc/175422/rus/12.12.2022
