act_code: '109305'
requisite: Решение акима Еркинкалинского сельского округа города Атырау Атырауской области от 23 декабря 2016 года № 700. Зарегистрировано Департаментом юстиции Атырауской области 20 января 2017 года № 3770
title:
  rus: О присвоении наименовании улицам
  kaz: Көшелерге атау беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2016-12-23
approved_by:
- '156002004001'
version_date:
  kaz: 2016-12-23
  rus: 2016-12-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/109305/kaz/23.12.2016
  rus: https://zan.gov.kz/client/#!/doc/109305/rus/23.12.2016
