act_code: '177445'
requisite: Решение Курмангазинского районного маслихата Атырауской области от 22 декабря 2022 года № 212-VII
title:
  rus: Об утверждении бюджетов сельских округов Курмангазинского района на 2023-2025 годы
  kaz: 2023-2025 жылдарға арналған Құрманғазы ауданының ауылдық округтерінің бюджеттерін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-12-22
approved_by:
- '156003000002'
version_date:
  kaz: 2022-12-22
  rus: 2022-12-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/177445/kaz/22.12.2022
  rus: https://zan.gov.kz/client/#!/doc/177445/rus/22.12.2022
