act_code: '183195'
requisite: Решение Атырауского городского маслихата Атырауской области от 13 июня 2023 года № 38. Зарегистрировано в Департаменте юстиции Атырауской области 21 июня 2023 года № 5039-06
title:
  rus: Об утверждении норм образования и накопления коммунальных отходов по городу Атырау
  kaz: Атырау қаласы бойынша коммуналдық қалдықтардың түзілу және жинақталу нормаларын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2023-06-13
approved_by:
- '156002000002'
version_date:
  kaz: 2023-06-13
  rus: 2023-06-13
source:
  kaz: https://zan.gov.kz/client/#!/doc/183195/kaz/13.06.2023
  rus: https://zan.gov.kz/client/#!/doc/183195/rus/13.06.2023
