act_code: '117640'
requisite: Решение Исатайского районного маслихата Атырауской области от 14 декабря 2017 года № 120-VI. Зарегистрировано Департаментом юстиции Атырауской области 8 января 2018 года № 4032
title:
  rus: О районном бюджете на 2018-2020 годы
  kaz: 2018–2020 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2017-12-14
approved_by:
- '156005000002'
version_date:
  kaz: 2018-09-13
  rus: 2018-09-13
source:
  kaz: https://zan.gov.kz/client/#!/doc/117640/kaz/13.09.2018
  rus: https://zan.gov.kz/client/#!/doc/117640/rus/13.09.2018
caused_by:
  code: '124938'
  requisite: Решение Исатайского районного маслихата Атырауской области от 13 сентября 2018 года № 175-VI. Зарегистрировано Департаментом юстиции Атырауской области 28 сентября 2018 года № 4244
  title:
    rus: О внесении изменений и дополнений в решение Исатайского районного маслихата от 14 декабря 2017 года № 120-VI «О районном бюджете на 2018-2020 годы»
    kaz: Исатай аудандық мәслихатының 2017 жылғы 14 желтоқсандағы № 120-VI «2018-2020 жылдарға арналған аудандық бюджет туралы» шешіміне өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/124938/rus
