act_code: '23748'
requisite: Решение Атырауского областного маслихата 8 декабря 2004 года № 169-III. Зарегистрировано Департаментом юстиции Атырауской области 18 января 2005 года № 2272. Не подлежит гос. регистрации - письмо ДЮ Атырауской области № 3-2185/06 от 23 мая 2006 года. Утратило силу - письмом Атырауского областного маслихата от 3 октября 2011 года 275/1711/-МШ
title:
  rus: О региональной программе укрепления материально-технической базы общеобразовательных школ Атырауской области на 2005-2007 годы
  kaz: Атырау облысы жалпы білім беретін мектептерінің материалдық-техникалық базасын нығайтудың 2005-2007 жылдарға арналған өңірлік бағдарламасы туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2004-12-08
approved_by:
- '156000000002'
version_date:
  kaz: 2004-12-08
  rus: 2004-12-08
source:
  kaz: https://zan.gov.kz/client/#!/doc/23748/kaz/08.12.2004
  rus: https://zan.gov.kz/client/#!/doc/23748/rus/08.12.2004
