act_code: '17337'
requisite: Атырау қалалық Мәслихатының 2003 жылғы 27 қыркүйектегі № 5 шешімі. Атырау облыстық Әділет басқармасында 2003 жылғы 30 қазанда № 1688 тіркелді. Күші жойылды - Атырау облысы Атырау қалалық мәслихатының 2008 жылғы 15 желтоқсандағы № 104а шешімімен
title:
  rus: Атырау қалалық Мәслихатының регламентiн бекiту туралы
  kaz: Атырау қалалық Мәслихатының регламентiн бекiту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2003-09-26
approved_by:
- '156002000002'
version_date:
  kaz: 2003-09-26
source:
  kaz: https://zan.gov.kz/client/#!/doc/17337/kaz/26.09.2003
