act_code: '158582'
requisite: Решение Кызылкогинского районного маслихата Атырауской области от 8 сентября 2021 года № 7-2
title:
  rus: Об утверждении регламента собраний местного сообщества сельских округов по Кызылкогинскому району
  kaz: Қызылқоға ауданы бойынша ауылдық округтердегі жергілікті қоғамдастық жиналысының регламентін бекіту туралы
form: РЕШ
type_codes:
- РЕГЛ
- РЕШ
approved_on: 2021-09-08
approved_by:
- '156007000002'
version_date:
  kaz: 2021-09-08
  rus: 2021-09-08
source:
  kaz: https://zan.gov.kz/client/#!/doc/158582/kaz/08.09.2021
  rus: https://zan.gov.kz/client/#!/doc/158582/rus/08.09.2021
