act_code: '62731'
requisite: Решение Индерского районного маслихата Атырауской области от 15 декабря 2011 года № 335-IV. Зарегистрировано Департаментом юстиции Атырауской области 12 января 2012 года № 4-6-124. Утратило силу - решением Индерского районного маслихата Атырауской области от 28 марта 2013 года № 87-V
title:
  rus: О районном бюджете на 2012-2014 годы
  kaz: 2012-2014 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2011-12-15
approved_by:
- '156008000002'
version_date:
  kaz: 2012-10-15
  rus: 2012-10-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/62731/kaz/15.10.2012
  rus: https://zan.gov.kz/client/#!/doc/62731/rus/15.10.2012
caused_by:
  code: '68187'
  requisite: Решение Индерского районного маслихата Атырауской области от 15 октября 2012 года № 49-V. Зарегистрировано Департаментом юстиции Атырауской области 25 октября 2012 года № 2631. Утратило силу - решением Индерского районного маслихата Атырауской области от 28 марта 2013 года № 87-V
  title:
    rus: О внесении изменений в решение районного маслихата от 15 декабря 2011 года № 335-IV "О районном бюджете на 2012-2014 годы"
    kaz: Аудандық мәслихаттың 2011 жылғы 15 желтоқсандағы № 335-IV "2012-2014 жылдарға арналған аудандық бюджет туралы" шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/68187/rus
