act_code: '62731'
requisite: Решение Индерского районного маслихата Атырауской области от 15 декабря 2011 года № 335-IV. Зарегистрировано Департаментом юстиции Атырауской области 12 января 2012 года № 4-6-124. Утратило силу - решением Индерского районного маслихата Атырауской области от 28 марта 2013 года № 87-V
title:
  rus: О районном бюджете на 2012-2014 годы
  kaz: 2012-2014 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2011-12-15
approved_by:
- '156008000002'
version_date:
  kaz: 2011-12-15
  rus: 2011-12-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/62731/kaz/15.12.2011
  rus: https://zan.gov.kz/client/#!/doc/62731/rus/15.12.2011
