act_code: '31710'
requisite: Атырау облысы Жылыой ауданы әкімінің 2006 жылғы 4 желтоқсандағы № 21 шешімі. Жылыой аудандық Әділет басқармасында 2006 жылғы 15 желтоқсанда № 4-2-56 болып тіркелді
title:
  rus: 2007 жылы әскери оқу орындарына үміткерлерді іріктеу туралы
  kaz: 2007 жылы әскери оқу орындарынаүміткерлерді іріктеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2006-12-04
approved_by:
- '156009000003'
version_date:
  kaz: 2006-12-04
source:
  kaz: https://zan.gov.kz/client/#!/doc/31710/kaz/04.12.2006
