act_code: '418'
requisite: Решение акима Атырауской области от 15 января 1998 года № 570. Зарегистрировано Департаментом юстиции Атырауской области от 9 марта 1998 года № 4
title:
  rus: О ходе выполнения в Жылыойском и Макатском районах Указа Президента РК от 6 марта 1997 года № 3398 «О мерах по усилению государственной поддержки и активизации развития малого предпринимательства» и решения акима области по реализации Указа
  kaz: ҚР Президентінің 1997 жылғы 6 наурыздағы № 3398 «Шағын кәсіпкерліктің дамуын арттыру және мемлекеттік қолдауды күшейту шаралары туралы» жарлығының және облыс әкімінің осы жарлықты іске асыру туралы шешімінің Жылыой және Мақат аудандарындағы орындалу барысы туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 1998-01-15
approved_by:
- '156000000003'
version_date:
  kaz: 1998-01-15
  rus: 1998-01-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/418/kaz/15.01.1998
  rus: https://zan.gov.kz/client/#!/doc/418/rus/15.01.1998
