act_code: '49011'
requisite: Атырау облысы Индер аудандық мәслихатының 2009 жылғы 27 қазандағы № 179-ІV шешімі. Атырау облысының Әділет департаменті Индер ауданының Әділет басқармасында 2009 жылғы 26 қарашада № 4-6-90 тіркелді. Күші жойылды - Индер аудандық мәслихатының 2010 жылғы 25 маусымдағы № 230-IV шешімімен
title:
  rus: Ұлы Отан соғысының қатысушылары мен мүгедектерінің пәтерлері мен тұрғын үйлеріне жөндеу жұмыстарын жүргізу үшін қаржы бөлу және төлеу қағидасы туралы
  kaz: Ұлы Отан соғысының қатысушылары мен мүгедектерінің пәтерлері мен тұрғын үйлеріне жөндеу жұмыстарын жүргізу үшін қаржы бөлу және төлеу қағидасы туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-10-27
approved_by:
- '156008000002'
version_date:
  kaz: 2009-10-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/49011/kaz/27.10.2009
