act_code: '222816'
requisite: Решение акима Жамбульского сельского округа Кызылкогинского района Атырауской области от 5 марта 2026 года № 6. Утратило силу решением акима Жамбульского сельского округа Кызылкогинского района Атырауской области от 13 апреля 2026 года № 11 (вводится в действие со дня его первого официального опубликования)
title:
  rus: О введении ограничительных мероприятии
  kaz: Шектеу іс–шараларын белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2026-03-05
approved_by:
- '156007007002'
version_date:
  kaz: 2026-03-05
  rus: 2026-03-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/222816/kaz/05.03.2026
  rus: https://zan.gov.kz/client/#!/doc/222816/rus/05.03.2026
