act_code: '88953'
requisite: Решение Атырауского областного маслихата Атырауской области от 13 марта 2015 года № 364-V. Зарегистрировано Департаментом юстиции Атырауской области 16 апреля 2015 года № 3178
title:
  rus: Об утверждении Правил выпаса сельскохозяйственных животных на территории Атырауской области
  kaz: Атырау облысының аумағында ауыл шаруашылығы жануарларын жаюдың Қағидаларын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-03-13
approved_by:
- '156000000002'
version_date:
  kaz: 2020-10-30
  rus: 2020-10-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/88953/kaz/30.10.2020
  rus: https://zan.gov.kz/client/#!/doc/88953/rus/30.10.2020
caused_by:
  code: '148075'
  requisite: Решение Атырауского областного маслихата от 30 октября 2020 года № 485-VI. Зарегистрировано Департаментом юстиции Атырауской области 30 октября 2020 года № 4779
  title:
    rus: О внесении изменений и дополнений в решение Атырауского областного маслихата от 13 марта 2015 года № 364-V «Об утверждении Правил содержания и выгула собак и кошек, Правил отлова и уничтожения бродячих собак и кошек в населенных пунктах Атырауской области»
    kaz: Атырау облыстық мәслихатының 2015 жылғы 13 наурыздағы № 364-V «Атырау облысының елді мекендерінде иттер мен мысықтарды асырау және серуендету Қағидасын, қаңғыбас иттер мен мысықтарды аулау және жою Қағидасын бекіту туралы» шешіміне өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/148075/rus
