act_code: '12558'
requisite: Атырау облысы әкiмiнiң 2002 жылғы 24 мамырда № 160 шешiмi. Атырау облысының Әділет басқармасында 2002 жылғы 26 маусымда № 1022 болып тіркелді
title:
  rus: Облыс азық-түлiк базарларының байқауын өткiзу туралы
  kaz: Облыс азық-түлiк базарларының байқауын өткiзу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2002-05-23
approved_by:
- '156000000003'
version_date:
  kaz: 2002-05-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/12558/kaz/23.05.2002
