act_code: '50061'
requisite: Исатай аудандық мәслихатының 2009 жылғы 23 желтоқсандағы № 144-IV шешімі. Исатай аудандық Әділет басқармасында 2010 жылғы 15 қаңтарда № 4-4-149 тіркелді. Күші жойылды - Исатай аудандық мәслихатының 2011 жылғы 25 қаңтардағы № 247-IV шешімімен
title:
  rus: Исатай ауданының 2010-2012 жылдарға арналған аудандық бюджеті туралы
  kaz: Исатай ауданының 2010-2012 жылдарға арналған аудандық бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-12-23
approved_by:
- '156005000002'
version_date:
  kaz: 2010-02-04
source:
  kaz: https://zan.gov.kz/client/#!/doc/50061/kaz/04.02.2010
caused_by:
  code: '51237'
  requisite: Атырау облысы Исатай аудандық мәслихатының 2010 жылғы 4 ақпандағы № 164-IV шешімі. Исатай аудандық Әділет басқармасында 2010 жылғы 16 наурызда № 4-4-156 тіркелді. Күші жойылды - Исатай аудандық мәслихатының 2011 жылғы 25 қаңтардағы № 247-IV шешімімен
  title:
    rus: Аудандық мәслихаттың 2009 жылғы 23 желтоқсандағы N 144-IV "Исатай ауданының 2010-2012 жылдарға арналған аудандық бюджеті туралы" шешіміне өзгерістер мен толықтырулар енгізу туралы
    kaz: Аудандық мәслихаттың 2009 жылғы 23 желтоқсандағы N 144-IV "Исатай ауданының 2010-2012 жылдарға арналған аудандық бюджеті туралы" шешіміне өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/51237/rus
