act_code: '85954'
requisite: Решение от 25.12.2014 №26-2, Маслихат Жылыойского района. Утратило силу решением  Жылыойского районного маслихата Атырауской области от 29 февраля 2016 года  № 37-2.
title:
  rus: О районном бюджете на 2015-2017 годы
  kaz: 2015 - 2017 жылдарға  арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2014-12-25
approved_by:
- '156009000002'
version_date:
  kaz: 2015-09-18
  rus: 2015-09-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/85954/kaz/18.09.2015
  rus: https://zan.gov.kz/client/#!/doc/85954/rus/18.09.2015
caused_by:
  code: '94145'
  requisite: Решение от 18.09.2015 №32-1, Маслихат Жылыойского района. Утратило силу решением  Жылыойского районного маслихата Атырауской области от 29 февраля 2016 года  № 37-2.
  title:
    rus: О внесении изменений в решение районного маслихата   от  25 декабря 2014 года  № 26-2  «О районном  бюджете  на  2015 - 2017 годы »
    kaz: Аудандық  мәслихаттың   2014  жылғы 25 желтоқсандағы   № 26-2 «2015-2017 жылдарға арналған аудандық бюджет туралы» шешіміне өзгерістер  енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/94145/rus
