act_code: '71220'
requisite: Решение Махамбетского районного маслихата Атырауской области от 8 февраля 2013 года № 68. Зарегистрировано Департаментом юстиции Атырауской области 27 февраля 2013 года № 2699. Утратило силу решением Махамбетского районного маслихата Атырауской области от 30 мая 2014 года № 208
title:
  rus: Об определении размера и правил оказания жилищной помощи малообеспеченным семьям (гражданам), проживающим в Махамбетском районе
  kaz: Махамбет ауданында тұратын аз қамтамасыз етілген отбасыларға (азаматтарға)  тұрғын үй көмегін көрсетудің мөлшері мен қағидасын айқындау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2013-02-08
approved_by:
- '156004000002'
version_date:
  kaz: 2013-02-08
  rus: 2013-02-08
source:
  kaz: https://zan.gov.kz/client/#!/doc/71220/kaz/08.02.2013
  rus: https://zan.gov.kz/client/#!/doc/71220/rus/08.02.2013
