act_code: '176599'
requisite: Решение Исатайского районного маслихата Атырауской области от 15 декабря 2022 года № 181-VII
title:
  rus: Об утверждении бюджетов сельских округов Исатайского района на 2023-2025 годы
  kaz: 2023-2025 жылдарға арналған Исатай ауданының ауылдық округтерінің бюджеттерін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-12-15
approved_by:
- '156005000002'
version_date:
  kaz: 2022-12-15
  rus: 2022-12-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/176599/kaz/15.12.2022
  rus: https://zan.gov.kz/client/#!/doc/176599/rus/15.12.2022
