act_code: '15172'
requisite: II сайланған Атырау облыстық мәслихаты XXIII сессиясының 2003 жылғы 7 наурыздағы № 284-II шешімі. Атырау облысының Әділет басқармасында 2003  жылғы 26 наурызда № 1362 болып тіркелді
title:
  rus: Атырау облысындағы телефон байланысы мен телехабарларды тарату жұмыстарының бүгінгі жағдайы және оларды болашақта жақсартудың шаралары туралы
  kaz: Атырау облысындағы телефон байланысы мен телехабарларды тарату жұмыстарының бүгінгі жағдайы және оларды болашақта жақсартудың шаралары туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2003-03-07
approved_by:
- '156000000002'
version_date:
  kaz: 2003-03-07
source:
  kaz: https://zan.gov.kz/client/#!/doc/15172/kaz/07.03.2003
