act_code: '56686'
requisite: Решение Жылыойского районного маслихата Атырауской области от 7 декабря 2010 года № 24-I. Зарегистрировано Департаментом юстиции Атырауской области 10 января 2011 года № 4-2-150. Утратило силу - решением Жылыойского районного маслихата Атырауской области от 12 декабря 2011 года № 31-3
title:
  rus: О районном бюджете на 2011-2013 годы
  kaz: 2011-2013 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-12-07
approved_by:
- '156009000002'
version_date:
  kaz: 2011-03-18
  rus: 2011-03-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/56686/kaz/18.03.2011
  rus: https://zan.gov.kz/client/#!/doc/56686/rus/18.03.2011
caused_by:
  code: '57959'
  requisite: Решение Жылыойского районного маслихата Атырауского области от 18 марта 2011 года № 27-1. Зарегистрировано Департаментом юстиции Атырауской области 31 марта 2011 года № 4-2-153. Утратило силу решением Жылыойского районного маслихата Атырауской области 12 декабря 2011 года № 31-3
  title:
    rus: О внесении изменений в решение районного маслихата от 7 декабря 2010 года № 24-1 "О районном бюджете на 2011-2013 годы"
    kaz: Аудандық мәслихаттың 2010 жылғы 7 желтоқсандағы № 24-1 "2011-2013 жылдарға арналған аудандық бюджет туралы" шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/57959/rus
