act_code: '162874'
requisite: Решение Исатайского районного маслихата Атырауской области от 30 декабря 2021 года № 104-VII
title:
  rus: Об утверждении бюджетов сельских округов Исатайского района на 2022-2024 годы
  kaz: 2022-2024 жылдарға арналған Исатай ауданының ауылдық округтерінің бюджеттерін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-12-30
approved_by:
- '156005000002'
version_date:
  kaz: 2022-04-14
  rus: 2022-04-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/162874/kaz/14.04.2022
  rus: https://zan.gov.kz/client/#!/doc/162874/rus/14.04.2022
caused_by:
  code: '166582'
  requisite: Решение Исатайского районного маслихата Атырауской области от 14 апреля 2022 года № 126-VII
  title:
    rus: О внесении изменений в решение районного маслихата от 30 декабря 2021 года № 104-VІІ «Об утверждении бюджетов сельских округов Исатайского района на 2022-2024 годы»
    kaz: Исатай ауданы мәслихаттың 2021 жылғы 30 желтоқсандағы № 104-VІІ «2022-2024 жылдарға арналған Исатай ауданының ауылдық округтерінің бюджеттерін бекіту туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/166582/rus
