act_code: '221615'
requisite: Решение акима Боденевского сельского округа Индерского района Атырауской области от 23 января 2026 года № 4
title:
  rus: О переименовании улицы «Кеңес» в селе Бодене Индерского района
  kaz: Индер ауданы Бөдене ауылындағы «Кеңес» көшесінің атауын қайта атау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2026-01-23
approved_by:
- '156008006002'
version_date:
  kaz: 2026-01-23
  rus: 2026-01-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/221615/kaz/23.01.2026
  rus: https://zan.gov.kz/client/#!/doc/221615/rus/23.01.2026
