act_code: '148053'
requisite: Решение акима Миялинского сельского округа Кызылкогинского района Атырауской области от 29 октября 2020 года № 226. Зарегистрировано Департаментом юстиции Атырауской области 30 октября 2020 года № 4776
title:
  rus: Об утрате силы решения акима Миялинского сельского округа от 2 июля 2020 года № 98 «Об установлении ограничительных мероприятий»
  kaz: Миялы ауылдық округі әкімінің 2020 жылғы 2 шілдедегі № 98 «Шектеу іс-шараларын белгілеу туралы» шешімінің күшін жою туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-10-29
approved_by:
- '156007010002'
version_date:
  kaz: 2020-10-29
  rus: 2020-10-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/148053/kaz/29.10.2020
  rus: https://zan.gov.kz/client/#!/doc/148053/rus/29.10.2020
