act_code: '53889'
requisite: Атырау облысы Индер ауданы әкімдігінің 2010 жылғы 27 шілдедегі № 153 қаулысы. Атырау облысының Әділет департаменті Индер ауданының Әділет басқармасында 2010 жылғы 10 тамызда № 4-6-104 тіркелді. Күші жойылды - Индер ауданы әкімдігінің 2013 жылғы 7 наурыздағы № 90 қаулысымен
title:
  rus: Ауданның әлеуметтік жағынан дәрменсіз топтарына біржолғы әлеуметтік төлем төлеу туралы
  kaz: Ауданның әлеуметтік жағынан дәрменсіз топтарына біржолғы әлеуметтік төлем төлеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-07-27
approved_by:
- '156008000001'
version_date:
  kaz: 2010-07-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/53889/kaz/27.07.2010
