act_code: '1653'
requisite: Решение XXI сессии Атырауского областного маслихата I созыва от 10 апреля 1998 года № 232-I. Зарегистрировано департаментом юстиции Атырауской области 30 июня 1998 года № 22
title:
  rus: О выполнении решения XIV сессии областного Маслихата от 30 декабря 1996 года «О ходе выполнения в области Указа Президента Республики Казахстан», имеющего силу Закона «О медицинском страховании граждан»
  kaz: Облыстық Мәслихаттың 1996 жылғы 30 желтоқсандағы XIV сессиясының «Қазақстан Республикасы Президентінің Заң күші бар» «Азаматтарды міндетті медициналық сақтандыру туралы» Жарлығының орындалу барысы жөніндегі» шешімінің іске асу жәйі туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 1998-04-09
approved_by:
- '156000000002'
version_date:
  kaz: 1998-04-09
  rus: 1998-04-09
source:
  kaz: https://zan.gov.kz/client/#!/doc/1653/kaz/09.04.1998
  rus: https://zan.gov.kz/client/#!/doc/1653/rus/09.04.1998
