act_code: '46535'
requisite: Атырау облысы Исатай ауданы Жанбай ауылдық округі әкімінің 2009 жылғы 20 мамырдағы № 25 шешімі. Атырау облысының Әділет департаменті Исатай ауданының Әділет басқармасында 2009 жылғы 19 маусымда № 4-4-140 болып тіркелді
title:
  rus: Жаңа көшеге атау беру туралы
  kaz: Жаңа көшеге атау беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-05-20
approved_by:
- '156005003002'
version_date:
  kaz: 2009-05-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/46535/kaz/20.05.2009
