act_code: '46228'
requisite: Атырау облысы Индер аудандық мәслихатының 2009 жылғы 24 сәуірдегі № 141-ІV шешімі. Атырау облысының Әділет департаменті Индер ауданының Әділет басқармасында 2009 жылғы 2 маусымда № 4-6-81 тіркелді. Күші жойылды - Индер аудандық мәслихатының 2011 жылғы 19 шілдедегі № 311-IV шешімімен
title:
  rus: Индер ауданы инфрақұрылымы аумағын көріктендіру, Индербор кенті және басқа елді мекендерде тазалықты сақтау Ережесі туралы
  kaz: Индер ауданы инфрақұрылымы аумағын көріктендіру, Индербор кенті және басқа елді мекендерде тазалықты сақтау Ережесі туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-04-24
approved_by:
- '156008000002'
version_date:
  kaz: 2009-04-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/46228/kaz/24.04.2009
