act_code: '138309'
requisite: Решение Атырауского городского маслихата Атырауской области от 24 декабря 2019 года № 453. Зарегистрировано Департаментом юстиции Атырауской области 10 января 2020 года № 4571
title:
  rus: О бюджете сельских округов относящихся к городу Атырау на 2020-2022 годы
  kaz: 2020-2022 жылдарға арналған Атырау қаласына қарасты ауылдық округтер бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-12-24
approved_by:
- '156002000002'
version_date:
  kaz: 2019-12-24
  rus: 2019-12-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/138309/kaz/24.12.2019
  rus: https://zan.gov.kz/client/#!/doc/138309/rus/24.12.2019
