act_code: '50374'
requisite: Атырау облысы Құрманғазы аудандық мәслихатының 2009 жылғы 23 желтоқсандағы № 235-ХХV шешімі. Атырау облысы Әділет департаменті Құрманғазы ауданының Әділет басқармасында 2010 жылғы 27 қаңтарда № 4-8-180 тіркелді. Күші жойылды - Құрманғазы аудандық мәслихатының 2012 жылғы 8 мамырдағы № 42-V шешімімен
title:
  rus: 2010 жылға дара кәсіпкерлер мен заңды тұлғаларға ойын бизнесі саласында көрсеткен қызметіне тіркелген салық ставкаларының мөлшері туралы
  kaz: 2010 жылға дара кәсіпкерлер мен заңды тұлғаларға ойын бизнесі саласында көрсеткен қызметіне тіркелген салық ставкаларының мөлшері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-12-23
approved_by:
- '156003000002'
version_date:
  kaz: 2009-12-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/50374/kaz/23.12.2009
