act_code: '15767'
requisite: ХХІІI сессиясында қабылданған ІI сайланған Атырау облыстық мәслихатының 2003 жылғы 7 наурыздағы № 286-ІІ шешiмi. Атырау облысының Әділет басқармасында 2003 жылғы 20 наурызда № 1357 тіркелді
title:
  rus: Атырау облысында құқық бұзушылықтардың алдын алу мен қылмысқа қарсы күрестің 2003-2004 жылдарға арналған бағдарламасы туралы
  kaz: Атырау облысында құқық бұзушылықтардың алдын алу мен қылмысқа қарсы күрестің 2003-2004 жылдарға арналған бағдарламасы туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2003-03-07
approved_by:
- '156000000002'
version_date:
  kaz: 2003-03-07
source:
  kaz: https://zan.gov.kz/client/#!/doc/15767/kaz/07.03.2003
