act_code: '37781'
requisite: Атырау облысы Махамбет аудандық әкімінің 2007 жылғы 28 желтоқсандағы № 20 шешімі. Атырау облысының Әділет департаментінде 2008 жылғы 23 қаңтарда № 4-3-81 болып тіркелді
title:
  rus: 1991 жылы туылған азаматтарды шақыру учаскелеріне тіркеуді жүргізу туралы
  kaz: 1991 жылы туылған азаматтарды шақыру учаскелеріне тіркеуді жүргізу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2007-12-28
approved_by:
- '156004000003'
version_date:
  kaz: 2007-12-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/37781/kaz/28.12.2007
