act_code: '48359'
requisite: Атырау облысы Құрманғазы ауданы Асан селолық округі әкімінің 2009 жылғы 14 қазандағы № 5 шешімі. Атырау облысы Әділет департаменті Құрманғазы ауданының Әділет басқармасында 2009 жылғы 28 қазанда № 4-8-159 болып тіркелді. Күші жойылды - Атырау облысы Құрманғазы ауданы Асан селолық округі әкімінің 2010 жылғы 22 қазандағы № 77 шешімімен
title:
  rus: Асан селолық округіне қарасты Асан және Үштаған ауылдарындағы атауы жоқ көшелерге атау беру туралы
  kaz: Асан селолық округіне қарасты Асан және Үштаған ауылдарындағы атауы жоқ көшелерге атау беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-10-14
approved_by:
- '156003018002'
version_date:
  kaz: 2009-10-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/48359/kaz/14.10.2009
