act_code: '20965'
requisite: Атырау облысы Махамбет аудандық мәслихатының 2004 жылғы 15 шілдедегі № 92 шешімі. Атырау облысының Әділет департаментінде 2004 жылғы 13 тамызда № 2107 болып тіркелді
title:
  rus: Білім беру ұйымдарында күндіз оқитын және тәрбиеленетін оқушыларға қоғамдық көлікте (таксиден басқа) жеңілдікпен жүру ережесін бекіту туралы
  kaz: Білім беру ұйымдарында күндіз оқитын және тәрбиеленетін оқушыларға қоғамдық көлікте (таксиден басқа) жеңілдікпен жүру ережесін бекіту туралы
form: РЕШ
type_codes:
- ПОЛ
- РЕШ
approved_on: 2004-07-14
approved_by:
- '156004000002'
version_date:
  kaz: 2004-07-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/20965/kaz/14.07.2004
