act_code: '95808'
requisite: Решение от 28.10.2015 №33-5, Маслихат Жылыойского района. Утратило силу решением Жылыойского районного маслихата Атырауской области от 24.12.2015 № 35-15.
title:
  rus: Об  установлении   специалистам в области социального обеспечения,образования и культуры, являющимся гражданскими служащими и работающим в сельской  местности  повышенные должностные оклады  и  тарифные ставки
  kaz: Азаматтық қызметші болып табылатын және  ауылдық  жерде  жұмыс  істейтін әлеуметтік қамсыздандыру, білім беру және мәдениет саласындағы мамандарға жоғарылатылған лауазымдық айлықақылар мен тарифтік ставкалар белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-10-28
approved_by:
- '156009000002'
version_date:
  kaz: 2015-10-28
  rus: 2015-10-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/95808/kaz/28.10.2015
  rus: https://zan.gov.kz/client/#!/doc/95808/rus/28.10.2015
