act_code: '56491'
requisite: Атырау облысы Индер ауданы әкімінің 2010 жылғы 27 желтоқсандағы № 110 шешімі. Атырау облысының Әділет департаменті Индер ауданының Әділет басқармасында 2010 жылғы 31 желтоқсанда № 4-6-111 тіркелді
title:
  rus: 1994 жылы туған Индер ауданының азаматтарын 2011 жылдың қаңтар-наурыз айларында шақыру пунктінде тіркеуді өткізу туралы
  kaz: 1994 жылы туған Индер ауданының азаматтарын 2011 жылдың қаңтар-наурыз айларында шақыру пунктінде тіркеуді өткізу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-12-27
approved_by:
- '156008000003'
version_date:
  kaz: 2010-12-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/56491/kaz/27.12.2010
