act_code: '37788'
requisite: Атырау облысы Қызылқоға ауданы әкімінің 2007 жылғы 24 желтоқсандағы № 43 шешімі. Атырау облысы Әділет департаменті Қызылқоға ауданының Әділет басқармасында 2008 жылғы 3 қаңтарда № 4-5-87 болып тіркелді
title:
  rus: 1991 жылы туылған азаматтарды аудандық қорғаныс істері жөніндегі бөлімнің шақыру пунктіне тіркеу өткізу туралы
  kaz: 1991 жылы туылған азаматтарды аудандық қорғаныс істері жөніндегі бөлімнің шақыру пунктіне тіркеу өткізу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2007-12-24
approved_by:
- '156007000003'
version_date:
  kaz: 2007-12-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/37788/kaz/24.12.2007
