act_code: '12483'
requisite: Екінші сайланған Атырау облыстық мәслихаты кезектен тыс ХVI сессиясының 2002 жылғы 6 ақпандағы № 183-II шешімі. Атырау облысының Әділет басқармасында 2002 жылғы 21 наурызда № 840 болып тіркелді
title:
  rus: Атырау облысының 2010 жылға дейiнгi Стратегиялық даму жоспары туралы
  kaz: Атырау облысының 2010 жылға дейiнгi Стратегиялық даму жоспары туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2002-02-06
approved_by:
- '156000000002'
version_date:
  kaz: 2002-02-06
source:
  kaz: https://zan.gov.kz/client/#!/doc/12483/kaz/06.02.2002
