act_code: '85984'
requisite: Решение от 24.12.2014 №228-V, Маслихат Исатайского района. Утратило силу решением маслихата Исатайского района Атырауской области от 13 января 2016 года № 308-V.
title:
  rus: О  районном бюджете на 2015-2017 годы
  kaz: 2015-2017  жылдарға  арналған аудандық  бюджет  туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2014-12-24
approved_by:
- '156005000002'
version_date:
  kaz: 2014-12-24
  rus: 2014-12-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/85984/kaz/24.12.2014
  rus: https://zan.gov.kz/client/#!/doc/85984/rus/24.12.2014
