act_code: '12233'
requisite: Решение акима Атырауской области от 28 марта 2002 года № 411. Зарегистрированo Управлением юстиции Атырауской области 18 апреля 2002 года за № 917
title:
  rus: Об организации отдыха, оздоровления, занятости детей и подростков в летний период 2002 года
  kaz: Балалар мен жасөспірімдердің 2002 жылғы жазғы демалысын, сауықтырылуын және жұмыспен қамтылуын ұйымдастыру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2002-03-28
approved_by:
- '156000000003'
version_date:
  kaz: 2002-03-28
  rus: 2002-03-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/12233/kaz/28.03.2002
  rus: https://zan.gov.kz/client/#!/doc/12233/rus/28.03.2002
