act_code: '187701'
requisite: Решение Атырауского городского маслихата Атырауской области от 27 сентября 2023 года № 56
title:
  rus: Об утверждении плана по управлению пастбищами и их использованию по городу Атырау на 2023-2024 годы
  kaz: Атырау қаласы бойынша 2023–2024 жылдарға арналған жайылымдарды басқару және оларды пайдалану жоспарын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2023-09-27
approved_by:
- '156002000002'
version_date:
  kaz: 2023-09-27
  rus: 2023-09-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/187701/kaz/27.09.2023
  rus: https://zan.gov.kz/client/#!/doc/187701/rus/27.09.2023
