act_code: '113048'
requisite: Решение Исатайского районного маслихата Атырауской области от 6 июня 2017 года № 94-VI. Зарегистрировано Департаментом юстиции Атырауской области 20 июня 2017 года № 3897. Утратило силу решением Исатайского районного маслихата Атырауской области от 5 октября 2023 года № 46-VІII (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении правил оказания социальной помощи, установления размеров и определения перечня отдельных категорий нуждающихся граждан
  kaz: Әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың қағидаларын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2017-06-06
approved_by:
- '156005000002'
version_date:
  kaz: 2022-07-28
  rus: 2022-07-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/113048/kaz/28.07.2022
  rus: https://zan.gov.kz/client/#!/doc/113048/rus/28.07.2022
caused_by:
  code: '170533'
  requisite: Решение Исатайского районного маслихата Атырауской области от 28 июля 2022 года № 147-VII. Зарегистрировано в Министерстве юстиции Республики Казахстан 10 августа 2022 года № 29078. Утратило силу решением Исатайского районного маслихата Атырауской области от 5 октября 2023 года № 46-VІII (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
  title:
    rus: О внесении изменения в решение Исатайского районного маслихата от 6 июня 2017 года № 94-VІ «Об утверждении Правил оказания социальной помощи, установления размеров и определения перечня отдельных категорий нуждающихся граждан»
    kaz: Исатай аудандық мәслихатының 2017 жылғы 6 маусымдағы № 94-VІ «Әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың қағидаларын бекіту туралы» шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/170533/rus
