act_code: '113048'
requisite: Решение Исатайского районного маслихата Атырауской области от 6 июня 2017 года № 94-VI. Зарегистрировано Департаментом юстиции Атырауской области 20 июня 2017 года № 3897. Утратило силу решением Исатайского районного маслихата Атырауской области от 5 октября 2023 года № 46-VІII (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении правил оказания социальной помощи, установления размеров и определения перечня отдельных категорий нуждающихся граждан
  kaz: Әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың қағидаларын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2017-06-06
approved_by:
- '156005000002'
version_date:
  kaz: 2021-03-29
  rus: 2021-03-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/113048/kaz/29.03.2021
  rus: https://zan.gov.kz/client/#!/doc/113048/rus/29.03.2021
caused_by:
  code: '154516'
  requisite: Решение Исатайского районного маслихата Атырауской области от 29 марта 2021 года № 15-VIІ. Зарегистрировано Департаментом юстиции Атырауской области 9 апреля 2021 года № 4922. Утратило силу решением Исатайского районного маслихата Атырауской области от 5 октября 2023 года № 46-VІII (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
  title:
    rus: О внесении изменений в некоторые решение Исатайского районного маслихата от 6 июня 2017 года № 94-VI «Об утверждении Правил оказания социальной помощи, установления размеров и определения перечня отдельных категорий нуждающихся граждан»
    kaz: Исатай аудандық мәслихатының 2017 жылғы 6 маусымдағы № 94-VI «Әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың қағидаларын бекіту туралы» кейбір шешімдеріне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/154516/rus
