act_code: '135128'
requisite: Решение акима Жангельдинского сельского округа Кызылкогинского района Атырауской области от 7 октября 2019 года № 19. Зарегистрировано Департаментом юстиции Атырауской области 8 октября 2019 года № 4498. Утратило силу решением акима Жангельдинского сельского округа Кызылкогинского района Атырауской области от 10 декабря 2019 года № 27 (вводится в действие после дня его первого официального опубликования)
title:
  rus: Об установлении карантина
  kaz: Карантин белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-10-07
approved_by:
- '156007003002'
version_date:
  kaz: 2019-10-07
  rus: 2019-10-07
source:
  kaz: https://zan.gov.kz/client/#!/doc/135128/kaz/07.10.2019
  rus: https://zan.gov.kz/client/#!/doc/135128/rus/07.10.2019
