act_code: '16236'
requisite: Атырау облыстық мәслихатының XXIV сессиясында қабылданған ІІ сайланған 2003 жылғы 6 маусымдағы № 296-ІІ шешімі. Атырау облыстық Әділет басқармасында 2003 жылы 14 шілдеде № 1563 тіркелді. Күші жойылды - Атырау облыстық мәслихатының 2013 жылғы 24 қаңтардағы № 103-V шешімімен
title:
  rus: Аз қамтылған отбасыларына азаматтарға тұрғын үйді жеке тұрғын үй ұстағаннан басқа ұстау және коммуналдық қызметтермен пайдалану төлемдерін өтеуге тұрғын үй көмегін көрсету Тәртібі туралы
  kaz: Аз қамтылған отбасыларына азаматтарға тұрғын үйді жеке тұрғын үй ұстағаннан басқа ұстау және коммуналдық қызметтермен пайдалану төлемдерін өтеуге тұрғын үй көмегін көрсету Тәртібі туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2003-06-05
approved_by:
- '156000000002'
version_date:
  kaz: 2003-06-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/16236/kaz/05.06.2003
