act_code: '48231'
requisite: Атырау облысы Жылыой ауданы Қосшағыл селолық округі әкімінің 2009 жылғы 1 қазандағы № 16 шешімі. Жылыой аудандық Әділет департаментінде 2009 жылғы 20 қазанда № 4-2-129 тіркелді. Күші жойылды - Жылыой ауданы Қосшағыл селолық округі әкімінің 2010 жылғы 23 маусымдағы № 58 шешімімен
title:
  rus: Қосшағыл селосы мен Тұрғызба, Қарағай елді мекендердегі көшелерге атау беру туралы
  kaz: Қосшағыл селосы мен Тұрғызба, Қарағай елді мекендердегі көшелерге атау беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-10-01
approved_by:
- '156009006001'
version_date:
  kaz: 2009-10-01
source:
  kaz: https://zan.gov.kz/client/#!/doc/48231/kaz/01.10.2009
