act_code: '195330'
requisite: Решение акима Атырауской области от 7 апреля 2024 года № 3. Утратило силу решением акима Атырауской области от 24 сентября 2025 года № 7 (вводится в действие со дня его первого официального опубликования)
title:
  rus: Об объявлении чрезвычайной ситуации природного характера
  kaz: Табиғи сипаттағы төтенше жағдайды жариялау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-04-07
approved_by:
- '156000000003'
version_date:
  kaz: 2024-04-07
  rus: 2024-04-07
source:
  kaz: https://zan.gov.kz/client/#!/doc/195330/kaz/07.04.2024
  rus: https://zan.gov.kz/client/#!/doc/195330/rus/07.04.2024
