act_code: '37773'
requisite: Атырау облысы Махамбет аудандық мәслихатының 2007 жылғы 19 желтоқсандағы № 25 шешімі. Атырау облысы Махамбет аудандық Әділет басқармасында 2008 жылғы 9 қаңтарда № 4-3-77 болып тіркелді
title:
  rus: Махамбет ауданының 2008 жылға арналған аудандық бюджеті туралы
  kaz: Махамбет ауданының 2008 жылға арналған аудандық бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2007-12-19
approved_by:
- '156004000002'
version_date:
  kaz: 2007-12-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/37773/kaz/19.12.2007
