act_code: '14955'
requisite: Екінші сайланған Атырау облыстық мәслихаты ХХІ сессиясының 2002 жылғы 6 желтоқсандағы № 261-ІІ шешiмi. Атырау облысының Әділет басқармасында 2002 жылғы 25 желтоқсанда № 1239 болып тіркелді
title:
  rus: Атырау облысында шағын және орта кәсiпкерлiктi дамыту және қолдаудың 2003-2005 жылдарға арналған бағдарламасы туралы
  kaz: Атырау облысында шағын және орта кәсiпкерлiктi дамыту және қолдаудың 2003-2005 жылдарға арналған бағдарламасы туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2002-12-06
approved_by:
- '156000000002'
version_date:
  kaz: 2002-12-06
source:
  kaz: https://zan.gov.kz/client/#!/doc/14955/kaz/06.12.2002
