act_code: '11087'
requisite: Решение акима Атырауской области от 20 марта 1998 года № 620. Зарегистрировано Управлением юстиции Атырауской области 23 апреля 1998 года за № 15. Утратило силу постановлением акима Атырауской области от 20 декабря 2004 года № 248
title:
  rus: Об управлении по миграции и демографии
  kaz: Об управлении по миграции и демографии
form: РЕШ
type_codes:
- РЕШ
approved_on: 1998-03-20
approved_by:
- '156000000001'
version_date:
  rus: 1998-03-20
source:
  rus: https://zan.gov.kz/client/#!/doc/11087/rus/20.03.1998
