act_code: '37802'
requisite: Атырау облысы Құрманғазы ауданы әкімінің 2007 жылғы 26 желтоқсандағы № 77 шешімі. Атырау облысы Әділет департаменті Құрманғазы ауданының Әділет басқармасында 2008 жылғы 17 қаңтарда № 4-8-121 болып тіркелді
title:
  rus: 1991 жылы туған азаматтарды 2008 жылы шақыру учаскесіне тіркеуді жүргізу туралы
  kaz: 1991 жылы туған азаматтарды 2008 жылы шақыру учаскесіне тіркеуді жүргізу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2007-12-26
approved_by:
- '156003000003'
version_date:
  kaz: 2007-12-26
source:
  kaz: https://zan.gov.kz/client/#!/doc/37802/kaz/26.12.2007
