act_code: '73963'
requisite: Решение Макатского районного маслихата Атырауской области от 6 августа 2013 года № 145-V. Зарегистрировано Департаментом юстиции Атырауской области 16 августа 2013 года № 2772. Утратило силу решением маслихата Макатского района Атырауской области от 21 декабря 2015 № 343-V.
title:
  rus: Об утверждении Правил оказания социальной помощи, установления размеров и   определения перечня отдельных категорий нуждающихся граждан
  kaz: Әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж  азаматтардың жекелеген санаттарының тізбесін айқындаудың қағидасын бекіту  туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2013-08-06
approved_by:
- '156006000002'
version_date:
  kaz: 2013-08-06
  rus: 2013-08-06
source:
  kaz: https://zan.gov.kz/client/#!/doc/73963/kaz/06.08.2013
  rus: https://zan.gov.kz/client/#!/doc/73963/rus/06.08.2013
