act_code: '43544'
requisite: Решение от 13.11.2008 №45, Акимат Кара-Арнинского сельского округа
title:
  rus: Көше атын беру туралы
  kaz: Көше атын беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-11-13
approved_by:
- '156009005001'
version_date:
  kaz: 2008-11-13
source:
  kaz: https://zan.gov.kz/client/#!/doc/43544/kaz/13.11.2008
