act_code: '50055'
requisite: Решение Индерского районного маслихата Атырауской области от 23 декабря 2009 года № 186-IV. Зарегистрировано Управлением юстиции Индерского района Атырауской области 15 января 2010 года № 4-6-92. Утратило силу решением Индерского районного маслихата Атырауской области от 28 марта 2013 года № 87-V
title:
  rus: 2010-2012 жылдарға арналған аудандық бюджет туралы
  kaz: 2010-2012 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-12-23
approved_by:
- '156008000002'
version_date:
  kaz: 2010-12-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/50055/kaz/14.12.2010
caused_by:
  code: '56439'
  requisite: Атырау облысы Индер аудандық мәслихатының 2010 жылғы 14 желтоқсандағы № 260-IV шешімі. Атырау облысының Әділет департаменті Индер ауданының Әділет басқармасында 2010 жылғы 21 желтоқсанда № 4-6-109 тіркелді. Күші жойылды - Атырау облысы Индер аудандық мәслихатының 2013 жылғы 28 наурыздағы № 87-V шешімімен
  title:
    rus: Аудандық мәслихаттың 2009 жылғы 23 желтоқсандағы № 186-IV "2010-2012 жылдарға арналған аудандық бюджет туралы" шешіміне өзгерістер мен толықтырулар енгізу туралы
    kaz: Аудандық мәслихаттың 2009 жылғы 23 желтоқсандағы № 186-IV "2010-2012 жылдарға арналған аудандық бюджет туралы" шешіміне өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/56439/rus
