act_code: '205654'
requisite: Решение Жылыойского районного маслихата Атырауской области от 25 декабря 2024 года № 26-1
title:
  rus: О бюджетах города Кульсары, поселка Жана-Каратон, сельских округов Жем, Косчагиль, Кара-Арна, Майкумген и Аккиизтогай на 2025-2027 годы
  kaz: 2025-2027 жылдарға арналған Құлсары қаласының, Жаңа-Қаратон кентінің, Жем, Қосшағыл, Қара-Арна, Майкөмген және Ақкиізтоғай ауылдық округтерінің бюджеттері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-12-25
approved_by:
- '156009000002'
version_date:
  kaz: 2025-09-08
  rus: 2025-09-08
source:
  kaz: https://zan.gov.kz/client/#!/doc/205654/kaz/08.09.2025
  rus: https://zan.gov.kz/client/#!/doc/205654/rus/08.09.2025
caused_by:
  code: '214107'
  requisite: Решение Жылыойского районного маслихата Атырауской области от 8 сентября 2025 года № 34-1
  title:
    rus: О внесении изменений в решение Жылыойского районного маслихата «О бюджетах города Кульсары, поселка Жана-Каратон, сельских округов Жем, Косчагиль, Кара-Арна, Майкумген и Аккиизтогай на 2025-2027 годы» от 25 декабря 2024 года № 26-1
    kaz: «2025-2027 жылдарға арналған Құлсары қаласының, Жаңа-Қаратон кентінің, Жем, Қосшағыл, Қара-Арна, Майкөмген және Ақкиізтоғай ауылдық округтерінің бюджеттері туралы» Жылыой аудандық мәслихатының 2024 жылғы 25 желтоқсандағы № 26-1 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/214107/rus
