act_code: '205654'
requisite: Решение Жылыойского районного маслихата Атырауской области от 25 декабря 2024 года № 26-1
title:
  rus: О бюджетах города Кульсары, поселка Жана-Каратон, сельских округов Жем, Косчагиль, Кара-Арна, Майкумген и Аккиизтогай на 2025-2027 годы
  kaz: 2025-2027 жылдарға арналған Құлсары қаласының, Жаңа-Қаратон кентінің, Жем, Қосшағыл, Қара-Арна, Майкөмген және Ақкиізтоғай ауылдық округтерінің бюджеттері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-12-25
approved_by:
- '156009000002'
version_date:
  kaz: 2024-12-25
  rus: 2024-12-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/205654/kaz/25.12.2024
  rus: https://zan.gov.kz/client/#!/doc/205654/rus/25.12.2024
