act_code: '12480'
requisite: Решение акима Атырауской области от 31 мая 2002 года № 438. Зарегистрированo Управлением юстиции Атырауской области 10 июня 2002 года за № 1002. Утратило силу решением акима Атырауской области от 8 мая 2003 года № 38
title:
  rus: Об утверждении перечня документов и показателей, необходимых для определения финансового состояния заявителя на осуществление деятельности по организации и проведению тотализаторов и казино
  kaz: Тотализатор мен казиноларды ұйымдастыру және өткізу жөніндегі қызметті жүзеге асыру үшін өтініш берушінің қаржылық жағдайын анықтауға қажетті құжаттар мен көрсеткіштердің тізбесін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2002-05-30
approved_by:
- '156000000003'
version_date:
  kaz: 2002-05-30
  rus: 2002-05-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/12480/kaz/30.05.2002
  rus: https://zan.gov.kz/client/#!/doc/12480/rus/30.05.2002
