act_code: '120847'
requisite: Решение Кызылкогинского районного маслихата Атырауской области от 4 апреля 2018 года № XXIII-2. Зарегистрировано Департаментом юстиции Атырауской области 12 апреля 2018 года № 4109. Утратило силу решением Кызылкогинского районного маслихата Атырауской области от 28 сентября 2020 года № LVI-3 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: О повышении ставок единого земельного налога и базовых ставок земельного налога на не используемые в соответствии с земельным законодательством Республики Казахстан земли сельскохозяйственного назначения  в Кызылкогинском районе
  kaz: Қазақстан Республикасының жер заңнамасына сәйкес Қызылқоға ауданында пайдаланылмайтын ауыл шаруашылығы мақсатындағы жерлерге бірыңғай жер салығының мөлшерлемелерін және жер салығының базалық мөлшерлемелерін арттыру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-04-04
approved_by:
- '156007000002'
version_date:
  kaz: 2018-04-04
  rus: 2018-04-04
source:
  kaz: https://zan.gov.kz/client/#!/doc/120847/kaz/04.04.2018
  rus: https://zan.gov.kz/client/#!/doc/120847/rus/04.04.2018
