act_code: '99707'
requisite: Решение акима Мукурского сельского округа Кызылкогинского района Атырауской области от 22 февраля 2016 года № 12. Зарегистрировано Департаментом юстиции Атырауской области 25 февраля 2016 года № 3467
title:
  rus: О присвоении наименования улице
  kaz: Көшеге атау беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2016-02-22
approved_by:
- '156007002001'
version_date:
  kaz: 2016-02-22
  rus: 2016-02-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/99707/kaz/22.02.2016
  rus: https://zan.gov.kz/client/#!/doc/99707/rus/22.02.2016
