act_code: '21643'
requisite: Атырау облысы Жылыой аудандық мәслихатының 2004 жылғы 30 қыркүйектегі № 9-9 шешімі. Атырау облысының Әділет департаментінде 2004 жылғы 22 қазанда № 2172 болып тіркелді
title:
  rus: Құлсары қаласында ауыл шаруашылығы жануарларын ұстау Ережесі туралы
  kaz: Құлсары қаласында ауыл шаруашылығы жануарларын ұстау Ережесі туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2004-09-29
approved_by:
- '156009000002'
version_date:
  kaz: 2004-09-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/21643/kaz/29.09.2004
