act_code: '43392'
requisite: Атырау облысы Құрманғазы аудандық мәслихатының 2008 жылғы 24 желтоқсандағы № 123-ХІІІ шешімі. Атырау облысы Әділет департаменті Құрманғазы ауданының Әділет басқармасында 2009 жылғы 9 қаңтарда № 4-8-135 болып тіркелді
title:
  rus: 2009 жылға арналған аудандық бюджет туралы
  kaz: 2009 жылға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-12-24
approved_by:
- '156003000002'
version_date:
  kaz: 2009-01-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/43392/kaz/28.01.2009
caused_by:
  code: '44470'
  requisite: Атырау облысы Құрманғазы аудандық мәслихатының 2009 жылғы 28 қаңтардағы № 138-XIV шешімі. Атырау облысы Әділет департаменті Құрманғазы ауданының Әділет басқармасында 2009 жылғы 23 ақпанда № 4-8-142 болып тіркелді
  title:
    rus: Аудандық Мәслихаттың 2008 жылғы 24 желтоқсандағы № 123-ХІІІ "2009 жылға арналған аудандық бюджет туралы" шешіміне өзгерістер мен толықтырулар енгізу туралы
    kaz: Аудандық Мәслихаттың 2008 жылғы 24 желтоқсандағы № 123-ХІІІ "2009 жылға арналған аудандық бюджет туралы" шешіміне өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/44470/rus
