act_code: '43392'
requisite: Атырау облысы Құрманғазы аудандық мәслихатының 2008 жылғы 24 желтоқсандағы № 123-ХІІІ шешімі. Атырау облысы Әділет департаменті Құрманғазы ауданының Әділет басқармасында 2009 жылғы 9 қаңтарда № 4-8-135 болып тіркелді
title:
  rus: 2009 жылға арналған аудандық бюджет туралы
  kaz: 2009 жылға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-12-24
approved_by:
- '156003000002'
version_date:
  kaz: 2009-04-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/43392/kaz/27.04.2009
caused_by:
  code: '46032'
  requisite: Атырау облысы Құрманғазы аудандық мәслихатының 2009 жылғы 27 сәуірдегі № 164-XVІІ шешімі. Атырау облысы Әділет департаменті Құрманғазы ауданының Әділет басқармасында 2009 жылғы 20 мамырда № 4-8-147 тіркелді. Күші жойылды - Атырау облысы Құрманғазы аудандық мәслихатының 2009 жылғы 23 желтоқсандағы № 229-XXV шешімімен
  title:
    rus: Аудандық Мәслихаттың 2008 жылғы 24 желтоқсандағы № 123-ХІІІ "2009 жылға арналған аудандық бюджет туралы" шешіміне өзгерістер мен толықтырулар  енгізу туралы
    kaz: Аудандық Мәслихаттың 2008 жылғы 24 желтоқсандағы № 123-ХІІІ "2009 жылға арналған аудандық бюджет туралы" шешіміне өзгерістер мен толықтырулар  енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/46032/rus
