act_code: '221552'
requisite: Решение акима Жарсуатского сельского округа Индерского района Атырауской области от 27 января 2026 года № 1
title:
  rus: О наименовании и переименовании улиц в селах Жарсуат, Кызылжар Жарсуатского сельского округа
  kaz: Жарсуат ауылдық округінің Жарсуат, Қызылжар ауылындағы көшелерге атау беру және қайта атау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2026-01-27
approved_by:
- '156008003002'
version_date:
  kaz: 2026-01-27
  rus: 2026-01-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/221552/kaz/27.01.2026
  rus: https://zan.gov.kz/client/#!/doc/221552/rus/27.01.2026
