act_code: '96240'
requisite: Решение от 18.11.2015 №XXXV-5, Маслихат Кызылкогинского района. Зарегистрировано Департаментом юстиции Атырауской области 09 декабря 2015 года № 3388.    Утратило силу решением  Кызылкогинского  районного маслихата Атырауской области от 26 февраля 2016 года № XXXVIII-3.
title:
  rus: О повышении ставок единого земельного налога и ставок земельного налога на не используемые в соответствии с земельным законодательством Республики Казахстан земли сельскохозяйственного назначения в Кызылкогинском районе
  kaz: Қазақстан Республикасының жер заңнамасына сәйкес Қызылқоға ауданында пайдаланылмайтын ауыл шаруашылығы мақсатындағы жерлерге бірыңғай жер салығының мөлшерлемелерін және жер салығының мөлшерлемелерін жоғарылату туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-11-18
approved_by:
- '156007000002'
version_date:
  kaz: 2015-11-18
  rus: 2015-11-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/96240/kaz/18.11.2015
  rus: https://zan.gov.kz/client/#!/doc/96240/rus/18.11.2015
