act_code: '50378'
requisite: Атырау облысы Құрманғазы ауданы әкімінің 2010 жылғы 5 қаңтардағы № 1 шешімі. Атырау облысы Әділет департаменті Құрманғазы ауданының Әділет басқармасында 2010 жылғы 27 қаңтарда № 4-8-182 тіркелді. Күші жойылды - Атырау облысы Құрманғазы ауданы әкімінің 2011 жылғы 12 қаңтардағы № 2 шешімімен
title:
  rus: Атырау облысы Құрманғазы ауданының 1993 жылы туған азаматтарын 2010 жылы шақыру учаскесіне тіркеуді өткізу туралы
  kaz: Атырау облысы Құрманғазы ауданының 1993 жылы туған азаматтарын 2010 жылы шақыру учаскесіне тіркеуді өткізу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-01-05
approved_by:
- '156003000001'
version_date:
  kaz: 2010-03-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/50378/kaz/05.03.2010
caused_by:
  code: '51074'
  requisite: Атырау облысы Құрманғазы ауданы әкімінің 2010 жылғы 5 наурыздағы № 17 шешімі. Атырау облысы Әділет департаменті Құрманғазы ауданының Әділет басқармасында 2010 жылғы 10 наурызда № 4-8-183 тіркелді. Күші жойылды - Атырау облысы Құрманғазы ауданы әкімінің 2011 жылғы 12 қаңтардағы № 2 шешімімен
  title:
    rus: Аудан әкімінің 2010 жылғы 05 қаңтардағы № 01 "Атырау облысы Құрманғазы ауданының 1993 жылы туған азаматтарын 2010 жылы шақыру учаскесіне тіркеуді өткізу туралы" шешіміне өзгерістер енгізу туралы
    kaz: Аудан әкімінің 2010 жылғы 05 қаңтардағы № 01 "Атырау облысы Құрманғазы ауданының 1993 жылы туған азаматтарын 2010 жылы шақыру учаскесіне тіркеуді өткізу туралы" шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/51074/rus
