act_code: '203710'
requisite: Решение Макатского районного маслихата Атырауской области от 5 декабря 2024 года № 126-VIII. Зарегистрировано в Департаменте юстиции Атырауской области 6 декабря 2024 года № 5237-06
title:
  rus: О признании утратившим силу решения Макатского районного маслихата от 17 сентября 2015 года № 327-V «Об утверждении методики ежегодной оценки деятельности административных государственных служащих корпуса «Б» аппарата Макаткого районного маслихата»
  kaz: «Мақат аудандық мәслихаты аппаратының "Б" корпусы мемлекеттік әкімшілік қызметшілерінің қызметін жыл сайынғы бағалау әдістемесін бекіту туралы» Мақат аудандық мәслихатының 2015 жылғы 17 қыркүйектегі № 327-V шешімінің күшін жою туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-12-05
approved_by:
- '156006000002'
version_date:
  kaz: 2024-12-05
  rus: 2024-12-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/203710/kaz/05.12.2024
  rus: https://zan.gov.kz/client/#!/doc/203710/rus/05.12.2024
