act_code: '117312'
requisite: Решение Атырауского областного маслихата от 13 декабря 2017 года № 167-VI. Зарегистрировано Департаментом юстиции Атырауской области 29 декабря 2017 года № 4023
title:
  rus: Об областном бюджете на 2018-2020 годы
  kaz: 2018-2020 жылдарға арналған облыстық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2017-12-13
approved_by:
- '156000000002'
version_date:
  kaz: 2018-06-20
  rus: 2018-06-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/117312/kaz/20.06.2018
  rus: https://zan.gov.kz/client/#!/doc/117312/rus/20.06.2018
caused_by:
  code: '123368'
  requisite: Решение Атырауского областного маслихата от 20 июня 2018 года № 210-VI. Зарегистрировано Департаментом юстиции Атырауской области 10 июля 2018 года № 4195
  title:
    rus: О внесении изменений и дополнений в решение ХІХ сессии областного маслихата VІ созыва от 13 декабря 2017 года № 167-VІ «Об областном бюджете на 2018-2020 годы»
    kaz: «VІ шақырылған облыстық мәслихаттың ХІХ сессиясының 2017 жылғы 13 желтоқсандағы № 167-VІ «2018-2020 жылдарға арналған облыстық бюджет туралы» шешіміне өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/123368/rus
