act_code: '75972'
requisite: Решение Жылыойского районного маслихата Атырауской области от 11 декабря 2013 года № 17-22. Зарегистрировано Департаментом юстиции Атырауской области 19 декабря 2013 года № 2823. Утратило силу решением Жылыойского районного маслихата Атырауской области от 28 сентября 2021 года № 9-6 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об установлении перечня памятных дат и праздничных дней, кратности оказания социальной помощи и установление размера социальной помощи для отдельно взятой категории получателей
  kaz: Алушылардың жекелеген санаттары үшін әлеуметтік көмек көрсету еселігін және әлеуметтік көмек мөлшерін, атаулы күндер мен мереке күндерінің тізбесін белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2013-12-11
approved_by:
- '156009000002'
version_date:
  kaz: 2016-04-28
  rus: 2016-04-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/75972/kaz/28.04.2016
  rus: https://zan.gov.kz/client/#!/doc/75972/rus/28.04.2016
caused_by:
  code: '102249'
  requisite: Решение Жылыойского районного маслихата Атырауской области от 28 апреля 2016 года № 2-4. Зарегистрировано Департаментом юстиции Атырауской области 11 мая 2016 года № 3512. Утратило силу решением Жылыойского районного маслихата Атырауской области от 28 сентября 2021 года № 9-6 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
  title:
    rus: О внесении изменений в решение Жылыойского районного маслихата от 11 декабря 2013 года №17-22 «Об установлении  перечня памятных дат и праздничных дней, кратности оказания социальной помощи и установление  размеров социальной помощи  для отдельно взятой категории получателей»
    kaz: Жылыой аудандық мәслихатының 2013 жылғы 11 желтоқсандағы №17-22 «Алушылардың жекелеген санаттары үшін әлеуметтік көмек  көрсету еселігін және  әлеуметтік  көмек  мөлшерлерін, атаулы күндер мен мереке күндерінің тізбесін белгілеу  туралы»  шешіміне  өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/102249/rus
