act_code: '103866'
requisite: Решение Жылыойского районного маслихата Атырауской области от 22 июня 2016 года № 3-11. Утратило силу решением Жылыойского районного маслихата Атырауской области от 19 мая 2023 года № 3-6 (вводиться в дейтвие со дня первого официального опубликования)
title:
  rus: Об утверждении Положения государственного  учреждения «Аппарат маслихата Жылыойского  района»
  kaz: «Жылыой ауданы мәслихатының аппараты»  мемлекеттік мекемесінің Ережесін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2016-06-22
approved_by:
- '156009000002'
version_date:
  kaz: 2016-06-22
  rus: 2016-06-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/103866/kaz/22.06.2016
  rus: https://zan.gov.kz/client/#!/doc/103866/rus/22.06.2016
