act_code: '128787'
requisite: Решение акима Махамбетского района Атырауской области от 21 января 2019 года № 3. Зарегистрировано Департаментом юстиции Атырауской области 28 января 2019 года № 4337
title:
  rus: Об образовании избирательных участков на территории Махамбетского района
  kaz: Махамбет ауданы аумағында сайлау учаскелерін құру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-01-21
approved_by:
- '156004000003'
version_date:
  kaz: 2024-02-29
  rus: 2024-02-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/128787/kaz/29.02.2024
  rus: https://zan.gov.kz/client/#!/doc/128787/rus/29.02.2024
caused_by:
  code: '193880'
  requisite: Решение акима Махамбетского района Атырауской области от 29 февраля 2024 года № 12. Зарегистрировано в Департаменте юстиции Атырауской области 4 марта 2024 года № 5141-06
  title:
    rus: О внесении изменений в решение акима Махамбетского района от 21 января 2019 года № 3 «Об образовании избирательных участков на территории Махамбетского района»
    kaz: Махамбет ауданы әкімінің 2019 жылғы 21 қаңтардағы «Махамбет ауданы аумағында сайлау учаскелерін құру туралы» № 3 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/193880/rus
