act_code: '213023'
requisite: Решение акима Курмангазинского района Атырауской области от 31 июля 2025 года № 16. Утратило силу решением акима Курмангазинского района Атырауской области от 4 мая 2026 года № 8 (вводится в действие после дня его первого официального опубликования)
title:
  rus: Об объявлении чрезвычайной ситуации природного характера местного масштаба на территории Курмангазинского района
  kaz: Құрманғазы ауданы аумағында жергілікті ауқымдағы табиғи сипаттағы төтенше жағдайды жариялау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2025-07-31
approved_by:
- '156003000003'
version_date:
  kaz: 2025-07-31
  rus: 2025-07-31
source:
  kaz: https://zan.gov.kz/client/#!/doc/213023/kaz/31.07.2025
  rus: https://zan.gov.kz/client/#!/doc/213023/rus/31.07.2025
