act_code: '40619'
requisite: Атырау облысы Қызылқоға ауданы Сағыз селолық округі әкімінің 2008 жылғы 23 маусымдағы № 16 шешімі. Атырау облысы Әділет департаменті Қызылқоға ауданының Әділет басқармасында 2008 жылғы 14 шілдеде № 4-5-97 болып тіркелді
title:
  rus: Село көшелеріне ат беру туралы
  kaz: Село көшелеріне ат беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-06-23
approved_by:
- '156007001002'
version_date:
  kaz: 2008-06-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/40619/kaz/23.06.2008
