act_code: '420'
requisite: Решение акима Атырауской области от 17 февраля 1998 года № 593. Зарегистрировано Управлением юстиции Атырауской области 9 марта 1998 года за № 6. Утратило силу постановлением акима Атырауской области от 20 декабря 2004 года № 248
title:
  rus: Об упорядочении реализации хлеба, хлебобулочных изделий
  kaz: Об упорядочении реализации хлеба, хлебобулочных изделий
form: РЕШ
type_codes:
- РЕШ
approved_on: 1998-02-17
approved_by:
- '156000000001'
version_date:
  rus: 1998-02-17
source:
  rus: https://zan.gov.kz/client/#!/doc/420/rus/17.02.1998
