act_code: '108586'
requisite: Решение акима Уильского сельского округа Кызылкогинского района Атырауской области от 15 декабря 2016 года № 41. Зарегистрировано Департаментом юстиции Атырауской области 27 декабря 2016 года № 3725
title:
  rus: Об утрате силы решения акима Уильского сельского округа от 3 октября 2016 года №32 «Об установлении ограничительных мероприятий»
  kaz: «Шектеу іс-шараларын белгілеу туралы» Ойыл ауылдық округі әкімінің 2016 жылғы 3 қазандағы №32 шешімінің күшін жою туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2016-12-15
approved_by:
- '156007004001'
version_date:
  kaz: 2016-12-15
  rus: 2016-12-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/108586/kaz/15.12.2016
  rus: https://zan.gov.kz/client/#!/doc/108586/rus/15.12.2016
