act_code: '127316'
requisite: Решение Атырауского областного маслихата от 14 декабря 2018 года № 274-VI. Зарегистрировано Департаментом юстиции Атырауской области 25 декабря 2018 года № 4300
title:
  rus: Об областном бюджете на 2019-2021 годы
  kaz: 2019-2021 жылдарға арналған облыстық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-12-14
approved_by:
- '156000000002'
version_date:
  kaz: 2019-04-26
  rus: 2019-04-26
source:
  kaz: https://zan.gov.kz/client/#!/doc/127316/kaz/26.04.2019
  rus: https://zan.gov.kz/client/#!/doc/127316/rus/26.04.2019
caused_by:
  code: '131035'
  requisite: Решение Атырауского областного маслихата от 26 апреля 2019 года № 313-VI. Зарегистрировано Департаментом юстиции Атырауской области 30 апреля 2019 года № 4389
  title:
    rus: О внесении изменений и дополнений в решение ХХVІІ сессии маслихата Атырауской области VІ созыва от 14 декабря 2018 года № 274-VІ «Об областном бюджете на 2019-2021 годы»
    kaz: «VІ шақырылған Атырау облыстық мәслихатының ХХVІІ сессиясы 2018 жылғы 14 желтоқсандағы № 274-VІ «2019-2021 жылдарға арналған облыстық бюджет туралы» шешіміне өзгерістер мен толықтыруларенгізу туралы
  link: https://zan.gov.kz/client/#!/doc/131035/rus
