act_code: '123080'
requisite: Решение акима Геологского сельского округа города Атырау Атырауской области от 20 июня 2018 года № 114. Зарегистрировано Департаментом юстиции Атырауской области 29 июня 2018 года № 4186
title:
  rus: О присвоении наименования улице
  kaz: Көшеге атау беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-06-20
approved_by:
- '156002007002'
version_date:
  kaz: 2018-06-20
  rus: 2018-06-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/123080/kaz/20.06.2018
  rus: https://zan.gov.kz/client/#!/doc/123080/rus/20.06.2018
