act_code: '85939'
requisite: Решение Индерского районного маслихата Атырауской области от 24 декабря 2014 года № 248-V. Зарегистрировано Департаментом юстиции Атырауской области 16 января 2015 года № 3087
title:
  rus: 'О районном бюджете на 2015-2017 годы '
  kaz: '2015 -2017 жылдарға арналған аудандық бюджет туралы '
form: РЕШ
type_codes:
- РЕШ
approved_on: 2014-12-24
approved_by:
- '156008000002'
version_date:
  kaz: 2015-09-16
  rus: 2015-09-16
source:
  kaz: https://zan.gov.kz/client/#!/doc/85939/kaz/16.09.2015
  rus: https://zan.gov.kz/client/#!/doc/85939/rus/16.09.2015
caused_by:
  code: '94166'
  requisite: Решение Индерского районного маслихата Атырауской области от 16 сентября 2015 года № 297-V. Зарегистрировано Департаментом юстиции Атырауской области 30 сентября 2015 года № 3305
  title:
    rus: О внесении изменений и дополнений в решение районного маслихата от 24 декабря 2014 года № 248-V «О районном бюджете на 2015-2017 годы»
    kaz: Аудандық мәслихаттың 2014 жылғы 24 желтоқсандағы № 248-V «2015-2017 жылдарға арналған  аудандық бюджет туралы» шешіміне өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/94166/rus
