act_code: '205042'
requisite: Решение Курмангазинского районного маслихата Атырауской области от 26 декабря 2024 года № 185-VIII. Зарегистрировано в Департаменте юстиции Атырауской области 30 декабря 2024 года № 5245-06
title:
  rus: О признании утратившим силу решение Курмангазинского районного маслихата от 25 августа 2020 года № 533-VI «Об установлении специалистам в области социального обеспечения, образования, культуры, спорта и ветеринарии, являющимся гражданскими служащими и работающим в сельской местности повышенные должностные оклады и тарифные ставки»
  kaz: «Азаматтық қызметшілер болып табылатын және ауылдық жерде жұмыс істейтін әлеуметтік қамсыздандыру, білім беру, мәдениет, спорт және ветеринария саласындағы мамандарға жоғарылатылған лауазымдық айлықақылар мен тарифтік мөлшерлемелер белгілеу туралы» Құрманғазы аудандық мәслихатының 2020 жылғы 25 тамыздағы № 533-VI шешімінің күшін жою туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-12-26
approved_by:
- '156003000002'
version_date:
  kaz: 2024-12-26
  rus: 2024-12-26
source:
  kaz: https://zan.gov.kz/client/#!/doc/205042/kaz/26.12.2024
  rus: https://zan.gov.kz/client/#!/doc/205042/rus/26.12.2024
