act_code: '123338'
requisite: Решение Атырауского областного маслихата от 20 июня 2018 года № 224-VI. Зарегистрировано Департаментом юстиции Атырауской области 10 июля 2018 года № 4194
title:
  rus: Об утверждении ставок платы за лесные пользования на участках государственного лесного фонда по Атырауской области
  kaz: Атырау облысы бойынша мемлекеттік орман қоры учаскелерінде орман пайдалану төлемақысының ставкаларын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-06-20
approved_by:
- '156000000002'
version_date:
  kaz: 2019-06-21
  rus: 2019-06-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/123338/kaz/21.06.2019
  rus: https://zan.gov.kz/client/#!/doc/123338/rus/21.06.2019
caused_by:
  code: '132950'
  requisite: Решение Атырауского областного маслихата от 21 июня 2019 года № 331-VI. Зарегистрировано Департаментом юстиции Атырауской области 1 июля 2019 года № 4434
  title:
    rus: О внесении изменений в решение ХХІІ сессии Атырауского областного маслихата VI созыва от 20 июня 2018 года № 224-VI «Об утверждении ставок платы за лесные пользования на участках государственного лесного фонда по Атырауской области»
    kaz: VI шақырылған Атырау облыстық мәслихатының XXII сессиясының 2018 жылғы 20 маусымдағы № 224-VI «Атырау облысы бойынша мемлекеттік орман қоры учаскелерінде орман пайдалану төлемақысының ставкаларын бекіту туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/132950/rus
