act_code: '123338'
requisite: Решение Атырауского областного маслихата от 20 июня 2018 года № 224-VI. Зарегистрировано Департаментом юстиции Атырауской области 10 июля 2018 года № 4194
title:
  rus: Об утверждении ставок платы за лесные пользования на участках государственного лесного фонда по Атырауской области
  kaz: Атырау облысы бойынша мемлекеттік орман қоры учаскелерінде орман пайдалану төлемақысының ставкаларын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-06-20
approved_by:
- '156000000002'
version_date:
  kaz: 2018-06-20
  rus: 2018-06-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/123338/kaz/20.06.2018
  rus: https://zan.gov.kz/client/#!/doc/123338/rus/20.06.2018
