act_code: '96415'
requisite: Решение от 25.11.2015 №318-V, Маслихат Индерского района. Зарегистрировано Департаментом юстиции Атырауской области 14 декабря 2015 года № 3393. Утратило силу решением Индерского районного маслихата Атырауской области от 11 июля 2016 года № 25-VI
title:
  rus: Об утверждении Положения государственного учреждения «Аппарат Индерского районного маслихата»
  kaz: «Индер  аудандық мәслихатының аппараты» мемлекеттік мекемесінің Ережесін бекіту туралы
form: РЕШ
type_codes:
- ПОЛ
- РЕШ
approved_on: 2015-11-25
approved_by:
- '156008000002'
version_date:
  kaz: 2015-11-25
  rus: 2015-11-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/96415/kaz/25.11.2015
  rus: https://zan.gov.kz/client/#!/doc/96415/rus/25.11.2015
