act_code: '20160'
requisite: Решение акима Атырауской области от 29 апреля 2004 года № 48. Зарегистрировано Департаментом юстиции Атырауской области от 4 июня 2004 года № 1996
title:
  rus: О лицензировании
  kaz: О лицензировании
form: РЕШ
type_codes:
- РЕШ
approved_on: 2004-04-28
approved_by:
- '156000000003'
version_date:
  rus: 2004-04-28
source:
  rus: https://zan.gov.kz/client/#!/doc/20160/rus/28.04.2004
