act_code: '11951'
requisite: II сайланған Атырау облыстық мәслихаты VI сессиясының 2000 жылғы 28 тамыздағы № 76-II шешімі. Атырау облысының Әділет басқармасында 2002 жылғы 21 қаңтарда № 719 болып тіркелді
title:
  rus: «Атырау облысының Құрметті азаматы атағын белгілеу туралы
  kaz: «Атырау облысының Құрметті азаматы атағын белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2000-08-27
approved_by:
- '156000000002'
version_date:
  kaz: 2000-08-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/11951/kaz/27.08.2000
