act_code: '68050'
requisite: Решение акима Махамбетского района Атырауской области от 11 октября 2012 года № 19. Зарегистрировано Департаментом юстиции Атырауской области 15 октября 2012 года № 2626. Утратило силу решением акима Махамбетского района Атырауской области от 21 января 2019 года № 3 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об образовании избирательных участков на территории Махамбетского района
  kaz: Махамбет ауданының аумағында сайлау учаскелерін құру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2012-10-11
approved_by:
- '156004000001'
version_date:
  kaz: 2015-02-27
  rus: 2015-02-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/68050/kaz/27.02.2015
  rus: https://zan.gov.kz/client/#!/doc/68050/rus/27.02.2015
caused_by:
  code: '87143'
  requisite: Решение акима Махамбетского района Атырауской области от 27 февраля 2015 года № 4. Зарегистрировано Департаментом юстиции Атырауской области 27 февраля 2015 года № 3109. Утратило силу решением акима Махамбетского района Атырауской области от 21 января 2019 года № 3 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
  title:
    rus: О внесении изменений в решение акима района от 11 октября 2012 года № 19 «Об образовании избирательных участков на территории Махамбетского района»
    kaz: Аудан әкімінің 2012 жылғы 11 қазандағы № 19 «Махамбет ауданының аумағында сайлау учаскелерін құру туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/87143/rus
