act_code: '43390'
requisite: Махамбет аудандық мәслихатының 2008 жылғы 24 желтоқсандағы № 93 шешімі. Атырау облысы Әділет департаменті Махамбет ауданының Әділет басқармасында 2009 жылғы 14 қаңтарда 4-3-111 тіркелді
title:
  rus: Махамбет ауданының 2009 жылға арналған аудандық бюджеті туралы
  kaz: Махамбет ауданының 2009 жылға арналған аудандық бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-12-24
approved_by:
- '156004000002'
version_date:
  kaz: 2009-12-10
source:
  kaz: https://zan.gov.kz/client/#!/doc/43390/kaz/10.12.2009
caused_by:
  code: '49645'
  requisite: Решение Махамбетского районного маслихата Атырауской области от 10 декабря 2009 года № 189. Зарегистрировано Управлением юстиции Махамбетского района Атырауской области 5 января 2010 года № 4-3-136
  title:
    rus: Аудандық мәслихаттың 2008 жылғы 24 желтоқсандағы № 93 "Махамбет ауданының 2009 жылға арналған аудандық бюджеті туралы" шешіміне өзгерістер мен толықтыру енгізу туралы
    kaz: Аудандық мәслихаттың 2008 жылғы 24 желтоқсандағы № 93 "Махамбет ауданының 2009 жылға арналған аудандық бюджеті туралы" шешіміне өзгерістер мен толықтыру енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/49645/rus
