act_code: '43390'
requisite: Махамбет аудандық мәслихатының 2008 жылғы 24 желтоқсандағы № 93 шешімі. Атырау облысы Әділет департаменті Махамбет ауданының Әділет басқармасында 2009 жылғы 14 қаңтарда 4-3-111 тіркелді
title:
  rus: Махамбет ауданының 2009 жылға арналған аудандық бюджеті туралы
  kaz: Махамбет ауданының 2009 жылға арналған аудандық бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-12-24
approved_by:
- '156004000002'
version_date:
  kaz: 2008-12-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/43390/kaz/24.12.2008
