act_code: '128190'
requisite: Решение Курмангазинского районного маслихата Атырауской области от 29 декабря 2018 года № 372-VI. Зарегистрировано Департаментом юстиции Атырауской области 9 января 2019 года № 4322
title:
  rus: Об утверждении районного бюджета на 2019-2021 годы
  kaz: 2019-2021 жылдарға арналған ауданның бюджетін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-12-29
approved_by:
- '156003000002'
version_date:
  kaz: 2019-04-05
  rus: 2019-04-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/128190/kaz/05.04.2019
  rus: https://zan.gov.kz/client/#!/doc/128190/rus/05.04.2019
caused_by:
  code: '130318'
  requisite: Решение Курмангазинского районного маслихата Атырауской области от 5 апреля 2019 года № 399-VI. Зарегистрировано Департаментом юстиции Атырауской области 10 апреля 2019 года № 4376
  title:
    rus: О внесении изменений и дополнений в решение районного маслихата от 29 декабря 2018 года № 372-VІ «Об утверждении районного бюджета на 2019-2021 годы»
    kaz: Аудандық мәслихаттың 2018 жылғы 29 желтоқсандағы № 372-VІ «2019-2021 жылдарға арналған ауданның бюджетін бекіту туралы» шешіміне өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/130318/rus
