act_code: '44467'
requisite: Атырау облысы Қызылқоға ауданы мәслихатының 2009 жылғы 26 қаңтардағы № IX-7 шешімі. Атырау облысы Әділет департаменті Қызылқоға ауданының Әділет басқармасында 2009 жылғы 24 ақпанда № 4-5-105 болып тіркелді
title:
  rus: 2009 жылғы бір жолға талондардың құны мөлшерін белгілеу туралы
  kaz: 2009 жылғы бір жолға талондардың құны мөлшерін белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-01-26
approved_by:
- '156007000002'
version_date:
  kaz: 2009-01-26
source:
  kaz: https://zan.gov.kz/client/#!/doc/44467/kaz/26.01.2009
