act_code: '37484'
requisite: Атырау облысы Атырау қалалық мәслихатының 2007 жылғы 14 желтоқсандағы № 30 шешімі. Атырау облысының Әділет басқармасында 2008 жылғы 24 қаңтарда № 4-1-76 болып тіркелді
title:
  rus: 2008 жылға арналған қала бюджеті туралы
  kaz: 2008 жылға арналған қала бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2007-12-14
approved_by:
- '156002000002'
version_date:
  kaz: 2007-12-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/37484/kaz/14.12.2007
