act_code: '226207'
requisite: Решение акима Жылыойского района Атырауской области от 5 июня 2026 года № 20
title:
  rus: Об объявлении чрезвычайной ситуации объектового масштаба
  kaz: Объектілік масштабтағы төтенше жағдайды жариялау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2026-06-05
approved_by:
- '156009000003'
version_date:
  kaz: 2026-06-05
  rus: 2026-06-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/226207/kaz/05.06.2026
  rus: https://zan.gov.kz/client/#!/doc/226207/rus/05.06.2026
