act_code: '8739'
requisite: Решение внеочередной IХ-ой сессии Атырауского областного маслихата II созыва от 12 января 2001 года № 100-II. Зарегистрировано Управлением юстиции Атырауской области 26 февраля 2001 года № 351. Утратило силу решением областного маслихата Атырауской области от 20 декабря 2004 года № 248
title:
  rus: Об утверждении региональной программы по реализации концепции миграционной политики Республики Казахстан по Атырауской области и план мероприятий по ее реализации
  kaz: Қазақстан Республикасы көші-қон саясатының тұжырымдамасын Атырау облысы бойынша іске асырудың аймақтық бағдарламасы туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2001-01-12
approved_by:
- '156000000002'
version_date:
  kaz: 2001-01-12
  rus: 2001-01-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/8739/kaz/12.01.2001
  rus: https://zan.gov.kz/client/#!/doc/8739/rus/12.01.2001
