act_code: '94600'
requisite: Решение от 22.09.2015 №320, Маслихат Махамбетского района.  Утратило силу решением  Махамбетского районного маслихата Атырауской области от 24 февраля 2016 года № 367.
title:
  rus: О повышении ставок единого земельного налога и ставок земельного налога на неиспользуемые в соответствии с земельным законодательством Республики Казахстан земли сельскохозяйственного назначения в Махамбетском районе
  kaz: Қазақстан Республикасының жер заңнамасына сәйкес Махамбет ауданында пайдаланылмайтын ауыл шаруашылығы мақсатындағы жерлерге  бірыңғай жер салығының мөлшерлемелерін  және жер салығының мөлшерлемелерін жоғарылату туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-09-22
approved_by:
- '156004000002'
version_date:
  kaz: 2015-12-24
  rus: 2015-12-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/94600/kaz/24.12.2015
  rus: https://zan.gov.kz/client/#!/doc/94600/rus/24.12.2015
caused_by:
  code: '97922'
  requisite: Решение Махамбетского районного маслихата Атырауской области от 24 декабря 2015 года № 351. Зарегистрировано Департаментом юстиции Атырауской области 11 января 2016 года № 3425.   Утратило силу решением  Махамбетского районного маслихата Атырауской области от 24 февраля 2016 года № 367.
  title:
    rus: О внесении изменений в решение районного маслихата  от  22   сентября  2015 года №320 «О повышении ставок единого земельного налога и базовых ставок земельного налога на не используемые в соответствии с земельным законодательством Республики Казахстан земли сельскохозяйственного назначения в Махамбетском районе»
    kaz: Аудандық     мәслихаттың    2015  жылғы 22 қыркүйектегі №320 «Қазақстан Республикасының жер заңнамасына сәйкес Махамбет ауданында пайдаланылмайтын ауыл шаруашылығы мақсатындағы жерлерге  бірыңғай жер салығының мөлшерлемелерін  және базалық жер салығының мөлшерлемелерін жоғарылату туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/97922/rus
