act_code: '144368'
requisite: Решение акима Жангельдинского сельского округа Кызылкогинского района Атырауской области от 30 июня 2020 года № 13. Зарегистрировано Департаментом юстиции Атырауской области 2 июля 2020 года № 4687. Утратило силу решением акима Жангельдинского сельского округа Кызылкогинского района Атырауской области от 15 октября 2020 года № 28 (вводится в действие после дня его первого официального опубликования)
title:
  rus: Об установлении ограничительных мероприятий
  kaz: Шектеу іс-шараларын белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-06-30
approved_by:
- '156007003002'
version_date:
  kaz: 2020-06-30
  rus: 2020-06-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/144368/kaz/30.06.2020
  rus: https://zan.gov.kz/client/#!/doc/144368/rus/30.06.2020
