act_code: '42791'
requisite: Атырау облысы Индер аудандық мәслихатының 2008 жылғы 15 желтоқсандағы № 98-IV шешімі. Атырау облысы Индер аудандық Әділет басқармасында 2008 жылғы 15 желтоқсанда № 4-6-74 болып тіркелді
title:
  rus: Аудандық мәслихаттың 2007 жылғы 24 желтоқсандағы № 21-IV «2008 жылға арналған аудандық бюджет туралы» шешіміне өзгертулер енгізу туралы
  kaz: Аудандық мәслихаттың 2007 жылғы 24 желтоқсандағы № 21-IV «2008 жылға арналған аудандық бюджет туралы» шешіміне өзгертулер енгізу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-12-15
approved_by:
- '156008000002'
version_date:
  kaz: 2008-12-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/42791/kaz/15.12.2008
