act_code: '50060'
requisite: Решение Махамбетского районного маслихата Атырауской области от 23 декабря 2009 года № 192. Зарегистрировано Управлением юстиции Махамбетского района Атырауской области 18 января 2010 года № 4-3-138. Утратило силу решением Махамбетского районного маслихата Атырауской области от 28 марта 2013 года № 81
title:
  rus: Махамбет ауданының 2010-2012 жылдарға арналған аудандық бюджеті туралы
  kaz: Махамбет ауданының 2010-2012 жылдарға арналған аудандық бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-12-23
approved_by:
- '156004000002'
version_date:
  kaz: 2010-02-09
source:
  kaz: https://zan.gov.kz/client/#!/doc/50060/kaz/09.02.2010
caused_by:
  code: '51206'
  requisite: Решение Махамбетского районного маслихата Атырауской области от 9 февраля 2010 года № 199. Зарегистрировано Управлением юстиции Махамбетского района Атырауской области 16 марта 2010 года № 4-3-141. Утратило силу решением Махамбетского районного маслихата Атырауской области от 28 марта 2013 года № 81
  title:
    rus: Аудандық мәслихаттың 2009 жылғы 23 желтоқсандағы № 192 "Махамбет ауданының  2010-2012 жылдарға арналған бюджеті туралы" шешіміне өзгерістер мен толықтыру енгізу туралы
    kaz: Аудандық мәслихаттың 2009 жылғы 23 желтоқсандағы № 192 "Махамбет ауданының  2010-2012 жылдарға арналған бюджеті туралы" шешіміне өзгерістер мен толықтыру енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/51206/rus
