act_code: '50060'
requisite: Решение Махамбетского районного маслихата Атырауской области от 23 декабря 2009 года № 192. Зарегистрировано Управлением юстиции Махамбетского района Атырауской области 18 января 2010 года № 4-3-138. Утратило силу решением Махамбетского районного маслихата Атырауской области от 28 марта 2013 года № 81
title:
  rus: Махамбет ауданының 2010-2012 жылдарға арналған аудандық бюджеті туралы
  kaz: Махамбет ауданының 2010-2012 жылдарға арналған аудандық бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-12-23
approved_by:
- '156004000002'
version_date:
  kaz: 2010-10-13
source:
  kaz: https://zan.gov.kz/client/#!/doc/50060/kaz/13.10.2010
caused_by:
  code: '55656'
  requisite: Решение Махамбетского районного маслихата Атырауской области от 13 октября 2010 года № 238. Зарегистрировано Управлением юстиции Махамбетского района Атырауской области 24 ноября 2010 года № 4-3-147. Утратило силу решением Махамбетского районного маслихата Атырауской области от 28 марта 2013 года № 81
  title:
    rus: Аудандық Мәслихаттың 2009 жылғы 23 желтоқсандағы № 192 "Махамбет ауданының 2010-2012 жылға арналған аудандық бюджеті туралы" шешіміне өзгерістер енгізу туралы
    kaz: Аудандық Мәслихаттың 2009 жылғы 23 желтоқсандағы № 192 "Махамбет ауданының 2010-2012 жылға арналған аудандық бюджеті туралы" шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/55656/rus
