act_code: '194559'
requisite: Решение Индерского районного маслихата Атырауской области от 18 марта 2024 года № 84-VIII. Зарегистрировано в Департаменте юстиции Атырауской области 19 марта 2024 года № 5154-06
title:
  rus: Об утверждении ставок туристского взноса для иностранцев на 2024 год по Индерскому району
  kaz: Индер ауданы бойынша шетелдіктер үшін 2024 жылға арналған туристік жарна мөлшерлемелерін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-03-18
approved_by:
- '156008000002'
version_date:
  kaz: 2024-03-18
  rus: 2024-03-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/194559/kaz/18.03.2024
  rus: https://zan.gov.kz/client/#!/doc/194559/rus/18.03.2024
