act_code: '224214'
requisite: Решение Индерского районного маслихата Атырауской области от 15 апреля 2026 года № 212-VIII
title:
  rus: Об утверждении Плана по управлению пастбищами и их использованию по Индерскому району на 2026-2030 годы
  kaz: Индер ауданы бойынша 2026-2030 жылдарға арналған жайылымдарды басқару және оларды пайдалану жөніндегі жоспарын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2026-04-15
approved_by:
- '156008000002'
version_date:
  kaz: 2026-04-15
  rus: 2026-04-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/224214/kaz/15.04.2026
  rus: https://zan.gov.kz/client/#!/doc/224214/rus/15.04.2026
