act_code: '17630'
requisite: Атырау облысының Қызылқоға аудандық мәслихатының ХХV сессиясының 2003 жылғы 28 тамыздағы № ХХV-3 шешімі. Атырау облыстық Әділет басқармасында 2003 жылғы 25 қыркүйекте № 1637 тіркелді. Күші жойылды - Атырау облысы Қызылқоға аудандық мәслихатының 2007 жылғы 7 ақпандағы № 29-3 шешімімен
title:
  rus: Қызылқоға ауданының 2003-2010 жылдарға арналған "Ауыз-су бағдарламасы" туралы
  kaz: Қызылқоға ауданының 2003-2010 жылдарға арналған "Ауыз-су бағдарламасы" туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2003-08-27
approved_by:
- '156007000002'
version_date:
  kaz: 2003-08-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/17630/kaz/27.08.2003
