act_code: '48884'
requisite: Атырау облысы Махамбет ауданы Жалғансай селолық округі әкімінің 2009 жылғы 3 қарашадағы № 8 шешімі. Атырау облысы Әділет департаменті Махамбет ауданының Әділет басқармасында 2009 жылғы 1 желтоқсанда № 4-3-134 тіркелді. Күші жойылды - Атырау облысы Махамбет ауданы Жалғансай селолық округі әкімінің 2010 жылғы 9 желтоқсандағы № 12 шешімімен
title:
  rus: Жалғансай селосындағы жаңа көшелерге атаулар беру туралы
  kaz: Жалғансай селосындағы жаңа көшелерге атаулар беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-11-03
approved_by:
- '156004009001'
version_date:
  kaz: 2009-11-03
source:
  kaz: https://zan.gov.kz/client/#!/doc/48884/kaz/03.11.2009
