act_code: '75751'
requisite: Решение Индерского районного маслихата Атырауской области от 27 ноября 2013 года № 155-V. Зарегистрировано Департаментом юстиции Атырауской области 10 декабря 2013 года № 2799. Утратило силу решением Индерского районного маслихата Атырауской области от 27 сентября 2022 года № 136-VІI (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждений перечня категорий получателей и предельных размеров социальной помощи
  kaz: Алушылар санатының тізбесін және әлеуметтік көмектің шекті мөлшерлерін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2013-11-27
approved_by:
- '156008000002'
version_date:
  kaz: 2019-05-16
  rus: 2019-05-16
source:
  kaz: https://zan.gov.kz/client/#!/doc/75751/kaz/16.05.2019
  rus: https://zan.gov.kz/client/#!/doc/75751/rus/16.05.2019
caused_by:
  code: '131778'
  requisite: Решение Индерского районного маслихата Атырауской области от 16 мая 2019 года № 289-VI. Зарегистрировано Департаментом юстиции Атырауской области 22 мая 2019 года № 4405. Утратило силу решением Индерского районного маслихата Атырауской области от 27 сентября 2022 года № 136-VІI (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
  title:
    rus: О внесении дополнений в решение районного маслихата от 27 ноября 2013 года № 155-V «Об утверждении перечня категорий получателей и предельных размеров социальной помощи»
    kaz: Аудандық мәслихаттың 2013 жылғы 27 қарашадағы № 155-V «Алушылар санатының тізбесін және әлеуметтік көмектің шекті мөлшерлерін бекіту туралы» шешіміне толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/131778/rus
