act_code: '33868'
requisite: Атырау облысы Жылыой ауданы әкімінің 2007 жылғы 10 мамырдағы № 12 шешімі. Жылыой аудандық Әділет басқармасында 2007 жылғы 15 маусымда № 4-2-68 болып тіркелді
title:
  rus: Орта білім беру оқу орындарының ер балалар-түлектерімен оқу-дала (лагерлік) жиындарын өткізу туралы
  kaz: Орта білім беру оқу орындарының ер балалар-түлектерімен оқу-дала (лагерлік) жиындарын өткізу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2007-05-10
approved_by:
- '156009000003'
version_date:
  kaz: 2007-05-10
source:
  kaz: https://zan.gov.kz/client/#!/doc/33868/kaz/10.05.2007
