act_code: '97773'
requisite: Решение Курмангазинского районного маслихата Атырауской области от 23 декабря 2015 года № 473-V. Зарегистрировано Департаментом юстиции Атырауской области 14 января 2016 года № 3438. Утратило силу решением Курмангазинского районного маслихата Атырауской области от 24 февраля 2017 года № 127-VI
title:
  rus: О районном бюджете на 2016 - 2018 годы
  kaz: 2016 - 2018  жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-12-23
approved_by:
- '156003000002'
version_date:
  kaz: 2016-12-14
  rus: 2016-12-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/97773/kaz/14.12.2016
  rus: https://zan.gov.kz/client/#!/doc/97773/rus/14.12.2016
caused_by:
  code: '108239'
  requisite: Решение Курмангазинского районного маслихата Атырауской области от 14 декабря 2016 года № 100-VI. Зарегистрировано Департаментом юстиции Атырауской области 15 декабря 2016 года № 3716
  title:
    rus: О внесении изменений и дополнения в решение районного маслихата от 23 декабря 2015 года №473-V «О районном бюджете на 2016-2018 годы»
    kaz: Аудандық мәслихаттың 2015 жылғы 23 желтоқсандағы №473-V «2016-2018 жылдарға арналған аудандық бюджет туралы» шешіміне өзгерістер мен толықтыру енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/108239/rus
