act_code: '97773'
requisite: Решение Курмангазинского районного маслихата Атырауской области от 23 декабря 2015 года № 473-V. Зарегистрировано Департаментом юстиции Атырауской области 14 января 2016 года № 3438. Утратило силу решением Курмангазинского районного маслихата Атырауской области от 24 февраля 2017 года № 127-VI
title:
  rus: О районном бюджете на 2016 - 2018 годы
  kaz: 2016 - 2018  жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-12-23
approved_by:
- '156003000002'
version_date:
  kaz: 2016-07-13
  rus: 2016-07-13
source:
  kaz: https://zan.gov.kz/client/#!/doc/97773/kaz/13.07.2016
  rus: https://zan.gov.kz/client/#!/doc/97773/rus/13.07.2016
caused_by:
  code: '104566'
  requisite: Решение Курмангазинского районного маслихата Атырауской области от 13 июля 2016 года № 51-VI. Зарегистрировано Департаментом юстиции Атырауской области 15 июля 2016 года № 3565. Утратило силу решением Курмангазинского районного маслихата Атырауской области от 24 февраля 2017 года № 127-VI
  title:
    rus: О внесении изменений и дополнений в решение районного маслихата от 23 декабря 2015 года №473-V «О районном бюджете на 2016 - 2018 годы»
    kaz: Аудандық мәслихаттың 2015 жылғы 23 желтоқсандағы №473-V «2016 - 2018 жылдарға арналған аудандық бюджет туралы» шешіміне өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/104566/rus
