act_code: '217104'
requisite: Решение акима Кенузекского сельского округа города Атырау Атырауской области от 19 ноября 2025 года № 633. Отменен решением Кенузекского сельского округа города Атырау Атырауской области от 23 января 2026 года № 19 (вводится в действие со дня подписания)
title:
  rus: Об установлении ограничительных мероприятий на территории Кенузекского сельского округа
  kaz: Кеңөзек ауылдық округі аумағында шектеу шараларын белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2025-11-19
approved_by:
- '156002009002'
version_date:
  kaz: 2025-11-19
  rus: 2025-11-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/217104/kaz/19.11.2025
  rus: https://zan.gov.kz/client/#!/doc/217104/rus/19.11.2025
