act_code: '186399'
requisite: Решение Махамбетского районного маслихата Атырауской области от 14 сентября 2023 года № 63. Зарегистрировано в Департаменте юстиции Атырауской области 22 сентября 2023 года № 5082-06
title:
  rus: Об утверждении правил оказания социальной помощи, установления ее размеров и определения перечня отдельных категорий нуждающихся граждан
  kaz: Әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың қағидаларын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2023-09-14
approved_by:
- '156004000002'
version_date:
  kaz: 2024-06-21
  rus: 2024-06-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/186399/kaz/21.06.2024
  rus: https://zan.gov.kz/client/#!/doc/186399/rus/21.06.2024
caused_by:
  code: '198064'
  requisite: Решение Махамбетского районного маслихата Атырауской области от 21 июня 2024 года № 125. Зарегистрировано в Департаменте юстиции Атырауской области 25 июня 2024 года № 5210-06
  title:
    rus: О внесении изменений в решение Махамбетского районного маслихата от 14 сентября 2023 года № 63 «Об утверждении правил оказания социальной помощи, установления ее размеров и определения перечня отдельных категорий нуждающихся граждан»
    kaz: Махамбет аудандық мәслихатының 2023 жылғы 14 қыркүйектегі № 63 «Әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың қағидаларын бекіту туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/198064/rus
