act_code: '157209'
requisite: Решение акима Макатского района Атырауской области от 21 июля 2021 года № 18. Зарегистрировано в Министерстве юстиции Республики Казахстан 22 июля 2021 года № 23654. Утратило силу решением акима Макатского района Атырауской области от 28 мая 2026 года № 17 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об образовании избирательных участков на территории Макатского района
  kaz: Мақат ауданының аумағында сайлау учаскелерін құру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-07-21
approved_by:
- '156006000003'
version_date:
  kaz: 2021-07-21
  rus: 2021-07-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/157209/kaz/21.07.2021
  rus: https://zan.gov.kz/client/#!/doc/157209/rus/21.07.2021
