act_code: '44590'
requisite: Атырау облысы Индер ауданы әкімінің 2009 жылғы 27 қаңтардағы № 4 шешімі. Атырау облысының Әділет департаменті Индер ауданының Әділет басқармасында 2009 жылғы 10 ақпанда № 4-6-77 тіркелді
title:
  rus: Индер ауданының 1992 жылы туған азаматтарын 2009 жылы шақыру учаскесіне тіркеуді өткізу туралы
  kaz: Индер ауданының 1992 жылы туған азаматтарын 2009 жылы шақыру учаскесіне тіркеуді өткізу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-01-27
approved_by:
- '156008000001'
version_date:
  kaz: 2009-01-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/44590/kaz/27.01.2009
