act_code: '146180'
requisite: Решение акима Тайсойганского сельского округа Кызылкогинского района Атырауской области от 7 сентября 2020 года № 9. Зарегистрировано Департаментом юстиции Атырауской области 9 сентября 2020 года № 4721
title:
  rus: Об утрате силы решения акима Тайсойганского сельского округа от 26 февраля 2020 года № 3 «Об установлении ограничительных мероприятий»
  kaz: Тайсойған ауылдық округі әкімінің 2020 жылғы 26 ақпандағы № 3 «Шектеу іс-шараларын белгілеу туралы» шешімінің күшін жою туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-09-07
approved_by:
- '156007009002'
version_date:
  kaz: 2020-09-07
  rus: 2020-09-07
source:
  kaz: https://zan.gov.kz/client/#!/doc/146180/kaz/07.09.2020
  rus: https://zan.gov.kz/client/#!/doc/146180/rus/07.09.2020
