act_code: '147097'
requisite: Решение Макатского районного маслихата Атырауской области от 30 сентября 2020 года № 404-VI. Зарегистрировано Департаментом юстиции Атырауской области 5 октября 2020 года № 4746. Утратило силу решением Макатского районного маслихата Атырауской области от 9 февраля 2024 года № 75-VIII (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: О проведении мирных собраний в Макатском районе
  kaz: Мақат ауданында бейбіт жиналыстарды өткізу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-09-30
approved_by:
- '156006000002'
version_date:
  kaz: 2020-09-30
  rus: 2020-09-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/147097/kaz/30.09.2020
  rus: https://zan.gov.kz/client/#!/doc/147097/rus/30.09.2020
