act_code: '76524'
requisite: Решение Махамбетского районного маслихата Атырауской области от 23 декабря 2013 года № 144. Зарегистрировано Департаментом юстиции Атырауской области 13 января 2014 года № 2834. Утратило силу решением Махамбетского районного маслихата Атырауской области от 26 февраля 2015 года № 262
title:
  rus: О районном бюджете на 2014 – 2016 годы
  kaz: 2014 - 2016 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2013-12-23
approved_by:
- '156004000002'
version_date:
  rus: 2014-04-16
source:
  rus: https://zan.gov.kz/client/#!/doc/76524/rus/16.04.2014
caused_by:
  code: '79794'
  requisite: Решение Махамбетского районного маслихата Атырауской области от 16 апреля 2014 года № 196. Зарегистрировано Департаментом юстиции Атырауской области 14 мая 2014 года № 2919. Утратило силу решением Махамбетского районного маслихата Атырауской области от 26 февраля 2015 года № 262
  title:
    rus: О внесении изменений и дополнений в решение Махамбетского районного маслихата от 23 декабря 2013 года № 144 "О районном бюджете на 2014 – 2016 годы"
    kaz: Махамбет аудандық мәслихатының 2013 жылғы 23 желтоқсандағы № 144 "2014-2016 жылдарға арналған аудандық бюджеті туралы" шешіміне өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/79794/rus
