act_code: '32178'
requisite: Атырау облысы Мақат ауданы әкімінің 2007 жылғы 12 ақпандағы № 4 шешімі. Атырау облысының Әділет департаменті Мақат ауданының Әділет басқармасында 2007 жылғы 28 ақпанда № 4-7-51 болып тіркелді
title:
  rus: Мақат ауданында әскери міндеттілер мен әскерге шақырушылардың есебін жүргізу туралы
  kaz: Мақат ауданында әскери міндеттілер мен әскерге шақырушылардың есебін жүргізу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2007-02-12
approved_by:
- '156006000003'
version_date:
  kaz: 2007-02-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/32178/kaz/12.02.2007
