act_code: '194353'
requisite: Решение акима Бөкейханского сельского округа Курмангазинского района Атырауской области от 14 марта 2024 года № 6
title:
  rus: О присвоении наименования новой улице в селе Бөкейхан
  kaz: Бөкейхан ауылындағы жаңа көшеге атау беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-03-14
approved_by:
- '156003004002'
version_date:
  kaz: 2024-03-14
  rus: 2024-03-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/194353/kaz/14.03.2024
  rus: https://zan.gov.kz/client/#!/doc/194353/rus/14.03.2024
