act_code: '97526'
requisite: Решение акима поселка Индербор Индерского района Атырауской области от 23 декабря 2015 года № 139. Зарегистрировано Департаментом юстиции Атырауской области 05 января 2016 года № 3417
title:
  rus: 'О переименовании некоторых улиц поселка Индербор Индерского района '
  kaz: 'Индер ауданы Индербор кентінің кейбір көшелерін қайта атау туралы '
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-12-23
approved_by:
- '156008007001'
version_date:
  kaz: 2015-12-23
  rus: 2015-12-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/97526/kaz/23.12.2015
  rus: https://zan.gov.kz/client/#!/doc/97526/rus/23.12.2015
