act_code: '189699'
requisite: Решение Макатского районного маслихата Атырауской области от 30 ноября 2023 года № 58-VIII. Зарегистрировано в Департаменте юстиции Атырауской области 8 декабря 2023 года № 5103-06
title:
  rus: Об утверждении проектов (схем) зонирования земель, границ оценочных зон и поправочных коэффициентов к базовым ставкам платы за земельные участки Макатского района
  kaz: Мақат ауданының жерлерін аймақтарға бөлу жобаларын (схемаларын), бағалау аймақтарының шекараларын және жер учаскелері үшін төлемақының базалық ставкаларына түзету коэффициенттерін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2023-11-30
approved_by:
- '156006000002'
version_date:
  kaz: 2023-11-30
  rus: 2023-11-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/189699/kaz/30.11.2023
  rus: https://zan.gov.kz/client/#!/doc/189699/rus/30.11.2023
