act_code: '8811'
requisite: Решение акима Атырауской области от 23 апреля 2001 года № 149. Зарегистрировано Управлением юстиции Атырауской области 28 апреля 2001 года № 413
title:
  rus: О структуре акимата области
  kaz: Облыс әкімиятының құрылымы туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2001-04-22
approved_by:
- '156000000003'
version_date:
  kaz: 2001-04-22
  rus: 2001-04-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/8811/kaz/22.04.2001
  rus: https://zan.gov.kz/client/#!/doc/8811/rus/22.04.2001
