act_code: '221641'
requisite: Решение акима Уильского сельского округа Кызылкогинского района Атырауской области от 29 января 2026 года № 7
title:
  rus: О присвоении наименования улице
  kaz: Көше атауын беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2026-01-29
approved_by:
- '156007004002'
version_date:
  kaz: 2026-01-29
  rus: 2026-01-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/221641/kaz/29.01.2026
  rus: https://zan.gov.kz/client/#!/doc/221641/rus/29.01.2026
