act_code: '181207'
requisite: Решение акима Баксайского сельского округа Махамбетского района Атырауской области от 25 ноября 2022 года № 84. Зарегистрировано в Министерстве юстиции Республики Казахстан 28 ноября 2022 года № 30776
title:
  rus: О присвоении наименования новой улице села Тандай Баксайского сельского округа Махамбетского района
  kaz: Махамбет ауданы Бақсай ауылдық округі Таңдай ауылының жаңа көшеге атау беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-11-25
approved_by:
- '156004011002'
version_date:
  kaz: 2022-11-25
  rus: 2022-11-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/181207/kaz/25.11.2022
  rus: https://zan.gov.kz/client/#!/doc/181207/rus/25.11.2022
