act_code: '133244'
requisite: Решение акима Забурунского сельского округа Исатайского района Атырауской области от 10 июля 2019 года № 12. Зарегистрировано Департаментом юстиции Атырауской области 11 июля 2019 года № 4446. Утратило силу решением акима Зинеденского сельского округа Исатайского района Атырауской области от 25 июня 2020 года № 16 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об установлении ограничительных мероприятий
  kaz: Шектеу іс-шараларын белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-07-10
approved_by:
- '156005004002'
version_date:
  kaz: 2019-07-10
  rus: 2019-07-10
source:
  kaz: https://zan.gov.kz/client/#!/doc/133244/kaz/10.07.2019
  rus: https://zan.gov.kz/client/#!/doc/133244/rus/10.07.2019
