act_code: '31731'
requisite: Атырау облысы Құрманғазы аудандық мәслихатының 2006 жылғы 15 желтоқсандағы № 305-XXXIY шешімі. Атырау облысының Құрманғазы аудандық Әділет басқармасында 2006 жылғы 25 желтоқсанда № 4-8-69 болып тіркелді
title:
  rus: 2007 жылға жеке кәсіпкер, заңды тұлға, оның бөлімдері, құрылымдары және басқа да жекеленген структуралық ойын бизнесі саласында көрсеткен қызметіне тіркелген жиынтық салық ставкаларының мөлшері туралы
  kaz: 2007 жылға жеке кәсіпкер, заңды тұлға, оның бөлімдері, құрылымдары және басқа да жекеленген структуралық ойын бизнесі саласында көрсеткен қызметіне тіркелген жиынтық салық ставкаларының мөлшері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2006-12-15
approved_by:
- '156003000002'
version_date:
  kaz: 2006-12-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/31731/kaz/15.12.2006
