act_code: '175316'
requisite: Решение акима поселка Макат Макатского района Атырауской области от 8 декабря 2022 года № 131. Зарегистрировано в Министерстве юстиции Республики Казахстан 13 декабря 2022 года № 31086
title:
  rus: О присвоении наименований и переименований улиц в поселке Макат
  kaz: Мақат кентінде көшелерге атаулар беру және қайта атау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-12-08
approved_by:
- '156006001001'
version_date:
  kaz: 2022-12-08
  rus: 2022-12-08
source:
  kaz: https://zan.gov.kz/client/#!/doc/175316/kaz/08.12.2022
  rus: https://zan.gov.kz/client/#!/doc/175316/rus/08.12.2022
