act_code: '52033'
requisite: Решение Атырауского областного маслихата от 31 марта 2010 года № 318-IV. Зарегистрировано Департаментом юстиции Атырауской области 28 апреля 2010 года за № 2565. Утратило силу - решением Атырауского областного маслихата от 6 марта 2014 года № 231-V
title:
  rus: Об утверждении ставок платежей за размещение наружной (визуальной) рекламы в полосе отвода автомобильных дорог областного значения по Атырауской области
  kaz: Атырау облысы бойынша облыстық маңызы бар автомобиль жолдарының бөлінген белдеулерінде сыртқы (көрнекі) жарнаманы орналастырғаны үшін төлемақы ставкаларын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-03-31
approved_by:
- '156000000002'
version_date:
  kaz: 2010-03-31
  rus: 2010-03-31
source:
  kaz: https://zan.gov.kz/client/#!/doc/52033/kaz/31.03.2010
  rus: https://zan.gov.kz/client/#!/doc/52033/rus/31.03.2010
