act_code: '123342'
requisite: Решение акима Курмангазинского района Атырауской области от 27 июня 2018 года № 23. Зарегистрировано Департаментом юстиции Атырауской области 11 июля 2018 года № 4196. Утратило силу решением акима Курмангазинского района Атырауской области от 12 июля 2021 года № 26 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об образовании избирательных участков на территории Курмангазинского района
  kaz: Құрманғазы ауданы аумағында сайлау учаскелерін құру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-06-27
approved_by:
- '156003000003'
version_date:
  kaz: 2018-06-27
  rus: 2018-06-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/123342/kaz/27.06.2018
  rus: https://zan.gov.kz/client/#!/doc/123342/rus/27.06.2018
