act_code: '29871'
requisite: Атырау облысы Мақат ауданы әкімінің 2006 жылғы 16 қазандағы № 19 шешімі. Мақат аудандық Әділет басқармасында 2006 жылғы 18 қазанда № 4-7-46 болып тіркелді
title:
  rus: Аудан көлеміндегі Қазақстан Республикасының Қарулы Күштеріне шақырушылар қатарынан 2006-2007 жылдарға азаматтарды әскери техникалық мамандықтар бойынша даярлау туралы
  kaz: Аудан көлеміндегі Қазақстан Республикасының Қарулы Күштеріне шақырушылар қатарынан 2006-2007 жылдарға азаматтарды әскери техникалық мамандықтар бойынша даярлау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2006-10-16
approved_by:
- '156006000003'
version_date:
  kaz: 2006-10-16
source:
  kaz: https://zan.gov.kz/client/#!/doc/29871/kaz/16.10.2006
