act_code: '48080'
requisite: Атырау облысы Махамбет ауданы Бақсай селолық округі әкімінің 2009 жылғы 10 қыркүйектегі № 21 шешімі. Атырау облысы Әділет департаменті Махамбет ауданының Әділет басқармасында 2009 жылғы 7 қазанда № 4-3-125 тіркелді. Күші жойылды - Атырау облысы Махамбет ауданы Бақсай селолық округі әкімінің 2010 жылғы 19 қарашадағыі № 15 шешімімен
title:
  rus: Бақсай селолық округіне қарасты елді мекендердегі көшелерге атаулар беру туралы
  kaz: Бақсай селолық округіне қарасты елді мекендердегі көшелерге атаулар беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-09-10
approved_by:
- '156004011002'
version_date:
  kaz: 2009-09-10
source:
  kaz: https://zan.gov.kz/client/#!/doc/48080/kaz/10.09.2009
