act_code: '108588'
requisite: Решение акима Миялинского сельского округа Кызылкогинского района Атырауской области от 12 декабря 2016 года № 102. Зарегистрировано Департаментом юстиции Атырауской области 27 декабря 2016 года № 3724. Утратило силу решением акима Миялинского сельского округа Кызылкогинского района Атырауской области от 24 марта 2017 года № 5
title:
  rus: Об установлении ограничительных мероприятий
  kaz: Шектеу іс-шараларын белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2016-12-12
approved_by:
- '156007010001'
version_date:
  kaz: 2016-12-12
  rus: 2016-12-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/108588/kaz/12.12.2016
  rus: https://zan.gov.kz/client/#!/doc/108588/rus/12.12.2016
