act_code: '167060'
requisite: Решение акима города Атырау Атырауской области от 20 апреля 2022 года № 19. Зарегистрировано в Министерстве юстиции Республики Казахстан 27 апреля 2022 года № 27784. Утратило силу решением акима города Атырау Атырауской области от 14 июня 2022 года № 27 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об объявлении чрезвычайной ситуации природного характера местного масштаба
  kaz: Жергілікті ауқымдағы табиғи сипаттағы төтенше жағдайды жариялау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-04-20
approved_by:
- '156002000003'
version_date:
  kaz: 2022-04-20
  rus: 2022-04-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/167060/kaz/20.04.2022
  rus: https://zan.gov.kz/client/#!/doc/167060/rus/20.04.2022
