act_code: '33130'
requisite: Атырау облысы Исатай ауданы мәслихатының 2007 жылғы 16 сәуірдегі № 255-ІІІ шешімі. Атырау облысының Әділет департаментінде 2007 жылғы 7 мамырда  № 4-4-65 болып тіркелді
title:
  rus: Ауданның елді мекендерінде орналасқан базар, жанар-жағар май сатушы, автотұрақтар орналасқан телімдер мен санитарлық қорғаушы аймақтары алып жатқан жерлерге, елді мекендерден тыс орналасқан өнеркәсіп жерлеріне салынатын жер салығы мөлшерін 2007 жылға белгілеу туралы
  kaz: Ауданның елді мекендерінде орналасқан базар, жанар-жағар май сатушы, автотұрақтар орналасқан телімдер мен санитарлық қорғаушы аймақтары алып жатқан жерлерге, елді мекендерден тыс орналасқан өнеркәсіп жерлеріне салынатын жер салығы мөлшерін 2007 жылға белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2007-04-16
approved_by:
- '156005000002'
version_date:
  kaz: 2007-04-16
source:
  kaz: https://zan.gov.kz/client/#!/doc/33130/kaz/16.04.2007
