act_code: '21216'
requisite: Атырау облысы Қызылқоға аудандық мәслихатының 2004 жылғы 3 қыркүйектегі № VII-1 шешімі. Атырау облысының Әділет департаментінде 2004 жылғы 7 қыркүйекте № 2128 болып тіркелді
title:
  rus: Қызылқоға ауданының «Құрметті азаматы» атағы туралы Ережеге өзгертулер енгізу туралы
  kaz: Қызылқоға ауданының «Құрметті азаматы» атағы туралы Ережеге өзгертулер енгізу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2004-09-02
approved_by:
- '156007000002'
version_date:
  kaz: 2004-09-02
source:
  kaz: https://zan.gov.kz/client/#!/doc/21216/kaz/02.09.2004
