act_code: '31702'
requisite: Атырау облысы Мақат ауданы әкімінің 2006 жылғы 22 желтоқсандағы № 23 шешімі. Мақат аудандық Әділет басқармасында 2006 жылғы 29 желтоқсанда № 4-7-50 болып тіркелді
title:
  rus: Мақат ауданының 1990 жылы туған азаматтарын 2007 жылы шақыру учаскелеріне тіркеуді өткізу туралы
  kaz: Мақат ауданының 1990 жылы туған азаматтарын 2007 жылы шақыру учаскелеріне тіркеуді өткізу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2006-12-22
approved_by:
- '156006000003'
version_date:
  kaz: 2006-12-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/31702/kaz/22.12.2006
