act_code: '10011'
requisite: Решение акима Атырауской области от 11 июля 2001 года № 248. Зарегистрировано Управлением юстиции Атырауской области 24 августа 2001 года № 587
title:
  rus: О неотложных мерах по обеспечению безопасности граждан на водоемах Атырауской области в 2001 году
  kaz: 2001 жылғы Атырау облысының су тоғандарында азаматтардың қауіпсіздігін қамтамасыз ету жөніндегі шұғыл шаралар туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2001-07-10
approved_by:
- '156000000003'
version_date:
  kaz: 2001-07-10
  rus: 2001-07-10
source:
  kaz: https://zan.gov.kz/client/#!/doc/10011/kaz/10.07.2001
  rus: https://zan.gov.kz/client/#!/doc/10011/rus/10.07.2001
