act_code: '50269'
requisite: Решение Индерского районного маслихата Атырауской области от 23 декабря 2009 года № 191-IV. Зарегистрировано Управлением юстиции Индерского района Атырауской области 26  января 2010 года № 4-6-93. Утратило силу решением Индерского районного маслихата Атырауской области от 14 декабря 2010 года № 258-V
title:
  rus: Салық ставкаларын белгілеу туралы
  kaz: Салық ставкаларын белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-12-23
approved_by:
- '156008000002'
version_date:
  kaz: 2009-12-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/50269/kaz/23.12.2009
