act_code: '163282'
requisite: Решение Жылыойского районного маслихата Атырауской области от 30 декабря 2021 года № 15-1
title:
  rus: О бюджетах города Кульсары, поселка Жана-Каратон, сельских округов Жем, Косчагиль, Кара-Арна, Майкумгени Аккиизтогай на 2022-2024 годы
  kaz: 2022-2024 жылдарға арналған Құлсары қаласының, Жаңа-Қаратон кентінің, Жем, Қосшағыл, Қара-Арна, Майкөмген және Ақкиізтоғай ауылдық округтерінің бюджеттері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-12-30
approved_by:
- '156009000002'
version_date:
  kaz: 2022-03-31
  rus: 2022-03-31
source:
  kaz: https://zan.gov.kz/client/#!/doc/163282/kaz/31.03.2022
  rus: https://zan.gov.kz/client/#!/doc/163282/rus/31.03.2022
caused_by:
  code: '166395'
  requisite: Решение Жылыойского районного маслихата Атырауской области от 31 марта 2022 года № 18-1
  title:
    rus: О внесении изменений в решение Жылыойского районного маслихата «О бюджетах города Кульсары, поселка Жана-Каратон, сельских округов Жем, Косчагиль, Кара-Арна, Майкумген и Аккиизтогай на 2022-2024 годы» от 30 декабря 2021 года № 15-1
    kaz: «2022-2024 жылдарға арналған Құлсары қаласының, Жаңа-Қаратон кентінің, Жем, Қосшағыл, Қара-Арна, Майкөмген және Ақкиізтоғай ауылдық округтерінің бюджеттері туралы» Жылыой аудандық мәслихатының 2021 жылғы 30 желтоқсандағы № 15-1 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/166395/rus
