act_code: '215003'
requisite: Решение акима Жарсуатского сельского округа Индерского района Атырауской области от 22 сентября 2025 года № 42
title:
  rus: О найменовании и переименовании улиц в селах Жарсуат, Курылыс Жарсуатского сельского округа
  kaz: Жарсуат ауылдық округінің Жарсуат, Құрылыс ауылындағы көшелерге атау беру және қайта атау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2025-09-22
approved_by:
- '156008003002'
version_date:
  kaz: 2025-09-22
  rus: 2025-09-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/215003/kaz/22.09.2025
  rus: https://zan.gov.kz/client/#!/doc/215003/rus/22.09.2025
