act_code: '12089'
requisite: Атырау облысы мәслихатының 2001 жылғы 27 желтоқсандағы № 174-II шешімі. Атырау облысының Әділет басқармасында 2002 жылғы 13 ақпанда № 781 болып тіркелді
title:
  rus: Атырау облысы демографиялық дамуының 2001-2005 жылдарға арналған бағдарламасы туралы 2001
  kaz: Атырау облысы демографиялық дамуының 2001-2005 жылдарға арналған бағдарламасы туралы 2001
form: РЕШ
type_codes:
- РЕШ
approved_on: 2001-12-27
approved_by:
- '156000000002'
version_date:
  kaz: 2001-12-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/12089/kaz/27.12.2001
