act_code: '146988'
requisite: Решение Индерского районного маслихата Атырауской области от 18 сентября 2020 года № 395-VI. Зарегистрировано Департаментом юстиции Атырауской области 1 октября 2020 года № 4738. Утратило силу решением Индерского районного маслихата Атырауской области от 28 июня 2024 года № 99-VIII (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: О проведении мирных собраний в Индерском районе
  kaz: Индер ауданында бейбіт жиналыстарды өткізу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-09-18
approved_by:
- '156008000002'
version_date:
  kaz: 2020-09-18
  rus: 2020-09-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/146988/kaz/18.09.2020
  rus: https://zan.gov.kz/client/#!/doc/146988/rus/18.09.2020
