act_code: '44022'
requisite: Атырау облысы Махамбет ауданы әкімінің 2009 жылғы 19 қаңтардағы № 1 шешімі. Атырау облысы Әділет департаменті Махамбет ауданының Әділет басқармасында 2009 жылғы 5 ақпанда 4-3-112 тіркелді
title:
  rus: 1992 жылы туылған азаматтарды шақыру учаскелеріне тіркеуді жүргізу туралы
  kaz: 1992 жылы туылған азаматтарды шақыру учаскелеріне тіркеуді жүргізу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-01-19
approved_by:
- '156004000001'
version_date:
  kaz: 2009-01-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/44022/kaz/19.01.2009
