act_code: '20459'
requisite: Постановление акимата Атырауской области от 6 июня 2004 года № 1. Зарегистрировано Департаментом юстиции Атырауской области от 30 июня 2004 года № 2037
title:
  rus: Об утверждении плана мероприятий по профилактике карантинных и особо опасных инфекций в Атырауской области на 2004-2006 годы
  kaz: Атырау облысында карантиндік және аса қауіпті жұқпалы аурулардың алдын алу жөніндегі 2004-2006 жылдарға арналған іс-шаралар жоспарын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2004-06-05
approved_by:
- '156000000001'
version_date:
  kaz: 2004-06-05
  rus: 2004-06-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/20459/kaz/05.06.2004
  rus: https://zan.gov.kz/client/#!/doc/20459/rus/05.06.2004
