act_code: '96427'
requisite: Решение Атырауского городского маслихата Атырауской области от 19 ноября 2015 года № 308. Зарегистрировано Департаментом юстиции Атырауской области 10 декабря 2015 года № 3389. Утратило силу решением маслихата города Атырау Атырауской области от 12 апреля 2024 года № 102 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об определении размера и порядка оказания жилищной помощи в городе Атырау
  kaz: Атырау қаласында тұрғын үй көмегін көрсетудің мөлшері мен тәртібін айқындау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-11-19
approved_by:
- '156002000002'
version_date:
  kaz: 2020-04-10
  rus: 2020-04-10
source:
  kaz: https://zan.gov.kz/client/#!/doc/96427/kaz/10.04.2020
  rus: https://zan.gov.kz/client/#!/doc/96427/rus/10.04.2020
caused_by:
  code: '141820'
  requisite: Решение Атырауского городского маслихата Атырауской области от 10 апреля 2020 года № 486. Зарегистрировано Департаментом юстиции Атырауской области 16 апреля 2020 года № 4640. Утратило силу решением маслихата города Атырау Атырауской области от 12 апреля 2024 года № 102 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
  title:
    rus: О внесении изменений в решение Атырауского городского маслихата от 19 ноября 2015 года № 308 «Об утверждении правил оказания жилищной помощи малообеспеченным семьям (гражданам), проживающим в городе Атырау»
    kaz: Атырау қалалық мәслихатының 2015 жылғы 19 қарашадағы № 308 «Атырау қаласында тұратын аз қамтылған отбасыларға (азаматтарға) тұрғын үй көмегін көрсетудің қағидасын бекіту туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/141820/rus
