act_code: '220182'
requisite: Решение Курмангазинского районного маслихата Атырауской области от 22 декабря 2025 года № 254-VIII
title:
  rus: Об утверждении бюджетов сельских округов Курмангазинского района на 2026-2028 годы
  kaz: 2026-2028 жылдарға арналған Құрманғазы ауданының ауылдық округтерінің бюджеттерін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2025-12-22
approved_by:
- '156003000002'
version_date:
  kaz: 2025-12-22
  rus: 2025-12-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/220182/kaz/22.12.2025
  rus: https://zan.gov.kz/client/#!/doc/220182/rus/22.12.2025
