act_code: '97600'
requisite: Решение Исатайского районного маслихата Атырауской области от 23 декабря 2015 года № 291-V. Зарегистрировано Департаментом юстиции Атырауской области 15 января 2016 года № 3444. Утратило силу решением Исатайского районного маслихата Атырауской области от 24 марта 2017 года № 80-VI
title:
  rus: О  районном бюджете на 2016-2018 годы
  kaz: 2016-2018   жылдарға  арналған аудандық  бюджет  туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-12-23
approved_by:
- '156005000002'
version_date:
  kaz: 2016-11-04
  rus: 2016-11-04
source:
  kaz: https://zan.gov.kz/client/#!/doc/97600/kaz/04.11.2016
  rus: https://zan.gov.kz/client/#!/doc/97600/rus/04.11.2016
caused_by:
  code: '107674'
  requisite: Решение Исатайского районного маслихата Атырауской области от 4 ноября 2016 года № 53-VI. Зарегистрировано Департаментом юстиции Атырауской области 22 ноября 2016 года № 3678. Утратило силу решением Исатайского районного маслихата Атырауской области от 24 марта 2017 года № 80-VI
  title:
    rus: О внесении изменений и дополнения в решение XXXIV cессии районного маслихата V созыва от 23 декабря 2015 года №291-V «О районном бюджете на 2016-2018  годы»
    kaz: V шақырылған аудандық мәслихаттың XXXIV cессиясының 2015 жылғы 23 желтоқсандағы №291-V «2016-2018 жылдарға арналған аудандық бюджет туралы»  шешіміне өзгерістер мен толықтыру енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/107674/rus
