act_code: '37766'
requisite: Атырау облысы Жылыой аудандық мәслихатының 2007 жылғы 19 желтоқсандағы № 3-2 шешімі. Атырау облысы Жылыой аудандық Әділет басқармасында 2008 жылғы 8 қаңтарда № 4-2-75 болып тіркелді
title:
  rus: Жылыой ауданының 2008 жылға арналған аудандық бюджеті туралы
  kaz: Жылыой ауданының 2008 жылға арналған аудандық бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2007-12-19
approved_by:
- '156009000002'
version_date:
  kaz: 2007-12-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/37766/kaz/19.12.2007
