act_code: '118059'
requisite: Решение Атырауского городского маслихата Атырауской области от 21 декабря 2017 года № 185. Зарегистрировано Департаментом юстиции Атырауской области 12 января 2018 года № 4041
title:
  rus: Об утверждении плана по управлению пастбищами города Атырау и их использованию на 2018-2019 годы
  kaz: Атырау қаласының жайылымдарды басқару және оларды пайдалану жөніндегі 2018-2019 жылдарға арналған жоспарын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2017-12-21
approved_by:
- '156002000002'
version_date:
  kaz: 2017-12-21
  rus: 2017-12-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/118059/kaz/21.12.2017
  rus: https://zan.gov.kz/client/#!/doc/118059/rus/21.12.2017
