act_code: '81868'
requisite: Решение от 23.07.2014 №243-V, Маслихат Макатского района. Утратило силу - решением Макатского районного маслихата Атырауской области  от 17 сентября 2015 года № 326-V.
title:
  rus: О назначении материального обеспечения детям-инвалидам, обучающимся на дому
  kaz: Үйде оқитын мүгедек балаларға материалдық қамсыздандыруды тағайындау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2014-07-23
approved_by:
- '156006000002'
version_date:
  kaz: 2014-07-23
  rus: 2014-07-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/81868/kaz/23.07.2014
  rus: https://zan.gov.kz/client/#!/doc/81868/rus/23.07.2014
