act_code: '78107'
requisite: Решение Курмангазинского районного маслихата Атырауской области от 12 февраля 2014 года № 275-V. Зарегистрировано Департаментом юстиции Атырауской области 19 марта 2014 года № 2875. Утратило силу решением Курмангазинского районного маслихата Атырауской области от 29 сентября 2017 года № 203-VI
title:
  rus: Об утверждении регламента Курмангазинского районного маслихата
  kaz: Құрманғазы аудандық мәслихатының регламентін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2014-02-12
approved_by:
- '156003000002'
version_date:
  kaz: 2014-02-12
  rus: 2014-02-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/78107/kaz/12.02.2014
  rus: https://zan.gov.kz/client/#!/doc/78107/rus/12.02.2014
