act_code: '191740'
requisite: Решение Курмангазинского районного маслихата Атырауской области от 25 декабря 2023 года № 89-VIII
title:
  rus: Об утверждении районного бюджета на 2024-2026 годы
  kaz: 2024-2026 жылдарға арналған ауданның бюджетін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2023-12-25
approved_by:
- '156003000002'
version_date:
  kaz: 2024-04-25
  rus: 2024-04-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/191740/kaz/25.04.2024
  rus: https://zan.gov.kz/client/#!/doc/191740/rus/25.04.2024
caused_by:
  code: '196334'
  requisite: Решение Курмангазинского районного маслихата Атырауской области от 25 апреля 2024 года № 122-VIII
  title:
    rus: О внесении изменений и дополнений в решение районного маслихата от 25 декабря 2023 года № 89-VІІІ «Об утверждении районного бюджета на 2024-2026 годы»
    kaz: Аудандық мәслихаттың 2023 жылғы 25 желтоқсандағы № 89-VІІІ «2024-2026 жылдарға арналған ауданның бюджетін бекіту туралы» шешіміне өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/196334/rus
