act_code: '175818'
requisite: Решение Исатайского районного маслихата Атырауской области от 12 декабря 2022 года № 172-VII. Зарегистрировано в Министерстве юстиции Республики Казахстан 21 декабря 2022 года № 31186
title:
  rus: Об утверждении проектов (схем) зонирования земель, границ оценочных зон и поправочных коэффициентов к базовым ставкам платы за земельные участки сельских населенных пунктов Исатайского района
  kaz: Исатай ауданының ауылдық елді мекен жерлерін аймақтарға бөлу жобаларын (схемаларын), бағалау аймақтарының шекараларын және жер учаскелері үшін төлемақының базалық ставкаларына түзету коэффициенттерін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-12-12
approved_by:
- '156005000002'
version_date:
  kaz: 2022-12-12
  rus: 2022-12-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/175818/kaz/12.12.2022
  rus: https://zan.gov.kz/client/#!/doc/175818/rus/12.12.2022
