act_code: '102394'
requisite: Решение акима Кара-Арнинского сельского округа Жылыойского района Атырауской области от 10 декабря 2010 года № 31
title:
  rus: О признании  утратившим силу  решения акима Кара Арнинского сельского округа от 13 ноября 2008 года №46  «О присвоении названии улицам»
  kaz: Қара Арна  селолық округ  әкімінің 2008 жылғы 13 қарашадағы №46 «Көше атын беру туралы» шешімінің күшін жою туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-12-10
approved_by:
- '156009005001'
version_date:
  kaz: 2010-12-10
  rus: 2010-12-10
source:
  kaz: https://zan.gov.kz/client/#!/doc/102394/kaz/10.12.2010
  rus: https://zan.gov.kz/client/#!/doc/102394/rus/10.12.2010
