act_code: '96841'
requisite: Решение от 22.12.2015 №646, Акимат Кайыршахтинского сельского округа. Зарегистрировано Департаментом юстиции Атырауской области 29 декабря 2015 года № 3414
title:
  rus: О присвоении наименовании улицам
  kaz: Көшелерге атау беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-12-22
approved_by:
- '156002008001'
version_date:
  kaz: 2015-12-22
  rus: 2015-12-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/96841/kaz/22.12.2015
  rus: https://zan.gov.kz/client/#!/doc/96841/rus/22.12.2015
