act_code: '37776'
requisite: Атырау облысы Махамбет аудандық мәслихатының 2007 жылғы 19 желтоқсандағы № 28 шешімі. Атырау облысы Махамбет аудандық Әділет басқармасында 2008 жылғы 14 қаңтарда № 4-3-78 болып тіркелді
title:
  rus: 2008 жылға салық ставкалары мен басқа да төлем мөлшерлерін белгілеу туралы
  kaz: 2008 жылға салық ставкалары мен басқа да төлем мөлшерлерін белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2007-12-19
approved_by:
- '156004000002'
version_date:
  kaz: 2007-12-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/37776/kaz/19.12.2007
