act_code: '215556'
requisite: Решение акима Мукурского сельского округа Кызылкогинского района Атырауской области от 14 октября 2025 года № 45
title:
  rus: О присвоении наименования улице
  kaz: Көше атауын беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2025-10-14
approved_by:
- '156007002002'
version_date:
  kaz: 2025-10-14
  rus: 2025-10-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/215556/kaz/14.10.2025
  rus: https://zan.gov.kz/client/#!/doc/215556/rus/14.10.2025
