act_code: '12481'
requisite: Атырау облысы әкiмiнiң 2002 жылғы 31 мамырдағы № 439 шешiмі. Атырау облысының Әділет басқармасында 2002 жылғы 14 маусымда № 1006 тіркелді
title:
  rus: Облыс әкімінің 1999 жылғы 28 желтоқсандағы № 293 "Заңсыз жолмен ауланған балықты тапсыруды тәртiпке келтiру туралы" және 2000 жылғы 18 сәуiрдегi № 441 "Облыс әкiмiнiң 1999 жылғы 28 желтоқсандағы № 293 "Заңсыз жолмен ауланған балықты тапсыруды тәртiпке келтiру туралы" шешiмiне толықтырулар енгiзу туралы" шешiмдерiнiң күшi жойылуы туралы
  kaz: Облыс әкімінің 1999 жылғы 28 желтоқсандағы № 293 "Заңсыз жолмен ауланған балықты тапсыруды тәртiпке келтiру туралы" және 2000 жылғы 18 сәуiрдегi № 441 "Облыс әкiмiнiң 1999 жылғы 28 желтоқсандағы № 293 "Заңсыз жолмен ауланған балықты тапсыруды тәртiпке келтiру туралы" шешiмiне толықтырулар енгiзу туралы" шешiмдерiнiң күшi жойылуы туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2002-05-30
approved_by:
- '156000000003'
version_date:
  kaz: 2002-05-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/12481/kaz/30.05.2002
