act_code: '214751'
requisite: Решение Исатайского районного маслихата Атырауской области от 24 сентября 2025 года № 195-VIII
title:
  rus: Об утверждении Плана по управлению пастбищами и их использованию по Исатайскому району на 2025-2030 годы
  kaz: Исатай ауданы бойынша 2025-2030 жылдарға арналған жайылымдарды басқару және оларды пайдалану жөніндегі жоспарын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2025-09-24
approved_by:
- '156005000002'
version_date:
  kaz: 2025-09-24
  rus: 2025-09-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/214751/kaz/24.09.2025
  rus: https://zan.gov.kz/client/#!/doc/214751/rus/24.09.2025
