act_code: '77541'
requisite: Решение Атырауского городского маслихата Атырауской области от 03 февраля 2014 года № 175. Зарегистрировано Департаментом юстиции Атырауской области 24 февраля 2014 года № 2856. Утратило силу решением маслихата города Атырау Атырауской области от 24 мая 2022 года № 166 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об установлении перечня памятных дат и праздничных дней, кратности оказания социальной помощи и установление размера социальной помощи для отдельно взятой категории получателей
  kaz: Алушылардың жекелеген санаттары үшін әлеуметтік көмек көрсету еселігін және әлеуметтік көмек мөлшерін, атаулы күндер мен мереке күндерінің тізбесін белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2014-02-03
approved_by:
- '156002000002'
version_date:
  kaz: 2014-02-03
  rus: 2014-02-03
source:
  kaz: https://zan.gov.kz/client/#!/doc/77541/kaz/03.02.2014
  rus: https://zan.gov.kz/client/#!/doc/77541/rus/03.02.2014
