act_code: '150761'
requisite: Решение Жылыойского районного маслихата Атырауской области от 15 декабря 2020 года № 54-2. Зарегистрировано Департаментом юстиции Атырауской области 28 декабря 2020 года № 4844
title:
  rus: О районном бюджете на 2021-2023 годы
  kaz: 2021-2023 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-12-15
approved_by:
- '156009000002'
version_date:
  kaz: 2021-03-26
  rus: 2021-03-26
source:
  kaz: https://zan.gov.kz/client/#!/doc/150761/kaz/26.03.2021
  rus: https://zan.gov.kz/client/#!/doc/150761/rus/26.03.2021
caused_by:
  code: '154464'
  requisite: Решение Жылыойского районного маслихата Атырауской области от 26 марта 2021 года № 3-1. Зарегистрировано Департаментом юстиции Атырауской области 8 апреля 2021 года № 4913
  title:
    rus: О внесении изменений в решение Жылыойского районного маслихата от 15 декабря 2020 года № 54-2 «О районном бюджете на 2021-2023 годы»
    kaz: Жылыой аудандық мәслихатының 2020 жылғы 15 желтоқсандағы № 54-2 «2021-2023 жылдарға арналған аудандық бюджет туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/154464/rus
