act_code: '150761'
requisite: Решение Жылыойского районного маслихата Атырауской области от 15 декабря 2020 года № 54-2. Зарегистрировано Департаментом юстиции Атырауской области 28 декабря 2020 года № 4844
title:
  rus: О районном бюджете на 2021-2023 годы
  kaz: 2021-2023 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-12-15
approved_by:
- '156009000002'
version_date:
  kaz: 2020-12-15
  rus: 2020-12-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/150761/kaz/15.12.2020
  rus: https://zan.gov.kz/client/#!/doc/150761/rus/15.12.2020
