act_code: '132986'
requisite: Решение Атырауского областного маслихата от 21 июня 2019 года № 330-VI. Зарегистрировано Департаментом юстиции Атырауской области 1 июля 2019 года № 4435. Утратило силу решением Атырауского областного маслихата от 21 сентября 2020 года № 481-VI (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об определении системы мер социальной поддержки медицинских и фармацевтических работников, направленных для работы в сельскую местность Атырауской области
  kaz: Атырау облысының ауылдық жерге жұмысқа жiберiлген медицина және фармацевтика қызметкерлерiн әлеуметтiк қолдау шараларының жүйесiн айқындау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-06-21
approved_by:
- '156000000002'
version_date:
  kaz: 2019-06-21
  rus: 2019-06-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/132986/kaz/21.06.2019
  rus: https://zan.gov.kz/client/#!/doc/132986/rus/21.06.2019
