act_code: '17602'
requisite: Решение акима Атырауской области от 23 октября 2003 года № 77. Зарегистрировано Управлением юстиции Атырауской области от 7 ноября 2003 года № 1702
title:
  rus: О подготовке призывников по военно-техническим специальностям в Атырауской области в 2003-2004 учебном году
  kaz: 2003-2004 оқу жылында Атырау облысында әскерге шақырылушыларды әскери-техникалық мамандықтар бойынша даярлау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2003-10-22
approved_by:
- '156000000003'
version_date:
  kaz: 2003-10-22
  rus: 2003-10-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/17602/kaz/22.10.2003
  rus: https://zan.gov.kz/client/#!/doc/17602/rus/22.10.2003
