act_code: '87583'
requisite: Решение акима Курмангазинского района Атырауской области от 26 февраля 2015 года № 5. Зарегистрировано Департаментом юстиции Атырауской области 02 марта 2015 года № 3116. Утратило силу решением Курмангазинского районного акимата Атырауской области от 16 мая 2016 № 19
title:
  rus: Об образовании избирательных участков на территории Курмангазинского района
  kaz: Құрманғазы ауданы аумағында сайлау учаскелерін құру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-02-26
approved_by:
- '156003000001'
version_date:
  kaz: 2015-02-26
  rus: 2015-02-26
source:
  kaz: https://zan.gov.kz/client/#!/doc/87583/kaz/26.02.2015
  rus: https://zan.gov.kz/client/#!/doc/87583/rus/26.02.2015
