act_code: '31741'
requisite: Решение Атырауского областного маслихата от 8 декабря 2006 года № 337-III. Зарегистрировано Департаментом юстиции Атырауской области 15 января 2007 года за № 2480. Утратило силу решением Атырауского областного маслихата от 1 октября 2010 года № 360-IV
title:
  rus: Об утверждении Правил создания, содержания и охраны зеленых насаждений в населенных пунктах Атырауской области
  kaz: Атырау облысының елді мекендерінде жасыл желекті екпелелер құру, күтіп ұстау және қорғау Ережесін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2006-12-08
approved_by:
- '156000000002'
version_date:
  kaz: 2007-05-18
  rus: 2007-05-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/31741/kaz/18.05.2007
  rus: https://zan.gov.kz/client/#!/doc/31741/rus/18.05.2007
caused_by:
  code: '33788'
  requisite: Решение Атырауского областного маслихата от 18 мая 2007 года № 442-III. Зарегистрировано Департаментом юстиции Атырауской области 20 июня 2007 года за № 2493. Утратило силу - на основании письма Атырауского областного маслихата от 1 апреля 2014 года № 152/959
  title:
    rus: О внесении изменений в решение Атырауского областного маслихата от 8 декабря 2006 года № 337-ІІІ "Об утверждении Правил создания, содержания и охраны зеленых насаждений в населенных пунктах Атырауской области"
    kaz: Атырау облыстық мәслихатының 2006 жылғы 8 желтоқсандағы № 337-ІІІ "Атырау облысының елді-мекендерінде жасыл желекті екпелер құру, күтіп ұстау және қорғау Ережесін бекіту туралы" шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/33788/rus
