act_code: '46031'
requisite: Атырау облысы Мақат аудандық мәслихатының 2009 жылғы 22 сәуірдегі № 123-IV шешімі. Атырау облысының Әділет департаменті Мақат ауданының әділет басқармасында 2009 жылғы 20 мамырда № 4-7-99 тіркелді
title:
  rus: Аудандық Мәслихаттың 2008 жылғы 19 желтоқсандағы "2009 жылға арналған аудандық бюджет туралы" № 90-IV шешіміне өзгерістер мен толықтырулар  енгізу туралы
  kaz: Аудандық Мәслихаттың 2008 жылғы 19 желтоқсандағы "2009 жылға арналған аудандық бюджет туралы" № 90-IV шешіміне өзгерістер мен толықтырулар  енгізу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-04-22
approved_by:
- '156006000002'
version_date:
  kaz: 2009-04-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/46031/kaz/22.04.2009
