act_code: '56901'
requisite: Решение Исатайского районного маслихата Атырауской области от 14 декабря 2010 года № 228-IV. Зарегистрировано Управлением юстиции Исатайского района Атырауской области 19 января 2011 года № 4-4-174. Утратило силу решением Исатайского районного маслихата Атырауской области от 8 октября 2012 года № 62-V
title:
  rus: Қызметі дүркін-дүркін сипаттағы кәсіпкерлік қызметке бір жолғы талон құнын 2011 жылға белгілеу туралы
  kaz: Қызметі дүркін-дүркін сипаттағы кәсіпкерлік қызметке бір жолғы талон құнын 2011 жылға белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-12-14
approved_by:
- '156005000002'
version_date:
  kaz: 2010-12-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/56901/kaz/14.12.2010
