act_code: '71396'
requisite: Решение Индерского районного маслихата Атырауской области от 6 февраля 2013 года № 75-V. Зарегистрировано Департаментом юстиции Атырауской области 6 марта 2013 года № 2708. Утратило силу - решением Индерского районного маслихата Атырауской области от 10 июня 2014 года № 205-V
title:
  rus: Об определении размера и правил оказания жилищной помощи малообеспеченным семьям (гражданам), проживающим в Индерском районе
  kaz: Индер ауданында тұратын аз қамтамасыз етілген отбасыларға (азаматтарға) тұрғын үй көмегін көрсетудің мөлшері мен қағидасын айқындау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2013-02-06
approved_by:
- '156008000002'
version_date:
  kaz: 2013-02-06
source:
  kaz: https://zan.gov.kz/client/#!/doc/71396/kaz/06.02.2013
