act_code: '52489'
requisite: Атырау облысы Қызылқоға ауданы Миялы селолық округі әкімінің 2010 жылғы 30 сәуірдегі № 16 шешімі. Әділет департаменті Қызылқоға ауданының Әділет басқармасында 2010 жылғы 18 мамырда № 4-5-124 тіркелді. Күші жойылды - Қызылқоға ауданы Миялы селолық округі әкімінің 2010 жылғы 25 мамырдағы № 20 шешімімен
title:
  rus: Миялы селосындағы жаңа көшеге ат беру туралы
  kaz: Миялы селосындағы жаңа көшеге ат беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-04-30
approved_by:
- '156007010001'
version_date:
  kaz: 2010-04-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/52489/kaz/30.04.2010
