act_code: '56521'
requisite: Решение Атырауского городского маслихата Атырауской области от 15 декабря 2010 года № 135. Зарегистрировано Управлением юстиции Атырауской области 10 января 2011 года за № 4-1-130
title:
  rus: 1994 жылғы туған Атырау қаласы азаматтарын 2011 жылдың қаңтар-наурыз айларында шақыру учаскесінде тіркеуден өткізу туралы
  kaz: 1994 жылғы туған Атырау қаласы азаматтарын 2011 жылдың қаңтар-наурыз айларында шақыру учаскесінде тіркеуден өткізу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-12-15
approved_by:
- '156002000001'
version_date:
  kaz: 2010-12-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/56521/kaz/15.12.2010
