act_code: '217095'
requisite: Решение акима поселка Индербор Атырауской области от 19 ноября 2025 года № 96. Утратило силу решением акима поселка Индербор Индерского района Атырауской области от 26 января 2026 года № 16 (вводится в действие со дня его первого официального опубликования)
title:
  rus: Об объявлении чрезвычайной ситуации техногенного характера на территории поселка Индербор
  kaz: Индербор кенті аумағында техногендік сипаттағы төтенше жағдайды жариялау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2025-11-19
approved_by:
- '156008007001'
version_date:
  kaz: 2025-11-19
  rus: 2025-11-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/217095/kaz/19.11.2025
  rus: https://zan.gov.kz/client/#!/doc/217095/rus/19.11.2025
