act_code: '124691'
requisite: Решение Атырауского областного маслихата от 27 августа 2018 года № 242-VI. Зарегистрировано Департаментом юстиции Атырауской области 21 сентября 2018 года № 4239. Утратило силу решением Атырауского областного маслихата от 18 марта 2026 года № 227-VIII (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении ставок платы за пользование водными ресурсами из поверхностных источников по Атырауской области
  kaz: Атырау облысы бойынша жер үсті көздеріндегі су ресурстарын пайдаланғаны үшін төлемақы ставкаларын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-08-27
approved_by:
- '156000000002'
version_date:
  kaz: 2018-08-27
  rus: 2018-08-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/124691/kaz/27.08.2018
  rus: https://zan.gov.kz/client/#!/doc/124691/rus/27.08.2018
