act_code: '32031'
requisite: Атырау облысы Атырау қалалық мәслихатының 2007 жылғы 2 ақпандағы № 279 шешімі. Атырау облысының Әділет басқармасында 2007 жылғы 22 ақпанда № 4-1-52 болып тіркелді
title:
  rus: Білім беру ұйымдарының күндізгі оқу нысанынды оқитындар мен тәрбиеленушілерге қоғамдық көлікте (таксиден басқа) жүру үшін жеңілдік беру туралы
  kaz: Білім беру ұйымдарының күндізгі оқу нысанынды оқитындар мен тәрбиеленушілерге қоғамдық көлікте (таксиден басқа) жүру үшін жеңілдік беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2007-02-02
approved_by:
- '156002000002'
version_date:
  kaz: 2007-02-02
source:
  kaz: https://zan.gov.kz/client/#!/doc/32031/kaz/02.02.2007
