act_code: '148174'
requisite: Решение акима Тасшагильского сельского округа Кызылкогинского района Атырауской области от 30 октября 2020 года № 22. Зарегистрировано Департаментом юстиции Атырауской области 3 ноября 2020 года № 4780
title:
  rus: Об утрате силы решения акима Тасшагильского сельского округа от 16 июля 2020 года № 15 «Об установлении ограничительных мероприятий»
  kaz: Тасшағыл ауылдық округі әкімінің 2020 жылғы 16 шілдедегі № 15 «Шектеу іс-шараларын белгілеу туралы» шешімінің күшін жою туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-10-30
approved_by:
- '156007006002'
version_date:
  kaz: 2020-10-30
  rus: 2020-10-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/148174/kaz/30.10.2020
  rus: https://zan.gov.kz/client/#!/doc/148174/rus/30.10.2020
