act_code: '95805'
requisite: Решение от 22.10.2015 №57, Акимат Дамбинского сельского округа
title:
  rus: О присвоении наименовании улицам
  kaz: 'Көшелерге атау беру туралы '
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-10-22
approved_by:
- '156002005001'
version_date:
  kaz: 2015-10-22
  rus: 2015-10-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/95805/kaz/22.10.2015
  rus: https://zan.gov.kz/client/#!/doc/95805/rus/22.10.2015
