act_code: '49339'
requisite: Атырау облысы Жылыой ауданы әкімінің 2009 жылғы 25 қарашадағы № 19 шешімі. Жылыой аудандық Әділет департаментінде 2009 жылғы 20 желтоқсанда № 4-2-135 тіркелді
title:
  rus: 2010 жылғы қаңтар-наурыз айларында аудан көлемінде әскери есепке алу бөлімшесіне 1993 жылы туған азаматтарды тіркеу туралы
  kaz: 2010 жылғы қаңтар-наурыз айларында аудан көлемінде әскери есепке алу бөлімшесіне 1993 жылы туған азаматтарды тіркеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-11-25
approved_by:
- '156009000001'
version_date:
  kaz: 2009-11-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/49339/kaz/25.11.2009
