act_code: '37774'
requisite: Атырау облысы Мақат аудандық мәслихатының 2007 жылғы 21 желтоқсандағы № 28-IV шешімі. Атырау облысы Мақат аудандық Әділет басқармасында 2008 жылғы 16 қаңтарда № 4-7-77 болып тіркелді
title:
  rus: Аудан бойынша 2008 жылға ара-тұра сипаттағы кәсіпкерлік қызмет түрлеріне берілетін бір жолғы талон құнының мөлшері туралы
  kaz: Аудан бойынша 2008 жылға ара-тұра сипаттағы кәсіпкерлік қызмет түрлеріне берілетін бір жолғы талон құнының мөлшері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2007-12-21
approved_by:
- '156006000002'
version_date:
  kaz: 2007-12-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/37774/kaz/21.12.2007
