act_code: '41295'
requisite: Атырау облысы Индер аудандық мәслихатының 2008 жылғы 5 тамыздағы № 71-IV шешімі. Атырау облысы Индер аудандық Әділет басқармасында 2008 жылғы 26 тамызда № 4-6-72 болып тіркелді
title:
  rus: Аудандық мәслихаттың 2007 жылғы 24 желтоқсандағы № 21-IV «2008 жылға арналған аудандық бюджет туралы» шешіміне өзгертулер енгізу туралы
  kaz: Аудандық мәслихаттың 2007 жылғы 24 желтоқсандағы № 21-IV «2008 жылға арналған аудандық бюджет туралы» шешіміне өзгертулер енгізу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-08-05
approved_by:
- '156008000002'
version_date:
  kaz: 2008-08-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/41295/kaz/05.08.2008
