act_code: '16779'
requisite: Атырау облысы Жылыой аудандық мәслихаты ХХХ сессиясының 2003 жылғы 21 мамырдағы 30-4 шешімі. Атырау облыстық Әділет басқармасында 2003 жылғы 26 маусымда № 1530 тіркелді. Күші жойылды - Атырау облысы Жылыой аудандық мәслихатының 2007 жылғы 19 желтоқсандағы № 3-5 шешімімен
title:
  rus: Жылыой ауданында аз қамтылған отбасыларына (азаматтарға) тұрғын үйді ұстауға (жеке тұрғын үй ұстағаннан басқа) және коммуналдық қызметтерді тұтынуға төлем төлеуге тұрғын үй көмегін көрсету тәртібі туралы Ереже туралы
  kaz: Жылыой ауданында аз қамтылған отбасыларына (азаматтарға) тұрғын үйді ұстауға (жеке тұрғын үй ұстағаннан басқа) және коммуналдық қызметтерді тұтынуға төлем төлеуге тұрғын үй көмегін көрсету тәртібі туралы Ереже туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2003-05-20
approved_by:
- '156009000002'
version_date:
  kaz: 2003-05-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/16779/kaz/20.05.2003
