act_code: '42177'
requisite: Атырау облысы Қызылқоға ауданы Қызылқоға ауылдық округі әкімінің 2008 жылғы 23 қазандағы № 12 шешімі. Атырау облысы Әділет департаменті Қызылқоға ауданының Әділет басқармасында 2008 жылғы 11 қарашада № 4-5-100 болып тіркелді
title:
  rus: Қарабау ауылынан Н. Көмековтың атына көше беру туралы
  kaz: Қарабау ауылынан Н. Көмековтың атына көше беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-10-23
approved_by:
- '156007008002'
version_date:
  kaz: 2008-10-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/42177/kaz/23.10.2008
