act_code: '88811'
requisite: Решение Атырауского городского маслихата Атырауской области от 27 марта 2015 года № 269. Зарегистрировано Департаментом юстиции Атырауской области 20 апреля 2015 года № 3182
title:
  rus: Об установлении специалистам в области образования и культуры,повышенных окладов и тарифных ставок
  kaz: Бiлiм беру және мәдениет саласындағы мамандарға жоғарылатылған айлықақылар мен тарифтiк мөлшерлемелерін белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-03-27
approved_by:
- '156002000002'
version_date:
  kaz: 2015-03-27
  rus: 2015-03-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/88811/kaz/27.03.2015
  rus: https://zan.gov.kz/client/#!/doc/88811/rus/27.03.2015
