act_code: '37487'
requisite: Атырау облысы Атырау қалалық мәслихатының 2007 жылғы 14 желтоқсандағы № 38 шешімі. Атырау облысының Әділет басқармасында 2008 жылғы 25 қантарда № 4-1-79 болып тіркелді
title:
  rus: Қала аумағындағы жоғары және арнаулы орта оқу орындарының студенттеріне қоғамдық көлікте (таксиден баска) жүруге жеңілдік беру туралы
  kaz: Қала аумағындағы жоғары және арнаулы орта оқу орындарының студенттеріне қоғамдық көлікте (таксиден баска) жүруге жеңілдік беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2007-12-14
approved_by:
- '156002000002'
version_date:
  kaz: 2007-12-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/37487/kaz/14.12.2007
