act_code: '117581'
requisite: Решение акима Уильского сельского округа Кызылкогинского района Атырауской области от 20 декабря 2017 года № 27. Зарегистрировано Департаментом юстиции Атырауской области 3 января 2018 года № 4024
title:
  rus: О присвоении наименования улице
  kaz: Көше атауын беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2017-12-20
approved_by:
- '156007004002'
version_date:
  kaz: 2017-12-20
  rus: 2017-12-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/117581/kaz/20.12.2017
  rus: https://zan.gov.kz/client/#!/doc/117581/rus/20.12.2017
