act_code: '47429'
requisite: Атырау облысы Индер аудандық мәслихатының 2009 жылғы 4 шілдедегі № 152-IV шешімі. Атырау облысының Әділет департаменті Индер ауданының Әділет басқармасында 2009 жылғы 4 тамызда № 4-6-86 тіркелді. Күші жойылды - Индер аудандық мәслихатының 2009 жылғы 23 желтоқсандағы № 191-IV шешімімен
title:
  rus: Салық ставкаларын белгілеу туралы
  kaz: Салық ставкаларын белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-07-04
approved_by:
- '156008000002'
version_date:
  kaz: 2009-07-04
source:
  kaz: https://zan.gov.kz/client/#!/doc/47429/kaz/04.07.2009
