act_code: '56788'
requisite: Решение Индерского районного маслихата Атырауской области № 259-IV от 14 декабря 2010 года. Зарегистрировано Департаментом юстиции Атырауской области 14 января 2011 года № 4-6-112. Утратило силу - решением Индерского районного маслихата Атырауской области от 28 марта 2013 года № 87-V
title:
  rus: О районном бюджете на 2011-2013 годы
  kaz: 2011 - 2013 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-12-14
approved_by:
- '156008000002'
version_date:
  kaz: 2011-03-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/56788/kaz/18.03.2011
