act_code: '56788'
requisite: Решение Индерского районного маслихата Атырауской области № 259-IV от 14 декабря 2010 года. Зарегистрировано Департаментом юстиции Атырауской области 14 января 2011 года № 4-6-112. Утратило силу - решением Индерского районного маслихата Атырауской области от 28 марта 2013 года № 87-V
title:
  rus: О районном бюджете на 2011-2013 годы
  kaz: 2011 - 2013 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-12-14
approved_by:
- '156008000002'
version_date:
  kaz: 2011-02-17
  rus: 2011-02-17
source:
  kaz: https://zan.gov.kz/client/#!/doc/56788/kaz/17.02.2011
  rus: https://zan.gov.kz/client/#!/doc/56788/rus/17.02.2011
caused_by:
  code: '57404'
  requisite: Решение Индерского районного маслихата Атырауской области № 274-IV от 17 февраля 2011 года. Зарегистрировано Департаментом юстиции Атырауской области 25 февраля 2011 года № 4-6-113. Утратило силу решением Индерского районного маслихата Атырауской области от 28 марта 2013 года № 87-V
  title:
    rus: О внесении изменений в решение районного маслихата от 14 декабря 2010 года № 259-IV "О районном бюджете на 2011-2013 годы"
    kaz: Аудандық мәслихаттың 2010 жылғы 14 желтоқсандағы № 259-ІV "2011-2013 жылдарға арналған аудандық бюджет туралы" шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/57404/rus
