act_code: '48162'
requisite: Решение от 01.10.2009 №32, Акимат Жемского сельского округа
title:
  rus: Тұрғызба селосы мен Аққұдық, Қойсары, Қараша елді мекендеріндегі көшелерге атаулар беру туралы
  kaz: Тұрғызба селосы мен Аққұдық, Қойсары, Қараша елді мекендеріндегі көшелерге атаулар беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-10-01
approved_by:
- '156009001001'
version_date:
  kaz: 2009-10-01
source:
  kaz: https://zan.gov.kz/client/#!/doc/48162/kaz/01.10.2009
