act_code: '97907'
requisite: Решение Индерского районного маслихата Атырауской области от 21 декабря 2015 года № 327-V. Зарегистрировано Департаментом юстиции Атырауской области 14 января 2016 года № 3440. Утратило силу решением Индерского районного маслихата Атырауской области от 10 февраля 2017 года № 85-VI
title:
  rus: О районном бюджете на 2016-2018 годы»
  kaz: 2016 -2018 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-12-21
approved_by:
- '156008000002'
version_date:
  kaz: 2016-11-02
  rus: 2016-11-02
source:
  kaz: https://zan.gov.kz/client/#!/doc/97907/kaz/02.11.2016
  rus: https://zan.gov.kz/client/#!/doc/97907/rus/02.11.2016
caused_by:
  code: '107633'
  requisite: Решение Индерского районного маслихата Атырауской области от 2 ноября 2016 года № 49-VI. Зарегистрировано Департаментом юстиции Атырауской области 18 ноября 2016 года № 3672. Утратило силу решением Индерского районного маслихата Атырауской области от 10 февраля 2017 года № 85-VI
  title:
    rus: О внесении изменений и дополнений в решение районного маслихата от  21 декабря 2015 года №327-V «О районном бюджете на 2016-2018 годы»
    kaz: Аудандық мәслихаттың 2015 жылғы 21 желтоқсандағы №327-V «2016-2018 жылдарға арналған аудандық бюджет туралы» шешіміне өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/107633/rus
