act_code: '106479'
requisite: Решение акима поселка Жана Каратон Жылыойского района Атырауской области от 8 сентября 2016 года № 40. Зарегистрировано Департаментом юстиции Атырауской области 26 сентября 2016 года № 3620
title:
  rus: О присвоении наименовании улицам
  kaz: Көшелерге атау беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2016-09-08
approved_by:
- '156009003001'
version_date:
  kaz: 2016-09-08
  rus: 2016-09-08
source:
  kaz: https://zan.gov.kz/client/#!/doc/106479/kaz/08.09.2016
  rus: https://zan.gov.kz/client/#!/doc/106479/rus/08.09.2016
