act_code: '94434'
requisite: Решение от 15.09.2015 №446-V, Маслихат Курмангазинского района.  Утратило силу решением  Курмангазинского районного маслихата Атырауской области от 02 марта 2016 года № 516-V.
title:
  rus: О повышении ставок единого земельного налога и ставок земельного налога на не используемые в соответствии с земельным законодательством Республики Казахстан земли сельскохозяйственного назначения в Курмангазинском районе
  kaz: Қазақстан Республикасының жер заңнамасына сәйкес Құрманғазы ауданында пайдаланылмайтын ауыл шаруашылығы мақсатындағы жерлерге бірыңғай жер салығының мөлшерлемелерін және жер салығының мөлшерлемелерін жоғарылату туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-09-15
approved_by:
- '156003000002'
version_date:
  kaz: 2015-12-23
  rus: 2015-12-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/94434/kaz/23.12.2015
  rus: https://zan.gov.kz/client/#!/doc/94434/rus/23.12.2015
caused_by:
  code: '97760'
  requisite: Решение Курмангазинского районного маслихата Атырауской области от 23 декабря 2015 года № 474-V. Зарегистрировано Департаментом юстиции Атырауской области 05 января 2016 года № 3418.  Утратило силу решением  Курмангазинского районного маслихата Атырауской области от 02 марта 2016 года № 516-V.
  title:
    rus: О внесении изменений в решение районного маслихата от 15 сентября 2015 года №446-V «О повышении ставок единого земельного налога и базовых ставок земельного налога на не используемые в соответствии с земельным законодательством Республики Казахстан земли сельскохозяйственного назначения в Курмангазинском районе»
    kaz: Аудандық мәслихаттың 2015 жылғы 15 қыркүйектегі №446-V «Қазақстан Республикасының жер заңнамасына сәйкес Құрманғазы ауданында пайдаланылмайтын ауыл шаруашылығы мақсатындағы жерлерге бірыңғай жер салығының мөлшерлемелерін және базалық жер салығының мөлшерлемелерін жоғарылату туралы» шешіміне өзгерістер  енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/97760/rus
