act_code: '194046'
requisite: Решение Атырауского городского маслихата Атырауской области от 4 марта 2024 года № 94. Зарегистрировано в Департаменте юстиции Атырауской области 6 марта 2024 года № 5146-06. Утратило силу решением маслихата города Атырау Атырауской области от 30 апреля 2026 года № 216 (вводится в действие с 01.01.2026)
title:
  rus: О понижении размера ставки при применении специального налогового режима розничного налога по городу Атырау
  kaz: Атырау қаласы бойынша бөлшек салықтық арнаулы салық режимін қолдану кезінде мөлшерлемесінің мөлшерін төмендету туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-03-04
approved_by:
- '156002000002'
version_date:
  kaz: 2024-03-04
  rus: 2024-03-04
source:
  kaz: https://zan.gov.kz/client/#!/doc/194046/kaz/04.03.2024
  rus: https://zan.gov.kz/client/#!/doc/194046/rus/04.03.2024
