act_code: '37771'
requisite: Атырау облысы Мақат ауданы әкімінің 2007 жылғы 27 желтоқсандағы № 23 шешімі. Мақат аудандық Әділет басқармасында 2008 жылғы 15 қаңтарда № 4-7-76 болып тіркелді
title:
  rus: Мақат ауданының 1991 жылы туылған азаматтарын 2008 жылы шақыру учаскелеріне тіркеуді өткізу туралы
  kaz: Мақат ауданының 1991 жылы туылған азаматтарын 2008 жылы шақыру учаскелеріне тіркеуді өткізу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2007-12-27
approved_by:
- '156006000003'
version_date:
  kaz: 2007-12-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/37771/kaz/27.12.2007
