act_code: '58813'
requisite: Решение Атырауского областного маслихата от 20 апреля 2011 года № 426-IV. Зарегистрировано Департаментом юстиции Атырауской области 13 мая 2011 года № 2591. Утратило силу решением Атырауского областного маслихата от 21 сентября 2020 года № 481-VI (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: О предоставлении бесплатного или льготного проезда гражданам за пределы населенного пункта на лечение за счет бюджетных средств
  kaz: Азаматтарға елді мекен шегінен тысқары жерлерде емделуге бюджет қаражаты есебінен тегін немесе жеңілдікпен жол жүруді ұсыну туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2011-04-20
approved_by:
- '156000000002'
version_date:
  kaz: 2011-04-20
  rus: 2011-04-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/58813/kaz/20.04.2011
  rus: https://zan.gov.kz/client/#!/doc/58813/rus/20.04.2011
