act_code: '18366'
requisite: Атырау облыстық мәслихатының 2003 жылғы 6 маусымдағы № 301-ІІ шешімі. Атырау облысының Әділет басқармасында 2003 жылғы 10 шілдеде № 1557 тіркелді
title:
  rus: 2003-2005 жылдарға арналған Атырау облысында кемтар балаларды әлеуметтік және медициналық-педагогикалық түзеу арқылы қолдау Бағдарламасы туралы
  kaz: 2003-2005 жылдарға арналған Атырау облысында кемтар балаларды әлеуметтік және медициналық-педагогикалық түзеу арқылы қолдау Бағдарламасы туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2003-06-05
approved_by:
- '156000000002'
version_date:
  kaz: 2003-06-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/18366/kaz/05.06.2003
