act_code: '96413'
requisite: Решение от 25.11.2015 №319-V, Маслихат Индерского района. Зарегистрировано Департаментом юстиции Атырауской области 14 декабря 2015 года № 3394. Утратило силу решением  Индерского районного маслихата Атырауской области от 15 февраля 2016 года № 350-V
title:
  rus: О повышении ставок земельного налога и единого земельного налога на не используемые в соответствии с земельным законодательством Республики Казахстан земли сельскохозяйственного назначения  в Индерском  районе
  kaz: Қазақстан Республикасының жер заңнамасына сәйкес Индер ауданында пайдаланылмайтын ауыл шаруашылығы мақсатындағы  жерлерге жер салығының және бірыңғай жер салығының мөлшерлемелерін жоғарылату  туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-11-25
approved_by:
- '156008000002'
version_date:
  kaz: 2015-11-25
  rus: 2015-11-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/96413/kaz/25.11.2015
  rus: https://zan.gov.kz/client/#!/doc/96413/rus/25.11.2015
