act_code: '128228'
requisite: Решение Махамбетского районного маслихата Атырауской области от 26 декабря 2018 года № 296. Зарегистрировано Департаментом юстиции Атырауской области 3 января 2019 года № 4312
title:
  rus: О районном бюджете на 2019-2021 годы
  kaz: 2019 – 2021 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-12-26
approved_by:
- '156004000002'
version_date:
  kaz: 2019-06-27
  rus: 2019-06-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/128228/kaz/27.06.2019
  rus: https://zan.gov.kz/client/#!/doc/128228/rus/27.06.2019
caused_by:
  code: '133118'
  requisite: Решение Махамбетского районного маслихата Атырауской области от 27 июня 2019 года № 346. Зарегистрировано Департаментом юстиции Атырауской области 4 июля 2019 года № 4438
  title:
    rus: О внесении изменений и дополнений в решение Махамбетского районного маслихата от 26 декабря 2018 года № 296 «О районном бюджете на 2019-2021 годы»
    kaz: Махамбет аудандық мәслихаттың 2018 жылғы 26 желтоқсандағы № 296 «2019–2021 жылдарға арналған аудандық бюджет туралы» шешіміне өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/133118/rus
