act_code: '50857'
requisite: Решение Махамбетского районного маслихата Атырауской области от 9 февраля 2010 года № 201. Зарегистрировано Управлением юстиции Махамбетского района Атырауской области 24 февраля 2010 года № 4-3-140. Утратило силу решением Махамбетского районного маслихата Атырауской области от 30 мая 2014 года № 208
title:
  rus: Махамбет ауданы бойынша 2010 жылға арналған салық ставкаларын белгілеу туралы
  kaz: Махамбет ауданы бойынша 2010 жылға арналған салық ставкаларын белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-02-09
approved_by:
- '156004000002'
version_date:
  kaz: 2010-02-09
source:
  kaz: https://zan.gov.kz/client/#!/doc/50857/kaz/09.02.2010
