act_code: '85773'
requisite: Решение Макатского районного маслихата Атырауской области от 24 декабря 2014 года № 265-V. Зарегистрировано Департаментом юстиции Атырауской области 14 января 2015 года № 3080
title:
  rus: 'О районном бюджете на 2015-2017 годы '
  kaz: '2015–2017 жылдарға арналған аудандық бюджет туралы  '
form: РЕШ
type_codes:
- РЕШ
approved_on: 2014-12-24
approved_by:
- '156006000002'
version_date:
  kaz: 2015-11-25
  rus: 2015-11-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/85773/kaz/25.11.2015
  rus: https://zan.gov.kz/client/#!/doc/85773/rus/25.11.2015
caused_by:
  code: '96136'
  requisite: Решение Макатского районного маслихата Атырауской области от 25 декабря 2015 года № 331-V. Зарегистрировано Департаментом юстиции Атырауской области 7 декабря 2015 года № 3380
  title:
    rus: О внесении изменений и дополнения в решение районного маслихата от 24 декабря 2014 года № 265-V «О районном бюджете на 2015-2017 годы»
    kaz: Аудандық мәслихаттың 2014 жылғы 24 желтоқсандағы № 265-V «2015-2017 жылдарға арналған аудандық бюджет туралы» шешіміне өзгерістер мен толықтыру енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/96136/rus
