act_code: '51203'
requisite: Решение Индерского районного акимата Атырауской области от 22 февраля 2010 года № 36. Зарегистрировано Управлением юстиции Индерского района Атырауской области 12 марта 2010 года № 4-6-94
title:
  rus: Индер ауданының 1993 жылы туған азаматтарын 2010 жылы шақыру учаскесінде тіркеуді өткізу туралы
  kaz: Индер ауданының 1993 жылы туған азаматтарын 2010 жылы шақыру учаскесінде тіркеуді өткізу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-02-22
approved_by:
- '156008000001'
version_date:
  kaz: 2010-02-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/51203/kaz/22.02.2010
