act_code: '38215'
requisite: Атырау облысы Атырау қалалық мәслихатының 2008 жылғы 23 қаңтардағы № 50 шешімі. Атырау облысының Әділет басқармасында 2008 жылғы 4 наурызда № 4-1-84 болып тіркелді
title:
  rus: Жеке тұрғын үй қорындағы және жалға берілген түрғын үйлердегі түрғын үйді пайдаланғаны үшін жалдау ақысының шығыстары жергілікті бюджетке жүктелетін азаматтар санатын белгілеу туралы
  kaz: Жеке тұрғын үй қорындағы және жалға берілген түрғын үйлердегі түрғын үйді пайдаланғаны үшін жалдау ақысының шығыстары жергілікті бюджетке жүктелетін азаматтар санатын белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-01-23
approved_by:
- '156002000002'
version_date:
  kaz: 2008-01-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/38215/kaz/23.01.2008
