act_code: '55336'
requisite: Атырау облысы Қызылқоға аудандық мәслихатының 2010 жылғы 13 қазандағы № XXII-7 шешімі. Әділет департаменті Қызылқоға ауданының Әділет басқармасында 2010 жылғы 9 қарашада № 4-5-135 тіркелді. Күші жойылды - Қызылқоға аудандық мәслихатының 2012 жылғы 7 желтоқсандағы № IX-5 шешімімен
title:
  rus: Ауылдық елді мекендерде тұратын және жұмыс істейтін мемлекеттік денсаулық сақтау, білім беру, әлеуметтік қорғау, мәдениет және спорт ұйымдарының мамандарына отын сатып алу үшін әлеуметтік көмек беру туралы
  kaz: Ауылдық елді мекендерде тұратын және жұмыс істейтін мемлекеттік денсаулық сақтау, білім беру, әлеуметтік қорғау, мәдениет және спорт ұйымдарының мамандарына отын сатып алу үшін әлеуметтік көмек беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-10-13
approved_by:
- '156007000002'
version_date:
  kaz: 2010-10-13
source:
  kaz: https://zan.gov.kz/client/#!/doc/55336/kaz/13.10.2010
