act_code: '96538'
requisite: Решение от 19.11.2015 №285-V, Маслихат Исатайского района. Зарегистрировано Департаментом юстиции Атырауской области 15 декабря 2015 года № 3396. Утратило силу решением Исатайского районного маслихата Атырауской области от 16 апреля 2024 года № 80-VIII (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об определении размера и порядка оказания жилищной помощи в Исатайском районе
  kaz: Исатай ауданында тұрғын үй көмегін көрсетудің мөлшері мен тәртібін айқындау туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2015-11-19
approved_by:
- '156005000002'
version_date:
  kaz: 2016-01-13
  rus: 2016-01-13
source:
  kaz: https://zan.gov.kz/client/#!/doc/96538/kaz/13.01.2016
  rus: https://zan.gov.kz/client/#!/doc/96538/rus/13.01.2016
caused_by:
  code: '99013'
  requisite: Решение Исатайского районного маслихата Атырауской области от 13 января 2016 года № 304-V. Зарегистрировано Департаментом юстиции Атырауской области 2 февраля 2016 года № 3454. Утратило силу решением Исатайского районного маслихата Атырауской области от 16 апреля 2024 года № 80-VIII (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
  title:
    rus: О внесении изменений и дополнения в решение районного маслихата от 19 ноября 2015 года №285-V «Об утверждении правил оказания жилищной помощи малообеспеченным семьям (гражданам), проживающим в Исатайском районе»
    kaz: Аудандық мәслихаттың 2015 жылғы 19 қарашадағы №285-V «Исатай ауданында тұратын аз қамтылған отбасыларға (азаматтарға) тұрғын үй көмегін көрсетудің қағидасын бекіту туралы» шешіміне өзгерістер мен толықтыру енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/99013/rus
