act_code: '37756'
requisite: Атырау облысы Индер ауданы әкімінің 2007 жылғы 26 желтоқсандағы № 95 шешімі. Атырау облысының Әділет департаменті Индер ауданының Әділет басқармасында 2008 жылғы 15 қаңтарда № 4-6-65 болып тіркелді
title:
  rus: 1991 жылы туылған және бұрын есепке тіркелмеген ер азаматтарды 2008 жылдың қаңтар-наурыз айларында шақыру пунктінде тіркеу жүргізу туралы
  kaz: 1991 жылы туылған және бұрын есепке тіркелмеген ер азаматтарды 2008 жылдың қаңтар-наурыз айларында шақыру пунктінде тіркеу жүргізу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2007-12-26
approved_by:
- '156008000003'
version_date:
  kaz: 2007-12-26
source:
  kaz: https://zan.gov.kz/client/#!/doc/37756/kaz/26.12.2007
