act_code: '165598'
requisite: Решение акима Сагизского сельского округа Кызылкогинского района Атырауской области от 25 марта 2022 года № 20
title:
  rus: Об установленин карантина
  kaz: Карантин белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-03-25
approved_by:
- '156007001002'
version_date:
  kaz: 2022-03-25
  rus: 2022-03-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/165598/kaz/25.03.2022
  rus: https://zan.gov.kz/client/#!/doc/165598/rus/25.03.2022
