act_code: '208096'
requisite: Решение Макатского районного маслихата Атырауской области от 13 марта 2025 года № 149-VIII
title:
  rus: Об утверждении Положения о государственном учреждении «Аппарат Макатского районного маслихата»
  kaz: «Мақат аудандық мәслихатының аппараты» мемлекеттік мекемесінің Ережесін бекіту туралы
form: РЕШ
type_codes:
- ПОЛ
- РЕШ
approved_on: 2025-03-13
approved_by:
- '156006000002'
version_date:
  kaz: 2025-03-13
  rus: 2025-03-13
source:
  kaz: https://zan.gov.kz/client/#!/doc/208096/kaz/13.03.2025
  rus: https://zan.gov.kz/client/#!/doc/208096/rus/13.03.2025
