act_code: '44757'
requisite: Атырау облысы Мақат аудандық мәслихатының 2009 жылғы 20 ақпандағы № 107-IV шешімі. Атырау облысының Әділет департаменті Мақат ауданының Әділет басқармасында 2009 жылғы 16 наурызда № 4-7-96 тіркелді
title:
  rus: Мақат ауданы бойынша жер салығының базалық ставкалары туралы
  kaz: Мақат ауданы бойынша жер салығының базалық ставкалары туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-02-20
approved_by:
- '156006000002'
version_date:
  kaz: 2009-02-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/44757/kaz/20.02.2009
