act_code: '31691'
requisite: Атырау облысы Индер аудандық мәслихатының 2006 жылғы 9 желтоқсандағы № 204-III шешімі. Атырау облысы Индер аудандық Әділет басқармасында 2006 жылғы 12 желтоқсанда № 4-6-44 болып тіркелді
title:
  rus: 2006 жылға арналған аудандық бюджетті нақтылау туралы
  kaz: 2006 жылға арналған аудандық бюджетті нақтылау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2006-12-09
approved_by:
- '156008000002'
version_date:
  kaz: 2006-12-09
source:
  kaz: https://zan.gov.kz/client/#!/doc/31691/kaz/09.12.2006
