act_code: '220180'
requisite: Решение Курмангазинского районного маслихата Атырауской области от 22 декабря 2025 года № 253-VIII
title:
  rus: Об утверждении районного бюджета на 2026-2028 годы
  kaz: 2026-2028 жылдарға арналған ауданның бюджетін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2025-12-22
approved_by:
- '156003000002'
version_date:
  kaz: 2026-05-15
  rus: 2026-05-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/220180/kaz/15.05.2026
  rus: https://zan.gov.kz/client/#!/doc/220180/rus/15.05.2026
caused_by:
  code: '225464'
  requisite: Решение Курмангазинского районного маслихата Атырауской области от 15 мая 2026 года № 277-VIII
  title:
    rus: О внесении изменений и дополнений в решение районного маслихата от 22 декабря 2025 года № 253-VІІІ «Об утверждении районного бюджета на 2026-2028 годы»
    kaz: Аудандық мәслихаттың 2025 жылғы 22 желтоқсандағы № 253-VІІІ «2026-2028 жылдарға арналған ауданның бюджетін бекіту туралы» шешіміне өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/225464/rus
