act_code: '119508'
requisite: Решение акима Кара Арнинского сельского округа Жылыойского района Атырауской области от 5 марта 2018 года № 16. Зарегистрировано Департаментом юстиции Атырауской области 16 марта 2018 года № 4074. Утратило силу решением акима Кара Арнинского сельского округа Жылыойского  района Атырауской области от 16 июля 2018 года № 36
title:
  rus: Об установлении ограничительных мероприятий
  kaz: Шектеу іс-шараларын белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-03-05
approved_by:
- '156009005002'
version_date:
  kaz: 2018-03-05
  rus: 2018-03-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/119508/kaz/05.03.2018
  rus: https://zan.gov.kz/client/#!/doc/119508/rus/05.03.2018
