act_code: '81865'
requisite: Решение Макатского районного маслихата Атырауской области от 23 июля 2014 года № 244-V. Зарегистрировано Департаментом юстиции Атырауской области 12 августа 2014 года № 2965. Утратило силу решением Макатского районного маслихата Атырауской области от 19 марта 2018 года № 164-VI
title:
  rus: Об утверждении регламента Макатского районного маслихата
  kaz: Мақат аудандық мәслихатының регламентін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2014-07-23
approved_by:
- '156006000002'
version_date:
  kaz: 2014-07-23
  rus: 2014-07-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/81865/kaz/23.07.2014
  rus: https://zan.gov.kz/client/#!/doc/81865/rus/23.07.2014
