act_code: '97935'
requisite: Решение Атырауского городского маслихата Атырауской области от 18 декабря 2015 года № 316. Зарегистрировано Департаментом юстиции Атырауской области 14 января 2016 года № 3439
title:
  rus: 'О бюджете города на 2016-2018 годы '
  kaz: '2016-2018 жылдарға арналған қала бюджеті туралы '
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-12-18
approved_by:
- '156002000002'
version_date:
  kaz: 2016-07-08
  rus: 2016-07-08
source:
  kaz: https://zan.gov.kz/client/#!/doc/97935/kaz/08.07.2016
  rus: https://zan.gov.kz/client/#!/doc/97935/rus/08.07.2016
caused_by:
  code: '104648'
  requisite: Решение Атырауского городского маслихата Атырауской области от 8 июля 2016 года № 43. Зарегистрировано Департаментом юстиции Атырауской области 15 июля 2016 года № 3567
  title:
    rus: О внесении изменений и дополнения в решение городского маслихата от 18 декабря 2015 года № 316 «О бюджете города на 2016-2018 годы»
    kaz: Қалалық мәслихаттың 2015 жылғы 18 желтоқсандағы № 316 «2016-2018 жылдарға арналған қала бюджеті туралы»  шешіміне өзгерістер мен толықтыру енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/104648/rus
