act_code: '97935'
requisite: Решение Атырауского городского маслихата Атырауской области от 18 декабря 2015 года № 316. Зарегистрировано Департаментом юстиции Атырауской области 14 января 2016 года № 3439
title:
  rus: 'О бюджете города на 2016-2018 годы '
  kaz: '2016-2018 жылдарға арналған қала бюджеті туралы '
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-12-18
approved_by:
- '156002000002'
version_date:
  kaz: 2015-12-18
  rus: 2015-12-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/97935/kaz/18.12.2015
  rus: https://zan.gov.kz/client/#!/doc/97935/rus/18.12.2015
