act_code: '14386'
requisite: Екінші сайланған Атырау облыстық мәслихаты кезектен тыс ХХII сессиясының 2003 жылғы 15 қаңтардағы № 279-II шешімі. Атырау облысының Әділет басқармасында 2003 жылғы 24 қаңтарда № 1289 болып тіркелді
title:
  rus: 2003-2005 жылдарға арналған Атырау облысында еңбектi қорғау жөнiндегi бағдарлама туралы
  kaz: 2003-2005 жылдарға арналған Атырау облысында еңбектi қорғау жөнiндегi бағдарлама туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2003-01-15
approved_by:
- '156000000002'
version_date:
  kaz: 2003-01-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/14386/kaz/15.01.2003
