act_code: '113642'
requisite: Решение Кызылкогинского районного маслихата Атырауской области от 30 июня 2017 года № ХIII-3. Зарегистрировано Департаментом юстиции Атырауской области 24 июля 2017 года № 3931. Утратило силу решением Кызылкогинского районного маслихата Атырауской области от 28 сентября 2023 года № 8-3 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении правил оказания социальной помощи, установления размеров и определения перечня отдельных категорий нуждающихся граждан
  kaz: Әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың қағидаларын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2017-06-30
approved_by:
- '156007000002'
version_date:
  kaz: 2020-12-03
  rus: 2020-12-03
source:
  kaz: https://zan.gov.kz/client/#!/doc/113642/kaz/03.12.2020
  rus: https://zan.gov.kz/client/#!/doc/113642/rus/03.12.2020
caused_by:
  code: '149475'
  requisite: Решение Кызылкогинского районного маслихата Атырауской области от 3 декабря 2020 года № LХ-13. Зарегистрировано Департаментом юстиции Атырауской области 8 декабря 2020 года № 4796. Утратило силу решением Кызылкогинского районного маслихата Атырауской области от 28 сентября 2023 года № 8-3 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
  title:
    rus: О внесении изменений в решение Кызылкогинского районного маслихата от 30 июня 2017 года № ХІІІ-3 «Об утверждении правил оказания социальной помощи, установления размеров и определения перечня отдельных категорий нуждающихся граждан»
    kaz: Қызылқоға аудандық мәслихатының 2017 жылғы 30 маусымдағы № ХIII-3 «Әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың қағидаларын бекіту туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/149475/rus
