act_code: '87146'
requisite: Решение акима Жылыойского района Атырауской области от 27 февраля 2015 года № 8. Зарегистрировано Департаментом юстиции Атырауской области 27 февраля 2015 года № 3111. Утратило силу постановлением акима Жылыойского района Атырауской области от 29 ноября 2018 года № 59 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об образовании  избирательных  участков на  территории  Жылыойского района
  kaz: Жылыой ауданы аумағында сайлау учаскелерін құру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-02-27
approved_by:
- '156009000001'
version_date:
  kaz: 2018-03-13
  rus: 2018-03-13
source:
  kaz: https://zan.gov.kz/client/#!/doc/87146/kaz/13.03.2018
  rus: https://zan.gov.kz/client/#!/doc/87146/rus/13.03.2018
caused_by:
  code: '120082'
  requisite: Решение акима Жылыойского района Атырауской области от 13 марта 2018 года № 11. Зарегистрировано Департаментом юстиции Атырауской области 27 марта 2018 года № 4080. Утратило силу постановлением акима Жылыойского района Атырауской области от 29 ноября 2018 года № 59 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
  title:
    rus: О внесении изменения в решение акима Жылыойского района от 27 февраля 2015 года № 8 «Об образовании избирательных  участков на территории Жылыойского района»
    kaz: Жылыой ауданы әкімінің 2015 жылғы 27 ақпандағы № 8 «Жылыой ауданы аумағында сайлау учаскелерін құру туралы» шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/120082/rus
