act_code: '16956'
requisite: Атырау облысы Махамбет ауданының әкімінің 2003 жылғы 14 тамыздағы № 188 шешімі. Атырау облыстық Әділет басқармасында 2003 жылғы 17 қыркүйекте 1626 тіркелді. Күші жойылды - Атырау облысы Махамбет ауданы әкімінің 2006 жылғы 26 желтоқсандағы № 14 шешімімен
title:
  rus: Махамбет ауданы көлемінде қоғамдық тәртіпті сақтау жөніндегі ерікті жасақшылардың аудандық штабын құру туралы
  kaz: Махамбет ауданы көлемінде қоғамдық тәртіпті сақтау жөніндегі ерікті жасақшылардың аудандық штабын құру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2003-08-13
approved_by:
- '156004000001'
version_date:
  kaz: 2003-08-13
source:
  kaz: https://zan.gov.kz/client/#!/doc/16956/kaz/13.08.2003
