act_code: '182392'
requisite: Решение Махамбетского районного маслихата Атырауской области от 30 мая 2023 года № 27
title:
  rus: Об утверждении Плана по управлению пастбищами и их использованию по Махамбетскому району на 2023-2024 годы
  kaz: Махамбет ауданы бойынша 2023-2024 жылдарға арналған жайылымдарды басқару және оларды пайдалану жөніндегі жоспарын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2023-05-30
approved_by:
- '156004000002'
version_date:
  kaz: 2023-05-30
  rus: 2023-05-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/182392/kaz/30.05.2023
  rus: https://zan.gov.kz/client/#!/doc/182392/rus/30.05.2023
