act_code: '21060'
requisite: Атырау облысы Мақат аудандық мәслихатының 2004 жылғы 14 шілдедегі № 87-III шешімі. Атырау облысының Әділет департаментінде 2004 жылғы 19 тамызда № 2111 болып тіркелді
title:
  rus: Мақат ауданының «Құрметті азаматы» атағын беру ережесі туралы
  kaz: Мақат ауданының «Құрметті азаматы» атағын беру ережесі туралы
form: РЕШ
type_codes:
- ПОЛ
- РЕШ
approved_on: 2004-07-13
approved_by:
- '156006000002'
version_date:
  kaz: 2004-07-13
source:
  kaz: https://zan.gov.kz/client/#!/doc/21060/kaz/13.07.2004
