act_code: '32770'
requisite: Атырау облысы Құрманғазы аудандық мәслихатының 2007 жылғы 11 сәуірдегі № 344-XXXYIII шешімі. Атырау облысының Құрманғазы аудандық Әділет басқармасында 2007 жылғы 19 сәуірде № 4-8-76 болып тіркелді
title:
  rus: Аз қамтылған отбасыларына (азаматтарға) тұрғын үйді ұстауға (жеке тұрған үйді ұстаудан басқа) және коммуналдық қызметтерді тұтынуға төлем төлеуге тұрғын үй көмегін көрсету тәртібін бекіту туралы
  kaz: Аз қамтылған отбасыларына (азаматтарға) тұрғын үйді ұстауға (жеке тұрған үйді ұстаудан басқа) және коммуналдық қызметтерді тұтынуға төлем төлеуге тұрғын үй көмегін көрсету тәртібін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2007-04-11
approved_by:
- '156003000002'
version_date:
  kaz: 2007-04-11
source:
  kaz: https://zan.gov.kz/client/#!/doc/32770/kaz/11.04.2007
