act_code: '190728'
requisite: Решение Жылыойского районного маслихата Атырауской области от 20 декабря 2023 года № 10-5
title:
  rus: Об утверждении регламентов собраний местного сообщества города Кульсары, поселка Жана Каратон и сельских округов Жылыойского района
  kaz: Жылыой ауданының Құлсары қаласы, Жаңа Қаратон кентінің және ауылдық округтердегі жергілікті қоғамдастық жиналыстарының регламенттерін бекіту туралы
form: РЕШ
type_codes:
- РЕГЛ
- РЕШ
approved_on: 2023-12-20
approved_by:
- '156009000002'
version_date:
  kaz: 2023-12-20
  rus: 2023-12-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/190728/kaz/20.12.2023
  rus: https://zan.gov.kz/client/#!/doc/190728/rus/20.12.2023
