act_code: '144799'
requisite: Решение Индерского районного маслихата Атырауской области от 30 июня 2020 года № 389-VI. Зарегистрировано Департаментом юстиции Атырауской области 14 июля 2020 года № 4697
title:
  rus: Об установлении специалистам в области социального обеспечения, образования, культуры и спорта являющимся гражданскими служащими и работающим в сельской местности повышенные должностные оклады и тарифные ставки
  kaz: Азаматтық қызметшілер болып табылатын және ауылдық жерде жұмыс iстейтiн әлеуметтiк қамсыздандыру, бiлiм беру, мәдениет және спорт саласындағы мамандарға жоғарылатылған лауазымдық айлықақылар мен тарифтiк мөлшерлемелер белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-06-30
approved_by:
- '156008000002'
version_date:
  kaz: 2020-06-30
  rus: 2020-06-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/144799/kaz/30.06.2020
  rus: https://zan.gov.kz/client/#!/doc/144799/rus/30.06.2020
