act_code: '118879'
requisite: Решение Махамбетского районного маслихата Атырауской области от 26 января 2018 года № 209. Зарегистрировано Департаментом юстиции Атырауской области 15 февраля 2018 года № 4059. Утратило силу решением Махамбетского районного маслихата Атырауской области от 29 июня 2020 года № 443 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об установлении единых ставок фиксированного налога
  kaz: Тіркелген салықтың бірыңғай мөлшерлемелерін белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-01-26
approved_by:
- '156004000002'
version_date:
  kaz: 2019-01-22
  rus: 2019-01-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/118879/kaz/22.01.2019
  rus: https://zan.gov.kz/client/#!/doc/118879/rus/22.01.2019
caused_by:
  code: '128842'
  requisite: Решение Махамбетского районного маслихата Атырауской области от 22 января 2019 года № 316. Зарегистрировано Департаментом юстиции Атырауской области 29 января 2019 года № 4338. Утратило силу решением Махамбетского районного маслихата Атырауской области от 29 июня 2020 года № 443 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
  title:
    rus: О внесении изменения в решение Махамбетского районного маслихата от 26 января 2018 года № 209 «Об установлении единых ставок фиксированного налога»
    kaz: Махамбет аудандық мәслихатының 2018 жылғы 26 қаңтардағы № 209 «Тіркелген салықтың бірыңғай мөлшерлемелерін белгілеу туралы» шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/128842/rus
