act_code: '187142'
requisite: Решение Исатайского районного маслихата Атырауской области от 5 октября 2023 года № 46-VIII. Зарегистрировано в Департаменте юстиции Атырауской области 13 октября 2023 года № 5093-06
title:
  rus: Об утверждении правил оказания социальной помощи, установления ее размеров и определения перечня отдельных категорий нуждающихся граждан
  kaz: Әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың қағидаларын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2023-10-05
approved_by:
- '156005000002'
version_date:
  kaz: 2024-12-25
  rus: 2024-12-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/187142/kaz/25.12.2024
  rus: https://zan.gov.kz/client/#!/doc/187142/rus/25.12.2024
caused_by:
  code: '205048'
  requisite: Решение Исатайского районного маслихата Атырауской области от 25 декабря 2024 года № 134-VIII. Зарегистрировано в Департаменте юстиции Атырауской области 30 декабря 2024 года № 5247-06
  title:
    rus: О внесении изменения в решение Исатайского районного маслихата от 5 октября 2023 года № 46-VIII «Об утверждении правил оказания социальной помощи, установления ее размеров и определения перечня отдельных категорий нуждающихся граждан»
    kaz: «Әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың қағидаларын бекіту туралы» Исатай аудандық мәслихатының 2023 жылғы 5 қазандағы № 46-VIII шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/205048/rus
