act_code: '128497'
requisite: Решение Индерского районного маслихата Атырауской области от 11 января 2019 года № 247-VI. Зарегистрировано Департаментом юстиции Атырауской области 15 января 2019 года № 4329
title:
  rus: О бюджетах сельских округов и поселка Индербор Индерского района на 2019-2021 годы
  kaz: 2019-2021 жылдарға арналған Индер ауданының ауылдық округтерінің және Индербор кентінің бюджеттері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-01-11
approved_by:
- '156008000002'
version_date:
  kaz: 2019-11-08
  rus: 2019-11-08
source:
  kaz: https://zan.gov.kz/client/#!/doc/128497/kaz/08.11.2019
  rus: https://zan.gov.kz/client/#!/doc/128497/rus/08.11.2019
caused_by:
  code: '136115'
  requisite: Решение Индерского районного маслихата Атырауской области от 8 ноября 2019 года № 327-VI. Зарегистрировано Департаментом юстиции Атырауской области 15 ноября 2019 года № 4525
  title:
    rus: О внесении изменений в решение районного маслихата от 11 января 2019 года № 247-VІ «О бюджетах сельских округов и поселка Индербор Индерского района на 2019-2021 годы»
    kaz: Аудандық мәслихаттың 2019 жылғы 11 қаңтардағы № 247-VІ «2019-2021 жылдарға арналған Индер ауданының ауылдық округтерінің және Индербор кентінің бюджеттері туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/136115/rus
