act_code: '66924'
requisite: Решение Махамбетского районного маслихата Атырауской области № 33 от 16 июля 2012 года. Зарегистрировано Департаментом юстиции Атырауской области 1 августа 2012 года № 4-3-179. Утратило силу решением Махамбетского районного маслихата Атырауской области от 10 декабря 2012 года № 54
title:
  rus: Об определении размера и правил оказания жилищной помощи  малообеспеченным семьям (гражданам), проживающим в Махамбетском районе
  kaz: Махамбет ауданында тұратын аз қамтамасыз етілген отбасыларға (азаматтарға) тұрғын үй көмегін көрсетудің мөлшері мен қағидасын айқындау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2012-07-16
approved_by:
- '156004000002'
version_date:
  kaz: 2012-10-01
  rus: 2012-10-01
source:
  kaz: https://zan.gov.kz/client/#!/doc/66924/kaz/01.10.2012
  rus: https://zan.gov.kz/client/#!/doc/66924/rus/01.10.2012
caused_by:
  code: '67994'
  requisite: Решение Махамбетского районного маслихата Атырауской области от 1 октября 2012 года № 42. Зарегистрировано Департаментом юстиции Атырауской области 11 октября 2012 года № 2623. Утратило силу - решением Махамбетского районного маслихата Атырауской области от 10 декабря 2012 года № 54
  title:
    rus: О внесении дополнений в решение Махамбетского районного маслихата от 16 июля 2012года № 33 "Об определении размера и правил оказания жилищной помощи малообеспеченным семьям (гражданам), проживающим в Махамбетском районе"
    kaz: Махамбет аудандық мәслихаттың 2012 жылғы 16 шілдедегі № 33 "Махамбет      ауданында тұратын аз қамтамасыз етілген отбасыларға (азаматтарға) тұрғын   үй көмегін көрсетудің мөлшері мен қағидасын айқындау туралы" шешіміне  толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/67994/rus
