act_code: '66924'
requisite: Решение Махамбетского районного маслихата Атырауской области № 33 от 16 июля 2012 года. Зарегистрировано Департаментом юстиции Атырауской области 1 августа 2012 года № 4-3-179. Утратило силу решением Махамбетского районного маслихата Атырауской области от 10 декабря 2012 года № 54
title:
  rus: Об определении размера и правил оказания жилищной помощи  малообеспеченным семьям (гражданам), проживающим в Махамбетском районе
  kaz: Махамбет ауданында тұратын аз қамтамасыз етілген отбасыларға (азаматтарға) тұрғын үй көмегін көрсетудің мөлшері мен қағидасын айқындау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2012-07-16
approved_by:
- '156004000002'
version_date:
  kaz: 2012-07-16
  rus: 2012-07-16
source:
  kaz: https://zan.gov.kz/client/#!/doc/66924/kaz/16.07.2012
  rus: https://zan.gov.kz/client/#!/doc/66924/rus/16.07.2012
