act_code: '38023'
requisite: Атырау облысы Махамбет аудандық мәслихатының 2007 жылғы 22 қаңтардағы № 36 шешімі. Атырау облысы Махамбет аудандық Әділет басқармасында 2008 жылғы 25 ақпанда № 4-3-86 болып тіркелді
title:
  rus: Аудандық әкімияттың 2007 жылғы 21 қарашадағы № 415 "Аз қамтылған отбасыларына (азаматтарға) тұрғын үйді ұстауға және коммуналдық қызметтерді тұтынуға төлем төлеуге тұрғын  үй көмегін көрсету туралы" қаулысын бекіту туралы
  kaz: Аудандық әкімияттың 2007 жылғы 21 қарашадағы № 415 "Аз қамтылған отбасыларына (азаматтарға) тұрғын үйді ұстауға және коммуналдық қызметтерді тұтынуға төлем төлеуге тұрғын  үй көмегін көрсету туралы" қаулысын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-01-22
approved_by:
- '156004000002'
version_date:
  kaz: 2008-01-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/38023/kaz/22.01.2008
