act_code: '31722'
requisite: Атырау облысы Қызылқоға аудандық мәслихатының 2006 жылғы 11 желтоқсандағы № XXIX-7 шешімі. Атырау облысының Әділет департаменті Қызылқоға  ауданының Әділет басқармасында 2006 жылғы 25 желтоқсанда № 4-5-64 болып тіркелді
title:
  rus: Аудандық мәслихаттың 2006 жылғы 17 сәуірдегі мемлекеттік тіркеу 4-5-59 «Қызылқоға ауданындағы жер учаскелеріне құқық табыстау Ережелері туралы»  № XXV-5 шешімінің күшін жою туралы
  kaz: Аудандық мәслихаттың 2006 жылғы 17 сәуірдегі мемлекеттік тіркеу 4-5-59 «Қызылқоға ауданындағы жер учаскелеріне құқық табыстау Ережелері туралы»  № XXV-5 шешімінің күшін жою туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2006-12-11
approved_by:
- '156007000002'
version_date:
  kaz: 2006-12-11
source:
  kaz: https://zan.gov.kz/client/#!/doc/31722/kaz/11.12.2006
