act_code: '12488'
requisite: Екiншi сайланған Атырау облыстық мәслихаты XVII сессиясының шешімі 2002 жылғы 19 сәуір № 203-ІІ. Атырау облысының Әділет басқармасында 2002 жылғы 1 маусымда № 986 тіркелді
title:
  rus: Исатай ауданында Нарын, Жанбай селолық округтерiн құру және Исатай, Забурын, Аққыстау, Тұщықұдық селолық округтерiнiң әкiмшiлiк-аумақтық шекараларын өзгерту туралы
  kaz: Исатай ауданында Нарын, Жанбай селолық округтерiн құру және Исатай, Забурын, Аққыстау, Тұщықұдық селолық округтерiнiң әкiмшiлiк-аумақтық шекараларын өзгерту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2002-04-18
approved_by:
- '156000000002'
version_date:
  kaz: 2014-10-10
source:
  kaz: https://zan.gov.kz/client/#!/doc/12488/kaz/10.10.2014
