act_code: '49060'
requisite: Атырау облысы Махамбет ауданы Махамбет селолық округі әкімінің 2009 жылғы 12 қарашадағы № 385 шешімі. Атырау облысы Әділет департаменті Махамбет ауданының Әділет басқармасында 2009 жылғы 7 желтоқсанда № 4-3-135 тіркелді. Күші жойылды - Атырау облысы Махамбет ауданы Махамбет селолық округі әкімінің 2010 жылғы 21 маусымдағы № 123 шешімімен
title:
  rus: Жаңа көшелерге атаулар беру туралы
  kaz: Жаңа көшелерге атаулар беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-11-12
approved_by:
- '156004012002'
version_date:
  kaz: 2009-11-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/49060/kaz/12.11.2009
