act_code: '120337'
requisite: Решение Атырауского областного маслихата от 16 марта 2018 года № 199-VI. Зарегистрировано Департаментом юстиции Атырауской области 9 апреля 2018 года № 4092
title:
  rus: Об утверждении Правил благоустройства территорий городов и населенных пунктов Атырауской области
  kaz: Атырау облысының қалалары мен елді мекендерінің аумақтарында абаттандырудың қағидаларын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2018-03-16
approved_by:
- '156000000002'
version_date:
  kaz: 2018-03-16
  rus: 2018-03-16
source:
  kaz: https://zan.gov.kz/client/#!/doc/120337/kaz/16.03.2018
  rus: https://zan.gov.kz/client/#!/doc/120337/rus/16.03.2018
