act_code: '37791'
requisite: Атырау облысы Жылыой ауданы әкімінің 2007 жылғы 29 желтоқсандағы № 30 шешімі. Жылыой аудандық Әділет басқармасында 2008 жылғы 18 қаңтарда № 4-2-89 болып тіркелді
title:
  rus: 2008 жылғы қаңтар-наурыз айларында аудан көлемінде әскери есепке алу бөлімшесіне 1991 жылы туған азаматтарды тіркеу туралы
  kaz: 2008 жылғы қаңтар-наурыз айларында аудан көлемінде әскери есепке алу бөлімшесіне 1991 жылы туған азаматтарды тіркеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2007-12-29
approved_by:
- '156009000003'
version_date:
  kaz: 2007-12-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/37791/kaz/29.12.2007
