act_code: '129135'
requisite: Решение акима Есболского сельского округа Индерского района Атырауской области от 15 февраля 2019 года № 8. Зарегистрировано Департаментом юстиции Атырауской области 18 февраля 2019 года № 4341. Утратило силу решением акима Есболского сельского округа Индерского района Атырауской области от 14 июня 2019 года № 33
title:
  rus: Об установлении ограничительных мероприятий
  kaz: Шектеу іс-шараларын белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-02-15
approved_by:
- '156008002002'
version_date:
  kaz: 2019-02-15
  rus: 2019-02-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/129135/kaz/15.02.2019
  rus: https://zan.gov.kz/client/#!/doc/129135/rus/15.02.2019
