act_code: '4716'
requisite: Решение акима Атырауской области от 18 октября 1999 года № 204. Зарегистрировано Управлением юстиции Атырауской области 11 ноября 1999 года № 115. Утратило силу постановлением акима Атырауской области от 20 декабря 2004 года № 248
title:
  rus: О кредитовании бизнес-проектов малого предпринимательства на местном уровне
  kaz: О кредитовании бизнес-проектов малого предпринимательства на местном уровне
form: РЕШ
type_codes:
- РЕШ
approved_on: 1999-10-17
approved_by:
- '156000000001'
version_date:
  rus: 1999-10-17
source:
  rus: https://zan.gov.kz/client/#!/doc/4716/rus/17.10.1999
