act_code: '52001'
requisite: Атырау облысы Құрманғазы ауданы Бірлік селолық округі әкімінің 2010 жылғы 16 сәуірдегі № 3 шешімі. Атырау облысы Әділет департаменті Құрманғазы ауданының Әділет басқармасында 2010 жылғы 27 сәуірде № 4-8-185 тіркелді. Күші жойылды - Атырау облысы Құрманғазы ауданы Бірлік селолық округі әкімінің 2010 жылғы 22 қазандағы № 77 шешімімен
title:
  rus: Бірлік селолық округіне қарасты Бірлік селосындағы "Утеринская" көшесінің атауын өзгерту туралы
  kaz: Бірлік селолық округіне қарасты Бірлік селосындағы "Утеринская" көшесінің атауын өзгерту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-04-16
approved_by:
- '156003005002'
version_date:
  kaz: 2010-04-16
source:
  kaz: https://zan.gov.kz/client/#!/doc/52001/kaz/16.04.2010
