act_code: '50229'
requisite: Атырау облысы Исатай ауданы әкімінің 2009 жылғы 23 желтоқсандағы № 64 шешімі. Исатай аудандық Әділет басқармасында 2010 жылғы 22 қаңтарда № 4-4-150 тіркелді. Күші жойылды - Атырау облысы Исатай ауданы әкімінің 2011 жылғы 15 тамыздағы № 30 қаулысымен
title:
  rus: Исатай ауданының 1993 жылы туылған азаматтарын 2010 жылы шақыру учаскелеріне тіркеуді жүргізу туралы
  kaz: Исатай ауданының 1993 жылы туылған азаматтарын 2010 жылы шақыру учаскелеріне тіркеуді жүргізу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-12-23
approved_by:
- '156005000001'
version_date:
  kaz: 2009-12-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/50229/kaz/23.12.2009
