act_code: '18987'
requisite: Атырау облыстық мәслихатының 2004 жылғы 23 қаңтардағы № 63-III шешiмi. Атырау облысының Әділет департаментінде 2004 жылғы 20 ақпанда № 1852 болып тіркелді
title:
  rus: Атырау облысында туризм саласын дамытудың 2004-2005 жылдарға арналған Бағдарламасын бекіту туралы
  kaz: Атырау облысында туризм саласын дамытудың 2004-2005 жылдарға арналған Бағдарламасын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2004-01-23
approved_by:
- '156000000002'
version_date:
  kaz: 2004-01-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/18987/kaz/23.01.2004
