act_code: '20713'
requisite: Решение акима Атырауской области от 21 мая 2004 года № 51. Зарегистрировано Департаментом юстиции Атырауской области от 1 июля 2004 года № 2042
title:
  rus: О некоторых вопросах борьбы с коррупцией
  kaz: О некоторых вопросах борьбы с коррупцией
form: РЕШ
type_codes:
- РЕШ
approved_on: 2004-05-20
approved_by:
- '156000000003'
version_date:
  rus: 2004-05-20
source:
  rus: https://zan.gov.kz/client/#!/doc/20713/rus/20.05.2004
