act_code: '107783'
requisite: Решение Курмангазинского районного маслихата Атырауской области от 2 ноября 2016 года № 87-VI. Зарегистрировано Департаментом юстиции Атырауской области 24 ноября 2016 года № 3686. Утратило силу решением Курмангазинского районного маслихата Атырауской области от 24 мая 2017 года № 165-VI
title:
  rus: Об утверждении правил оказания социальной помощи, установления размеров и определения перечня отдельных категорий нуждающихся граждан
  kaz: Әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың қағидаларын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2016-11-02
approved_by:
- '156003000002'
version_date:
  kaz: 2016-11-02
  rus: 2016-11-02
source:
  kaz: https://zan.gov.kz/client/#!/doc/107783/kaz/02.11.2016
  rus: https://zan.gov.kz/client/#!/doc/107783/rus/02.11.2016
