act_code: '134547'
requisite: Решение акима Суюндукского сельского округа Курмангазинского района Атырауской области от 5 сентября 2019 года № 26. Зарегистрировано Департаментом юстиции Атырауской области 9 сентября 2019 года № 4488
title:
  rus: О признании утратившим силу решения акима сельского округа Суюндук от 24 июля 2019 года № 23 «Об установлении карантина»
  kaz: Сүйіндік ауылдық округі әкімінің 2019 жылғы 24 шілдедегі № 23 «Карантин белгілеу туралы» шешімінің күшін жою туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-09-05
approved_by:
- '156003015002'
version_date:
  kaz: 2019-09-05
  rus: 2019-09-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/134547/kaz/05.09.2019
  rus: https://zan.gov.kz/client/#!/doc/134547/rus/05.09.2019
