act_code: '32412'
requisite: Атырау облысы Махамбет аудандық мәслихатының 2007 жылғы 14 наурыздағы № 341 шешімі. Атырау облысы Махамбет аудандық Әділет басқармасында 2007 жылғы 20 наурызда № 4-3-59 болып тіркелді
title:
  rus: Азаматтардың кейбір санаттарына газетке жазылуға берілетін әлеуметтік көмек көрсету тәртібі туралы
  kaz: Азаматтардың кейбір санаттарына газетке жазылуға берілетін әлеуметтік көмек көрсету тәртібі туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2007-03-14
approved_by:
- '156004000002'
version_date:
  kaz: 2007-03-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/32412/kaz/14.03.2007
