act_code: '97106'
requisite: Решение от 11.12.2015 №419-V, Маслихат Атырауской области . Зарегистрировано Департаментом юстиции Атырауской области 5 января 2016 года № 3421. Утратило силу решением Атырауского областного маслихата от 17 марта 2017 года № 95-VI
title:
  rus: Об областном бюджете на 2016-2018 годы
  kaz: 2016 - 2018 жылдарға арналған облыстық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-12-11
approved_by:
- '156000000002'
version_date:
  kaz: 2016-10-28
  rus: 2016-10-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/97106/kaz/28.10.2016
  rus: https://zan.gov.kz/client/#!/doc/97106/rus/28.10.2016
caused_by:
  code: '107520'
  requisite: Решение Атырауского областного маслихата от 28 октября 2016 года № 51-VI. Зарегистрировано Департаментом юстиции Атырауской области 11 ноября 2016 года № 3670. Утратило силу решением Атырауского областного маслихата от 17 марта 2017 года № 95-VI
  title:
    rus: О внесении изменений и дополнений в решение XXХVІ сессии областного маслихата V созыва от 11 декабря 2015 года № 419-V «Об областном бюджете на 2016-2018 годы»
    kaz: V шақырылған облыстық мәслихаттың ХХХVІ сессиясының 2015 жылғы 11 желтоқсандағы № 419-V «2016-2018 жылдарға арналған облыстық бюджет туралы» шешіміне өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/107520/rus
