act_code: '97106'
requisite: Решение от 11.12.2015 №419-V, Маслихат Атырауской области . Зарегистрировано Департаментом юстиции Атырауской области 5 января 2016 года № 3421. Утратило силу решением Атырауского областного маслихата от 17 марта 2017 года № 95-VI
title:
  rus: Об областном бюджете на 2016-2018 годы
  kaz: 2016 - 2018 жылдарға арналған облыстық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-12-11
approved_by:
- '156000000002'
version_date:
  kaz: 2016-07-04
  rus: 2016-07-04
source:
  kaz: https://zan.gov.kz/client/#!/doc/97106/kaz/04.07.2016
  rus: https://zan.gov.kz/client/#!/doc/97106/rus/04.07.2016
caused_by:
  code: '104428'
  requisite: Решение маслихата Атырауской области от 4 июля 2016 года № 39-VI. Зарегистрировано Департаментом юстиции Атырауской области 13 июля 2016 года № 3556. Утратило силу решением Атырауского областного маслихата от 17 марта 2017 года № 95-VI
  title:
    rus: О внесении изменений и дополнений в решение XXХVІ сессии областного маслихата V созыва от 11 декабря 2015 года № 419-V «Об областном бюджете на 2016-2018 годы»
    kaz: V шақырылған облыстық мәслихаттың ХХХVІ сессиясының 2015 жылғы 11 желтоқсандағы 419-V «2016-2018 жылдарға арналған облыстық бюджет туралы» шешіміне өзгерістер мен толықтырулар енгізу  туралы
  link: https://zan.gov.kz/client/#!/doc/104428/rus
