act_code: '47632'
requisite: Атырау облысы Индер ауданы Индербор кенттік округі әкімінің 2009 жылғы 14 тамыздағы № 211 шешімі. Атырау облысының Әділет департаменті Индер ауданының Әділет басқармасында 2009 жылғы 19 тамызда № 4-6-87 тіркелді. Күші жойылды - Атырау облысы Индер ауданы Индербор кенттік округі әкімінің 2010 жылғы 29 қазандағы № 134 шешімімен
title:
  rus: Көшеге жаңа атау беру туралы
  kaz: Көшеге жаңа атау беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-08-14
approved_by:
- '156008007001'
version_date:
  kaz: 2009-08-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/47632/kaz/14.08.2009
