act_code: '172453'
requisite: Решение акима Атырауского сельского округа города Атырау Атырауской области от 26 сентября 2022 года № 707. Зарегистрировано в Министерстве юстиции Республики Казахстан 4 октября 2022 года № 29987
title:
  rus: О присвоении наименований и переименовании улиц Атырауского сельского округа города Атырау
  kaz: Атырау қаласы Атырау ауылдық округінің көшелеріне атаулар беру және қайта атау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-09-26
approved_by:
- '156002003002'
version_date:
  kaz: 2022-09-26
  rus: 2022-09-26
source:
  kaz: https://zan.gov.kz/client/#!/doc/172453/kaz/26.09.2022
  rus: https://zan.gov.kz/client/#!/doc/172453/rus/26.09.2022
