act_code: '198420'
requisite: Решение акима Кызылкогинского района Атырауской области от 1 июля 2024 года № 23
title:
  rus: О признании утратившим силу решение акима Кызылкогинского района «Об объявлении чрезвычайной ситуации природного характера местного масштаба на территории Кызылкогинского района»
  kaz: Қызылқоға ауданы әкімінің «Қызылқоға ауданы аумағында жергілікті ауқымдағы табиғи сипаттағы төтенше жағдайды жариялау туралы» шешімінің күшін жою туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-07-01
approved_by:
- '156007000003'
version_date:
  kaz: 2024-07-01
  rus: 2024-07-01
source:
  kaz: https://zan.gov.kz/client/#!/doc/198420/kaz/01.07.2024
  rus: https://zan.gov.kz/client/#!/doc/198420/rus/01.07.2024
