act_code: '10860'
requisite: Решение акима Атырауской области от 2 ноября 2001 года № 332. Зарегистрирован Управлением юстиции Атырауской области 13 декабря 2001 года за № 689
title:
  rus: Об утверждении плана мероприятий по повышению эффективности управления государственным имуществом и приватизации на 2001 год по Атырауской области
  kaz: Атырау облысы бойынша мемлекеттік мүлік пен жекешелендіруді басқару тиімділігін арттыру жөніндегі 2001 жылға арналған шаралар жоспарын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2001-11-02
approved_by:
- '156000000003'
version_date:
  kaz: 2001-11-02
  rus: 2001-11-02
source:
  kaz: https://zan.gov.kz/client/#!/doc/10860/kaz/02.11.2001
  rus: https://zan.gov.kz/client/#!/doc/10860/rus/02.11.2001
