act_code: '225332'
requisite: Решение Исатайского районного маслихата Атырауской области от 12 мая 2026 года № 234-VIII
title:
  rus: Об утверждении тарифов для населения на сбор, транспортировку, сортировку и захоронение твердых бытовых отходов по Исатайскому району
  kaz: Исатай ауданы бойынша халық үшін тұрмыстық қатты қалдықтарды жинауға, тасымалдауға, сұрыптауға және көмуге арналған тарифтерді бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2026-05-12
approved_by:
- '156005000002'
version_date:
  kaz: 2026-05-12
  rus: 2026-05-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/225332/kaz/12.05.2026
  rus: https://zan.gov.kz/client/#!/doc/225332/rus/12.05.2026
