act_code: '134993'
requisite: Решение Макатского районного маслихата Атырауской области от 13 сентября 2019 года № 303-VI. Зарегистрировано Департаментом юстиции Атырауской области 25 сентября 2019 года № 4494
title:
  rus: Об утверждении Правил и размера оказания социальной поддержки по оплате коммунальных услуг и приобретению топлива специалистам государственных организаций здравоохранения, социального обеспечения, образования, культуры, спорта и ветеринарии, проживающим и работающим в сельских населенных пунктах Макатского района
  kaz: Мақат ауданының ауылдық елді мекендерінде тұратын және жұмыс істейтін мемлекеттік денсаулық сақтау, әлеуметтік қамсыздандыру, білім беру, мәдениет, спорт және ветеринария ұйымдарының мамандарына коммуналдық көрсетілетін қызметтерге ақы төлеу және отын сатып алу бойынша әлеуметтік қолдау көрсету қағидасы мен мөлшерін бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2019-09-13
approved_by:
- '156006000002'
version_date:
  kaz: 2023-09-08
  rus: 2023-09-08
source:
  kaz: https://zan.gov.kz/client/#!/doc/134993/kaz/08.09.2023
  rus: https://zan.gov.kz/client/#!/doc/134993/rus/08.09.2023
caused_by:
  code: '186148'
  requisite: Решение Макатского районного маслихата Атырауской области от 8 сентября 2023 года № 42-VIII. Зарегистрировано в Департаменте юстиции Атырауской области 15 сентября 2023 года № 5079-06
  title:
    rus: О внесении изменений в решение Макатского районного маслихата от 13 сентября 2019 года № 303-VI «Об утверждении Правил и размера оказания социальной поддержки по оплате коммунальных услуг и приобретению топлива специалистам государственных организаций здравоохранения, социального обеспечения, образования, культуры, спорта и ветеринарии, проживающим и работающим в сельских населенных пунктах Макатского района»
    kaz: Мақат аудандық мәслихатының 2019 жылғы 13 қыркүйектегі № 303-VI «Мақат ауданының ауылдық елді мекендерінде тұратын және жұмыс істейтін  мемлекеттік денсаулық сақтау, әлеуметтік қамсыздандыру, білім беру, мәдениет, спорт және ветеринария ұйымдарының мамандарына коммуналдық көрсетілетін қызметтерге ақы төлеу және отын сатып алу бойынша әлеуметтік қолдау көрсету қағидасы мен мөлшерін бекіту туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/186148/rus
