act_code: '118054'
requisite: Решение Атырауского городского маслихата Атырауской области от 21 декабря 2017 года № 184. Зарегистрировано Департаментом юстиции Атырауской области 12 января 2018 года № 4040
title:
  rus: О бюджете сельских округов относящихся к городу Атырау на 2018–2020 годы
  kaz: 2018–2020 жылдарға арналған Атырау қаласына қарасты ауылдық округтер бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2017-12-21
approved_by:
- '156002000002'
version_date:
  kaz: 2018-06-28
  rus: 2018-06-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/118054/kaz/28.06.2018
  rus: https://zan.gov.kz/client/#!/doc/118054/rus/28.06.2018
caused_by:
  code: '123834'
  requisite: Решение Атырауского городского маслихата Атырауской области от 28 июня 2018 года № 234. Зарегистрировано Департаментом юстиции Атырауской области 20 июля 2018 года № 4206
  title:
    rus: О внесении изменений в решение городского маслихата от 21 декабря 2017 года № 184 «О бюджете сельских округов города Атырау на 2018-2020 годы»
    kaz: Қалалық мәслихаттың 2017 жылғы 21 желтоқсандағы № 184 «2018-2020 жылдарға арналған Атырау қаласына қарасты ауылдық округтер бюджеті туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/123834/rus
