act_code: '199741'
requisite: Решение Исатайского районного маслихата Атырауской области от 30 июля 2024 года № 102-VIII. Зарегистрировано в Департаменте юстиции Атырауской области 13 августа 2024 года № 5219-06
title:
  rus: О некоторых вопросах проведения мирных собраний
  kaz: Бейбіт жиналыстар өткізудің кейбір мәселелері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-07-30
approved_by:
- '156005000002'
version_date:
  kaz: 2024-07-30
  rus: 2024-07-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/199741/kaz/30.07.2024
  rus: https://zan.gov.kz/client/#!/doc/199741/rus/30.07.2024
