act_code: '48164'
requisite: Решение от 01.10.2009 №16, Акимат Кара-Арнинского сельского округа
title:
  rus: Шоқпартоғай селосы көшелеріне атау беру туралы
  kaz: Шоқпартоғай селосы көшелеріне атау беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-10-01
approved_by:
- '156009005001'
version_date:
  kaz: 2009-10-01
source:
  kaz: https://zan.gov.kz/client/#!/doc/48164/kaz/01.10.2009
