act_code: '97035'
requisite: Решение Курмангазинского районного маслихата Атырауской области от 23 декабря 2015 года № 475-V. Зарегистрировано Департаментом юстиции Атырауской области 29 декабря 2015 года № 3408. Утратило силу решением Курмангазинского районного маслихата Атырауской области от 25 апреля 2024 года № 127-VIII (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об определении размера и порядка оказания жилищной помощи в Курмангазинском районе
  kaz: Құрманғазы ауданында тұрғын үй көмегін көрсетудің мөлшері мен тәртібін айқындау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-12-23
approved_by:
- '156003000002'
version_date:
  kaz: 2016-01-29
  rus: 2016-01-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/97035/kaz/29.01.2016
  rus: https://zan.gov.kz/client/#!/doc/97035/rus/29.01.2016
caused_by:
  code: '99747'
  requisite: Решение Курмангазинского районного маслихата Атырауской области от 29 января 2016 года № 504-V. Зарегистрировано Департаментом юстиции Атырауской области 25 февраля 2016 года № 3466. Утратило силу решением Курмангазинского районного маслихата Атырауской области от 25 апреля 2024 года № 127-VIII (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
  title:
    rus: «О внесении изменений и дополнения в решение районного маслихата от 23 декабря 2015 года №475-V «Об утверждении правил оказания жилищной помощи малообеспеченным семьям (гражданам), проживающим в Курмангазинском районе»
    kaz: Аудандық мәслихаттың 2015 жылғы 23 желтоқсандағы №475-V «Құрманғазы ауданында тұратын аз қамтылған отбасыларға (азаматтарға) тұрғын үй көмегін көрсетудің қағидасын бекіту туралы» шешіміне өзгерістер мен толықтыру енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/99747/rus
