act_code: '75970'
requisite: Решение Жылыойского районного маслихата Атырауской области от 11 декабря 2013 года № 17-17. Зарегистрировано Департаментом юстиции Атырауской области 18 декабря 2013 года № 2819. Утратило силу решением Жылыойского районного маслихата Атырауской области от 28 сентября 2021 года № 9-6 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении перечня категорий получателей и предельных размеров социальной помощи
  kaz: Алушылар санатының тізбесін және әлеуметтік көмектің шекті мөлшерлерін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2013-12-11
approved_by:
- '156009000002'
version_date:
  kaz: 2016-09-15
  rus: 2016-09-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/75970/kaz/15.09.2016
  rus: https://zan.gov.kz/client/#!/doc/75970/rus/15.09.2016
caused_by:
  code: '106835'
  requisite: Решение Жылыойского районного маслихата Атырауской области от 15 сентября 2016 года № 5-5. Зарегистрировано Департаментом юстиции Атырауской области 6 октября 2016 года № 3632. Утратило силу решением Жылыойского районного маслихата Атырауской области от 28 сентября 2021 года № 9-6 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
  title:
    rus: О внесении дополнения в решение районного маслихата от 11 декабря 2013 года №17-17 «Об утверждении перечня категорий получателей и предельных размеров  социальной  помощи»
    kaz: Аудандық мәслихаттың 2013 жылғы 11 желтоқсандағы №17-17 «Алушылар санатының тізбесін және әлеуметтік көмектің шекті мөлшерлерін бекіту туралы» шешіміне толықтыру енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/106835/rus
