act_code: '180718'
requisite: Решение Исатайского районного маслихата Атырауской области от 27 апреля 2023 года № 9-VIII
title:
  rus: Об утверждении Плана по управлению пастбищами и их использованию по Исатайскому району на 2023-2024 годы
  kaz: Исатай ауданы бойынша 2023-2024 жылдарға арналған жайылымдарды басқару және оларды пайдалану жөніндегі жоспарын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2023-04-27
approved_by:
- '156005000002'
version_date:
  kaz: 2023-04-27
  rus: 2023-04-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/180718/kaz/27.04.2023
  rus: https://zan.gov.kz/client/#!/doc/180718/rus/27.04.2023
