act_code: '138639'
requisite: Решение Макатского районного маслихата Атырауской области от 30 декабря 2019 года № 343-VI. Зарегистрировано Департаментом юстиции Атырауской области 15 января 2020 года № 4577
title:
  rus: О бюджетах поселков Макат, Доссор и сельского округа Байгетобе на 2020-2022 годы
  kaz: 2020-2022 жылдарға арналған Мақат, Доссор кенттерінің және Байгетөбе ауылдық округінің бюджеттері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-12-30
approved_by:
- '156006000002'
version_date:
  kaz: 2019-12-30
  rus: 2019-12-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/138639/kaz/30.12.2019
  rus: https://zan.gov.kz/client/#!/doc/138639/rus/30.12.2019
