act_code: '56871'
requisite: Решение Курмангазинского районного маслихата Атырауской области от 14 декабря 2010 года № 335-XXХIV. Зарегистрировано Управлением юстиции Курмангазинского района Атырауской области 19 января 2011 года за № 4-8-198. Утратило силу - решением Курмангазинского районного маслихата Атырауской области от 14 марта 2013 года № 147-V
title:
  rus: О районном бюджете на 2011-2013 годы
  kaz: Ауданның 2011-2013 жылдарға арналған бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-12-14
approved_by:
- '156003000002'
version_date:
  kaz: 2011-08-22
  rus: 2011-08-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/56871/kaz/22.08.2011
  rus: https://zan.gov.kz/client/#!/doc/56871/rus/22.08.2011
caused_by:
  code: '60422'
  requisite: Решение Курмангазинского районного маслихата Атырауской области от 22 августа 2011 года № 413-XXXXI. Зарегистрировано Управлением юстиции Курмангазинского района Атырауской области 13 сентября 2011 года № 4-8-212. Утратило силу - решением Курмангазинского районного маслихата Атырауской области от 14 марта 2013 года № 147-V
  title:
    rus: О внесении изменений и дополнений в решение районного маслихата от 14 декабря 2010 года № 335-ХХХІV "О районном бюджете на 2011-2013 годы"
    kaz: Аудандық мәслихаттың 2010 жылғы 14 желтоқсандағы № 335-ХХХIV "Ауданның 2011-2013 жылдарға арналған бюджеті туралы" шешіміне өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/60422/rus
