act_code: '183854'
requisite: Решение Кызылкогинского районного маслихата Атырауской области от 4 июля 2023 года № 5-2. Зарегистрировано в Департаменте юстиции Атырауской области 12 июля 2023 года № 5064-06. Утратило силу решением Кызылкогинского районного маслихата Атырауской области от 13 декабря 2023 года № 10-3 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении ставок туристского взноса для иностранцев на 2023 год по Кызылкогинскому району
  kaz: Қызылқоға ауданы бойынша шетелдіктер үшін 2023 жылға арналған туристік жарна мөлшерлемелерін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2023-07-04
approved_by:
- '156007000002'
version_date:
  kaz: 2023-07-04
  rus: 2023-07-04
source:
  kaz: https://zan.gov.kz/client/#!/doc/183854/kaz/04.07.2023
  rus: https://zan.gov.kz/client/#!/doc/183854/rus/04.07.2023
