act_code: '110160'
requisite: Решение Атырауского областного маслихата от 25 января 2017 года № 89-VI. Зарегистрировано Департаментом юстиции Атырауской области 3 марта 2017 года № 3790. Утратило силу решением Атырауского областного маслихата от 16  марта 2018 года № 207-VI
title:
  rus: Об утверждении методики оценки деятельности административных государственных служащих корпуса «Б» государственного учреждения «Аппарат Атырауского областного маслихата»
  kaz: «Атырау облыстық мәслихатының аппараты» мемлекеттік мекемесінің «Б» корпусы мемлекеттік әкімшілік қызметшілерінің қызметін бағалаудың әдістемесін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2017-01-25
approved_by:
- '156000000002'
version_date:
  kaz: 2017-01-25
  rus: 2017-01-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/110160/kaz/25.01.2017
  rus: https://zan.gov.kz/client/#!/doc/110160/rus/25.01.2017
