act_code: '98144'
requisite: Решение акима Орликовского сельского округа Индерского района Атырауской области от 30 декабря 2015 года № 23. Зарегистрировано Департаментом юстиции Атырауской области 21 января 2016 года № 3449
title:
  rus: 'О  присвоении  наименования  улице '
  kaz: 'Көшеге  атау беру  туралы '
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-12-30
approved_by:
- '156008004001'
version_date:
  kaz: 2015-12-30
  rus: 2015-12-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/98144/kaz/30.12.2015
  rus: https://zan.gov.kz/client/#!/doc/98144/rus/30.12.2015
