act_code: '174114'
requisite: Решение акима Бейбарыского сельского округа Махамбетского района Атырауской области от 22 ноября 2022 года № 45. Зарегистрировано в Министерстве юстиции Республики Казахстан 24 ноября 2022 года № 30708
title:
  rus: О присвоении наименования безымянной улице села Талдыколь Бейбарыского сельского округа
  kaz: Бейбарыс ауылдық округінің Талдыкөл ауылындағы атауы жоқ көшеге атау беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-11-22
approved_by:
- '156004006002'
version_date:
  kaz: 2022-11-22
  rus: 2022-11-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/174114/kaz/22.11.2022
  rus: https://zan.gov.kz/client/#!/doc/174114/rus/22.11.2022
