act_code: '80826'
requisite: Решение от 10.06.2014 №204-V, Маслихат Индерского района. Утратило силу - решением Индерского районного маслихата Атырауской области  от 16 сентября 2015 года № 303-V.
title:
  rus: О предоставлении социальной помощи на приобретение топлива специалистам государственных организаций здравоохранения, социального обеспечения, образования, культуры, спорта и ветеринарии проживающим и работающим в сельских населенных пунктах Индерского района
  kaz: Индер ауданының ауылдық елді мекендерінде тұратын және жұмыс істейтін мемлекеттік денсаулық сақтау, әлеуметтік қамсыздандыру, білім беру, мәдениет, спорт және ветеринария ұйымдарының мамандарына отын сатып алу үшін әлеуметтік көмек беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2014-06-10
approved_by:
- '156008000002'
version_date:
  kaz: 2014-12-05
  rus: 2014-12-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/80826/kaz/05.12.2014
  rus: https://zan.gov.kz/client/#!/doc/80826/rus/05.12.2014
caused_by:
  code: '85139'
  requisite: Решение от 05.12.2014 №242-V, Маслихат Индерского района. Утратило силу - решением Индерского районного маслихата Атырауской области  от 16 сентября 2015 года № 303-V.
  title:
    rus: О внесении изменении в решение районного маслихата от 10 июня 2014 года № 204-V "О предоставлении социальной помощи на приобретение топлива специалистам государственных организаций здравоохранения, социального обеспечения, образования, культуры, спорта и ветеринарии проживающим и работающим в сельских населенных пунктах Индерского района"
    kaz: Аудандық мәслихаттың 2014 жылғы 10 маусымдағы № 204-V "Индер ауданының ауылдық елді мекендерінде тұратын және жұмыс істейтін мемлекеттік денсаулық сақтау, әлеуметтік қамсыздандыру, білім беру, мәдениет, спорт және ветеринария ұйымдарының мамандарына отын сатып алу үшін әлеуметтік көмек беру туралы" шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/85139/rus
