act_code: '45664'
requisite: Махамбет аудандық мәслихатының 2009 жылғы 27 наурыздағы № 115 шешімі. Атырау облысы Әділет департаменті Махамбет ауданының Әділет басқармасында 2009 жылғы 6 мамырда 4-3-117 тіркелді
title:
  rus: Махамбет ауданы бойынша 2009 жылға тіркелген салық ставкасының мөлшерін белгілеу туралы
  kaz: Махамбет ауданы бойынша 2009 жылға тіркелген салық ставкасының мөлшерін белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-03-27
approved_by:
- '156004000002'
version_date:
  kaz: 2009-03-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/45664/kaz/27.03.2009
