act_code: '113768'
requisite: Решение Макатского районного маслихата Атырауской области от 30 июня 2017 года № 119-VI. Зарегистрировано Департаментом юстиции Атырауской области 24 июля 2017 года № 3933. Утратило силу решением Макатского районного маслихата Атырауской области от 8 сентября 2023 года № 43-VIII (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении правил оказания социальной помощи, установления размеров и определения перечня отдельных категорий нуждающихся граждан
  kaz: Әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың қағидаларын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2017-06-30
approved_by:
- '156006000002'
version_date:
  kaz: 2017-06-30
  rus: 2017-06-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/113768/kaz/30.06.2017
  rus: https://zan.gov.kz/client/#!/doc/113768/rus/30.06.2017
