act_code: '56805'
requisite: Решение Кызылкогинского районного маслихата Атырауской области №  XXIV-6 от 14 декабря 2010 года. Зарегистрировано Департаментом юстиции Атырауской области 17 января 2011 года № 4-5-141
title:
  rus: 2011 жылғы салық ставкаларының мөлшерін белгілеу туралы
  kaz: 2011 жылғы салық ставкаларының мөлшерін белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-12-14
approved_by:
- '156007000002'
version_date:
  kaz: 2010-12-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/56805/kaz/14.12.2010
