act_code: '129996'
requisite: Решение акима Жангельдинского сельского округа Кызылкогинского района Атырауской области от 29 марта 2019 года № 5. Зарегистрировано Департаментом юстиции Атырауской области 29 марта 2019 года № 4362. Утратило силу решением акима Жангельдинского сельского округа Кызылкогинского района Атырауской области от 28 июня 2019 года № 13 (вводится в действие после дня его первого официального опубликования)
title:
  rus: Об установлении ограничительных мероприятий
  kaz: Шектеу іс-шараларын белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-03-29
approved_by:
- '156007003002'
version_date:
  kaz: 2019-03-29
  rus: 2019-03-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/129996/kaz/29.03.2019
  rus: https://zan.gov.kz/client/#!/doc/129996/rus/29.03.2019
