act_code: '120957'
requisite: Решение Атырауского городского маслихата Атырауской области от 20 марта 2018 года № 204. Зарегистрировано Департаментом юстиции Атырауской области 12 апреля 2018 года № 4104. Утратило силу решением Атырауского городского маслихата Атырауской области от 18 сентября 2020 года № 530 (вводится в действие с 01.01.2020)
title:
  rus: Об установлении единых ставок фиксированного налога
  kaz: Тіркелген салықтың бірыңғай мөлшерлемелерін белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-03-20
approved_by:
- '156002000002'
version_date:
  kaz: 2018-08-28
  rus: 2018-08-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/120957/kaz/28.08.2018
  rus: https://zan.gov.kz/client/#!/doc/120957/rus/28.08.2018
caused_by:
  code: '125302'
  requisite: Решение Атырауского городского маслихата Атырауской области от 28 августа 2018 года № 260. Зарегистрировано Департаментом юстиции Атырауской области 4 октября 2018 года № 4250. Утратило силу решением Атырауского городского маслихата Атырауской области от 18 сентября 2020 года № 530 (вводится в действие с 01.01.2020)
  title:
    rus: О внесении изменения в решение Атырауского городского маслихата от 20 марта 2018 года № 204 «Об установлении единых ставок фиксированного налога»
    kaz: Атырау қалалық мәслихатының 2018 жылғы 20 наурыздағы № 204 «Тіркелген салықтың бірыңғай мөлшерлемелерін белгілеу туралы» шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/125302/rus
