act_code: '86140'
requisite: Решение Кызылкогинского районного маслихата Атырауской области от 25 декабря 2014 года № XXIX-1. Зарегистрировано Департаментом юстиции Атырауской области 21 января 2015 года № 3093
title:
  rus: 'О районном бюджете на 2015-2017 годы '
  kaz: 2015-2017 жылдарға арналған аудандық бюджет  туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2014-12-25
approved_by:
- '156007000002'
version_date:
  kaz: 2015-09-15
  rus: 2015-09-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/86140/kaz/15.09.2015
  rus: https://zan.gov.kz/client/#!/doc/86140/rus/15.09.2015
caused_by:
  code: '93968'
  requisite: Решение Кызылкогинского районного маслихата Атырауской области от 15 сентября 2015 года № XXXIV-3. Зарегистрировано Департаментом юстиции Атырауской области 28 сентября 2015 года № 3299
  title:
    rus: О внесении изменений в решение Кызылкогинского районного маслихата от 25 декабря 2014 года № ХХІХ-1 «О районном бюджете на 2015-2017 годы»
    kaz: Қызылқоға аудандық мәслихатының 2014 жылғы 25 желтоқсандағы № ХХІХ-1 «2015-2017 жылдарға арналған аудандық бюджет туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/93968/rus
