act_code: '86140'
requisite: Решение Кызылкогинского районного маслихата Атырауской области от 25 декабря 2014 года № XXIX-1. Зарегистрировано Департаментом юстиции Атырауской области 21 января 2015 года № 3093
title:
  rus: 'О районном бюджете на 2015-2017 годы '
  kaz: 2015-2017 жылдарға арналған аудандық бюджет  туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2014-12-25
approved_by:
- '156007000002'
version_date:
  kaz: 2014-12-25
  rus: 2014-12-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/86140/kaz/25.12.2014
  rus: https://zan.gov.kz/client/#!/doc/86140/rus/25.12.2014
