act_code: '177235'
requisite: Решение Жылыойского районного маслихата Атырауской области от 27 декабря 2022 года № 28-1
title:
  rus: О бюджетах города Кульсары, поселка Жана-Каратон, сельских округов Жем, Косчагиль, Кара-Арна, Майкумген и Аккиизтогай на 2023-2025 годы
  kaz: 2023-2025 жылдарға арналған Құлсары қаласының, Жаңа-Қаратон кентінің, Жем, Қосшағыл, Қара-Арна, Майкөмген және Ақкиізтоғай ауылдық округтерінің бюджеттері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-12-27
approved_by:
- '156009000002'
version_date:
  kaz: 2022-12-27
  rus: 2022-12-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/177235/kaz/27.12.2022
  rus: https://zan.gov.kz/client/#!/doc/177235/rus/27.12.2022
