act_code: '177235'
requisite: Решение Жылыойского районного маслихата Атырауской области от 27 декабря 2022 года № 28-1
title:
  rus: О бюджетах города Кульсары, поселка Жана-Каратон, сельских округов Жем, Косчагиль, Кара-Арна, Майкумген и Аккиизтогай на 2023-2025 годы
  kaz: 2023-2025 жылдарға арналған Құлсары қаласының, Жаңа-Қаратон кентінің, Жем, Қосшағыл, Қара-Арна, Майкөмген және Ақкиізтоғай ауылдық округтерінің бюджеттері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-12-27
approved_by:
- '156009000002'
version_date:
  kaz: 2023-05-24
  rus: 2023-05-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/177235/kaz/24.05.2023
  rus: https://zan.gov.kz/client/#!/doc/177235/rus/24.05.2023
caused_by:
  code: '182239'
  requisite: Решение Жылыойского районного маслихата Атырауской области от 24 мая 2023 года № 4-1
  title:
    rus: О внесении изменений в решение Жылыойского районного маслихата «О бюджетах города Кульсары, поселка Жана-Каратон, сельских округов Жем, Косчагиль, Кара-Арна, Майкумген и Аккиизтогай на 2023-2025 годы» от 27 декабря 2022 года № 28-1
    kaz: «2023-2025 жылдарға арналған Құлсары қаласының, Жаңа-Қаратон кентінің, Жем, Қосшағыл, Қара-Арна, Майкөмген және Ақкиізтоғай ауылдық округтерінің бюджеттері туралы» Жылыой аудандық мәслихатының 2022 жылғы 27 желтоқсандағы № 28-1 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/182239/rus
