act_code: '18365'
requisite: Атырау облыстық мәслихатының 2003 жылғы 6 маусымдағы № 302-ІІ шешімі. Атырау облысының Әділет басқармасында 2003 жылғы 10 шілдеде № 1556 тіркелді
title:
  rus: Атырау облысының 2003-2005 жылдарға арналған қоршаған ортаны қорғау және экологиялық ахуалды жақсарту жөнiндегi кешендi бағдарлама туралы
  kaz: Атырау облысының 2003-2005 жылдарға арналған қоршаған ортаны қорғау және экологиялық ахуалды жақсарту жөнiндегi кешендi бағдарлама туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2003-06-05
approved_by:
- '156000000002'
version_date:
  kaz: 2003-06-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/18365/kaz/05.06.2003
