act_code: '128466'
requisite: Решение Макатского районного маслихата Атырауской области от 9 января 2019 года № 239-VI. Зарегистрировано Департаментом юстиции Атырауской области 11 января 2019 года № 4328
title:
  rus: «О бюджетах поселков Макат и Доссор на 2019-2021 годы»
  kaz: «2019-2021 жылдарға арналған Мақат және Доссор кенттерінің бюджеттері туралы»
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-01-09
approved_by:
- '156006000002'
version_date:
  kaz: 2019-01-09
  rus: 2019-01-09
source:
  kaz: https://zan.gov.kz/client/#!/doc/128466/kaz/09.01.2019
  rus: https://zan.gov.kz/client/#!/doc/128466/rus/09.01.2019
