act_code: '65894'
requisite: Постановление Жылыойского районного акимата Атырауской области от 21 мая 2012 года № 166. Зарегистрировано Департаментом юстиции Атырауской области 6 июня 2012 года № 4-2-174. Утратило силу - постановлением Жылыойского районного акимата Атырауской области № 115 от 28 февраля 2013 года
title:
  rus: Об оказании ежемесячной материальной помощи
  kaz: Ай сайынғы материалдық көмек көрсету туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2012-05-21
approved_by:
- '156009000001'
version_date:
  kaz: 2012-05-21
  rus: 2012-05-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/65894/kaz/21.05.2012
  rus: https://zan.gov.kz/client/#!/doc/65894/rus/21.05.2012
