act_code: '144087'
requisite: Решение акима Махамбетского сельского округа Махамбетского района Атырауской области от 22 июня 2020 года № 121. Зарегистрировано Департаментом юстиции Атырауской области 24 июня 2020 года № 4676
title:
  rus: О признании утратившим силу решения акима Махамбетского сельского округа от 25 февраля 2020 года № 53 «Об установлении ограничительных мероприятий»
  kaz: Махамбет ауылдық округі әкімінің 2020 жылғы 25 ақпандағы № 53 «Шектеу іс-шараларын белгілеу туралы» шешімінің күшін жою туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-06-22
approved_by:
- '156004012002'
version_date:
  kaz: 2020-06-22
  rus: 2020-06-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/144087/kaz/22.06.2020
  rus: https://zan.gov.kz/client/#!/doc/144087/rus/22.06.2020
