act_code: '10396'
requisite: Решение акима Атырауской области от 22 августа 2001 года № 278. Зарегистрировано Управлением юстиции Атырауской области от 10 ноября 2001 года № 619
title:
  rus: Об открытии осенне-зимней охоты на водоплавающую дичь и пушных зверей в Атырауской области в 2001 году
  kaz: 2001 жылы Атырау облысында суда жүзетін жабайы құстар және аңдарды аулаудың күзгі-қысқы маусымын ашу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2001-08-21
approved_by:
- '156000000003'
version_date:
  kaz: 2001-08-21
  rus: 2001-08-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/10396/kaz/21.08.2001
  rus: https://zan.gov.kz/client/#!/doc/10396/rus/21.08.2001
