act_code: '9237'
requisite: Решение акима Атырауской области от 28 марта 2001 года № 118. Зарегистрировано Управлением юстиции Атырауской области 10 мая 2001 года № 454
title:
  rus: О предоставлении права на промысловый лов рыбы и закреплении рыбохозяйственных водоемов (участков)
  kaz: Балық аулау кәсіпшілігі құқығын және балық шаруашылығы су айдындарын (телімдерін) бекітіп беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2001-03-27
approved_by:
- '156000000003'
version_date:
  kaz: 2001-03-27
  rus: 2001-03-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/9237/kaz/27.03.2001
  rus: https://zan.gov.kz/client/#!/doc/9237/rus/27.03.2001
