act_code: '90983'
requisite: Решение акима Сарайчиковского сельского округа Махамбетского района Атырауской области от 15 июня 2015 года № 16
title:
  rus: О   признании   утратившим силу решение акима сельского округа от  20 апреля 2015 года №10
  kaz: Ауылдық  округ  әкімінің 2015  жылғы 20 сәуірдегі № 10 шешімінің  күші жойылды  деп  тану  туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-06-15
approved_by:
- '156004008001'
version_date:
  kaz: 2015-06-15
  rus: 2015-06-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/90983/kaz/15.06.2015
  rus: https://zan.gov.kz/client/#!/doc/90983/rus/15.06.2015
