act_code: '155341'
requisite: Решение акима Зинеденского сельского округа Исатайского района Атырауской области от 27 апреля 2021 года № 5. Зарегистрировано Департаментом юстиции Атырауской области 28 апреля 2021 года № 4943. Утратило силу решением акима Зинеденского сельского округа Исатайского района Атырауской области от 15 июля 2021 года № 14 (вводится в действие со дня его первого официального опубликования)
title:
  rus: Об установлении ограничительных мероприятий
  kaz: Шектеу іс-шараларын белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-04-27
approved_by:
- '156005004002'
version_date:
  kaz: 2021-04-27
  rus: 2021-04-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/155341/kaz/27.04.2021
  rus: https://zan.gov.kz/client/#!/doc/155341/rus/27.04.2021
