act_code: '48361'
requisite: Атырау облысы Құрманғазы ауданы Шортанбай селолық округі әкімінің 2009 жылғы 16 қазандағы № 4 шешімі. Атырау облысы Әділет департаменті Құрманғазы ауданының Әділет басқармасында 2009 жылғы 29 қазанда № 4-8-161 болып тіркелді. Күші жойылды - Атырау облысы Құрманғазы ауданы Шортанбай селолық округі әкімінің 2010 жылғы 22 қазандағы № 77 шешімімен
title:
  rus: Шортанбай селолық округіне қарасты Жасталап ауылына көше атауларын беру туралы
  kaz: Шортанбай селолық округіне қарасты Жасталап ауылына көше атауларын беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-10-16
approved_by:
- '156003016002'
version_date:
  kaz: 2009-10-16
source:
  kaz: https://zan.gov.kz/client/#!/doc/48361/kaz/16.10.2009
