act_code: '15120'
requisite: Екінші сайланған Атырау облыстық мәслихаты ХХІ сессиясының 2003 жылғы 15 қаңтардағы № 275-ІІ шешiмi. Атырау облысының Әділет басқармасында 2003 жылғы 20 қаңтарда № 1285 тіркелді. Күші жойылды - Атырау облыстық мәслихатының 2005 жылғы 11 ақпандағы № 189 шешімімен
title:
  rus: Облыстық мәслихаттың ХХI сессиясының 2002 жылғы 6 желтоқсандағы № 258-II шешiмiне өзгерiстер мен толықтырулар енгiзу туралы
  kaz: Облыстық мәслихаттың ХХI сессиясының 2002 жылғы 6 желтоқсандағы № 258-II шешiмiне өзгерiстер мен толықтырулар енгiзу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2003-01-15
approved_by:
- '156000000002'
version_date:
  kaz: 2003-01-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/15120/kaz/15.01.2003
