act_code: '144273'
requisite: Решение акима Елтайского сельского округа Индерского района Атырауской области от 25 июня 2020 года № 42. Зарегистрировано Департаментом юстиции Атырауской области 29 июня 2020 года № 4680
title:
  rus: Об утрате силы решения акима Елтайского сельского округа от 20 марта 2020 года № 23 «Об установлении ограничительных мероприятий»
  kaz: Елтай ауылдық округі әкімінің 2020 жылғы 20 наурыздағы № 23 «Шектеу іс-шараларын белгілеу туралы» шешімінің күшін жою туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-06-25
approved_by:
- '156008001002'
version_date:
  kaz: 2020-06-25
  rus: 2020-06-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/144273/kaz/25.06.2020
  rus: https://zan.gov.kz/client/#!/doc/144273/rus/25.06.2020
