act_code: '553'
requisite: Решение XIX сессии Атырауского областного маслихата I созыва от 27 декабря 1997 года № 217-I. Зарегистрировано Департаментом юстиции Атырауской области 9 марта 1998 года № 3
title:
  rus: О состоянии и перспективах развития социальной сферы области в свете Послания Президента страны народу Казахстана
  kaz: Облыс әлеуметтік саласының жағдайы және оның ел Президентінің Қазақстан халқына Жолдауына сәйкес дамуының болашағы туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 1997-12-27
approved_by:
- '156000000002'
version_date:
  kaz: 1997-12-27
  rus: 1997-12-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/553/kaz/27.12.1997
  rus: https://zan.gov.kz/client/#!/doc/553/rus/27.12.1997
