act_code: '50062'
requisite: Атырау облысы Құрманғазы аудандық мәслихатының 2009 жылғы 23 желтоқсандағы № 229-XXV шешімі. Атырау облысы Әділет департаменті Құрманғазы ауданының Әділет басқармасында 2010 жылғы 18 қаңтарда № 4-8-177 тіркелді. Күші жойылды - Құрманғазы аудандық мәслихатының 2013 жылғы 14 наурыздағы № 147-V шешімімен
title:
  rus: Ауданның 2010-2012 жылдарға арналған бюджеті туралы
  kaz: Ауданның 2010-2012 жылдарға арналған бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-12-23
approved_by:
- '156003000002'
version_date:
  kaz: 2010-02-10
source:
  kaz: https://zan.gov.kz/client/#!/doc/50062/kaz/10.02.2010
caused_by:
  code: '51180'
  requisite: Атырау облысы Құрманғазы аудандық мәслихатының 2010 жылғы 10 ақпандағы № 246-XXVII шешімі. Атырау облысы Әділет департаменті Құрманғазы ауданының Әділет басқармасында 2010 жылғы 15 наурызда № 4-8-184 тіркелді. Күші жойылды - Құрманғазы аудандық мәслихатының 2013 жылғы 14 наурыздағы № 147-V шешімімен
  title:
    rus: Аудандық мәслихаттың 2009 жылғы 23 желтоқсандағы № 229-XXV "Ауданның  2010-2012 жылдарға арналған бюджеті туралы" шешіміне өзгерістер мен толықтырулар енгізу туралы
    kaz: Аудандық мәслихаттың 2009 жылғы 23 желтоқсандағы № 229-XXV "Ауданның  2010-2012 жылдарға арналған бюджеті туралы" шешіміне өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/51180/rus
