act_code: '50062'
requisite: Атырау облысы Құрманғазы аудандық мәслихатының 2009 жылғы 23 желтоқсандағы № 229-XXV шешімі. Атырау облысы Әділет департаменті Құрманғазы ауданының Әділет басқармасында 2010 жылғы 18 қаңтарда № 4-8-177 тіркелді. Күші жойылды - Құрманғазы аудандық мәслихатының 2013 жылғы 14 наурыздағы № 147-V шешімімен
title:
  rus: Ауданның 2010-2012 жылдарға арналған бюджеті туралы
  kaz: Ауданның 2010-2012 жылдарға арналған бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-12-23
approved_by:
- '156003000002'
version_date:
  kaz: 2010-07-16
source:
  kaz: https://zan.gov.kz/client/#!/doc/50062/kaz/16.07.2010
caused_by:
  code: '54154'
  requisite: Атырау облысы Құрманғазы аудандық мәслихатының 2010 жылғы 16 шілдедегі № 300-XXX шешімі. Атырау облысы Әділет департаменті Құрманғазы ауданының Әділет басқармасында 2010 жылғы 24 тамызда № 4-8-190 тіркелді. Күші жойылды - Құрманғазы аудандық мәслихатының 2013 жылғы 14 наурыздағы № 147-V шешімімен
  title:
    rus: Аудандық мәслихаттың 2009 жылғы 23 желтоқсандағы № 229-ХХV "Ауданның 2010-2012 жылдарға арналған бюджет туралы" шешіміне өзгерістер енгізу туралы
    kaz: Аудандық мәслихаттың 2009 жылғы 23 желтоқсандағы № 229-ХХV "Ауданның 2010-2012 жылдарға арналған бюджет туралы" шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/54154/rus
