act_code: '154882'
requisite: Решение Атырауского областного маслихата от 9 апреля 2021 года № 40-VІI. Зарегистрировано Департаментом юстиции Атырауской области 19 апреля 2021 года № 4932
title:
  rus: Об утверждении перечня социально значимых железнодорожных пассажирских межрайонных (междугородных внутриобластных) сообщений по Атырауской области
  kaz: Атырау облысының әлеуметтік мәні бар ауданаралық (облысішілік қалааралық) теміржол жолаушылар қатынасының тізбесін бекіту туралы
form: РЕШ
type_codes:
- ПРЧ
- РЕШ
approved_on: 2021-04-09
approved_by:
- '156000000002'
version_date:
  kaz: 2021-04-09
  rus: 2021-04-09
source:
  kaz: https://zan.gov.kz/client/#!/doc/154882/kaz/09.04.2021
  rus: https://zan.gov.kz/client/#!/doc/154882/rus/09.04.2021
