act_code: '69952'
requisite: Решение Махамбетского районного маслихата Атырауской области от 25 декабря 2012 года № 56. Зарегистрировано Департаментом юстиции Атырауской области 14 января 2013 года № 2673. Утратило силу-решением Махамбетского районного маслихата Атырауской области от 17 января 2014 года № 162
title:
  rus: О районном бюджете на 2013-2015 годы
  kaz: 2013 - 2015 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2012-12-25
approved_by:
- '156004000002'
version_date:
  kaz: 2013-12-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/69952/kaz/12.12.2013
caused_by:
  code: '75968'
  requisite: Решение Махамбетского районного маслихата Атырауской области от 12 декабря 2013 года № 139. Зарегистрировано Департаментом юстиции Атырауской области 13 декабря 2013 года № 2816. Утратило силу - решением Махамбетского районного маслихата Атырауской области от 17 января 2014 года № 162
  title:
    rus: О внесении изменений в решение Махамбетского районного маслихата от 25 декабря 2012 года № 56 "О районном бюджете на 2013-2015 годы"
    kaz: Махамбет аудандық мәслихатының 2012 жылғы 25 желтоқсандағы № 56 "2013-2015 жылдарға арналған аудандық бюджет туралы" шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/75968/rus
