act_code: '85669'
requisite: Решение Макатского районного маслихата Атырауской области от 24 декабря 2014 года № 273-V. Зарегистрировано Департаментом юстиции Атырауской области 08 января 2015 года № 3074. Утратило силу решением Макатского районного маслихата Атырауской области от 13 июля 2016 года № 41-VI
title:
  rus: Об утверждении Положения государственного учреждения «Аппарат Макатского районного маслихата»
  kaz: «Мақат аудандық мәслихат аппараты» мемлекеттік мекемесінің Ережесін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2014-12-24
approved_by:
- '156006000002'
version_date:
  kaz: 2014-12-24
  rus: 2014-12-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/85669/kaz/24.12.2014
  rus: https://zan.gov.kz/client/#!/doc/85669/rus/24.12.2014
