act_code: '139732'
requisite: Решение Жылыойского районного маслихата Атырауской области от 7 февраля 2020 года № 43-1. Зарегистрировано Департаментом юстиции Атырауской области 21 февраля 2020 года № 4596. Утратило силу решением Жылыойского районного маслихата Атырауской области от 18 сентября 2023 года № 6-11 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении регламентов собраний местного сообщества Майкумгенского и Аккиизтогайского сельских округов Жылыойского района
  kaz: Жылыой ауданының Майкөмген және Ақкиізтоғай ауылдық округтерінің жергілікті қоғамдастық жиналыстарының регламенттерін бекіту туралы
form: РЕШ
type_codes:
- РЕГЛ
- РЕШ
approved_on: 2020-02-07
approved_by:
- '156009000002'
version_date:
  kaz: 2021-10-28
  rus: 2021-10-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/139732/kaz/28.10.2021
  rus: https://zan.gov.kz/client/#!/doc/139732/rus/28.10.2021
caused_by:
  code: '160071'
  requisite: Решение Жылыойского районного маслихата Атырауской области от 28 октября 2021 года № 11-2. Утратило силу решением Жылыойского районного маслихата Атырауской области от 18 сентября 2023 года № 6-11 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
  title:
    rus: О внесении изменений в решение Жылыойского районного маслихата «Об утверждении регламентов собраний местного сообщества Майкумгенского и Аккиизтогайского сельских округов Жылыойского района» от 7 февраля 2020 года № 43-1
    kaz: «Жылыой ауданының Майкөмген және Ақкиізтоғай ауылдық округтерінің жергілікті қоғамдастық жиналыстарының регламенттерін бекіту туралы» Жылыой аудандық мәслихатының 2020 жылғы 7 ақпандағы № 43-1 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/160071/rus
