act_code: '42723'
requisite: Атырау облысы Исатай ауданы Қамысқала селолық округі әкімінің 2008 жылғы 20 қарашадағы № 84 шешімі. Атырау облысының Әділет департаменті Исатай ауданының Әділет басқармасында 2008 жылғы 10 желтоқсанда № 4-4-115 тіркелді. Күші жойылды - Атырау облысы Исатай ауданы Қамысқала селолық округі әкімінің 2010 жылғы 27 қазандағы № 31 шешімімен
title:
  rus: Х.Ерғалиев ауылының Жаңақұрылыс көшесіне еңбек ардагері Жұмағали Айтбаевтың есімін беру туралы
  kaz: Х.Ерғалиев ауылының Жаңақұрылыс көшесіне еңбек ардагері Жұмағали Айтбаевтың есімін беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-11-20
approved_by:
- '156005006002'
version_date:
  kaz: 2008-11-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/42723/kaz/20.11.2008
