act_code: '128526'
requisite: Решение Атырауского городского маслихата Атырауской области от 20 декабря 2018 года № 297. Зарегистрировано Департаментом юстиции Атырауской области 10 января 2019 года № 4324
title:
  rus: О бюджете города на 2019-2021 годы
  kaz: 2019-2021 жылдарға арналған қала бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-12-20
approved_by:
- '156002000002'
version_date:
  kaz: 2019-09-27
  rus: 2019-09-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/128526/kaz/27.09.2019
  rus: https://zan.gov.kz/client/#!/doc/128526/rus/27.09.2019
caused_by:
  code: '135391'
  requisite: Решение Атырауского городского маслихата Атырауской области от 27 сентября 2019 года № 419. Зарегистрировано Департаментом юстиции Атырауской области 11 октября 2019 года № 4502
  title:
    rus: О внесении изменений и дополнений в решение Атырауского городского Маслихата от 20 декабря 2018 года № 297 «О бюджете города на 2019-2021 годы»
    kaz: Атырау қалалық Мәслихатының 2018 жылғы 20 желтоқсандағы № 297 «2019-2021 жылдарға арналған қала бюджеті туралы» шешіміне өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/135391/rus
