act_code: '33516'
requisite: Атырау облысы Исатай ауданы мәслихатының 2007 жылғы 16 сәуірдегі № 249-ІІІ шешімі. Атырау облысының Әділет департаментінде 2007 жылғы 25 мамырда № 4-4-69 болып тіркелді
title:
  rus: Аз қамтылған отбасыларына (азаматтарға) тұрғын үйді (жеке тұрғын үй ұстағаннан басқа) коммуналдық қызметтерді пайдалану төлемдерін өтеуге тұрғын үй көмегін көрсету тәртібі туралы
  kaz: Аз қамтылған отбасыларына (азаматтарға) тұрғын үйді (жеке тұрғын үй ұстағаннан басқа) коммуналдық қызметтерді пайдалану төлемдерін өтеуге тұрғын үй көмегін көрсету тәртібі туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2007-04-16
approved_by:
- '156005000002'
version_date:
  kaz: 2007-04-16
source:
  kaz: https://zan.gov.kz/client/#!/doc/33516/kaz/16.04.2007
