act_code: '140623'
requisite: Решение Индерского районного маслихата Атырауской области от 12 марта 2020 года № 361-VI. Зарегистрировано Департаментом юстиции Атырауской области 27 марта 2020 года № 4616. Утратило силу решением Индерского районного маслихата Атырауской области от 30 ноября 2023 года № 51-VІII (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении регламента собрания местного сообщества Боденевского сельского округа
  kaz: Бөдене ауылдық округінің жергілікті қоғамдастық жиналысының регламентін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-03-12
approved_by:
- '156008000002'
version_date:
  kaz: 2020-03-12
  rus: 2020-03-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/140623/kaz/12.03.2020
  rus: https://zan.gov.kz/client/#!/doc/140623/rus/12.03.2020
