act_code: '108710'
requisite: Решение Исатайского сельского округа Исатайского района Атырауской области от 20 декабря 2016 года № 33. Зарегистрировано Департаментом юстиции Атырауской области 28 декабря 2016 года № 3733
title:
  rus: О переименовании улиц
  kaz: Көшелерге қайта атау беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2016-12-20
approved_by:
- '156005005001'
version_date:
  kaz: 2016-12-20
  rus: 2016-12-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/108710/kaz/20.12.2016
  rus: https://zan.gov.kz/client/#!/doc/108710/rus/20.12.2016
