act_code: '77912'
requisite: Решение Атырауского областного маслихата Атырауской области от 30 января 2014 года № 212-V. Зарегистрировано Департаментом юстиции Атырауской области 3 марта 2014 года № 2870
title:
  rus: Об утверждении Положения о награждении Почетной грамотой Атырауской области  (города, района)
  kaz: Атырау облысының (қаланың, ауданның) Құрмет грамотасымен наградтау туралы Ережені бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2014-01-30
approved_by:
- '156000000002'
version_date:
  kaz: 2023-05-24
  rus: 2023-05-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/77912/kaz/24.05.2023
  rus: https://zan.gov.kz/client/#!/doc/77912/rus/24.05.2023
caused_by:
  code: '182348'
  requisite: Решение Атырауского областного маслихата от 24 мая 2023 года № 25-VIII. Зарегистрировано в Департаменте юстиции Атырауской области 31 мая 2023 года № 5031-06
  title:
    rus: О внесении изменений и дополнения в решение Атырауского областного маслихата от 30 января 2014 года № 212-V «Об утверждении Положения о награждении Почетной грамотой Атырауской области (города, района)»
    kaz: Атырау облыстық мәслихатының 2014 жылғы 30 қаңтардағы № 212-V «Атырау облысының (қаланың, ауданның) Құрмет грамотасымен наградтау туралы Ережені бекіту туралы» шешіміне өзгерістер мен толықтыру енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/182348/rus
