act_code: '24322'
requisite: Решение Атырауского областного маслихата 27 апреля 2005 года № 209-III. Зарегистрировано Департаментом юстиции Атырауской области 31 мая 2005 года № 2426
title:
  rus: О региональной программе развития образования в Атыраускоцй области на 2005-2007 годы
  kaz: Атырау облысында білім беруді дамытудың 2005-2007 жылдарға арналған өңірлік бағдарламасы туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2005-04-27
approved_by:
- '156000000002'
version_date:
  kaz: 2005-04-27
  rus: 2005-04-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/24322/kaz/27.04.2005
  rus: https://zan.gov.kz/client/#!/doc/24322/rus/27.04.2005
