act_code: '10711'
requisite: Решение акима Атырауской области от 19 ноября 2001 года № 335. Зарегистрирован Управлением юстиции Атырауской области 20 декабря 2001 года за № 692
title:
  rus: О мерах по локализации эпидемической вспышки в Макатском районе
  kaz: «Мақат ауданы бойынша эпидемиялық тұтынуға шара қолдану туралы»
form: РЕШ
type_codes:
- РЕШ
approved_on: 2001-11-19
approved_by:
- '156000000003'
version_date:
  kaz: 2001-11-19
  rus: 2001-11-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/10711/kaz/19.11.2001
  rus: https://zan.gov.kz/client/#!/doc/10711/rus/19.11.2001
