act_code: '133546'
requisite: Решение акима Уильского сельского округа Кызылкогинского района Атырауской области от 18 июля 2019 года № 22. Зарегистрировано Департаментом юстиции Атырауской области 22 июля 2019 года № 4466
title:
  rus: Об утрате силы решения акима Уильского сельского округа от 9 июля 2018 года № 23 «Об установлении ограничительных мероприятий»
  kaz: Ойыл ауылдық округі әкімінің 2018 жылғы 9 шілдедегі № 23 «Шектеу іс-шараларын белгілеу туралы» шешімінің күшін жою туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-07-18
approved_by:
- '156007004002'
version_date:
  kaz: 2019-07-18
  rus: 2019-07-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/133546/kaz/18.07.2019
  rus: https://zan.gov.kz/client/#!/doc/133546/rus/18.07.2019
