act_code: '48360'
requisite: Атырау облысы Құрманғазы ауданы Теңіз селолық округі әкімінің 2009 жылғы 19 қазандағы № 7 шешімі. Атырау облысы Әділет департаменті Құрманғазы ауданының Әділет басқармасында 2009 жылғы 28 қазанда № 4-8-160 болып тіркелді. Күші жойылды - Атырау облысы Құрманғазы ауданы Теңіз селолық округі әкімінің 2010 жылғы 22 қазандағы № 77 шешімімен
title:
  rus: Теңіз селолық округіне қарасты шағын елді мекендердегі атауы жоқ көшелерге атау беру туралы
  kaz: Теңіз селолық округіне қарасты шағын елді мекендердегі атауы жоқ көшелерге атау беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-10-19
approved_by:
- '156003010002'
version_date:
  kaz: 2009-10-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/48360/kaz/19.10.2009
