act_code: '50231'
requisite: Атырау облысы Исатай аудандық мәслихатының 2009 жылғы 23 желтоқсандағы № 154-IV шешімі. Исатай аудандық Әділет басқармасында 2010 жылғы 22 қаңтарда № 4-4-152 тіркелді. Күші жойылды - Исатай аудандық мәслихатының 2011 жылғы 25 қаңтардағы № 247-IV шешімімен
title:
  rus: Қызметі дүркін-дүркін сипаттағы кәсіпкерлік қызметке бір жолғы талон құнын 2010 жылға белгілеу туралы
  kaz: Қызметі дүркін-дүркін сипаттағы кәсіпкерлік қызметке бір жолғы талон құнын 2010 жылға белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-12-23
approved_by:
- '156005000002'
version_date:
  kaz: 2009-12-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/50231/kaz/23.12.2009
