act_code: '31705'
requisite: Атырау облысы Махамбет аудандық мәслихатының 2006 жылғы 7 желтоқсандағы № 313 шешімі. Атырау облысы Махамбет аудандық Әділет басқармасында 2006 жылғы 22 желтоқсанда № 4-3-52 болып тіркелді
title:
  rus: Аудандық әкімдіктің 2006 жылғы 30 қарашадағы № 370 «2007 жылға салық ставкалары мен төлемақы мөлшерін белгілеу туралы» қаулысын бекіту туралы
  kaz: Аудандық әкімдіктің 2006 жылғы 30 қарашадағы № 370 «2007 жылға салық ставкалары мен төлемақы мөлшерін белгілеу туралы» қаулысын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2006-12-07
approved_by:
- '156004000002'
version_date:
  kaz: 2006-12-07
source:
  kaz: https://zan.gov.kz/client/#!/doc/31705/kaz/07.12.2006
