act_code: '164047'
requisite: Решение Атырауского городского маслихата Атырауской области от 27 декабря 2021 года № 130
title:
  rus: О бюджете сельских округов относящихся к городу Атырау на 2022-2024 годы
  kaz: 2022-2024 жылдарға арналған Атырау қаласына қарасты ауылдық округтер бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-12-27
approved_by:
- '156002000002'
version_date:
  kaz: 2022-10-28
  rus: 2022-10-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/164047/kaz/28.10.2022
  rus: https://zan.gov.kz/client/#!/doc/164047/rus/28.10.2022
caused_by:
  code: '173597'
  requisite: Решение Атырауского городского маслихата Атырауской области от 28 октября 2022 года № 198
  title:
    rus: О внесении изменений в решение Маслихата города Атырау от 27 декабря 2021 года № 130 «О бюджете сельских округов относящихся к городу Атырау на 2022-2024 годы»
    kaz: Атырау қаласы мәслихатының 2021 жылғы 27 желтоқсандағы № 130 «2022-2024 жылдарға арналған Атырау қаласына қарасты ауылдық округтер бюджеті туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/173597/rus
