act_code: '128525'
requisite: Решение Атырауского городского маслихата Атырауской области от 25 декабря 2018 года № 302. Зарегистрировано Департаментом юстиции Атырауской области 11 января 2019 года № 4326
title:
  rus: О бюджете сельских округов относящихся к городу Атырау на 2019-2021 годы
  kaz: 2019-2021 жылдарға арналған Атырау қаласына қарасты ауылдық округтер бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-12-25
approved_by:
- '156002000002'
version_date:
  kaz: 2019-03-29
  rus: 2019-03-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/128525/kaz/29.03.2019
  rus: https://zan.gov.kz/client/#!/doc/128525/rus/29.03.2019
caused_by:
  code: '130364'
  requisite: Решение Атырауского городского маслихата Атырауской области от 29 марта 2019 года № 349. Зарегистрировано Департаментом юстиции Атырауской области 4 апреля 2019 года № 4372
  title:
    rus: О внесении изменений в решение Маслихата города Атырау от 25 декабря 2018 года № 302 "О бюджете сельских округов относящихся к городу Атырау на 2019-2021 годы"
    kaz: Атырау қаласы Мәслихатының 2018 жылғы 25 желтоқсандағы № 302 "2019-2021 жылдарға арналған Атырау қаласына қарасты ауылдық округтер бюджеті туралы" шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/130364/rus
