act_code: '146711'
requisite: Решение акима сельского округа Орлы Курмангазинского района Атырауской области от 18 сентября 2020 года № 49. Зарегистрировано Департаментом юстиции Атырауской области 25 сентября 2020 года № 4734
title:
  rus: О признании утратившим силу решения акима сельского округа Орлы от 3 июня 2020 года № 27 «Об установлении ограничительных мероприятий»
  kaz: Орлы ауылдық округі әкімінің 2020 жылғы 3 маусымдағы № 27 «Шектеу іс-шараларын белгілеу туралы» шешімінің күшін жою туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-09-18
approved_by:
- '156003006002'
version_date:
  kaz: 2020-09-18
  rus: 2020-09-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/146711/kaz/18.09.2020
  rus: https://zan.gov.kz/client/#!/doc/146711/rus/18.09.2020
