act_code: '162949'
requisite: Решение Индерского районного маслихата Атырауской области от 30 декабря 2021 года № 80-VII
title:
  rus: О бюджетах сельских округов и поселка Индербор Индерского района на 2022-2024 годы
  kaz: 2022-2024 жылдарға арналған Индер ауданының ауылдық округтерінің және Индербор кентінің бюджеттері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-12-30
approved_by:
- '156008000002'
version_date:
  kaz: 2022-04-13
  rus: 2022-04-13
source:
  kaz: https://zan.gov.kz/client/#!/doc/162949/kaz/13.04.2022
  rus: https://zan.gov.kz/client/#!/doc/162949/rus/13.04.2022
caused_by:
  code: '166842'
  requisite: Решение Индерского районного маслихата Атырауской области от 13 апреля 2022 года № 108-VII
  title:
    rus: О внесении изменений в решение районного маслихата от 30 декабря 2021 года № 80-VІІ «О бюджетах сельских округов и поселка Индербор Индерского района на 2022-2024 годы»
    kaz: Аудандық мәслихаттың 2021 жылғы 30 желтоқсандағы № 80-VІІ «2022-2024 жылдарға арналған Индер ауданының ауылдық округтерінің және Индербор кентінің бюджеттері туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/166842/rus
