act_code: '23731'
requisite: Решение акима Атырауской области от 16 марта 2005 года № 10. Зарегистрировано Департаментом юстиции Атырауской области от 29 марта 2005 года № 2399
title:
  rus: Об организации отдыха, оздоровления, занятости детей и подростков в летний период 2005 года
  kaz: 2005 жылдың жазғы кезеңінде балалар мен жасөспірімдердің депалысын, сауықтыруды және жұмыспен қамтуды ұйымдастыру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2005-03-16
approved_by:
- '156000000003'
version_date:
  kaz: 2005-03-16
  rus: 2005-03-16
source:
  kaz: https://zan.gov.kz/client/#!/doc/23731/kaz/16.03.2005
  rus: https://zan.gov.kz/client/#!/doc/23731/rus/16.03.2005
