act_code: '176913'
requisite: Решение акима Сарайчиковского сельского округа Махамбетского района Атырауской области от 28 декабря 2022 года № 85. Зарегистрировано в Министерстве юстиции Республики Казахстан 5 января 2023 года № 31585
title:
  rus: О присвоении наименований улицам
  kaz: Көшелерге атау беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-12-28
approved_by:
- '156004008002'
version_date:
  kaz: 2022-12-28
  rus: 2022-12-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/176913/kaz/28.12.2022
  rus: https://zan.gov.kz/client/#!/doc/176913/rus/28.12.2022
