act_code: '108945'
requisite: Решение Исатайского районного маслихата Атырауской области от 14 декабря 2016 года № 62-VI. Зарегистрировано Департаментом юстиции Атырауской области 5 января 2017 года № 3749. Утратило силу решением Исатайского районного маслихата Атырауской области от 20 марта 2018 года № 147-VI
title:
  rus: О районном бюджете на 2017-2019 годы
  kaz: 2017 –  2019  жылдарға арналған  аудандық  бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2016-12-14
approved_by:
- '156005000002'
version_date:
  kaz: 2017-03-24
  rus: 2017-03-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/108945/kaz/24.03.2017
  rus: https://zan.gov.kz/client/#!/doc/108945/rus/24.03.2017
caused_by:
  code: '111514'
  requisite: Решение Исатайского районного маслихата Атырауской области от 24 марта 2017 года № 79-VI. Зарегистрировано Департаментом юстиции Атырауской области 14 апреля 2017 года № 3823. Утратило силу решением Исатайского районного маслихата Атырауской области от 20 марта 2018 года № 147-VI
  title:
    rus: О внесений изменений и дополнений в решение Исатайского районного маслихата от 14 декабря 2016 года № 62-VI «О районном бюджете на 2017-2019 годы»
    kaz: Исатай  аудандық мәслихатының 2016 жылғы 14 желтоқсандағы № 62-VI «2017–2019 жылдарға арналған аудандық бюджет туралы» шешіміне өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/111514/rus
