act_code: '41254'
requisite: Атырау облысы Индер ауданы Жарсуат ауылдық округ әкімінің 2008 жылғы 21 шілдедегі № 29 шешімі. Атырау облысының Әділет департаменті Индер ауданының Әділет басқармасында 2008 жылғы 25 тамызда № 4-6-71 тіркелді. Күші жойылды - Атырау облысы Индер ауданы Жарсуат ауылдық округ әкімінің 2010 жылғы 27 қазандағы № 15 шешімімен
title:
  rus: Жаңадан салынып жатырған екі көшеге ат беру туралы
  kaz: Жаңадан салынып жатырған екі көшеге ат беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-07-21
approved_by:
- '156008003002'
version_date:
  kaz: 2008-07-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/41254/kaz/21.07.2008
