act_code: '37799'
requisite: Атырау облысы Құрманғазы аудандық мәслихатының 2007 жылғы 21 желтоқсандағы № 41-III шешімі. Атырау облысының Құрманғазы аудандық Әділет басқармасында 2007 жылғы 17 қаңтарда № 4-8-118 болып тіркелді
title:
  rus: 2008 жылға жеке кәсіпкер, занды тұлға, оның бөлімдері,құрылымдары және басқа да жекеленген структуралық бөлімшелер ойын бизнесі саласында көрсеткен қызметіне тіркелген жиынтық салық ставкаларының мөлшері туралы
  kaz: 2008 жылға жеке кәсіпкер, занды тұлға, оның бөлімдері,құрылымдары және басқа да жекеленген структуралық бөлімшелер ойын бизнесі саласында көрсеткен қызметіне тіркелген жиынтық салық ставкаларының мөлшері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2007-12-21
approved_by:
- '156003000002'
version_date:
  kaz: 2007-12-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/37799/kaz/21.12.2007
