act_code: '56870'
requisite: Решение Кызылкогинского районного маслихата Атырауского области от 14 декабря 2010 года № XXIV-4. Зарегистрировано Департаментом юстиции Атырауской области 17 января 2011 года № 4-5-140. Утратило силу - решением Кызылкогинского районного маслихата от 19 апреля 2013 года № ХІІІ-4
title:
  rus: О районном бюджете на 2011-2013 годы
  kaz: 2011-2013 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-12-14
approved_by:
- '156007000002'
version_date:
  kaz: 2011-08-12
  rus: 2011-08-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/56870/kaz/12.08.2011
  rus: https://zan.gov.kz/client/#!/doc/56870/rus/12.08.2011
caused_by:
  code: '60410'
  requisite: Решение Кызылкогинского районного маслихата Атырауской области № XXХ-I от 12 августа 2011 года. Зарегистрировано Департаментом юстиции Атырауской области 12 сентября 2011 года № 4-5-151. Утратило силу - решением Кызылкогинского районного маслихата от 19 апреля 2013 года № ХІІІ-4
  title:
    rus: О внесении изменений и дополнения в решение ХХІV сессии Кызылкогинского районного маслихата от 14 декабря 2010 года № ХХIV-4 "О районном бюджете на 2011-2013 годы"
    kaz: Қызылқоға аудандық мәслихаттың ХХІV сессиясының 2010 жылғы 14 желтоқсандағы № ХХІV-4 "2011-2013 жылдарға арналған аудандық бюджет туралы" шешіміне өзгерістер мен толықтыру енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/60410/rus
