act_code: '56870'
requisite: Решение Кызылкогинского районного маслихата Атырауского области от 14 декабря 2010 года № XXIV-4. Зарегистрировано Департаментом юстиции Атырауской области 17 января 2011 года № 4-5-140. Утратило силу - решением Кызылкогинского районного маслихата от 19 апреля 2013 года № ХІІІ-4
title:
  rus: О районном бюджете на 2011-2013 годы
  kaz: 2011-2013 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-12-14
approved_by:
- '156007000002'
version_date:
  kaz: 2010-12-14
  rus: 2010-12-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/56870/kaz/14.12.2010
  rus: https://zan.gov.kz/client/#!/doc/56870/rus/14.12.2010
