act_code: '169985'
requisite: Решение акима Кызылкогинского района Атырауской области от 19 июля 2022 года № 26. Зарегистрировано в Министерстве юстиции Республики Казахстан 21 июля 2022 года № 28862. Утратило силу решением акима Кызылкогинского района Атырауской области от 23 января 2025 года № 3 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об объявлении чрезвычайной ситуации природного характера местного масштаба на территории Кызылкогинского района
  kaz: Қызылқоға ауданы аумағында жергілікті ауқымдағы табиғи сипаттағы төтенше жағдайды жариялау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-07-19
approved_by:
- '156007000003'
version_date:
  kaz: 2022-07-19
  rus: 2022-07-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/169985/kaz/19.07.2022
  rus: https://zan.gov.kz/client/#!/doc/169985/rus/19.07.2022
