act_code: '193792'
requisite: Решение Исатайского районного маслихата Атырауской области от 27 февраля 2024 года № 74-VIII. Зарегистрировано в Департаменте юстиции Атырауской области 28 февраля 2024 года № 5140-06. Утратило силу решением Исатайского районного маслихата Атырауской области от 12 мая 2026 года № 236-VIII (вводится в действие с 01.01.2026)
title:
  rus: О понижении размера ставки при применении специального налогового режима розничного налога по Исатайскому району
  kaz: Исатай ауданы бойынша бөлшек салықтың арнаулы салық режимін қолдану кезінде мөлшерлемесінің мөлшерін төмендету туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-02-27
approved_by:
- '156005000002'
version_date:
  kaz: 2024-02-27
  rus: 2024-02-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/193792/kaz/27.02.2024
  rus: https://zan.gov.kz/client/#!/doc/193792/rus/27.02.2024
