act_code: '12799'
requisite: Атырау облыстық мәслихаты XVII сессиясының Екiншi сайланған 2002 жылғы 19 сәуірдегі № 200-ІІ шешімі. Атырау облысының Әділет басқармасында 2002 жылғы 24 мамырда № 973 болып тіркелді
title:
  rus: Қазақстан Республикасы Үкіметінің 2001 жылғы 8 желтоқсандағы № 1599 "Құрамында сынап бар аспаптар мен бұйымдарды кәдеге жаратудың 2002-2003 жылдарға арналған бағдарламасын бекіту туралы" қаулысын орындау туралы
  kaz: Қазақстан Республикасы Үкіметінің 2001 жылғы 8 желтоқсандағы № 1599 "Құрамында сынап бар аспаптар мен бұйымдарды кәдеге жаратудың 2002-2003 жылдарға арналған бағдарламасын бекіту туралы" қаулысын орындау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2002-04-18
approved_by:
- '156000000002'
version_date:
  kaz: 2002-04-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/12799/kaz/18.04.2002
