act_code: '176293'
requisite: Решение Макатского районного маслихата Атырауской области от 15 декабря 2022 года № 159-VII
title:
  rus: О бюджетах поселков Макат, Доссор и сельского округа Байгетобе на 2023-2025 годы
  kaz: 2023-2025 жылдарға арналған Мақат, Доссор кенттерінің және Бәйгетөбе ауылдық округінің бюджеттері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-12-15
approved_by:
- '156006000002'
version_date:
  kaz: 2022-12-15
  rus: 2022-12-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/176293/kaz/15.12.2022
  rus: https://zan.gov.kz/client/#!/doc/176293/rus/15.12.2022
