act_code: '48647'
requisite: Атырау облысы Құрманғазы ауданы Сүйіндік селолық округі әкімінің 2009 жылғы 21 қазандағы № 13 шешімі. Атырау облысы Әділет департаменті Құрманғазы ауданының Әділет басқармасында 2009 жылғы 13 қарашада № 4-8-170 тіркелді. Күші жойылды - Атырау облысы Құрманғазы ауданы Сүйіндік селолық округі әкімінің 2010 жылғы 22 қазандағы № 77 шешімімен
title:
  rus: Сүйіндік селолық округіне қарасты Жалғызапан, Батырбек, Егінқұдық ауылдарындағы атауы жоқ көшелерге атау беру туралы
  kaz: Сүйіндік селолық округіне қарасты Жалғызапан, Батырбек, Егінқұдық ауылдарындағы атауы жоқ көшелерге атау беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-10-21
approved_by:
- '156003015001'
version_date:
  kaz: 2009-10-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/48647/kaz/21.10.2009
