act_code: '96412'
requisite: Решение Атырауского городского маслихата Атырауской области от 19 ноября 2015 года № 307. Зарегистрировано Департаментом юстиции Атырауской области 11 декабря 2015 года № 3390
title:
  rus: Об определении порядка и размера возмещения затрат на обучение на дому детей с ограниченными возможностями из числа детей с инвалидностью по индивидуальному учебному плану в городе Атырау
  kaz: Атырау қаласында мүгедектігі бар балалар қатарындағы кемтар балаларды жеке оқыту жоспары бойынша үйде оқытуға жұмсаған шығындарын өндіріп алу тәртібі мен мөлшерін айқындау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-11-19
approved_by:
- '156002000002'
version_date:
  kaz: 2015-11-19
  rus: 2015-11-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/96412/kaz/19.11.2015
  rus: https://zan.gov.kz/client/#!/doc/96412/rus/19.11.2015
