act_code: '20874'
requisite: Атырау облыстық мәслихатының 2004 жылғы 26 мамырдағы № 132-III шешiмi. Атырау облысының Әділет департаментінде 2004 жылғы 7 шілдеде № 2047 болып тіркелді. Күші жойылды - Атырау облыстық мәслихатының 2004 жылғы 6 қазандағы № 157-III шешімімен
title:
  rus: Атырау облысында тұрғын үй құрылысын дамытудың 2005-2007 жылдарға арналған өңірлік бағдарламасын бекіту туралы
  kaz: Атырау облысында тұрғын үй құрылысын дамытудың 2005-2007 жылдарға арналған өңірлік бағдарламасын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2004-05-25
approved_by:
- '156000000002'
version_date:
  rus: 2004-05-25
source:
  rus: https://zan.gov.kz/client/#!/doc/20874/rus/25.05.2004
