act_code: '37768'
requisite: Атырау облысы Мақат аудандық мәслихатының 2007 жылғы 21 желтоқсандағы № 27-IV шешімі. Атырау облысы Мақат аудандық Әділет басқармасында 2008 жылғы 15 қаңтарда № 4-7-75 болып тіркелді
title:
  rus: 2008 жылға арналған аудандық бюджет туралы
  kaz: 2008 жылға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2007-12-21
approved_by:
- '156006000002'
version_date:
  kaz: 2007-12-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/37768/kaz/21.12.2007
