act_code: '105592'
requisite: Решение акима поселка Индербор Атырауской области от 15 июля 2016 года № 79. Зарегистрировано Департаментом юстиции Атырауской области 1 августа 2016 года № 3576
title:
  rus: Об объявлении чрезвычайной ситуации природного характера местного масштаба
  kaz: Жергілікті ауқымдағы табиғи сипаттағы төтенше жағдайды жариялау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2016-07-15
approved_by:
- '156008007001'
version_date:
  kaz: 2016-07-15
  rus: 2016-07-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/105592/kaz/15.07.2016
  rus: https://zan.gov.kz/client/#!/doc/105592/rus/15.07.2016
