act_code: '194108'
requisite: Решение Курмангазинского районного маслихата Атырауской области от 5 марта 2024 года № 110-VIII. Зарегистрировано в Департаменте юстиции Атырауской области 11 марта 2024 года № 5149-06. Утратило силу решением Курмангазинского районного маслихата Атырауской области от 26 января 2026 года № 266-VIII (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: О понижении размера ставки при применении специального налогового режима розничного налога по Курмангазинскому району
  kaz: Құрманғазы ауданы бойынша бөлшек салықтық арнаулы салық режимін қолдану кезінде мөлшерлемесінің мөлшерін төмендету туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-03-05
approved_by:
- '156003000002'
version_date:
  kaz: 2024-03-05
  rus: 2024-03-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/194108/kaz/05.03.2024
  rus: https://zan.gov.kz/client/#!/doc/194108/rus/05.03.2024
