act_code: '121898'
requisite: Решение акима Кенузекского сельского округа города Атырау Атырауской области от 21 мая 2018 года № 73. Зарегистрировано Департаментом юстиции Атырауской области 23 мая 2018 года № 4155
title:
  rus: О признании утратившим силу решения акима Кенузекского сельского округа от 22 января 2018 года № 22 «Об установлении ограничительных мероприятий на территории Кенузекского сельского округа»
  kaz: Кеңөзек ауылдық округі әкімінің 2018 жылғы 22 қаңтардағы № 22 «Кеңөзек ауылдық округі аумағында шектеу іс-шараларын белгілеу туралы» шешімінің күшін жою туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-05-21
approved_by:
- '156002009002'
version_date:
  kaz: 2018-05-21
  rus: 2018-05-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/121898/kaz/21.05.2018
  rus: https://zan.gov.kz/client/#!/doc/121898/rus/21.05.2018
