act_code: '42026'
requisite: Жылыой ауданы Ақкиізтоғай селолық округі әкімінің 2008 жылғы 17 қыркүйектегі № 34 шешімі. Жылыой аудандық Әділет басқармасында 2008 жылғы 24 қазанда № 4-2-99 болып тіркелді
title:
  rus: Жанаев Тілекқабылға «Көше атын беру»
  kaz: Жанаев Тілекқабылға «Көше атын беру»
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-09-17
approved_by:
- '156009004002'
version_date:
  kaz: 2008-09-17
source:
  kaz: https://zan.gov.kz/client/#!/doc/42026/kaz/17.09.2008
