act_code: '31733'
requisite: Атырау облысы Құрманғазы аудандық мәслихатының 2006 жылғы 15 желтоқсандағы № 299-XXXIY шешімі. Атырау облысының Құрманғазы аудандық Әділет басқармасында 2006 жылғы 29 желтоқсанда № 4-8-71 болып тіркелді
title:
  rus: 2007 жылға арналған аудан бюджетін бекіту туралы
  kaz: 2007 жылға арналған аудан бюджетін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2006-12-15
approved_by:
- '156003000002'
version_date:
  kaz: 2006-12-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/31733/kaz/15.12.2006
