act_code: '48782'
requisite: Решение Атырауского областного маслихата от 16 октября 2009 года № 250-IV. Зарегистрировано Департаментом юстиции Атырауской области 23 ноября 2009 года за № 2555. Утратило силу решением Атырауского областного маслихата от 7 сентября 2026 года № 254-VIII (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении правил присвоения звания "Почетный гражданин области (города, района)"
  kaz: '"Облыстың (қаланың, ауданның) құрметті азаматы" атағын беру қағидасын бекіту туралы'
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-10-16
approved_by:
- '156000000002'
version_date:
  kaz: 2010-12-03
source:
  kaz: https://zan.gov.kz/client/#!/doc/48782/kaz/03.12.2010
caused_by:
  code: '56059'
  requisite: Решение Атырауского областного маслихата от 3 декабря 2010 года № 381-IV. Зарегистрировано Департаментом юстиции Атырауской области 22 декабря 2010 года за № 2578. Утратило силу решением Атырауского областного маслихата от 7 сентября 2026 года № 254-VIII (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
  title:
    rus: О внесении изменения и дополнений в решение ХVІІ сессии областного маслихата от 16 октября 2009 года № 250-ІV "Об утверждении правил присвоения звания "Почетный гражданин области (города, района)"
    kaz: Облыстық мәслихаттың ХVІІ сессиясының 2009 жылғы 16 қазандағы № 250-ІV "Облыстың (қаланың, ауданның) "Құрметті азаматы" атағын беру қағидасын бекіту туралы шешіміне өзгеріс пен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/56059/rus
