act_code: '182607'
requisite: Решение Махамбетского районного маслихата Атырауской области от 2 июня 2023 года № 35. Утратило силу решением Махамбетского районного маслихата Атырауской области от 4 ноября 2025 года № 231 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении Методики оценки деятельности административных государственных служащих корпуса «Б» государственного учреждения «Аппарат Махамбетского районного маслихата»
  kaz: «Махамбет аудандық мәслихатының аппараты» мемлекеттік мекемесінің «Б» корпусы мемлекеттік әкімшілік қызметшілерінің қызметін бағалаудың әдістемесін бекіту туралы
form: РЕШ
type_codes:
- МЕТ
- РЕШ
approved_on: 2023-06-02
approved_by:
- '156004000002'
version_date:
  kaz: 2023-12-15
  rus: 2023-12-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/182607/kaz/15.12.2023
  rus: https://zan.gov.kz/client/#!/doc/182607/rus/15.12.2023
caused_by:
  code: '190337'
  requisite: Решение Махамбетского районного маслихата Атырауской области от 15 декабря 2023 года № 84. Утратило силу решением Махамбетского районного маслихата Атырауской области от 4 ноября 2025 года № 231 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
  title:
    rus: О внесение изменений в решение Махамбетского районного маслихата от 02 июня 2023 года № 35 «Об утверждении Методики оценки деятельности административных государственных служащих корпуса «Б» государственного учреждения «Аппарат Махамбетского районного маслихата»»
    kaz: Махамбет аудандық мәслихатының 2023 жылғы 02 маусымдағы № 35 ««Махамбет аудандық мәслихатының аппараты» мемлекеттік мекемесінің «Б» корпусы мемлекеттік әкімшілік қызметшілерінің қызметін бағалаудың әдістемесін бекіту туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/190337/rus
