act_code: '26459'
requisite: Решение акима Атырауской области от 23 декабря 2005 года № 43. Зарегистрировано Департаментом юстиции Атырауской области 25 января 2006 года № 2457
title:
  rus: Об отборе кандидатов для поступления в военно-учебные заведения в 2006 году
  kaz: 2006 жылы әскери – оқу орындарына түсу үшін үміткерлерді іріктеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2005-12-23
approved_by:
- '156000000001'
version_date:
  kaz: 2005-12-23
  rus: 2005-12-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/26459/kaz/23.12.2005
  rus: https://zan.gov.kz/client/#!/doc/26459/rus/23.12.2005
