act_code: '1655'
requisite: Решение акима Атырауской области от 3 июля 1998 года № 674. Зарегистрировано Управлением юстиции Атырауской области 12 августа 1998 года № 24. Утратило силу постановлением акима Атырауской области от 20 декабря 2004 года № 248
title:
  rus: О мерах по упорядочению оборота алкогольной продукции
  kaz: О мерах по упорядочению оборота алкогольной продукции
form: РЕШ
type_codes:
- РЕШ
approved_on: 1998-07-02
approved_by:
- '156000000001'
version_date:
  rus: 1998-07-02
source:
  rus: https://zan.gov.kz/client/#!/doc/1655/rus/02.07.1998
