act_code: '146400'
requisite: Решение акима Камыскалинского сельского округа Исатайского района Атырауской области от 15 сентября 2020 года № 39. Зарегистрировано Департаментом юстиции Атырауской области 17 сентября 2020 года № 4727
title:
  rus: Об утрате силы решения акима Камыскалинского сельского округа от 12 июня 2020 года № 27 «Об установлении ограничительных мероприятий»
  kaz: Қамысқала ауылдық округі әкімінің 2020 жылғы 12 маусымдағы № 27 «Шектеу іс-шараларын белгілеу туралы» шешімінің күшін жою туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-09-15
approved_by:
- '156005006002'
version_date:
  kaz: 2020-09-15
  rus: 2020-09-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/146400/kaz/15.09.2020
  rus: https://zan.gov.kz/client/#!/doc/146400/rus/15.09.2020
