act_code: '18885'
requisite: Решение акима Атырауской области от 11 февраля 2004 года № 14. Зарегистрировано Департаментом юстиции Атырауской области от 2 марта 2004 года за № 1868. Утратило силу решением акима Атырауской области от 30 марта 2009 года № 15
title:
  rus: О продолжении сплошного обследования населения области на туберкулез
  kaz: О продолжении сплошного обследования населения области на туберкулез
form: РЕШ
type_codes:
- РЕШ
approved_on: 2004-02-11
approved_by:
- '156000000003'
version_date:
  rus: 2004-02-11
source:
  rus: https://zan.gov.kz/client/#!/doc/18885/rus/11.02.2004
