act_code: '77540'
requisite: Решение Атырауского городского маслихата Атырауской области от 03 февраля 2014 года № 174. Зарегистрировано Департаментом юстиции Атырауской области 24 февраля 2014 года № 2855. Утратило силу решением маслихата города Атырау Атырауской области от 29 июня 2020 года № 506 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении перечня категории получателей и предельных размеров социальной помощи
  kaz: Алушылар санатының тізбесін және әлеуметтік көмектің шекті мөлшерлерін  бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2014-02-03
approved_by:
- '156002000002'
version_date:
  kaz: 2019-04-24
  rus: 2019-04-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/77540/kaz/24.04.2019
  rus: https://zan.gov.kz/client/#!/doc/77540/rus/24.04.2019
caused_by:
  code: '131147'
  requisite: Решение маслихата города Атырау Атырауской области от 24 апреля 2019 года № 353. Зарегистрировано Департаментом юстиции Атырауской области 3 мая 2019 года № 4391. Утратило силу решением маслихата города Атырау Атырауской области от 29 июня 2020 года № 506 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
  title:
    rus: О внесении дополнении в решение Атырауского городского маслихата от 03 февраля 2014 года № 174 "Об утверждении перечня категории получателей и предельных размеров социальной помощи"
    kaz: Атырау қалалық мәслихатының 2014 жылғы 03 ақпандағы № 174 "Алушылар санатының тізбесін және әлеуметтік көмектің шекті мөлшерлерін бекіту туралы" шешіміне толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/131147/rus
