act_code: '224000'
requisite: Решение акима Жамбульского сельского округа Кызылкогинского района Атырауской области от 13 апреля 2026 года № 11
title:
  rus: Об отмене действия решения акима Жамбульского сельского округа № 6 от 5 марта 2026 года «Об установлении ограничительных мероприятий»
  kaz: Жамбыл ауылдық округі әкімінің 2026 жылғы 5 наурыздағы № 6 «Шектеу іс-шараларын белгілеу туралы» шешімінің күшін жою туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2026-04-13
approved_by:
- '156007007002'
version_date:
  kaz: 2026-04-13
  rus: 2026-04-13
source:
  kaz: https://zan.gov.kz/client/#!/doc/224000/kaz/13.04.2026
  rus: https://zan.gov.kz/client/#!/doc/224000/rus/13.04.2026
