act_code: '42438'
requisite: Жылыой ауданы Жаңа Қаратон поселкелік округі әкімінің 2008 жылғы 28 қазандағы № 46 шешімі. Жылыой аудандық Әділет басқармасында 2008 жылғы 25 қарашада № 4-2-100 тіркелді. Күші жойылды - Жаңа Қаратон поселкелік округі әкімінің 2010 жылғы 6 желтоқсандағы № 69 шешімімен
title:
  rus: Көше атын беру туралы
  kaz: Көше атын беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-10-28
approved_by:
- '156009003002'
version_date:
  kaz: 2008-10-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/42438/kaz/28.10.2008
