act_code: '31715'
requisite: Атырау облысы Жылыой аудандық мәслихатының 2006 жылғы 7 желтоқсандағы № 28-10 шешімі. Атырау облысы Жылыой аудандық Әділет басқармасында 2006 жылғы 25 желтоқсанда № 4-2-60 болып тіркелді
title:
  rus: 2007 жылға ұсынылған ойын бизнесіне қатысты тіркелген жиынтық салық ставкалары және бірыңғай акциз ставкасы туралы
  kaz: 2007 жылға ұсынылған ойын бизнесіне қатысты тіркелген жиынтық салық ставкалары және бірыңғай акциз ставкасы туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2006-12-07
approved_by:
- '156009000002'
version_date:
  kaz: 2006-12-07
source:
  kaz: https://zan.gov.kz/client/#!/doc/31715/kaz/07.12.2006
