act_code: '71335'
requisite: Решение Кызылкогинского районного маслихата Атырауской области от 8 февраля 2013 года № XI-6. Зарегистрировано Департаментом юстиции Атырауской области 5 марта 2013 года № 2707. Утратило силу решением Кызылкогинского районного маслихата Атырауской области от 21 мая 2014 года № ХХІІІ-2
title:
  rus: Об определении размера и правил оказания жилищной помощи малообеспеченным семьям (гражданам), проживающим в Кызылкогинском районе
  kaz: Қызылқоға ауданында тұратын аз қамтамасыз етілген отбасыларға (азаматтарға) тұрғын үй көмегін көрсетудің мөлшері мен қағидасын айқындау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2013-02-08
approved_by:
- '156007000002'
version_date:
  kaz: 2013-02-08
  rus: 2013-02-08
source:
  kaz: https://zan.gov.kz/client/#!/doc/71335/kaz/08.02.2013
  rus: https://zan.gov.kz/client/#!/doc/71335/rus/08.02.2013
