act_code: '62593'
requisite: Решение Макатского районного маслихата Атырауской области от 13 декабря 2011 года № 328-IV. Зарегистрировано Департаментом юстиции Атырауской области 10 января 2012 года № 4-7-139. Утратило силу решением Макатского районного маслихата Атырауской области от 13 марта 2013 года № 105-V
title:
  rus: О районном бюджете на 2012-2014 годы
  kaz: 2012-2014 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2011-12-13
approved_by:
- '156006000002'
version_date:
  kaz: 2012-08-08
source:
  kaz: https://zan.gov.kz/client/#!/doc/62593/kaz/08.08.2012
caused_by:
  code: '67298'
  requisite: Решение Макатского районного маслихата Атырауской области от 8 августа 2012 года № 60-V. Зарегистрировано Департаментом юстиции Атырауской области 22 августа 2012 года № 4-7-151. Утратило силу - решением Макатского районного маслихата Атырауской области от 13 марта 2013 года № 105-V
  title:
    rus: О внесении изменений в решение районного маслихата от 13 декабря 2011 года № 328-IV "О районном бюджете на 2012-2014 годы"
    kaz: Аудандық мәслихаттың 2011 жылғы 13 желтоқсандағы № 328-ІV "2012-2014 жылдарға арналған аудандық бюджет туралы" шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/67298/rus
