act_code: '194160'
requisite: Решение Курмангазинского районного маслихата Атырауской области от 5 марта 2024 года № 116-VIII
title:
  rus: Об утверждении правил проведения раздельных сходов местного сообщества и определения количества представителей жителей села, улицы, многоквартирного жилого дома для участия в сходе местного сообщества на территории сельских округов Курмангазинского района
  kaz: Құрманғазы ауданының ауылдық округтерінің аумағында жергілікті қоғамдастықтың бөлек жиындарын өткізу және жергілікті қоғамдастық жиынына қатысу үшін ауыл, көше, көппәтерлі тұрғын үй тұрғындары өкілдерінің санын айқындау қағидаларын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2024-03-05
approved_by:
- '156003000002'
version_date:
  kaz: 2024-03-05
  rus: 2024-03-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/194160/kaz/05.03.2024
  rus: https://zan.gov.kz/client/#!/doc/194160/rus/05.03.2024
