act_code: '13622'
requisite: Решение акима Атырауской области от 11 октября 2002 года № 495. Зарегистрированo Управлением юстиции Атырауской области 5 ноября 2002 года за № 1187
title:
  rus: О квоте иммиграции оралманов на 2002 год
  kaz: Оралмандардың 2002 жылға арналған көшіп келу квотасы туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2002-10-10
approved_by:
- '156000000003'
version_date:
  kaz: 2002-10-10
  rus: 2002-10-10
source:
  kaz: https://zan.gov.kz/client/#!/doc/13622/kaz/10.10.2002
  rus: https://zan.gov.kz/client/#!/doc/13622/rus/10.10.2002
