act_code: '13192'
requisite: Екінші сайланған Атырау облыстық мәслихаты ХVIІ сессиясының 2002 жылғы 19 сәуірдегі № 198-II шешімі. Атырау облысының Әділет басқармасында 2002 жылғы 24 мамырда № 974 болып тіркелді
title:
  rus: '"2002-2005 жылдарға арналған Атырау облысының халқы арасында йод тапшылығынан науқастанудың алдын алу" аумақтық бағдарламасы туралы'
  kaz: '"2002-2005 жылдарға арналған Атырау облысының халқы арасында йод тапшылығынан науқастанудың алдын алу" аумақтық бағдарламасы туралы'
form: РЕШ
type_codes:
- РЕШ
approved_on: 2002-04-18
approved_by:
- '156000000002'
version_date:
  kaz: 2002-04-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/13192/kaz/18.04.2002
