act_code: '15623'
requisite: Решение ХIII-ой сессии Атырауского областного маслихата второго созыва от 5 октября 2001 года № 148-II. Зарегистрировано Управлением юстиции Атырауской области 21 января 2002 года за № 721. Утратило силу - решением Атырауского областного маслихата от 16 октября 2009 года за № 250-IV
title:
  rus: О порядке назначения и выплаты единовременного вознаграждения и ежемесячного пособия лицам, присвоенным звания "Почетный гражданин Атырауской области"
  kaz: '"Атырау облысының құрметті азаматы" атағы берілген адамдарға біржолғы сыйақы және ай сайынғы жәрдемақы тағайындау және төлеу тәртібін бекіту туралы'
form: РЕШ
type_codes:
- РЕШ
approved_on: 2001-10-04
approved_by:
- '156000000002'
version_date:
  kaz: 2001-10-04
  rus: 2001-10-04
source:
  kaz: https://zan.gov.kz/client/#!/doc/15623/kaz/04.10.2001
  rus: https://zan.gov.kz/client/#!/doc/15623/rus/04.10.2001
