act_code: '44758'
requisite: Атырау облысы Мақат аудандық мәслихатының 2009 жылғы 20 ақпандағы № 105-IV шешімі. Атырау облысының Әділет департаменті Мақат ауданының Әділет басқармасында 2009 жылғы 16 наурызда № 4-7-97 тіркелді. Күші жойылды - Мақат аудандық мәслихатының 2010 жылғы 9 ақпандағы № 197-V шешімімен
title:
  rus: Аудан бойынша 2009 жылға ара-тұра сипаттағы кәсіпкерлік қызмет түрлеріне берілетін бір жолғы талон құнының мөлшері туралы
  kaz: Аудан бойынша 2009 жылға ара-тұра сипаттағы кәсіпкерлік қызмет түрлеріне берілетін бір жолғы талон құнының мөлшері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-02-20
approved_by:
- '156006000002'
version_date:
  kaz: 2009-02-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/44758/kaz/20.02.2009
