act_code: '72394'
requisite: Решение Кызылкогинского районного маслихата Атырауской области от 19 апреля 2013 года № ХІІІ-3. Зарегистрировано Департаментом юстиции Атырауской области 4 мая 2013 года за № 2719. Утратило силу - решением Кызылкогинского районного маслихата Атырауской области от 10 июня 2013 № ХIV-1
title:
  rus: О предоставлении социальной помощи на приобретение топлива специалистам проживающим и работающим в сельских населенных пунктах
  kaz: Ауылдық елді мекендерде тұратын және жұмыс істейтін мамандарына отын сатып алу үшін әлеуметтік көмек беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2013-04-19
approved_by:
- '156007000002'
version_date:
  kaz: 2013-04-19
  rus: 2013-04-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/72394/kaz/19.04.2013
  rus: https://zan.gov.kz/client/#!/doc/72394/rus/19.04.2013
