act_code: '97929'
requisite: Решение Махамбетского районного маслихата Атырауской области от 24 декабря 2015 года № 349. Зарегистрировано Департаментом юстиции Атырауской области 12 января 2016 года № 3433. Утратило силу решением Махамбетского районного маслихата Атырауской области от 4 мая 2024 года № 117 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об определении размера и порядка оказания жилищной помощи в Махамбетском районе
  kaz: Махамбет ауданында тұрғын үй көмегін көрсетудің мөлшері мен тәртібін айқындау туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2015-12-24
approved_by:
- '156004000002'
version_date:
  kaz: 2015-12-24
  rus: 2015-12-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/97929/kaz/24.12.2015
  rus: https://zan.gov.kz/client/#!/doc/97929/rus/24.12.2015
