act_code: '97929'
requisite: Решение Махамбетского районного маслихата Атырауской области от 24 декабря 2015 года № 349. Зарегистрировано Департаментом юстиции Атырауской области 12 января 2016 года № 3433. Утратило силу решением Махамбетского районного маслихата Атырауской области от 4 мая 2024 года № 117 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об определении размера и порядка оказания жилищной помощи в Махамбетском районе
  kaz: Махамбет ауданында тұрғын үй көмегін көрсетудің мөлшері мен тәртібін айқындау туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2015-12-24
approved_by:
- '156004000002'
version_date:
  kaz: 2023-09-14
  rus: 2023-09-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/97929/kaz/14.09.2023
  rus: https://zan.gov.kz/client/#!/doc/97929/rus/14.09.2023
caused_by:
  code: '186400'
  requisite: Решение Махамбетского районного маслихата Атырауской области от 14 сентября 2023 года № 64. Зарегистрировано в Департаменте юстиции Атырауской области 22 сентября 2023 года № 5083-06. Утратило силу решением Махамбетского районного маслихата Атырауской области от 4 мая 2024 года № 117 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
  title:
    rus: О внесении изменений и дополнения в решение Махамбетского районного маслихата от 24 декабря 2015 года № 349 «Об определении размера и порядка оказания жилищной помощи в Махамбетском районе»
    kaz: Махамбет аудандық мәслихатының 2015 жылғы 24 желтоқсандағы № 349 «Махамбет ауданында тұрғын үй көмегін көрсетудің мөлшері мен тәртібін айқындау туралы» шешіміне өзгерістер мен толықтыру енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/186400/rus
