act_code: '85095'
requisite: Решение от 03.12.2014 №25-2, Маслихат Жылыойского района. Утратило силу решением Жылыойского районного маслихата Атырауской области от 18 сентября 2015 года № 32-3.
title:
  rus: Об утверждении правил оказания жилищной помощи малообеспеченным семьям (гражданам), проживающим в Жылыойском районе
  kaz: Жылыой ауданында тұратын аз қамтылған отбасыларға (азаматтарға) тұрғын үй көмегін көрсетудің қағидасын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2014-12-03
approved_by:
- '156009000002'
version_date:
  kaz: 2014-12-03
  rus: 2014-12-03
source:
  kaz: https://zan.gov.kz/client/#!/doc/85095/kaz/03.12.2014
  rus: https://zan.gov.kz/client/#!/doc/85095/rus/03.12.2014
