act_code: '71394'
requisite: Решение Макатского районного маслихата Атырауской области от 4 февраля 2013 года № 94-V. Зарегистрировано Департаментом юстиции Атырауской области 4 марта 2013 года № 2705. Утратило силу решением Макатского районного маслихата Атырауской области от 6 мая 2014 года № 230-V
title:
  rus: Об определении размера и правил оказания жилищной помощи малообеспеченным семьям (гражданам), проживающим в Макатском районе
  kaz: Мақат ауданында тұратын аз қамтамасыз етілген отбасыларға (азаматтарға)    тұрғын үй көмегін көрсетудің мөлшері мен қағидасын айқындау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2013-02-04
approved_by:
- '156006000002'
version_date:
  kaz: 2013-02-04
  rus: 2013-02-04
source:
  kaz: https://zan.gov.kz/client/#!/doc/71394/kaz/04.02.2013
  rus: https://zan.gov.kz/client/#!/doc/71394/rus/04.02.2013
