act_code: '43931'
requisite: Атырау облысы Құрманғазы ауданы әкімінің 2009 жылғы 14 қаңтардағы № 01 шешімі Атырау облысы Әділет департаменті Құрманғазы ауданының Әділет басқармасында 2009 жылғы 2 ақпанда № 4-8-139 тіркелді
title:
  rus: 1992 жылы туған азаматтарды 2009 жылы шақыру учаскесіне тіркеуді жүргізу туралы
  kaz: 1992 жылы туған азаматтарды 2009 жылы шақыру учаскесіне тіркеуді жүргізу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-01-14
approved_by:
- '156003000003'
version_date:
  kaz: 2009-01-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/43931/kaz/14.01.2009
