act_code: '43715'
requisite: Атырау облысы Мақат аудандық мәслихатының 2008 жылғы 19 желтоқсандағы № 90-IV шешімі. Атырау облысының Әділет департаменті Мақат ауданының Әділет басқармасында 2009 жылғы 26 қаңтарда № 4-7-93 тіркелді
title:
  rus: 2009 жылға арналған аудандық бюджет туралы
  kaz: 2009 жылға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-12-19
approved_by:
- '156006000002'
version_date:
  kaz: 2009-12-10
source:
  kaz: https://zan.gov.kz/client/#!/doc/43715/kaz/10.12.2009
caused_by:
  code: '49602'
  requisite: Решение маслихата Макатского района Атырауской области от 10 декабря 2009 года № 181-IV . Зарегистрировано Управлением юстиции Макатского района Атырауской области 5 января 2010 года № 4-7-108
  title:
    rus: Аудандық Мәслихаттың 2008 жылғы 19 желтоқсандағы "2009 жылға арналған аудандық бюджет туралы" № 90-IV шешіміне өзгерістер енгізу туралы
    kaz: Аудандық Мәслихаттың 2008 жылғы 19 желтоқсандағы "2009 жылға арналған аудандық бюджет туралы" № 90-IV шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/49602/rus
