act_code: '43715'
requisite: Атырау облысы Мақат аудандық мәслихатының 2008 жылғы 19 желтоқсандағы № 90-IV шешімі. Атырау облысының Әділет департаменті Мақат ауданының Әділет басқармасында 2009 жылғы 26 қаңтарда № 4-7-93 тіркелді
title:
  rus: 2009 жылға арналған аудандық бюджет туралы
  kaz: 2009 жылға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-12-19
approved_by:
- '156006000002'
version_date:
  kaz: 2009-10-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/43715/kaz/28.10.2009
caused_by:
  code: '48799'
  requisite: Атырау облысы Мақат аудандық мәслихатының 2009 жылғы 28 қазандағы № 170-IV шешімі. Атырау облысының Әділет департаменті Мақат ауданының Әділет басқармасында 2009 жылғы 24 қарашада № 4-7-107 тіркелді
  title:
    rus: Аудандық Мәслихаттың 2008 жылғы 19 желтоқсандағы "2009 жылға арналған аудандық бюджет туралы" № 90-IV шешіміне өзгерістер мен толықтырулар енгізу туралы
    kaz: Аудандық Мәслихаттың 2008 жылғы 19 желтоқсандағы "2009 жылға арналған аудандық бюджет туралы" № 90-IV шешіміне өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/48799/rus
