act_code: '43715'
requisite: Атырау облысы Мақат аудандық мәслихатының 2008 жылғы 19 желтоқсандағы № 90-IV шешімі. Атырау облысының Әділет департаменті Мақат ауданының Әділет басқармасында 2009 жылғы 26 қаңтарда № 4-7-93 тіркелді
title:
  rus: 2009 жылға арналған аудандық бюджет туралы
  kaz: 2009 жылға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-12-19
approved_by:
- '156006000002'
version_date:
  kaz: 2009-04-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/43715/kaz/22.04.2009
caused_by:
  code: '46031'
  requisite: Атырау облысы Мақат аудандық мәслихатының 2009 жылғы 22 сәуірдегі № 123-IV шешімі. Атырау облысының Әділет департаменті Мақат ауданының әділет басқармасында 2009 жылғы 20 мамырда № 4-7-99 тіркелді
  title:
    rus: Аудандық Мәслихаттың 2008 жылғы 19 желтоқсандағы "2009 жылға арналған аудандық бюджет туралы" № 90-IV шешіміне өзгерістер мен толықтырулар  енгізу туралы
    kaz: Аудандық Мәслихаттың 2008 жылғы 19 желтоқсандағы "2009 жылға арналған аудандық бюджет туралы" № 90-IV шешіміне өзгерістер мен толықтырулар  енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/46031/rus
