act_code: '52705'
requisite: Решение Индерского районного маслихата Атырауской области от 14 апреля 2010 года № 219-IV. Зарегистрировано Управлением юстиции Индерского района Атырауской области 21 мая 2010 года № 4-6-101. Утратило силу решением Индерского районного маслихата Атырауской области от 5 декабря 2012 года № 63-V
title:
  rus: Ауылдық елді мекендерде тұратын және жұмыс жасайтын денсаулық сақтау, білім беру, әлеуметтік қорғау, мәдениет және спорт салаларының мамандарына отын  сатып алуы үшін біржолғы ақшалай төлемдерді тағайындау, қаржыландыру және төлеу қағидасы туралы
  kaz: Ауылдық елді мекендерде тұратын және жұмыс жасайтын денсаулық сақтау, білім беру, әлеуметтік қорғау, мәдениет және спорт салаларының мамандарына отын  сатып алуы үшін біржолғы ақшалай төлемдерді тағайындау, қаржыландыру және төлеу қағидасы туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-04-14
approved_by:
- '156008000002'
version_date:
  kaz: 2010-04-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/52705/kaz/14.04.2010
