act_code: '117744'
requisite: Решение Махамбетского районного маслихата Атырауской области от 25 декабря 2017 года № 203. Зарегистрировано Департаментом юстиции Атырауской области 15 января 2018 года № 4042. Утратило силу решением Махамбетского районного маслихата Атырауской области от 22 января 2019 года № 318 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: О бюджетах сельских округов на 2018-2020 годы
  kaz: 2018–2020 жылдарға арналған ауылдық округтердің бюджеттері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2017-12-25
approved_by:
- '156004000002'
version_date:
  kaz: 2018-03-30
  rus: 2018-03-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/117744/kaz/30.03.2018
  rus: https://zan.gov.kz/client/#!/doc/117744/rus/30.03.2018
caused_by:
  code: '121014'
  requisite: Решение Махамбетского районного маслихата Атырауской области от 30 марта 2018 года № 229. Зарегистрировано Департаментом юстиции Атырауской области 19 апреля 2018 года № 4129. Утратило силу решением Махамбетского районного маслихата Атырауской области от 22 января 2019 года № 318 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
  title:
    rus: О внесении изменений и дополнения в решение районного маслихата от 25 декабря 2017 года № 203 «О бюджетах сельских округов на 2018-2020 годы»
    kaz: Аудандық мәслихаттың 2017 жылғы 25 желтоқсандағы № 203 «2018-2020 жылдарға арналған ауылдық округтердің бюджеттері туралы» шешіміне өзгерістер мен толықтыру енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/121014/rus
