act_code: '109120'
requisite: Решение Кызылкогинского районного маслихата Атырауской области от 14 декабря 2016 года № VIII-7. Зарегистрировано Департаментом юстиции Атырауской области 16 января 2017 года № 3762. Утратило силу решением Кызылкогинского районного маслихата Атырауской области от 2 февраля 2018 года № XXI-1
title:
  rus: О повышении ставок единого земельного налога и базовых ставок земельного налога на не используемые в соответствии с земельным законодательством Республики Казахстан земли сельскохозяйственного назначения  в Кызылкогинском районе
  kaz: Қазақстан Республикасының жер заңнамасына сәйкес Қызылқоға ауданында пайдаланылмайтын ауыл шаруашылығы мақсатындағы жерлерге бірыңғай жер салығының мөлшерлемелерін және жер салығының базалық мөлшерлемелерін жоғарылату туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2016-12-14
approved_by:
- '156007000002'
version_date:
  kaz: 2016-12-14
  rus: 2016-12-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/109120/kaz/14.12.2016
  rus: https://zan.gov.kz/client/#!/doc/109120/rus/14.12.2016
