act_code: '138087'
requisite: Решение Атырауского областного маслихата от 12 декабря 2019 года № 386-VI. Зарегистрировано Департаментом юстиции Атырауской области 30 декабря 2019 года № 4561
title:
  rus: Об областном бюджете на 2020-2022 годы
  kaz: 2020-2022 жылдарға арналған облыстық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-12-12
approved_by:
- '156000000002'
version_date:
  kaz: 2020-12-09
  rus: 2020-12-09
source:
  kaz: https://zan.gov.kz/client/#!/doc/138087/kaz/09.12.2020
  rus: https://zan.gov.kz/client/#!/doc/138087/rus/09.12.2020
caused_by:
  code: '149809'
  requisite: Решение Атырауского областного маслихата от 9 декабря 2020 года № 496-VI. Зарегистрировано Департаментом юстиции Атырауской области 11 декабря 2020 года № 4809
  title:
    rus: О внесении изменений и дополнений в решение Атырауского областного маслихата от 12 декабря 2019 года № 386-VІ «Об областном бюджете на 2020-2022 годы»
    kaz: Атырау облыстық мәслихатының 2019 жылғы 12 желтоқсандағы № 386-VІ «2020-2022 жылдарға арналған облыстық бюджет туралы» шешіміне өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/149809/rus
