act_code: '54186'
requisite: Атырау облысы Исатай аудандық мәслихатының 2010 жылғы 14 шілдедегі № 198-IV шешімі. Исатай аудандық Әділет басқармасында 2010 жылғы 26 тамызда № 4-4-168 тіркелді. Күші жойылды - Исатай аудандық мәслихатының 2012 жылғы 27 шілдедегі № 55-V шешімімен
title:
  rus: Аз қамтылған отбасыларына (азаматтарға) тұрғын үй көмегін көрсету қағидасы туралы
  kaz: Аз қамтылған отбасыларына (азаматтарға) тұрғын үй көмегін көрсету қағидасы туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-07-14
approved_by:
- '156005000002'
version_date:
  kaz: 2010-07-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/54186/kaz/14.07.2010
