act_code: '128709'
requisite: Решение Курмангазинского районного маслихата Атырауской области от 10 января 2019 года № 383-VI. Зарегистрировано Департаментом юстиции Атырауской области 21 января 2019 года № 4333
title:
  rus: Об утверждении бюджетов сельских округов Курмангазинского района на 2019-2021 годы
  kaz: 2019-2021 жылдарға арналған Құрманғазы ауданының ауылдық округтерінің бюджеттерін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-01-10
approved_by:
- '156003000002'
version_date:
  kaz: 2019-01-10
  rus: 2019-01-10
source:
  kaz: https://zan.gov.kz/client/#!/doc/128709/kaz/10.01.2019
  rus: https://zan.gov.kz/client/#!/doc/128709/rus/10.01.2019
