act_code: '178028'
requisite: Решение Атырауского городского маслихата Атырауской области от 27 декабря 2022 года № 219
title:
  rus: О бюджете сельских округов относящихся к городу Атырау на 2023-2025 годы
  kaz: 2023-2025 жылдарға арналған Атырау қаласына қарасты ауылдық округтер бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-12-27
approved_by:
- '156002000002'
version_date:
  kaz: 2023-12-21
  rus: 2023-12-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/178028/kaz/21.12.2023
  rus: https://zan.gov.kz/client/#!/doc/178028/rus/21.12.2023
caused_by:
  code: '191331'
  requisite: Решение Атырауского городского маслихата Атырауской области от 21 декабря 2023 года № 80
  title:
    rus: О внесении изменний в решение маслихата города Атырау от 27 декабря 2022 года № 219 «О бюджете сельских округов относящихся к городу Атырау на 2023-2025 годы»
    kaz: Атырау қаласы мәслихатының 2022 жылғы 27 желтоқсандағы № 219 «2023-2025 жылдарға арналған Атырау қаласына қарасты ауылдық округтер бюджеті туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/191331/rus
