act_code: '404'
requisite: I сайланған Атырау облыстық мәслихаты XIX сессиясының 1997 жылғы 27 желтоқсандағы № 218-I шешімі. Атырау облысының Әділет департаментінде 1998 жылғы 26 наурызда № 13 болып тіркелді
title:
  rus: Республика Президентінің «Қазақстан халқына Жолдауына» сәйкес облыстағы көп балалы отбасыларын әлеуметтік қорғау жөніндегі жұмыстар туралы
  kaz: Республика Президентінің «Қазақстан халқына Жолдауына» сәйкес облыстағы көп балалы отбасыларын әлеуметтік қорғау жөніндегі жұмыстар туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 1997-12-27
approved_by:
- '156000000002'
version_date:
  kaz: 1997-12-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/404/kaz/27.12.1997
