act_code: '107628'
requisite: Решение Индерского районного маслихата Атырауской области от 2 ноября 2016 года № 54-VI. Зарегистрировано Департаментом юстиции Атырауской области 22 ноября 2016 года № 3679. Утратило силу решением Индерского районного маслихата Атырауской области от 30 января 2018 года № 177-VI
title:
  rus: О повышении ставок единого земельного налога и базовых ставок земельного налога на не используемые в соответствии с земельным законодательством Республики Казахстан земли сельскохозяйственного назначения в Индерском районе
  kaz: Қазақстан Республикасының жер заңнамасына сәйкес Индер ауданында пайдаланылмайтын ауыл шаруашылығы мақсатындағы жерлерге бірыңғай жер салығының мөлшерлемелерін және жер салығының базалық мөлшерлемелерін жоғарылату туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2016-11-02
approved_by:
- '156008000002'
version_date:
  kaz: 2016-11-02
  rus: 2016-11-02
source:
  kaz: https://zan.gov.kz/client/#!/doc/107628/kaz/02.11.2016
  rus: https://zan.gov.kz/client/#!/doc/107628/rus/02.11.2016
