act_code: '23808'
requisite: Решение Атырауского областного маслихата 11 февраля 2005 года № 189-III. Зарегистрировано Департаментом юстиции Атырауской области 19 марта 2005 года № 2380. Утратило силу решением областного маслихата от 29 июля 2011 года № 448-II
title:
  rus: Об оказании социальной помощи отдельным категориям граждан
  kaz: Азаматтардың кейбір санаттарына әлеуметтік көмек көрсету туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2005-02-11
approved_by:
- '156000000002'
version_date:
  kaz: 2005-02-11
  rus: 2005-02-11
source:
  kaz: https://zan.gov.kz/client/#!/doc/23808/kaz/11.02.2005
  rus: https://zan.gov.kz/client/#!/doc/23808/rus/11.02.2005
