act_code: '135726'
requisite: Решение Курмангазинского районного маслихата Атырауской области от 24 октября 2019 года № 463-VI. Зарегистрировано Департаментом юстиции Атырауской области 31 октября 2019 года № 4518
title:
  rus: Об утверждении Правил и размера оказания социальной поддержки по оплате коммунальных услуг и приобретению топлива специалистам государственных организаций здравоохранения, социального обеспечения, образования, культуры, спорта и ветеринарии, проживающим и работающим в сельских населенных пунктах Курмангазинского района
  kaz: Құрманғазы ауданының ауылдық елді мекендерінде тұратын және жұмыс істейтін мемлекеттік денсаулық сақтау, әлеуметтік қамсыздандыру, білім беру, мәдениет, спорт және ветеринария ұйымдарының мамандарына коммуналдық көрсетілетін қызметтерге ақы төлеу және отын сатып алу бойынша әлеуметтік қолдау көрсету қағидасы мен мөлшерін бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2019-10-24
approved_by:
- '156003000002'
version_date:
  kaz: 2024-04-25
  rus: 2024-04-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/135726/kaz/25.04.2024
  rus: https://zan.gov.kz/client/#!/doc/135726/rus/25.04.2024
caused_by:
  code: '196254'
  requisite: Решение Курмангазинского районного маслихата Атырауской области от 25 апреля 2024 года № 126-VIII. Зарегистрировано в Департаменте юстиции Атырауской области 30 апреля 2024 года № 5188-06
  title:
    rus: О внесении изменения в решение Курмангазинского районного маслихата от 24 октября 2019 года № 463-VІ «Об утверждении Правил и размера оказания социальной поддержки по оплате коммунальных услуг и приобретению топлива специалистам государственных организаций здравоохранения, социального обеспечения, образования, культуры, спорта и ветеринарии, проживающим и работающим в сельских населенных пунктах Курмангазинского района»
    kaz: Құрманғазы аудандық мәслихатының 2019 жылғы 24 қазандағы № 463-VI «Құрманғазы ауданының ауылдық елді мекендерінде тұратын және жұмыс істейтін мемлекеттік денсаулық сақтау, әлеуметтік қамсыздандыру, білім беру, мәдениет, спорт және ветеринария ұйымдарының мамандарына коммуналдық көрсетілетін қызметтерге ақы төлеу және отын сатып алу бойынша әлеуметтік қолдау көрсету қағидасы мен мөлшерін бекіту туралы» шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/196254/rus
