act_code: '5586'
requisite: Решение акима Атырауской области от 4 февраля 2000 года № 349. Зарегистрировано Департаментом юстиции Атырауской области от 23 марта 2000 года № 166
title:
  rus: О кредитовании бизнес-проектов для развития малого предпринимательства на местном уровне
  kaz: Жергілікті деңгейде шағын кәсіпкерлікті дамыту үшін бизнес-жобаларды несиелеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2000-02-04
approved_by:
- '156000000003'
version_date:
  kaz: 2000-02-04
  rus: 2000-02-04
source:
  kaz: https://zan.gov.kz/client/#!/doc/5586/kaz/04.02.2000
  rus: https://zan.gov.kz/client/#!/doc/5586/rus/04.02.2000
