act_code: '31718'
requisite: Атырау облысы Исатай ауданы мәслихатының 2006 жылғы 19 желтоқсандағы № 226-ІІІ шешімі. Атырау облысының Әділет департаментінде 2007 жылғы 9 қаңтарда № 4-4-61 болып тіркелді
title:
  rus: 2007 жылға арналған аудандық бюджет туралы
  kaz: 2007 жылға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2006-12-19
approved_by:
- '156005000002'
version_date:
  kaz: 2006-12-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/31718/kaz/19.12.2006
