act_code: '213916'
requisite: Решение акима поселка Индербор Индерского района Атырауской области от 3 сентября 2025 года № 81. Утратило силу решением акима поселка Индербор Индерского района Атырауской области от 26 января 2026 года № 16 (вводится в действие со дня его первого официального опубликования)
title:
  rus: Об объявлении чрезвычайной ситуации природного характера местного масштаба на территории поселка Индербор
  kaz: Индербор кенті аумағында жергілікті ауқымдағы табиғи сипаттағы төтенше жағдайды жариялау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2025-09-03
approved_by:
- '156008007001'
version_date:
  kaz: 2025-09-03
  rus: 2025-09-03
source:
  kaz: https://zan.gov.kz/client/#!/doc/213916/kaz/03.09.2025
  rus: https://zan.gov.kz/client/#!/doc/213916/rus/03.09.2025
