act_code: '85217'
requisite: Решение Атырауского городского маслихата Атырауской области от 5 декабря 2014 года № 230. Зарегистрировано Департаментом юстиции Атырауской области 25 декабря 2014 года № 3069. Утратило силу решением Атырауского городского маслихата Атырауской области от 9 сентября 2015 года № 296
title:
  rus: Об утверждении правил оказания жилищной помощи малообеспеченным семьям (гражданам), проживающим в городе Атырау
  kaz: Атырау қаласында тұратын аз қамтылған отбасыларға (азаматтарға) тұрғын үй көмегін көрсетудің қағидасын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2014-12-05
approved_by:
- '156002000002'
version_date:
  kaz: 2014-12-05
  rus: 2014-12-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/85217/kaz/05.12.2014
  rus: https://zan.gov.kz/client/#!/doc/85217/rus/05.12.2014
