act_code: '196255'
requisite: Решение Курмангазинского районного маслихата Атырауской области от 25 апреля 2024 года № 124-VIII. Зарегистрировано в Департаменте юстиции Атырауской области 30 апреля 2024 года № 5187-06
title:
  rus: О некоторых вопросах проведения мирных собраний
  kaz: Бейбіт жиналыстар өткізудің кейбір мәселелері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-04-25
approved_by:
- '156003000002'
version_date:
  kaz: 2024-04-25
  rus: 2024-04-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/196255/kaz/25.04.2024
  rus: https://zan.gov.kz/client/#!/doc/196255/rus/25.04.2024
