act_code: '43639'
requisite: Атырау қаласы әкімінің 2008 жылғы 10 желтоқсандағы № 698 шешімі. Атырау қалалық Әділет басқармасында 2009 жылғы 16 қаңтарда № 4-1-95 тіркелді
title:
  rus: 1992 жылғы туған Атырау қаласы азаматтарын 2009 жылдың қаңтар-наурыз айларында шақыру учаскесінде тіркеуден өткізу туралы
  kaz: 1992 жылғы туған Атырау қаласы азаматтарын 2009 жылдың қаңтар-наурыз айларында шақыру учаскесінде тіркеуден өткізу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-12-10
approved_by:
- '156002000001'
version_date:
  kaz: 2008-12-10
source:
  kaz: https://zan.gov.kz/client/#!/doc/43639/kaz/10.12.2008
