act_code: '222115'
requisite: Решение акима Кенузекского сельского округа города Атырау Атырауской области от 23 января 2026 года № 19
title:
  rus: Об отмене ограничительных мероприятий на территории Кенузекского сельского округа
  kaz: Кеңөзек ауылдық округі аумағында шектеу шараларын тоқтату туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2026-01-23
approved_by:
- '156002009002'
version_date:
  kaz: 2026-01-23
  rus: 2026-01-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/222115/kaz/23.01.2026
  rus: https://zan.gov.kz/client/#!/doc/222115/rus/23.01.2026
