act_code: '138086'
requisite: Решение Исатайского районного маслихата Атырауской области от 23 декабря 2019 года № 283-VI. Зарегистрировано Департаментом юстиции Атырауской области 8 января 2020 года № 4565
title:
  rus: О районном бюджете на 2020-2022 годы
  kaz: 2020-2022 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-12-23
approved_by:
- '156005000002'
version_date:
  kaz: 2020-04-09
  rus: 2020-04-09
source:
  kaz: https://zan.gov.kz/client/#!/doc/138086/kaz/09.04.2020
  rus: https://zan.gov.kz/client/#!/doc/138086/rus/09.04.2020
caused_by:
  code: '141585'
  requisite: Решение Исатайского районного маслихата Атырауской области от 9 апреля 2020 года № 296-VI. Зарегистрировано Департаментом юстиции Атырауской области 14 апреля 2020 года № 4635
  title:
    rus: О внесении изменений и дополнения в решение Исатайского районного маслихата от 23 декабря 2019 года № 283-VI «О районном бюджете на 2020-2022 годы»
    kaz: Исатай ауданы мәслихатының 2019 жылғы 23 желтоқсандағы № 283-VI «2020-2022 жылдарға арналған аудандық бюджет туралы» шешіміне өзгерістер мен толықтыру енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/141585/rus
