act_code: '138086'
requisite: Решение Исатайского районного маслихата Атырауской области от 23 декабря 2019 года № 283-VI. Зарегистрировано Департаментом юстиции Атырауской области 8 января 2020 года № 4565
title:
  rus: О районном бюджете на 2020-2022 годы
  kaz: 2020-2022 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-12-23
approved_by:
- '156005000002'
version_date:
  kaz: 2019-12-23
  rus: 2019-12-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/138086/kaz/23.12.2019
  rus: https://zan.gov.kz/client/#!/doc/138086/rus/23.12.2019
