act_code: '221524'
requisite: Решение акима Дамбинского сельского округа города Атырау Атырауской области от 23 января 2026 года № 16
title:
  rus: О присвоении наименования улице села Дамба, Дамбинского сельского округа города Атырау
  kaz: Атырау қаласы, Дамбы ауылдық округінің Дамбы ауылының көшесіне атау беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2026-01-23
approved_by:
- '156002005002'
version_date:
  kaz: 2026-01-23
  rus: 2026-01-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/221524/kaz/23.01.2026
  rus: https://zan.gov.kz/client/#!/doc/221524/rus/23.01.2026
