act_code: '37797'
requisite: Атырау облысы Құрманғазы аудандық мәслихатының 2007 жылғы 21 желтоқсандағы № 38-III шешімі. Атырау облысының Құрманғазы аудандық Әділет басқармасында 2008 жылғы 17 қаңтарда № 4-8-116 болып тіркелді
title:
  rus: 2008 жылға сыртқы (көрнекі) жарнамалардың орналастырылуына алынатын айлық төлемақы мөлшері туралы
  kaz: 2008 жылға сыртқы (көрнекі) жарнамалардың орналастырылуына алынатын айлық төлемақы мөлшері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2007-12-21
approved_by:
- '156003000002'
version_date:
  kaz: 2007-12-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/37797/kaz/21.12.2007
