act_code: '56747'
requisite: Решение Атырауского городского маслихата Атырауской области от 8 декабря 2010 года № 227. Зарегистрировано Управлением юстиции Атырауской области 17 января 2011 года за № 4-1-132. Утратило силу - решением Атырауского городского маслихата Атырауской области от 26 апреля 2013 года № 120
title:
  rus: 2011-2013 жылдарға арналған қала бюджеті туралы
  kaz: 2011-2013 жылдарға арналған қала бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-12-08
approved_by:
- '156002000002'
version_date:
  kaz: 2011-08-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/56747/kaz/18.08.2011
caused_by:
  code: '60647'
  requisite: Решение Атырауского городского маслихата Атырауской области от 18 августа 2011 года № 290. Зарегистрировано департаментом Юстиции Атырауской области 20 сентября 2011 года № 4-1-146. Утратило силу - решением Атырауского городского маслихата Атырауской области от 26 апреля 2013 года № 120
  title:
    rus: О внесении изменений и дополнений в решение городского Маслихата от 8 декабря 2010 года № 227 "О бюджете города на 2011-2013 годы"
    kaz: Қалалық Мәслихаттың 2010 жылғы 8 желтоқсандағы № 227 "2011-2013 жылдарға арналған қала бюджеті туралы" шешіміне өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/60647/rus
