act_code: '145458'
requisite: Решение акима Аккиизтогайского сельского округа Жылыойского района Атырауской области от 7 августа 2020 года № 14. Зарегистрировано Департаментом юстиции Атырауской области 12 августа 2020 года № 4707
title:
  rus: Об утрате силы решения акима Аккиизтогайского сельского округа от 18 марта 2020 года № 10 «Об установлении ограничительных мероприятий»
  kaz: Ақкиізтоғай ауылдық округі әкімінің 2020 жылғы 18 наурыздағы № 10 «Шектеу іс-шараларын белгілеу туралы» шешімінің күшін жою туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-08-07
approved_by:
- '156009004002'
version_date:
  kaz: 2020-08-07
  rus: 2020-08-07
source:
  kaz: https://zan.gov.kz/client/#!/doc/145458/kaz/07.08.2020
  rus: https://zan.gov.kz/client/#!/doc/145458/rus/07.08.2020
