act_code: '164170'
requisite: Решение акима Мукурского сельского округа Кызылкогинского района Атырауской области от 27 января 2022 года № 3. Зарегистрировано в Министерстве юстиции Республики Казахстан 28 января 2022 года № 26677. Утратило силу решением акима Мукурского сельского округа Кызылкогинского района Атырауской области от 11 апреля 2022 года № 16 (вводится в действие после дня его первого официального опубликования)
title:
  rus: Об установлении ограничительных мероприятий
  kaz: Шектеу іс-шараларын белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-01-27
approved_by:
- '156007002002'
version_date:
  kaz: 2022-01-27
  rus: 2022-01-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/164170/kaz/27.01.2022
  rus: https://zan.gov.kz/client/#!/doc/164170/rus/27.01.2022
