act_code: '15648'
requisite: Решение ХIV сессии Атырауского областного маслихата второго созыва от 8 декабря 2001 года № 158-II. Зарегистрировано Управлением юстиции Атырауской области 21 февраля 2002 года за № 801
title:
  rus: Об утверждении постановления Атырауского областного акимата от 24 июля 2001 года № 13 "О концепции реформирования и развития системы здравоохранения Атырауской области на 2001-2003 годы"
  kaz: Атырау облыстық әкімиятының 2001 жылғы 24 шілдедегі № 13 "2001-2003 жылдарға Атырау облыстық денсаулық сақтау жүйесін реформалау мен дамыту тұжырымдамасы туралы" қаулысын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2001-12-08
approved_by:
- '156000000002'
version_date:
  kaz: 2001-12-08
  rus: 2001-12-08
source:
  kaz: https://zan.gov.kz/client/#!/doc/15648/kaz/08.12.2001
  rus: https://zan.gov.kz/client/#!/doc/15648/rus/08.12.2001
