act_code: '43928'
requisite: Атырау облысы Құрманғазы аудандық мәслихатының 2008 жылғы 24 желтоқсандағы № 130-ХІІІ шешімі. Атырау облысы Әділет департаменті Құрманғазы ауданының Әділет басқармасында 2009 жылғы 28 қаңтарда № 4-8-137 болып тіркелді. Күші жойылды - Атырау облысы Құрманғазы аудандық мәслихаттың 2009 жылғы 23 желтоқсандағы № 234-ХXV шешімімен
title:
  rus: 2009 жылға ауыл шаруашылығы мақсатындағы және елді мекендерден тыс орналасқан өнеркәсіп жерлеріне салынатын базалық салық ставкалары туралы
  kaz: 2009 жылға ауыл шаруашылығы мақсатындағы және елді мекендерден тыс орналасқан өнеркәсіп жерлеріне салынатын базалық салық ставкалары туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-12-24
approved_by:
- '156003000002'
version_date:
  kaz: 2008-12-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/43928/kaz/24.12.2008
