act_code: '14585'
requisite: Екінші сайланған Атырау облыстық мәслихаты ХХІ сессиясының 2002 жылғы 6 желтоқсандағы № 262-II шешімі. Атырау облысының Әділет басқармасында 2002 жылғы 25 желтоқсанда № 1237 болып тіркелді
title:
  rus: Атырау облысында кедейлiктi төмендету жөнiндегi 2003-2005 жылдарға арналған бағдарламасы туралы
  kaz: Атырау облысында кедейлiктi төмендету жөнiндегi 2003-2005 жылдарға арналған бағдарламасы туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2002-12-06
approved_by:
- '156000000002'
version_date:
  kaz: 2002-12-06
source:
  kaz: https://zan.gov.kz/client/#!/doc/14585/kaz/06.12.2002
