act_code: '199319'
requisite: Решение Исатайского районного маслихата Атырауской области от 30 июля 2024 года № 103-VIII
title:
  rus: Об утверждении программы по управления коммунальными отходами Исатайскому районе на 2024-2030 год
  kaz: Исатай ауданы бойынша коммуналдық қалдықтарды басқарудың 2024-2030 жылдарға арналған бағдарламаны бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-07-30
approved_by:
- '156005000002'
version_date:
  kaz: 2024-07-30
  rus: 2024-07-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/199319/kaz/30.07.2024
  rus: https://zan.gov.kz/client/#!/doc/199319/rus/30.07.2024
