act_code: '52710'
requisite: Атырау облысы Құрманғазы аудандық мәслихатының 2010 жылғы 14 сәуірдегі № 267-XXVIII шешімі. Атырау облысы Әділет департаменті Құрманғазы ауданының Әділет басқармасында 2010 жылғы 25 мамырда № 4-8-189 тіркелді. Күші жойылды - Атырау облысы Құрманғазы аудандық мәслихатының 2013 жылғы 6 ақпандағы № 117-V шешімімен
title:
  rus: Ауылдық елді мекендерде тұратын және жұмыс жасайтын мемлекеттік денсаулық сақтау, білім беру, әлеуметтік қамсыздандыру, мәдениет және спорт ұйымдарының мамандарына отын сатып алу үшін біржолғы ақшалай төлем мөлшерін белгілеу туралы
  kaz: Ауылдық елді мекендерде тұратын және жұмыс жасайтын мемлекеттік денсаулық сақтау, білім беру, әлеуметтік қамсыздандыру, мәдениет және спорт ұйымдарының мамандарына отын сатып алу үшін біржолғы ақшалай төлем мөлшерін белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-04-14
approved_by:
- '156003000002'
version_date:
  kaz: 2010-04-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/52710/kaz/14.04.2010
