act_code: '29497'
requisite: Атырау облысы Жылыой аудандық мәслихатының 2006 жылғы 28 маусымдағы № 25-3 шешімі. Атырау облысы Жылыой аудандық Әділет басқармасында 2006 жылғы 28 шілдеде № 4-2-48 болып тіркелді
title:
  rus: Жылыой ауданы мемлекеттік органдарының жер учаскелерін (жер пайдалану құқығын) алып қою (сатып алу) жөніндегі жұмыстары мен қарым қатынастарын ұйымдастыру Ережелері туралы
  kaz: Жылыой ауданы мемлекеттік органдарының жер учаскелерін (жер пайдалану құқығын) алып қою (сатып алу) жөніндегі жұмыстары мен қарым қатынастарын ұйымдастыру Ережелері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2006-06-28
approved_by:
- '156009000002'
version_date:
  kaz: 2006-06-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/29497/kaz/28.06.2006
