act_code: '13498'
requisite: Решение акима Атырауской области от 10 сентября 2002 года № 487. Зарегистрировано Управлением юстиции Атырауской области 16 октября 2002 года за № 1158
title:
  rus: О регулировании деятельности по ввозу, вывозу, реализации и использованию нефтепродуктов в Атырауской области
  kaz: О регулировании деятельности по ввозу, вывозу, реализации и использованию нефтепродуктов в Атырауской области
form: РЕШ
type_codes:
- РЕШ
approved_on: 2002-09-09
approved_by:
- '156000000003'
version_date:
  rus: 2002-09-09
source:
  rus: https://zan.gov.kz/client/#!/doc/13498/rus/09.09.2002
