act_code: '25503'
requisite: Постановление Атырауского областного акимата от 27 сентября 2005 года № 36. Зарегистрировано Департаментом юстиции Атырауской области 10 октября 2005 года № 2447
title:
  rus: О подготовке призывников по военно-техническим срециальностям по Атырауской области в 2005-2006 учебном году
  kaz: 2005-2006 оқу жылында Атырау облысы бойынша әскерге шақырылушыларды әскери-техникалық мамандықтарға даярлау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2005-09-27
approved_by:
- '156000000001'
version_date:
  kaz: 2005-09-27
  rus: 2005-09-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/25503/kaz/27.09.2005
  rus: https://zan.gov.kz/client/#!/doc/25503/rus/27.09.2005
