act_code: '170243'
requisite: Решение акима Махамбетского района Атырауской области от 25 июля 2022 года № 54. Зарегистрировано в Министерстве юстиции Республики Казахстан 1 августа 2022 года № 28972
title:
  rus: Об объявлении чрезвычайной ситуации природного характера местного масштаба на территории Махамбетского района
  kaz: Махамбет ауданы аумағында жергілікті ауқымдағы табиғи сипаттағы төтенше жағдайды жариялау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-07-25
approved_by:
- '156004000003'
version_date:
  kaz: 2022-07-25
  rus: 2022-07-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/170243/kaz/25.07.2022
  rus: https://zan.gov.kz/client/#!/doc/170243/rus/25.07.2022
