act_code: '112462'
requisite: Решение акима Кировского сельского округа Курмангазинского района Атырауской области от 2 мая 2017 года № 21. Зарегистрировано Департаментом юстиции Атырауской области 30 мая 2017 года № 3866
title:
  rus: О присвоении наименовании улицам села Хиуаз, Большой Куйген, Шагырлы, Жасарал сельского округа Жанаталап
  kaz: Жаңаталап ауылдық округіндегі Хиуаз, Үлкен Күйген, Шағырлы, Жасарал ауылдарындағы көшелерге атау беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2017-05-02
approved_by:
- '156003017002'
version_date:
  kaz: 2018-06-18
  rus: 2018-06-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/112462/kaz/18.06.2018
  rus: https://zan.gov.kz/client/#!/doc/112462/rus/18.06.2018
caused_by:
  code: '123243'
  requisite: Решение акима сельского округа Жанаталап Курмангазинского района Атырауской области от 18 июня 2018 года № 25. Зарегистрировано Департаментом юстиции Атырауской области 5 июля 2018 года № 4188
  title:
    rus: О внесении изменений в решение акима сельского округа от 02 мая 2017 года № 21 «О присвоении наименовании улицам села Дашино, Большой Куйген, Шагырлы, Жасарал Кировского сельского округа»
    kaz: Ауылдық округ әкімінің 2017 жылғы 02 мамырдағы № 21 «Киров ауылдық округіндегі Дәшін, Үлкен Күйген, Шағырлы, Жасарал ауылдарындағы көшелерге атау беру туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/123243/rus
