act_code: '187276'
requisite: Решение Жылыойского районного маслихата Атырауской области от 16 октября 2023 года № 8-1. Зарегистрировано в Департаменте юстиции Атырауской области 17 октября 2023 года № 5094-06
title:
  rus: Об утверждении правил оказания социальной помощи, установления ее размеров и определения перечня отдельных категорий нуждающихся граждан
  kaz: Әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың қағидаларын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2023-10-16
approved_by:
- '156009000002'
version_date:
  kaz: 2024-07-04
  rus: 2024-07-04
source:
  kaz: https://zan.gov.kz/client/#!/doc/187276/kaz/04.07.2024
  rus: https://zan.gov.kz/client/#!/doc/187276/rus/04.07.2024
caused_by:
  code: '198531'
  requisite: Решение Жылыойского районного маслихата Атырауской области от 4 июля 2024 года № 20-1. Зарегистрировано в Департаменте юстиции Атырауской области 5 июля 2024 года № 5215-06
  title:
    rus: О внесении изменений в решение Жылыойского районного маслихата от 16 октября 2023 года № 8-1 «Об утверждении правил оказания социальной помощи, установления ее размеров и определения перечня отдельных категорий нуждающихся граждан»
    kaz: Жылыой аудандық мәслихатының 2023 жылғы 16 қазандағы № 8-1 «Әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың қағидаларын бекіту туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/198531/rus
