act_code: '182884'
requisite: Решение Индерского районного маслихата Атырауской области от 6 июня 2023 года № 23-VIII. Зарегистрировано в Департаменте юстиции Атырауской области 13 июня 2023 года № 5035-06
title:
  rus: Об утверждении норм образования и накопления коммунальных отходов по Индерскому району
  kaz: Индер ауданы бойынша коммуналдық қалдықтардың түзілу және жинақталу нормаларын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2023-06-06
approved_by:
- '156008000002'
version_date:
  kaz: 2023-06-06
  rus: 2023-06-06
source:
  kaz: https://zan.gov.kz/client/#!/doc/182884/kaz/06.06.2023
  rus: https://zan.gov.kz/client/#!/doc/182884/rus/06.06.2023
