act_code: '80990'
requisite: Решение от 25.06.2014 №20-3, Маслихат Жылыойского района. Утратило силу решением Жылыойского районного маслихата Атырауской области от 18 сентября 2015 года № 32-3.
title:
  rus: О назначении материального обеспечения детям-инвалидам, обучающимся на дому
  kaz: Үйде оқитын мүгедек балаларға материалдық қамсыздандыруды тағайындау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2014-06-25
approved_by:
- '156009000002'
version_date:
  kaz: 2014-06-25
  rus: 2014-06-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/80990/kaz/25.06.2014
  rus: https://zan.gov.kz/client/#!/doc/80990/rus/25.06.2014
