act_code: '37864'
requisite: Атырау облысы Исатай ауданы әкімінің 2008 жылғы 1 ақпандағы № 5 шешімі. Атырау облысының Әділет департаменті Исатай ауданының Әділет басқармасында 2008 жылғы 14 ақпанда № 4-4-92 болып тіркелді
title:
  rus: Исатай ауданының 1991 жылы туылған азаматтарын 2008 жылы шақыру учаскелеріне тіркеуді жүргізу туралы
  kaz: Исатай ауданының 1991 жылы туылған азаматтарын 2008 жылы шақыру учаскелеріне тіркеуді жүргізу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-02-01
approved_by:
- '156005000003'
version_date:
  kaz: 2008-02-01
source:
  kaz: https://zan.gov.kz/client/#!/doc/37864/kaz/01.02.2008
