act_code: '219424'
requisite: Решение Кызылкогинского районного маслихата Атырауской области от 15 декабря 2025 года № 36-3
title:
  rus: О районном бюджете на 2026-2028 годы
  kaz: 2026-2028 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2025-12-15
approved_by:
- '156007000002'
version_date:
  kaz: 2025-12-15
  rus: 2025-12-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/219424/kaz/15.12.2025
  rus: https://zan.gov.kz/client/#!/doc/219424/rus/15.12.2025
