act_code: '168046'
requisite: Решение Исатайского районного маслихата Атырауской области от 20 мая 2022 года № 134-VІI. Отменен решением Исатайского районного маслихата Атырауской области от 27 апреля 2023 года № 12-VIII (вводится в действие со дня его первого официального опубликования)
title:
  rus: Об утверждении Положения государственного учреждения «Аппарат Исатайского районного маслихата»
  kaz: «Исатай аудандық мәслихатының аппараты» мемлекеттік мекемесінің Ережесін бекіту туралы
form: РЕШ
type_codes:
- ПОЛ
- РЕШ
approved_on: 2022-05-20
approved_by:
- '156005000002'
version_date:
  kaz: 2022-05-20
  rus: 2022-05-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/168046/kaz/20.05.2022
  rus: https://zan.gov.kz/client/#!/doc/168046/rus/20.05.2022
