act_code: '194557'
requisite: Решение Индерского районного маслихата Атырауской области от 18 марта 2024 года № 83-VIII. Зарегистрировано в Департаменте юстиции Атырауской области 19 марта 2024 года № 5153-06. Утратило силу решением Индерского районного маслихата Атырауской области от 20 апреля 2026 года № 215-VIII (вводится в действие с 01.01.2026)
title:
  rus: О понижении размера ставки налогов при применении специального налогового режима розничного налога по Индерскому району
  kaz: Индер ауданы бойынша бөлшек салықтың арнаулы салық режимін қолдану кезінде салық мөлшерлемесінің мөлшерін төмендету туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-03-18
approved_by:
- '156008000002'
version_date:
  kaz: 2024-03-18
  rus: 2024-03-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/194557/kaz/18.03.2024
  rus: https://zan.gov.kz/client/#!/doc/194557/rus/18.03.2024
