act_code: '83797'
requisite: Решение Атырауского областного маслихата от 10 сентября 2014 года № 314-V. Зарегистрировано Департаментом юстиции Атырауской области 21 октября 2014 года № 3018.  Утратило силу решением маслихата Атырауской области от 17 февраля 2016 года № 474-V.
title:
  rus: Об утверждении правил подготовки и проведения отопительного сезона в Атырауской области
  kaz: Атырау облысында жылу маусымына дайындық және оны өткізу Қағидасын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2014-09-10
approved_by:
- '156000000002'
version_date:
  kaz: 2014-09-10
  rus: 2014-09-10
source:
  kaz: https://zan.gov.kz/client/#!/doc/83797/kaz/10.09.2014
  rus: https://zan.gov.kz/client/#!/doc/83797/rus/10.09.2014
