act_code: '7085'
requisite: Решение акима Атырауской области от 11 апреля 2000 года № 434. Зарегистрировано Управлением юстиции Атырауской области 18 августа 2000 года за № 255. Утратило силу постановлением акима Атырауской области от 20 декабря 2004 года № 248
title:
  rus: О предоставлении права на промысловый лов рыбы и закрепление рыбохозяйственных водоемов (участков)
  kaz: Балық аулау кәсіпшілігі құқығын және балық шаруашылығы су айдындарын (телімдерін) бекітіп беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2000-04-11
approved_by:
- '156000000003'
version_date:
  rus: 2000-04-10
source:
  rus: https://zan.gov.kz/client/#!/doc/7085/rus/10.04.2000
