act_code: '197231'
requisite: Решение Индерского районного маслихата Атырауской области от 28 мая 2024 года № 93-VIII. Зарегистрировано в Департаменте юстиции Атырауской области 31 мая 2024 года № 5199-06
title:
  rus: Об определении размера и порядка оказания жилищной помощи в Индерском районе
  kaz: Индер ауданында тұрғын үй көмегін көрсетудің мөлшері мен тәртібін айқындау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-05-28
approved_by:
- '156008000002'
version_date:
  kaz: 2024-05-28
  rus: 2024-05-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/197231/kaz/28.05.2024
  rus: https://zan.gov.kz/client/#!/doc/197231/rus/28.05.2024
