act_code: '196256'
requisite: Решение Курмангазинского районного маслихата Атырауской области от 25 апреля 2024 года № 127-VIII. Зарегистрировано в Департаменте юстиции Атырауской области 30 апреля 2024 года № 5189-06
title:
  rus: Об определении размера и порядка оказания жилищной помощи в Курмангазинском районе
  kaz: Құрманғазы ауданында тұрғын үй көмегін көрсетудің мөлшері мен тәртібін айқындау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-04-25
approved_by:
- '156003000002'
version_date:
  kaz: 2024-04-25
  rus: 2024-04-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/196256/kaz/25.04.2024
  rus: https://zan.gov.kz/client/#!/doc/196256/rus/25.04.2024
