act_code: '76526'
requisite: Решение Курмангазинского районного маслихата Атырауской области от 11 декабря 2013 года № 252-V. Зарегистрировано Департаментом юстиции Атырауской области 13 января 2014 года № 2836. Утратило силу решением Курмангазинского районного маслихата Атырауской области от 3 февраля 2015 года № 375-V
title:
  rus: Об утверждении районного бюджета на 2014 - 2016 годы
  kaz: Ауданның 2014 - 2016 жылдарға арналған бюджетін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2013-12-11
approved_by:
- '156003000002'
version_date:
  kaz: 2014-07-23
  rus: 2014-07-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/76526/kaz/23.07.2014
  rus: https://zan.gov.kz/client/#!/doc/76526/rus/23.07.2014
caused_by:
  code: '81782'
  requisite: Решение Курмангазинского районного маслихата Атырауской области от 23 июля 2014 года № 314-V. Зарегистрировано Департаментом юстиции Атырауской области 7 августа 2014 года № 2955. Утратило силу решением Курмангазинского районного маслихата Атырауской области от 3 февраля 2015 года № 375-V
  title:
    rus: О внесении изменений и дополнений в решение районного маслихата от 11 декабря 2013 года № 252-V "Об утверждении районного бюджета на 2014-2016 годы"
    kaz: Аудандық мәслихаттың 2013 жылғы 11 желтоқсандағы №252-V "Ауданнық 2014-2016 жылдарға арналған бюджетін бекіту туралы" шешіміне өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/81782/rus
