act_code: '6815'
requisite: Решение акима Атырауской области от 27 января 2000 года № 331а Зарегистрировано Управлением юстиции Атырауской области 28 июля 2000 года за № 280
title:
  rus: Об утверждении правил финансирования государственного заказа
  kaz: Об утверждении правил финансирования государственного заказа
form: РЕШ
type_codes:
- РЕШ
approved_on: 2000-01-27
approved_by:
- '156000000001'
version_date:
  rus: 2000-07-23
source:
  rus: https://zan.gov.kz/client/#!/doc/6815/rus/23.07.2000
