act_code: '121795'
requisite: Решение акима Атырауского сельского округа города Атырау Атырауской области от 11 мая 2018 года № 239. Зарегистрировано Департаментом юстиции Атырауской области 15 мая 2018 года № 4152. Утратило силу решением Атырауского сельского округа города Атырау Атырауской области от 3 июля 2018 года № 351
title:
  rus: Об установлении карантина
  kaz: Карантин белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-05-11
approved_by:
- '156002003002'
version_date:
  kaz: 2018-05-11
  rus: 2018-05-11
source:
  kaz: https://zan.gov.kz/client/#!/doc/121795/kaz/11.05.2018
  rus: https://zan.gov.kz/client/#!/doc/121795/rus/11.05.2018
