act_code: '36893'
requisite: Решение Атырауского областного маслихата от 12 декабря 2007 года № 31-IV. Зарегистрировано Департаментом юстиции Атырауской области 17 января 2008 года за № 2509. Утратило силу в соответствии с письмом Атырауского областного маслихата от 3 октября 2011 года № 275/1711/-МШ
title:
  rus: Об областном бюджете на 2008 год
  kaz: 2008 жылға арналған облыстық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2007-12-12
approved_by:
- '156000000002'
version_date:
  kaz: 2007-12-12
  rus: 2007-12-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/36893/kaz/12.12.2007
  rus: https://zan.gov.kz/client/#!/doc/36893/rus/12.12.2007
