act_code: '36893'
requisite: Решение Атырауского областного маслихата от 12 декабря 2007 года № 31-IV. Зарегистрировано Департаментом юстиции Атырауской области 17 января 2008 года за № 2509. Утратило силу в соответствии с письмом Атырауского областного маслихата от 3 октября 2011 года № 275/1711/-МШ
title:
  rus: Об областном бюджете на 2008 год
  kaz: 2008 жылға арналған облыстық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2007-12-12
approved_by:
- '156000000002'
version_date:
  kaz: 2008-07-23
  rus: 2008-07-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/36893/kaz/23.07.2008
  rus: https://zan.gov.kz/client/#!/doc/36893/rus/23.07.2008
caused_by:
  code: '41440'
  requisite: Решение Атырауского областного маслихата от 23 июля 2008 года № 106-IV. Зарегистрировано Департаментом юстиции Атырауской области 29 августа 2008 года за № 2533. Утратило силу - письмом Атырауского областного маслихата от 3.10.2011 года № 275/1711/-МШ
  title:
    rus: О внесении изменений и дополнений в решение III сессии областного маслихата от 12 декабря 2007 года № 31-IV "Об областном бюджете на 2008 год"
    kaz: Облыстық мәслихаттың 2007 жылғы 12 желтоқсандағы III сессиясындағы № 31-IV "2008 жылғa арналған облыстық бюджет туралы" шешіміне өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/41440/rus
