act_code: '140114'
requisite: Решение Исатайского районного маслихата Атырауской области от 28 февраля 2020 года № 291-VI. Зарегистрировано Департаментом юстиции Атырауской области 10 марта 2020 года № 4607. Утратило силу решением Исатайского районного маслихата Атырауской области от 27 апреля 2023 года № 11-VIII (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении регламентов собраний местного сообщества сельских округов Исатайского района
  kaz: Исатай ауданының ауылдық округтердегі жергілікті қоғамдастық жиналыстарының регламенттерін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-02-28
approved_by:
- '156005000002'
version_date:
  kaz: 2020-02-28
  rus: 2020-02-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/140114/kaz/28.02.2020
  rus: https://zan.gov.kz/client/#!/doc/140114/rus/28.02.2020
