act_code: '50056'
requisite: Решение маслихата Макатского района Атырауской области от 21 декабря 2009 года № 184-IV . Зарегистрировано Управлением юстиции Макатского района Атырауской области 18 января 2010 года № 4-7-110. Утратило силу решением Макатского районного маслихата Атырауской области от 22 февраля 2011 года № 277-IV
title:
  rus: 2010-2012 жылдарға арналған аудандық бюджет туралы
  kaz: 2010-2012 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-12-21
approved_by:
- '156006000002'
version_date:
  kaz: 2009-12-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/50056/kaz/21.12.2009
