act_code: '14887'
requisite: Решение акима Атырауской области от 11 февраля 2003 года № 8. Зарегистрировано Департаментом юстиции Атырауской области 17 марта 2003 года № 1351
title:
  rus: Об организации и проведении предупредительных мероприятий по защите области от весеннего паводка 2003 года
  kaz: 2003 жылғы көктемгі су тасқынынан облысты қорғау жөніндегі сақтық іс-шараларын жүргізу және ұйымдастыру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2003-02-11
approved_by:
- '156000000003'
version_date:
  kaz: 2003-02-11
  rus: 2003-02-11
source:
  kaz: https://zan.gov.kz/client/#!/doc/14887/kaz/11.02.2003
  rus: https://zan.gov.kz/client/#!/doc/14887/rus/11.02.2003
