act_code: '123941'
requisite: Решение акима Куздыгаринского сельского округа Кызылкогинского района Атырауской области от 27 июля 2018 года № 07. Зарегистрировано Департаментом юстиции Атырауской области 1 августа 2018 года № 4212
title:
  rus: Об утрате силы решения акима Куздыгаринского сельского округа от 12 апреля 2018 года № 3 «Об установлении ограничительных мероприятий»
  kaz: Көздіғара ауылдық округі әкімінің 2018 жылғы 12 сәуірдегі № 3 «Шектеу іс-шараларын белгілеу туралы» шешімінің күшін жою туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-07-27
approved_by:
- '156007005002'
version_date:
  kaz: 2018-07-27
  rus: 2018-07-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/123941/kaz/27.07.2018
  rus: https://zan.gov.kz/client/#!/doc/123941/rus/27.07.2018
