act_code: '32180'
requisite: Атырау облысы Мақат аудандық мәслихатының 2007 жылғы 9 ақпандағы № 308-ІІІ шешімі. Атырау облысы Мақат аудандық Әділет басқармасында 2007 жылғы 28 ақпанда № 4-7-53 болып тіркелді
title:
  rus: 2007 жылға жеке кәсіпкерлік, заңды тұлға, оның бөлімдері, құрылымдары және басқа жекеленген структуралық бөлімшелер көрсеткен қызметіне ойын    бизнесі саласында тіркелген жиынтық салық ставка мөлшері туралы
  kaz: 2007 жылға жеке кәсіпкерлік, заңды тұлға, оның бөлімдері, құрылымдары және басқа жекеленген структуралық бөлімшелер көрсеткен қызметіне ойын    бизнесі саласында тіркелген жиынтық салық ставка мөлшері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2007-02-09
approved_by:
- '156006000002'
version_date:
  kaz: 2007-02-09
source:
  kaz: https://zan.gov.kz/client/#!/doc/32180/kaz/09.02.2007
