act_code: '5818'
requisite: II сайланған Атырау облыстық мәслихаты III сессиясының 2000 жылғы 2 наурыздағы № 38-II шешімі. Атырау облысының Әділет департаментінде 2000 жылғы 18 сәуірде № 178 болып тіркелді
title:
  rus: '"Атырау облысының аз қамтылған азаматтарына (отбасыларына) 2000 жылы атаулы әлеуметтік көмек көрсету туралы" облыс әкімінің 2000 жылғы  24 ақпандағы № 360 шешімі'
  kaz: '"Атырау облысының аз қамтылған азаматтарына (отбасыларына) 2000 жылы атаулы әлеуметтік көмек көрсету туралы" облыс әкімінің 2000 жылғы  24 ақпандағы № 360 шешімі'
form: РЕШ
type_codes:
- РЕШ
approved_on: 2000-03-02
approved_by:
- '156000000002'
version_date:
  kaz: 2000-03-02
source:
  kaz: https://zan.gov.kz/client/#!/doc/5818/kaz/02.03.2000
