act_code: '18512'
requisite: Атырау облыстық мәслихатының ІІІ сессиясының 2003 жылғы 12 желтоқсандағы № 30-ІІІ шешімі. Атырау облысының Әділет департаментінде 2004 жылғы 22 қаңтарда № 1829 болып тіркелді. Күші жойылды - Атырау облыстық мәслихаттың 2011 жылғы 29 шілдедегі № 448-II шешiмімен
title:
  rus: Атырау облысы өңiрiне құрылыс салу ережесiн бекiту туралы
  kaz: Атырау облысы өңiрiне құрылыс салу ережесiн бекiту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2003-12-12
approved_by:
- '156000000002'
version_date:
  kaz: 2003-12-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/18512/kaz/12.12.2003
