act_code: '128346'
requisite: Решение Кызылкогинского районного маслихата Атырауской области от 29 декабря 2018 года № XXXI-2. Зарегистрировано Департаментом юстиции Атырауской области 8 января 2019 года № 4317
title:
  rus: Об утверждении бюджетов сельских округов Кызылкогинского района на 2019-2021 годы
  kaz: 2019-2021 жылдарға арналған Қызылқоға ауданының ауылдық округтерінің бюджеттерін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-12-29
approved_by:
- '156007000002'
version_date:
  kaz: 2019-10-24
  rus: 2019-10-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/128346/kaz/24.10.2019
  rus: https://zan.gov.kz/client/#!/doc/128346/rus/24.10.2019
caused_by:
  code: '135727'
  requisite: Решение Кызылкогинского районного маслихата Атырауской области от 24 октября 2019 года № XLIII-1. Зарегистрировано Департаментом юстиции Атырауской области 31 октября 2019 года № 4519
  title:
    rus: О внесении изменений в решение Кызылкогинского районного маслихата от 29 декабря 2018 года № ХХХІ-2 «Об утверждении бюджетов сельских округов Кызылкогинского района на 2019-2021 годы»
    kaz: Қызылқоға аудандық мәслихатының 2018 жылғы 29 желтоқсандағы № ХХХІ-2 «2019-2021 жылдарға арналған Қызылқоға ауданының ауылдық округтерінің бюджеттерін бекіту туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/135727/rus
