act_code: '227002'
requisite: Решение Атырауского областного маслихата от 19 июня 2026 года № 240-VIII
title:
  rus: О дополнительном предоставлении гарантированного объема бесплатной медицинской помощи, в том числе лекарственных средств, специализированных лечебных продуктов, медицинских изделий, отдельным категориям граждан Атырауской области при амбулаторном лечении бесплатно и (или) на льготных условиях
  kaz: Атырау облысы азаматтарының жекелеген санаттарына амбулаторлық емдеу кезінде тегін және (немесе) жеңілдікті шарттармен тегін медициналық көмектің кепілдік берілген көлемін, оның ішінде дәрілік заттарды, арнайы емдік өнімдерді, медициналық бұйымдарды қосымша беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2026-06-19
approved_by:
- '156000000002'
version_date:
  kaz: 2026-06-19
  rus: 2026-06-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/227002/kaz/19.06.2026
  rus: https://zan.gov.kz/client/#!/doc/227002/rus/19.06.2026
