act_code: '12485'
requisite: Атырау облыстық мәслихаты екінші сайланған ХVI сессиясының 2002 жылғы 6 ақпандағы № 190-II шешімі. Атырау облысының Әділет басқармасында 2002 жылғы 2 сәуiрде № 876 болып тіркелді. Күші жойылды - Атырау облыстық мәслихаттың 2011 жылғы 29 шілдедегі № 448-II шешiмімен
title:
  rus: Мүгедек балаларын үйiнде оқытатын және тәрбиелейтін отбасыларына материалдық көмек төлеу туралы
  kaz: Мүгедек балаларын үйiнде оқытатын және тәрбиелейтін отбасыларына материалдық көмек төлеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2002-02-06
approved_by:
- '156000000002'
version_date:
  kaz: 2002-02-06
source:
  kaz: https://zan.gov.kz/client/#!/doc/12485/kaz/06.02.2002
