act_code: '4447'
requisite: Решение акима Атырауской области от 26 августа 1999 года № 180. Зарегистрировано Управлением юстиции Атырауской области 20 октября 1999 года № 108. Утратило силу постановлением акима Атырауской области от 20 декабря 2004 года № 248
title:
  rus: О пособиях на детей-инвалидов, воспитывающихся и обучающихся на дому
  kaz: О пособиях на детей-инвалидов, воспитывающихся и обучающихся на дому
form: РЕШ
type_codes:
- РЕШ
approved_on: 1999-08-25
approved_by:
- '156000000001'
version_date:
  rus: 1999-08-25
source:
  rus: https://zan.gov.kz/client/#!/doc/4447/rus/25.08.1999
