act_code: '128226'
requisite: Решение Махамбетского районного маслихата Атырауской области от 28 декабря 2018 года № 303. Зарегистрировано Департаментом юстиции Атырауской области 9 января 2019 года № 4321
title:
  rus: О бюджете сельских округов на  2019-2021 годы
  kaz: 2019–2021 жылдарға арналған ауылдық округтердің бюджеттері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-12-28
approved_by:
- '156004000002'
version_date:
  kaz: 2019-03-29
  rus: 2019-03-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/128226/kaz/29.03.2019
  rus: https://zan.gov.kz/client/#!/doc/128226/rus/29.03.2019
caused_by:
  code: '130106'
  requisite: Решение Махамбетского районного маслихата Атырауской области от 29 марта 2019 года № 329. Зарегистрировано Департаментом юстиции Атырауской области 3 апреля 2019 года № 4371
  title:
    rus: О внесении изменений и дополнений в решение Махамбетского районного маслихата от 28 декабря 2018 года № 303 «О бюджете сельских округов на 2019-2021 годы»
    kaz: Махамбет аудандық мәслихаттың 2018 жылғы 28 желтоқсандағы № 303 «2019-2021 жылдарға арналған ауылдық округтердің бюджеттері туралы» шешіміне өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/130106/rus
