act_code: '43753'
requisite: Атырау қалалық Мәслихатының 2008 жылғы 15 желтоқсандағы № 93 шешімі. Атырау қалалық Әділет басқармасында 2009 жылғы 23 қаңтарда № 4-1-97 тіркелді
title:
  rus: 2009 жылға арналған қала бюджеті туралы
  kaz: 2009 жылға арналған қала бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-12-15
approved_by:
- '156002000002'
version_date:
  kaz: 2009-10-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/43753/kaz/23.10.2009
caused_by:
  code: '48987'
  requisite: Атырау қалалық мәслихатының 2009 жылғы 23 қазандағы № 145 шешімі. Атырау қалалық Әділет басқармасында 2009 жылғы 1 желтоқсанда ақпанда № 4-1-107 тіркелді
  title:
    rus: Қалалық Мәслихаттың 2008 жылғы 15 желтоқсандағы № 93 "2009 жылға арналған қала бюджеті туралы" шешіміне өзгерістер мен толықтырулар енгізу туралы
    kaz: Қалалық Мәслихаттың 2008 жылғы 15 желтоқсандағы № 93 "2009 жылға арналған қала бюджеті туралы" шешіміне өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/48987/rus
