act_code: '43753'
requisite: Атырау қалалық Мәслихатының 2008 жылғы 15 желтоқсандағы № 93 шешімі. Атырау қалалық Әділет басқармасында 2009 жылғы 23 қаңтарда № 4-1-97 тіркелді
title:
  rus: 2009 жылға арналған қала бюджеті туралы
  kaz: 2009 жылға арналған қала бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-12-15
approved_by:
- '156002000002'
version_date:
  kaz: 2008-12-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/43753/kaz/15.12.2008
