act_code: '44622'
requisite: Атырау қалалық Мәслихатының 2009 жылғы 21 қаңтардағы № 108 шешімі. Атырау қалалық Әділет басқармасында 2009 жылғы 28 ақпанда № 4-1-99 тіркелді. Күші жойылды - Атырау қалалық мәслихатының 2010 жылғы 3 ақпандағы N 175 шешімімен
title:
  rus: Атырау қаласы бойынша 2009 жылға салық ставкаларын бекіту туралы
  kaz: Атырау қаласы бойынша 2009 жылға салық ставкаларын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-01-21
approved_by:
- '156002000002'
version_date:
  kaz: 2009-01-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/44622/kaz/21.01.2009
