act_code: '181585'
requisite: Решение Курмангазинского районного маслихата Атырауской области от 17 мая 2023 года № 18-VIII
title:
  rus: Об утверждении Положения государственного учреждения «Аппарат Курмангазинского районного Маслихата»
  kaz: «Құрманғазы аудандық Маслихатының аппараты» мемлекеттік мекемесінің Ережесін бекіту туралы
form: РЕШ
type_codes:
- ПОЛ
- РЕШ
approved_on: 2023-05-17
approved_by:
- '156003000002'
version_date:
  kaz: 2023-05-17
  rus: 2023-05-17
source:
  kaz: https://zan.gov.kz/client/#!/doc/181585/kaz/17.05.2023
  rus: https://zan.gov.kz/client/#!/doc/181585/rus/17.05.2023
