act_code: '14670'
requisite: Екінші сайланған Атырау облыстық мәслихаты ХХІ сессиясының 2002 жылғы 6 желтоқсандағы № 265-II шешімі. Атырау облысының Әділет басқармасында 2002 жылғы 25 желтоқсанда № 1244 болып тіркелді. Күші жойылды - Атырау облысы әкімінің 2008 жылғы 12 қарашадағы № 132-ІХ шешімімен
title:
  rus: '"Атырау облысының 2003-2010 жылдардағы "Ауыз сулар" Аймақтық бағдарламасын бекіту туралы'
  kaz: '"Атырау облысының 2003-2010 жылдардағы "Ауыз сулар" Аймақтық бағдарламасын бекіту туралы'
form: РЕШ
type_codes:
- РЕШ
approved_on: 2002-12-06
approved_by:
- '156000000002'
version_date:
  kaz: 2006-10-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/14670/kaz/18.10.2006
