act_code: '37803'
requisite: Атырау облысы Құрманғазы аудандық мәслихатының 2007 жылғы 21 желтоқсандағы № 36-III шешімі. Атырау облысы Әділет департаменті Құрманғазы ауданының Әділет басқармасында 2008 жылғы 26 қаңтарда № 4-8-123 болып тіркелді
title:
  rus: Аз қамтылған отбасыларына (азаматтарға) тұрғын үйді ұстауға және коммуналдық қызметтерді тұтынуға төлем төлеуге тұрғын үй көмегін көрсету тәртібін бекіту туралы
  kaz: Аз қамтылған отбасыларына (азаматтарға) тұрғын үйді ұстауға және коммуналдық қызметтерді тұтынуға төлем төлеуге тұрғын үй көмегін көрсету тәртібін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2007-12-21
approved_by:
- '156003000002'
version_date:
  kaz: 2007-12-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/37803/kaz/21.12.2007
