act_code: '156964'
requisite: Решение акима Курмангазинского района Атырауской области от 12 июля 2021 года № 26. Зарегистрировано в Министерстве юстиции Республики Казахстан 13 июля 2021 года № 23481
title:
  rus: Об образовании избирательных участков на территории Курмангазинского района
  kaz: Құрманғазы ауданы аумағында сайлау учаскелерін құру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-07-12
approved_by:
- '156003000003'
version_date:
  kaz: 2026-02-06
  rus: 2026-02-06
source:
  kaz: https://zan.gov.kz/client/#!/doc/156964/kaz/06.02.2026
  rus: https://zan.gov.kz/client/#!/doc/156964/rus/06.02.2026
caused_by:
  code: '221951'
  requisite: Решение акима Курмангазинского района Атырауской области от 3 февраля 2026 года № 3
  title:
    rus: О внесении изменении в решение акима Курмангазинского района от 12 июля 2021 года № 26 «Об образовании избирательных участков на территории Курмангазинского района»
    kaz: Құрманғазы ауданы әкімінің 2021 жылғы 12 шілдедегі № 26 «Құрманғазы ауданы аумағында сайлау учаскелерін құру туралы» шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/221951/rus
