act_code: '3497'
requisite: Решение акима Атырауской области от 29 октября 1998 года № 732. Зарегистрировано Управлением юстиции Атырауской области 3 декабря 1998 года за № 30
title:
  rus: О мерах по реализации реформы бухгалтерского учета в области
  kaz: О мерах по реализации реформы бухгалтерского учета в области
form: РЕШ
type_codes:
- РЕШ
approved_on: 1998-10-29
approved_by:
- '156000000001'
version_date:
  rus: 1998-10-29
source:
  rus: https://zan.gov.kz/client/#!/doc/3497/rus/29.10.1998
