act_code: '147308'
requisite: Решение Макатского районного маслихата Атырауской области от 28 сентября 2020 года № 402-VI. Зарегистрировано Департаментом юстиции Атырауской области 12 октября 2020 года № 4755. Утратило силу решением Макатского районного маслихата Атырауской области от 26 мая 2022 года № 113-VІI (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: О повышении базовых ставок земельного налога на земли сельскохозяйственного назначения, не используемые в соответствии с земельным законодательством Республики Казахстан в Макатском районе
  kaz: Қазақстан Республикасының жер заңнамасына сәйкес Мақат ауданында пайдаланылмайтын ауыл шаруашылығы мақсатындағы жерлерге жер салығының базалық мөлшерлемелерін арттыру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-09-28
approved_by:
- '156006000002'
version_date:
  kaz: 2020-09-28
  rus: 2020-09-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/147308/kaz/28.09.2020
  rus: https://zan.gov.kz/client/#!/doc/147308/rus/28.09.2020
