act_code: '68199'
requisite: Решение Жылыойского районного маслихата Атырауской области от 5 октября 2012 года № 6-14. Зарегистрировано Департаментом юстиции Атырауской области 29 октября 2012 года № 2637. Утратило силу - решением Жылыойского районного маслихата Атырауской области от 7 февраля 2013 года № 10-12
title:
  rus: Об определении отдельных категорий нуждающихся граждан района на 2012 год
  kaz: 2012 жылғы ауданның мұқтаж азаматтарының жекелеген санаттарын айқындау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2012-10-05
approved_by:
- '156009000002'
version_date:
  kaz: 2012-10-05
  rus: 2012-10-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/68199/kaz/05.10.2012
  rus: https://zan.gov.kz/client/#!/doc/68199/rus/05.10.2012
