act_code: '50855'
requisite: Решение маслихата Макатского района Атырауской области от 9 февраля 2010 года № 197-IV . Зарегистрировано Управлением юстиции Макатского района Атырауской области 23 февраля 2010 года № 4-7-113
title:
  rus: Аудан бойынша 2010 жылға ара-тұра сипаттағы кәсіпкерлік қызмет түрлеріне берілетін бір жолғы талон құнының мөлшері туралы
  kaz: Аудан бойынша 2010 жылға ара-тұра сипаттағы кәсіпкерлік қызмет түрлеріне берілетін бір жолғы талон құнының мөлшері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-02-09
approved_by:
- '156006000002'
version_date:
  kaz: 2010-02-09
source:
  kaz: https://zan.gov.kz/client/#!/doc/50855/kaz/09.02.2010
