act_code: '122864'
requisite: Решение Исатайского районного маслихата Атырауской области от 6 июня 2018 года № 160-VI. Зарегистрировано Департаментом юстиции Атырауской области 18 июня 2018 года № 4169. Утратило силу решением Исатайского районного маслихата Атырауской области от 27 апреля 2023 года № 11-VIII (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении регламентов собраний местного сообщества сельских округов Исатайского района
  kaz: Исатай ауданының ауылдық округтердегі жергілікті қоғамдастық жиналыстарының регламенттерін бекіту туралы
form: РЕШ
type_codes:
- РЕГЛ
- РЕШ
approved_on: 2018-06-06
approved_by:
- '156005000002'
version_date:
  kaz: 2018-06-06
  rus: 2018-06-06
source:
  kaz: https://zan.gov.kz/client/#!/doc/122864/kaz/06.06.2018
  rus: https://zan.gov.kz/client/#!/doc/122864/rus/06.06.2018
