act_code: '140725'
requisite: Решение акима Жемского сельского округа Жылыойского района Атырауской области от 30 марта 2020 года № 35. Зарегистрировано Департаментом юстиции Атырауской области 30 марта 2020 года № 4623
title:
  rus: О присвоении наименования улице
  kaz: Көшеге атау беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-03-30
approved_by:
- '156009001002'
version_date:
  kaz: 2020-03-30
  rus: 2020-03-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/140725/kaz/30.03.2020
  rus: https://zan.gov.kz/client/#!/doc/140725/rus/30.03.2020
