act_code: '50856'
requisite: Решение Махамбетского районного маслихата Атырауской области от 9 февраля 2010 года № 203. Зарегистрировано Управлением юстиции Махамбетского района Атырауской области 24 февраля 2010 года № 4-3-139
title:
  rus: Махамбет ауданы бойынша 2010 жылға тіркелген салық ставкасының мөлшерін белгілеу туралы
  kaz: Махамбет ауданы бойынша 2010 жылға тіркелген салық ставкасының мөлшерін белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-02-09
approved_by:
- '156004000002'
version_date:
  kaz: 2010-02-09
source:
  kaz: https://zan.gov.kz/client/#!/doc/50856/kaz/09.02.2010
