act_code: '33131'
requisite: Атырау облысы Исатай ауданы мәслихатының 2007 жылғы 16 сәуірдегі № 256-ІІІ шешімі. Атырау облысының Әділет департаментінде 2007 жылғы 7 мамырда  № 4-4-66 болып тіркелді
title:
  rus: Қызметті ара-тұра сипаттағы және базарда жасалынатын кәсіпкерлік қызмет түрлерінің тізбесі мен бір жолғы талон құнын 2007 жылға белгілеу туралы
  kaz: Қызметті ара-тұра сипаттағы және базарда жасалынатын кәсіпкерлік қызмет түрлерінің тізбесі мен бір жолғы талон құнын 2007 жылға белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2007-04-16
approved_by:
- '156005000002'
version_date:
  kaz: 2007-04-16
source:
  kaz: https://zan.gov.kz/client/#!/doc/33131/kaz/16.04.2007
