act_code: '48081'
requisite: Атырау облысы Махамбет ауданы Алмалы селолық округі әкімінің 2009 жылғы 28 тамыздағы № 53 шешімі. Атырау облысы Әділет департаменті Махамбет ауданының Әділет басқармасында 2009 жылғы 7 қазанда № 4-3-126 тіркелді. Күші жойылды - Атырау облысы Махамбет ауданы Алмалы селолық округі әкімінің 2010 жылғы 22 қарашадағы № 59 шешімімен
title:
  rus: Жаңа көшелерге атаулар беру туралы
  kaz: Жаңа көшелерге атаулар беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-08-28
approved_by:
- '156004002002'
version_date:
  kaz: 2009-08-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/48081/kaz/28.08.2009
