act_code: '69948'
requisite: Решение Макатского районного маслихата Атырауской области от 21 декабря 2012 года № 86-V. Зарегистрировано Департаментом юстиции Атырауской области 14 января 2013 года № 2669. Утратило силу - решением Макатского районного маслихата Атырауской области от 7 февраля 2014 года № 188-V
title:
  rus: О районном бюджете на 2013-2015 годы
  kaz: 2013-2015 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2012-12-21
approved_by:
- '156006000002'
version_date:
  kaz: 2013-04-23
  rus: 2013-04-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/69948/kaz/23.04.2013
  rus: https://zan.gov.kz/client/#!/doc/69948/rus/23.04.2013
caused_by:
  code: '72489'
  requisite: Решение Макатского районного маслихата Атырауской области от 23 апреля 2013 года № 112-V. Зарегистрировано Департаментом юстиции Атырауской области 8 мая 2013 года за № 2725. Утратило силу - решением Макатского районного маслихата Атырауской области от 7 февраля 2014 года № 188-V
  title:
    rus: О внесении изменений в решение районного маслихата от 21 декабря 2012 года № 86-V "О районном бюджете на 2013-2015 годы"
    kaz: Аудандық мәслихаттың 2012 жылғы 21 желтоқсандағы № 86-V "2013-2015 жылдарға арналған аудандық бюджет туралы" шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/72489/rus
