act_code: '14880'
requisite: Екінші сайланған Атырау облыстық Мәслихаты ХV сессиясының 2001 жылғы 27 желтоқсандағы № 175-II шешімі. Атырау облысының Әділет басқармасында 2002 жылғы 8 ақпанда № 774 болып тіркелді
title:
  rus: Қоршаған ортаны ластағаны үшін 2002 жылға төлем мөлшерін бекіту туралы
  kaz: Қоршаған ортаны ластағаны үшін 2002 жылға төлем мөлшерін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2001-12-27
approved_by:
- '156000000002'
version_date:
  kaz: 2001-12-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/14880/kaz/27.12.2001
