act_code: '15525'
requisite: Решение акима Атырауской области от 2 апреля 2003 года № 25. Зарегистрировано Управлением юстиции Атырауской области от 29 апреля 2003 года за № 1469
title:
  rus: О предоставлении права на промысловый лов рыб и закреплении рыбохозяйственных водоемов (участков)
  kaz: О предоставлении права на промысловый лов рыб и закреплении рыбохозяйственных водоемов (участков)
form: РЕШ
type_codes:
- РЕШ
approved_on: 2003-04-01
approved_by:
- '156000000001'
version_date:
  rus: 2003-04-01
source:
  rus: https://zan.gov.kz/client/#!/doc/15525/rus/01.04.2003
