act_code: '85262'
requisite: Решение Исатайского районного маслихата Атырауской области от 3 декабря 2014 года № 222-V. Зарегистрировано Департаментом юстиции Атырауской области 25 декабря 2014 года № 3068. Утратило силу решением Исатайского районного маслихата Атырауской области от 18 сентября 2015 года № 280-V
title:
  rus: Об утверждении правил оказания жилищной помощи малообеспеченным семьям (гражданам), проживающим в Исатайском районе
  kaz: Исатай ауданында тұратын аз қамтылған отбасыларға (азаматтарға) тұрғын үй көмегін көрсетудің қағидасын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2014-12-03
approved_by:
- '156005000002'
version_date:
  kaz: 2014-12-03
  rus: 2014-12-03
source:
  kaz: https://zan.gov.kz/client/#!/doc/85262/kaz/03.12.2014
  rus: https://zan.gov.kz/client/#!/doc/85262/rus/03.12.2014
