act_code: '85262'
requisite: Решение Исатайского районного маслихата Атырауской области от 3 декабря 2014 года № 222-V. Зарегистрировано Департаментом юстиции Атырауской области 25 декабря 2014 года № 3068. Утратило силу решением Исатайского районного маслихата Атырауской области от 18 сентября 2015 года № 280-V
title:
  rus: Об утверждении правил оказания жилищной помощи малообеспеченным семьям (гражданам), проживающим в Исатайском районе
  kaz: Исатай ауданында тұратын аз қамтылған отбасыларға (азаматтарға) тұрғын үй көмегін көрсетудің қағидасын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2014-12-03
approved_by:
- '156005000002'
version_date:
  kaz: 2015-03-20
  rus: 2015-03-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/85262/kaz/20.03.2015
  rus: https://zan.gov.kz/client/#!/doc/85262/rus/20.03.2015
caused_by:
  code: '88265'
  requisite: Решение Исатайского районного маслихата Атырауской области от 20 марта 2015 года № 241-V. Зарегистрировано Департаментом юстиции Атырауской области 6 апреля 2015 года № 3144. Утратило силу решением Исатайского районного маслихата Атырауской области от 18 сентября 2015 года № 280-V
  title:
    rus: О внесении изменений в решение районного маслихата от 3 декабря 2014 года № 222-V «Об утверждении правил оказания жилищной помощи малообеспеченным семьям (гражданам), проживающим в Исатайском районе»
    kaz: Аудандық мәслихаттың 2014 жылғы 3 желтоқсандағы № 222-V «Исатай ауданында тұратын аз қамтылған отбасыларға (азаматтарға) тұрғын үй көмегін көрсетудің қағидасын бекіту туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/88265/rus
