act_code: '31698'
requisite: Атырау облысы Атырау қалалық мәслихатының 2006 жылғы 8 желтоқсандағы № 235 шешімі. Атырау облысының Әділет департаментінде 2007 жылғы 16 қаңтарда № 4-1-49 болып тіркелді
title:
  rus: 2007 жылға арналған қала бюджеті туралы
  kaz: 2007 жылға арналған қала бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2006-12-08
approved_by:
- '156002000002'
version_date:
  kaz: 2006-12-08
source:
  kaz: https://zan.gov.kz/client/#!/doc/31698/kaz/08.12.2006
