act_code: '205029'
requisite: Решение маслихата города Атырау Атырауской области от 20 декабря 2024 года № 151
title:
  rus: О бюджете сельских округов относящихся к городу Атырау на 2025-2027 годы
  kaz: 2025-2027 жылдарға арналған Атырау қаласына қарасты ауылдық округтер бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-12-20
approved_by:
- '156002000002'
version_date:
  kaz: 2025-04-29
  rus: 2025-04-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/205029/kaz/29.04.2025
  rus: https://zan.gov.kz/client/#!/doc/205029/rus/29.04.2025
caused_by:
  code: '210025'
  requisite: Решение маслихата города Атырау Атырауской области от 29 апреля 2025 года № 168
  title:
    rus: О бюджете сельских округов относящихся к городу Атырау на 2025–2027 годы
    kaz: 2025-2027 жылдарға арналған Атырау қаласына қарасты ауылдық округтер бюджеті туралы
  link: https://zan.gov.kz/client/#!/doc/210025/rus
