act_code: '42063'
requisite: Атырау облысы Исатай ауданы Аққыстау селолық округі әкімінің 2008 жылғы 25 қыркүйектегі № 1 шешімі. Исатай аудандық Әділет басқармасында 2008 жылғы 28 қазанда № 4-4-109 болып тіркелді
title:
  rus: Аққыстау селосындағы көшелерге жаңа аттар беру туралы
  kaz: Аққыстау селосындағы көшелерге жаңа аттар беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-09-25
approved_by:
- '156005001002'
version_date:
  kaz: 2008-09-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/42063/kaz/25.09.2008
