act_code: '12017'
requisite: Решение акима Атырауской области от 1 марта 2002 года № 397. Зарегистрировано Управлением юстиции Атырауской области 4 апреля 2002 года № 894
title:
  rus: О предоставлении права на промысловый лов рыбы и закреплении рыбохозяйственных водоемов (участков)
  kaz: Кәсіптік балық аулау құқығын беру және балық шаруашылығы су айдындарын (телімдерін) бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2002-03-01
approved_by:
- '156000000003'
version_date:
  rus: 2002-07-17
source:
  rus: https://zan.gov.kz/client/#!/doc/12017/rus/17.07.2002
