act_code: '55458'
requisite: Атырау облысы Қызылқоға аудандық мәслихатының 2010 жылғы 13 қазандағы № XXII-3 шешімі. Әділет департаменті Қызылқоға ауданының Әділет басқармасында 2010 жылғы 11 қарашада № 4-5-136 тіркелді. Күші жойылды - Қызылқоға аудандық мәслихатының 2011 жылғы 11 мамырдағы № XXIX-3 шешімімен
title:
  rus: Ауылдық елді мекендерге жұмыс істеуге және тұруға келген денсаулық сақтау, білім беру, әлеуметтік қамсыздандыру, мәдениет және спорт мамандарына көтерме жәрдемақы және тұрғын үй алу үшін әлеуметтік қолдау көрсету туралы
  kaz: Ауылдық елді мекендерге жұмыс істеуге және тұруға келген денсаулық сақтау, білім беру, әлеуметтік қамсыздандыру, мәдениет және спорт мамандарына көтерме жәрдемақы және тұрғын үй алу үшін әлеуметтік қолдау көрсету туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-10-13
approved_by:
- '156007000002'
version_date:
  kaz: 2010-11-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/55458/kaz/23.11.2010
caused_by:
  code: '55729'
  requisite: Атырау облысы Қызылқоға аудандық мәслихатының 2010 жылғы 23 қарашадағы № XXIIІ-2 шешімі. Әділет департаменті Қызылқоға ауданының Әділет басқармасында 2010 жылғы 8 желтоқсанда № 4-5-138 тіркелді. Күші жойылды - Қызылқоға аудандық мәслихатының 2011 жылғы 11 мамырдағы № XXIX-3 шешімімен
  title:
    rus: Аудандық мәслихаттың 2010 жылғы 13 қазандағы № ХХІІ-3 "Ауылдық елді мекендерге жұмыс істеуге және тұруға келген денсаулық сақтау, білім беру, әлеуметтік қамсыздандыру, мәдениет және спорт мамандарына көтерме жәрдемақы және тұрғын үй алу үшін әлеуметтік қолдау көрсету туралы" шешіміне толықтырулар енгізу туралы
    kaz: Аудандық мәслихаттың 2010 жылғы 13 қазандағы № ХХІІ-3 "Ауылдық елді мекендерге жұмыс істеуге және тұруға келген денсаулық сақтау, білім беру, әлеуметтік қамсыздандыру, мәдениет және спорт мамандарына көтерме жәрдемақы және тұрғын үй алу үшін әлеуметтік қолдау көрсету туралы" шешіміне толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/55729/rus
