act_code: '18782'
requisite: Атырау облыстық мәслихатының ІІІ сессиясының 2003 жылғы 12 желтоқсандағы № 23-ІІІ шешiмi. Атырау облысының Әділет департаментінде 2004 жылғы 22 қаңтарда № 1818 болып тіркелді
title:
  rus: 2004 жылға арналған облыстық бюджет туралы
  kaz: 2004 жылға арналған облыстық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2003-12-12
approved_by:
- '156000000002'
version_date:
  kaz: 2003-12-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/18782/kaz/12.12.2003
