act_code: '46724'
requisite: Атырау облысы Құрманғазы ауданы Еңбекші селолық округі әкімінің 2009 жылғы 11 маусымдағы № 15 шешімі. Атырау облысы Әділет департаменті Құрманғазы ауданының Әділет басқармасында 2009 жылғы 23 маусымда № 4-8-152 болып тіркелді. Күші жойылды - Атырау облысы Құрманғазы ауданы Еңбекші селолық округі әкімінің 2010 жылғы 22 қазандағы № 77 шешімімен
title:
  rus: Еңбекші селолық округіне қарасты, Кадырка ауылындағы атауы жоқ көшеге Бегалиев Бауыржан Мажитұлының есімін беру туралы
  kaz: Еңбекші селолық округіне қарасты, Кадырка ауылындағы атауы жоқ көшеге Бегалиев Бауыржан Мажитұлының есімін беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-06-11
approved_by:
- '156003008002'
version_date:
  kaz: 2009-06-11
source:
  kaz: https://zan.gov.kz/client/#!/doc/46724/kaz/11.06.2009
