act_code: '129250'
requisite: Решение акима Миялинского сельского округа Кызылкогинского района Атырауской области от 20 февраля 2019 года № 31. Зарегистрировано Департаментом юстиции Атырауской области 21 февраля 2019 года № 4343
title:
  rus: Об утрате силы решения акима Миялинского сельского округа от 9 апреля 2018 года № 30 «Об установлении ограничительных мероприятий»
  kaz: Миялы ауылдық округі әкімінің 2018 жылғы 9 сәуірдегі № 30 «Шектеу іс-шараларын белгілеу туралы» шешімінің күшін жою туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-02-20
approved_by:
- '156007010002'
version_date:
  kaz: 2019-02-20
  rus: 2019-02-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/129250/kaz/20.02.2019
  rus: https://zan.gov.kz/client/#!/doc/129250/rus/20.02.2019
