act_code: '17703'
requisite: Индер аудандық мәслихатының 2003 жылғы 5 қарашадағы № 6-III шешімі. Атырау облыстық Әділет басқармасында 2003 жылғы 19 қарашада № 1708 болып тіркелді
title:
  rus: '"Индер аудандық әкімиятының 2003-2005 жылдарға арналған Индер ауданының халқы арасында йод тапшылығынан науқастанудың алдын-алу аумақтық бағдарламасы туралы" қаулысын бекіту туралы'
  kaz: '"Индер аудандық әкімиятының 2003-2005 жылдарға арналған Индер ауданының халқы арасында йод тапшылығынан науқастанудың алдын-алу аумақтық бағдарламасы туралы" қаулысын бекіту туралы'
form: РЕШ
type_codes:
- РЕШ
approved_on: 2003-11-05
approved_by:
- '156008000002'
version_date:
  kaz: 2003-11-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/17703/kaz/05.11.2003
