act_code: '158905'
requisite: Решение акима Тенизского сельского округа Курмангазинского района Атырауской области от 8 июля 2021 года № 25. Зарегистрировано в Министерстве юстиции Республики Казахстан 15 июля 2021 года № 23537. Утратило силу решением акима сельского округа Тениз Курмангазинского района Атырауской области от 20 октября 2021 года № 61 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об установлении ограничительных мероприятий
  kaz: Шектеу іс-шараларын белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-07-08
approved_by:
- '156003010002'
version_date:
  kaz: 2021-07-08
  rus: 2021-07-08
source:
  kaz: https://zan.gov.kz/client/#!/doc/158905/kaz/08.07.2021
  rus: https://zan.gov.kz/client/#!/doc/158905/rus/08.07.2021
