act_code: '56361'
requisite: Атырау қалалық мәслихатының 2010 жылғы 8 желтоқсандағы № 231 шешімі. Атырау қалалық Әділет басқармасында 2010 жылғы 30 желтоқсанда № 4-1-129 тіркелді. Күші жойылды - Атырау қалалық мәслихатының 2011 жылғы 28 желтоқсандағы № 323 шешімімен
title:
  rus: Атырау қаласы бойынша 2011 жылға салық ставкаларын бекіту туралы
  kaz: Атырау қаласы бойынша 2011 жылға салық ставкаларын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-12-08
approved_by:
- '156002000002'
version_date:
  kaz: 2010-12-08
source:
  kaz: https://zan.gov.kz/client/#!/doc/56361/kaz/08.12.2010
