act_code: '48355'
requisite: Атырау облысы Жылыой ауданы Жаңа Қаратон поселкесі әкімінің 2009 жылғы 23 қыркүйектегі № 34 шешімі. Жылыой аудандық Әділет департаментінде 2009 жылғы 30 қазанда № 4-2-132 тіркелді. Күші жойылды - Жаңа Қаратон поселкесі әкімінің 2010 жылғы 11 маусымдағы № 29 шешімімен
title:
  rus: Көше атын беру туралы
  kaz: Көше атын беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-10-23
approved_by:
- '156009003001'
version_date:
  kaz: 2009-10-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/48355/kaz/23.10.2009
