act_code: '150944'
requisite: Решение Жылыойского районного маслихата Атырауской области от 21 декабря 2020 года № 55-1. Зарегистрировано Департаментом юстиции Атырауской области 29 декабря 2020 года № 4851
title:
  rus: О бюджетах города Кульсары, поселка Жана-Каратон, сельских округов Жем, Косчагиль, Кара-Арна, Майкумген и Аккиизтогай на 2021-2023 годы
  kaz: 2021-2023 жылдарға арналған Құлсары қаласының, Жаңа-Қаратон кентінің, Жем, Қосшағыл, Қара-Арна, Майкөмген және Ақкиізтоғай ауылдық округтерінің бюджеттері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-12-21
approved_by:
- '156009000002'
version_date:
  kaz: 2021-12-10
  rus: 2021-12-10
source:
  kaz: https://zan.gov.kz/client/#!/doc/150944/kaz/10.12.2021
  rus: https://zan.gov.kz/client/#!/doc/150944/rus/10.12.2021
caused_by:
  code: '161683'
  requisite: Решение Жылыойского районного маслихата Атырауской области от 10 декабря 2021 года № 13-1
  title:
    rus: О внесении изменений в решение Жылыойского районного маслихата «О бюджетах города Кульсары, поселка Жана-Каратон, сельских округов Жем, Косчагиль, Кара-Арна, Майкумген и Аккиизтогай на 2021-2023 годы» от 21 декабря 2020 года № 55-1
    kaz: «2021-2023 жылдарға арналған Құлсары қаласының, Жаңа-Қаратон кентінің, Жем, Қосшағыл, Қара-Арна, Майкөмген және Ақкиізтоғай ауылдық округтерінің бюджеттері туралы» Жылыой аудандық мәслихатының 2020 жылғы 21 желтоқсандағы № 55-1 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/161683/rus
