act_code: '220258'
requisite: Решение Жылыойского районного маслихата Атырауской области от 23 декабря 2025 года № 41-1
title:
  rus: «О бюджетах города Кульсары, поселка Жана-Каратон, сельских округов Жем, Косчагиль, Кара-Арна, Майкумген и Аккиизтогай на 2026-2028 годы»
  kaz: «2026-2028 жылдарға арналған Құлсары қаласының, Жаңа-Қаратон кентінің, Жем, Қосшағыл, Қара-Арна, Майкөмген және Ақкиізтоғай ауылдық округтерінің бюджеттері туралы»
form: РЕШ
type_codes:
- РЕШ
approved_on: 2025-12-23
approved_by:
- '156009000002'
version_date:
  kaz: 2026-03-31
  rus: 2026-03-31
source:
  kaz: https://zan.gov.kz/client/#!/doc/220258/kaz/31.03.2026
  rus: https://zan.gov.kz/client/#!/doc/220258/rus/31.03.2026
caused_by:
  code: '223482'
  requisite: Решение Жылыойского районного маслихата Атырауской области от 31 марта 2026 года № 43-1
  title:
    rus: О внесении изменений в решение Жылыойского районного маслихата «О бюджетах города Кульсары, поселка Жана-Каратон, сельских округов Жем, Косчагиль, Кара-Арна, Майкумген и Аккиизтогай на 2026-2028 годы» от 23 декабря 2025 года № 41-1
    kaz: «2026-2028 жылдарға арналған Құлсары қаласының, Жаңа-Қаратон кентінің, Жем, Қосшағыл, Қара-Арна, Майкөмген және Ақкиізтоғай ауылдық округтерінің бюджеттері туралы» Жылыой аудандық мәслихатының 2025 жылғы 23 желтоқсандағы № 41-1 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/223482/rus
