act_code: '42720'
requisite: Атырау облысы Исатай ауданы Исатай селолық округі әкімінің 2008 жылғы 6 қарашадағы № 27 шешімі. Атырау облысының Әділет департаменті Исатай ауданының Әділет басқармасында 2008 жылғы 10 желтоқсанда № 4-4-112 тіркелді. Күші жойылды - Исатай ауданы Әділет басқармасының 2010 жылғы 15 қарашадағы № 3370 хатымен
title:
  rus: Исатай селосының көшелеріне атау беру туралы
  kaz: Исатай селосының көшелеріне атау беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-11-06
approved_by:
- '156005005002'
version_date:
  kaz: 2008-11-06
source:
  kaz: https://zan.gov.kz/client/#!/doc/42720/kaz/06.11.2008
