act_code: '95798'
requisite: Решение от 28.10.2015 №33-3, Маслихат Жылыойского района. Утратило силу решением  Жылыойского районного маслихата Атырауской области от 29 февраля 2016 года  № 37-2.
title:
  rus: О повышении ставок единого земельного налога  и ставок земельного налога на не используемые в соответствии с земельным законодательством  Республики  Казахстан земли  сельскохозяйственного назначения  в  Жылыойском  районе
  kaz: Қазақстан Республикасының жер заңнамасына  сәйкес  Жылыой ауданында пайдаланылмайтын ауыл шаруашылығы мақсатындағы  жерлерге бірыңғай жер салығының мөлшерлемелерін  және жер салығының мөлшерлемелерін  жоғарылату туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-10-28
approved_by:
- '156009000002'
version_date:
  kaz: 2015-12-24
  rus: 2015-12-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/95798/kaz/24.12.2015
  rus: https://zan.gov.kz/client/#!/doc/95798/rus/24.12.2015
caused_by:
  code: '97648'
  requisite: Решение Жылыойского районного маслихата Атырауской области от 24 декабря 2015 года № 35-13. Зарегистрировано Департаментом юстиции Атырауской области 11 января 2016 года № 3426. Утратило силу решением  Жылыойского районного маслихата Атырауской области от 29 февраля 2016 года  № 37-2.
  title:
    rus: О внесении изменений в решение районного маслихата   от  28  октября 2015 года  № 33-3  «О повышении ставок единого земельного налога  и базовых ставок  земельного налога на не используемые  в соответствии с земельным законодательством  Республики  Казахстан земли сельскохозяйственного назначения в Жылыойском  районе»
    kaz: Аудандық  мәслихаттың   2015  жылғы 28  қазандағы   №33-3 «Қазақстан Республикасының жер заңнамасына сәйкес Жылыой ауданында пайдаланылмайтын ауыл шаруашылығы мақсатындағы  жерлерге бірыңғай жер салығының мөлшерлемелерін  және базалық  жер салығының мөлшерлемелерін жоғарылату туралы»  шешіміне  өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/97648/rus
