act_code: '15679'
requisite: Решение акима Атырауской области от 6 января 2003 года № 1. Зарегистрировано Управлением юстиции Атырауской области от 17 января 2003 года № 1283
title:
  rus: О проведении приписки граждан Республики Казахстан 1986 года рождения к призывным участкам в 2003 году
  kaz: 1986 жылғы туған Қазақстан Республикасының азаматтарын 2003 жылы шақыру учаскелерінде тіркеуден өткізу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2003-01-06
approved_by:
- '156000000003'
version_date:
  kaz: 2003-01-06
  rus: 2003-01-06
source:
  kaz: https://zan.gov.kz/client/#!/doc/15679/kaz/06.01.2003
  rus: https://zan.gov.kz/client/#!/doc/15679/rus/06.01.2003
