act_code: '132627'
requisite: Решение акима Есболского сельского округа Индерского района Атырауской области от 14 июня 2019 года № 33. Зарегистрировано Департаментом юстиции Атырауской области 17 июня 2019 года № 4421
title:
  rus: О признании утратившим силу решения акима Есболского сельского округа от 15 февраля 2019 года № 8 «Об установлении ограничительных мероприятий»
  kaz: Есбол ауылдық округі әкімінің 2019 жылғы 15 ақпандағы № 8 «Шектеу іс-шараларын белгілеу туралы» шешімінің күшін жою туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-06-14
approved_by:
- '156008002002'
version_date:
  kaz: 2019-06-14
  rus: 2019-06-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/132627/kaz/14.06.2019
  rus: https://zan.gov.kz/client/#!/doc/132627/rus/14.06.2019
