act_code: '49101'
requisite: Атырау облысы Құрманғазы ауданы Көптоғай селолық округі әкімінің 2009 жылғы 8 қазандағы № 7 шешімі. Атырау облысы Әділет департаменті Құрманғазы ауданының Әділет басқармасында 2009 жылғы 12 қарашада № 4-8-165 болып тіркелді. Күші жойылды - Атырау облысы Құрманғазы ауданы Көптоғай селолық округі әкімінің 2010 жылғы 22 қазандағы № 77 шешімімен
title:
  rus: Көптоғай селолық округіне қарасты Балықшы ауылындағы атауы жоқ көшеге "Сәулет" атауын беру туралы
  kaz: Көптоғай селолық округіне қарасты Балықшы ауылындағы атауы жоқ көшеге "Сәулет" атауын беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-10-08
approved_by:
- '156003019002'
version_date:
  kaz: 2009-10-08
source:
  kaz: https://zan.gov.kz/client/#!/doc/49101/kaz/08.10.2009
