act_code: '102788'
requisite: Решение акима Аккизтогайского сельского округа Жылыойского района Атырауской области от 17 июня 2010 года № 6
title:
  rus: Об утрате силы решения акима Аккиизтогайского сельского округа №31 от 05 октября 2009 года «О присвоении наименования улицам села Аккиизтогай»
  kaz: Ақкиізтоғай селолық округі әкімінің 2009 жылғы 5 қазандағы №31 «Ақкиізтоғай селосындағы көшелерге атаулар беру туралы» шешімінің күшін жою туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-06-17
approved_by:
- '156009004001'
version_date:
  kaz: 2010-06-17
  rus: 2010-06-17
source:
  kaz: https://zan.gov.kz/client/#!/doc/102788/kaz/17.06.2010
  rus: https://zan.gov.kz/client/#!/doc/102788/rus/17.06.2010
