act_code: '155478'
requisite: Решение акима сельского округа Коптогай Курмангазинского района Атырауской области от 29 апреля 2021 года № 6. Зарегистрировано Департаментом юстиции Атырауской области 30 апреля 2021 года № 4946. Утратило силу решением акима сельского округа Коптогай Курмангазинского района Атырауской области от 26 июля 2021 года № 11 (вводится в действие со дня его первого официального опубликования)
title:
  rus: Об установлении ограничительных мероприятий
  kaz: Шектеу іс-шараларын белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-04-29
approved_by:
- '156003019002'
version_date:
  kaz: 2021-04-29
  rus: 2021-04-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/155478/kaz/29.04.2021
  rus: https://zan.gov.kz/client/#!/doc/155478/rus/29.04.2021
