act_code: '55658'
requisite: Атырау облысы Құрманғазы аудандық мәслихатының 2010 жылғы 14 қазандағы № 314-ХХХІ шешімі. Атырау облысы Әділет департаменті Құрманғазы ауданының Әділет басқармасында 2010 жылғы 26 қарашада № 4-8-193 тіркелді. Күші жойылды - Құрманғазы аудандық мәслихатының 2012 жылғы 17 мамырдағы № 54-V шешімімен
title:
  rus: Құрманғазы ауданы аумағындағы елді мекендерде иттер мен мысықтарды күтіп-ұстау мен серуендету Ережесін бекіту туралы
  kaz: Құрманғазы ауданы аумағындағы елді мекендерде иттер мен мысықтарды күтіп-ұстау мен серуендету Ережесін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-10-14
approved_by:
- '156003000002'
version_date:
  kaz: 2010-10-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/55658/kaz/14.10.2010
