act_code: '8609'
requisite: II сайланған Атырау облыстық мәслихаты VIII сессиясының 2000 жылғы 29 қарашадағы № 90-II шешімі. Атырау облысының Әділет департаментінде 2001 жылғы 5 қаңтарда № 308 болып тіркелді
title:
  rus: Нашақорлыққа және есірткі бизнесіне қарсы күрес жөніндегі аймақтық бағдарламаны және оны жүзеге асыру туралы 2000-2001 жылдардағы жоспарын бекіту туралы
  kaz: Нашақорлыққа және есірткі бизнесіне қарсы күрес жөніндегі аймақтық бағдарламаны және оны жүзеге асыру туралы 2000-2001 жылдардағы жоспарын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2000-11-29
approved_by:
- '156000000002'
version_date:
  kaz: 2000-11-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/8609/kaz/29.11.2000
