act_code: '402'
requisite: Решение акима Атырауской области от 1 августа 1997 года № 485. Зарегистрировано Управлением юстиции Атырауской области 25 марта 1998 года № 9
title:
  rus: Об утверждении Положения об областном межведомственном координационном Совете правоохранительных органов
  kaz: Об утверждении Положения об областном межведомственном координационном Совете правоохранительных органов
form: РЕШ
type_codes:
- РЕШ
approved_on: 1997-07-31
approved_by:
- '156000000001'
version_date:
  rus: 1997-07-31
source:
  rus: https://zan.gov.kz/client/#!/doc/402/rus/31.07.1997
