act_code: '14464'
requisite: Екінші сайланған Атырау облыстық мәслихаты ХХI сессиясының 2002 жылғы 6 желтоқсандағы № 266-II шешімі. Атырау облысының Әділет басқармасында 2002 жылғы 25 желтоқсанда № 1235 болып тіркелді
title:
  rus: Атырау облысында нашақорлыққа және есірткі бизнесіне қарсы күрестің 2002-2003 жылдарға арналған Бағдарламасы туралы
  kaz: Атырау облысында нашақорлыққа және есірткі бизнесіне қарсы күрестің 2002-2003 жылдарға арналған Бағдарламасы туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2002-12-06
approved_by:
- '156000000002'
version_date:
  kaz: 2002-12-06
source:
  kaz: https://zan.gov.kz/client/#!/doc/14464/kaz/06.12.2002
