act_code: '128472'
requisite: Решение Исатайского районного маслихата Атырауской области от 29 декабря 2018 года № 203-VI. Зарегистрировано Департаментом юстиции Атырауской области 10 января 2019 года № 4325
title:
  rus: О районном бюджете на 2019-2021 годы
  kaz: 2019-2021 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-12-29
approved_by:
- '156005000002'
version_date:
  kaz: 2019-03-27
  rus: 2019-03-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/128472/kaz/27.03.2019
  rus: https://zan.gov.kz/client/#!/doc/128472/rus/27.03.2019
caused_by:
  code: '130408'
  requisite: Решение Исатайского районного маслихата Атырауской области от 27 марта 2019 года № 220-VI. Зарегистрировано Департаментом юстиции Атырауской области 3 апреля 2019 года № 4369
  title:
    rus: О внесении изменений и дополнений в решение Исатайского районного маслихата от 29 декабря 2018 года № 203-VI «О районном бюджете на 2019-2021 годы»
    kaz: Исатай ауданы мәслихатының 2018 жылғы 29 желтоқсандағы № 203-VI «2019-2021 жылдарға арналған аудандық бюджет туралы» шешіміне өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/130408/rus
