act_code: '41297'
requisite: Атырау облысы Мақат аудандық поселке әкімінің 2008 жылғы 21 тамыздағы № 89 шешімі. Атырау облысының Мақат ауданының Әділет басқармасында 2008 жылғы 26 тамызда № 4-7-88 тіркелді. Күші жойылды - Мақат ауданы Мақат поселке әкімінің 2010 жылғы 1 қарашадағы № 142 шешімімен
title:
  rus: Мақат поселкесінің көшесіне "Бекжанов Сәтқұлдың" есімін беру туралы
  kaz: Мақат поселкесінің көшесіне "Бекжанов Сәтқұлдың" есімін беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-08-21
approved_by:
- '156006001001'
version_date:
  kaz: 2008-08-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/41297/kaz/21.08.2008
