act_code: '50156'
requisite: Атырау облысы Қызылқоға аудандық мәслихатының 2009 жылғы 23 желтоқсандағы № XVI-1 шешімі. Әділет департаменті Қызылқоға ауданының Әділет басқармасында 2010 жылғы 25 қаңтарында № 4-5-120 тіркелді. Күші жойылды - Атырау облысы Қызылқоға аудандық мәслихатының 2013 жылғы 19 сәуірдегі № ХІІІ-4 шешімімен
title:
  rus: 2010-2012 жылдарға арналған аудандық бюджет туралы
  kaz: 2010-2012 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-12-23
approved_by:
- '156007000002'
version_date:
  kaz: 2010-02-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/50156/kaz/05.02.2010
caused_by:
  code: '51113'
  requisite: Атырау облысы Қызылқоға аудандық мәслихатының 2010 жылғы 5 ақпандағы № XVII-2 шешімі. Әділет департаменті Қызылқоға ауданының Әділет басқармасында 2010 жылғы 12 наурызда № 4-5-123 тіркелді. Күші жойылды - Атырау облысы Қызылқоға аудандық мәслихатының 2013 жылғы 19 сәуірдегі № ХІІІ-4 шешімімен
  title:
    rus: Қызылқоға аудандық мәслихатының 2009 жылғы 23 желтоқсандағы "2010-2012 жылдарға арналған аудандық бюджет туралы" № XVI-1 шешіміне өзгерістер мен толықтырулар енгізу туралы
    kaz: Қызылқоға аудандық мәслихатының 2009 жылғы 23 желтоқсандағы "2010-2012 жылдарға арналған аудандық бюджет туралы" № XVI-1 шешіміне өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/51113/rus
