act_code: '50156'
requisite: Атырау облысы Қызылқоға аудандық мәслихатының 2009 жылғы 23 желтоқсандағы № XVI-1 шешімі. Әділет департаменті Қызылқоға ауданының Әділет басқармасында 2010 жылғы 25 қаңтарында № 4-5-120 тіркелді. Күші жойылды - Атырау облысы Қызылқоға аудандық мәслихатының 2013 жылғы 19 сәуірдегі № ХІІІ-4 шешімімен
title:
  rus: 2010-2012 жылдарға арналған аудандық бюджет туралы
  kaz: 2010-2012 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-12-23
approved_by:
- '156007000002'
version_date:
  kaz: 2010-04-16
source:
  kaz: https://zan.gov.kz/client/#!/doc/50156/kaz/16.04.2010
caused_by:
  code: '52614'
  requisite: Атырау облысы Қызылқоға аудандық мәслихатының 2010 жылғы 16 сәуірдегі № XVIII-2 шешімі. Әділет департаменті Қызылқоға ауданының Әділет басқармасында 2010 жылғы 24 мамырда № 4-5-125 тіркелді. Күші жойылды - Атырау облысы Қызылқоға аудандық мәслихатының 2013 жылғы 19 сәуірдегі № ХІІІ-4 шешімімен
  title:
    rus: Қызылқоға аудандық мәслихатының 2009 жылғы 23 желтоқсандағы "2010-2012 жылдарға арналған аудандық бюджет туралы" № XVI-1 шешіміне өзгерістер мен толықтырулар енгізу туралы
    kaz: Қызылқоға аудандық мәслихатының 2009 жылғы 23 желтоқсандағы "2010-2012 жылдарға арналған аудандық бюджет туралы" № XVI-1 шешіміне өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/52614/rus
