act_code: '138178'
requisite: Решение Макатского районного маслихата Атырауской области от 23 декабря 2019 года № 339-VI. Зарегистрировано Департаментом юстиции Атырауской области 9 января 2020 года № 4568
title:
  rus: О районном бюджете на 2020-2022 годы
  kaz: 2020-2022 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-12-23
approved_by:
- '156006000002'
version_date:
  kaz: 2019-12-23
  rus: 2019-12-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/138178/kaz/23.12.2019
  rus: https://zan.gov.kz/client/#!/doc/138178/rus/23.12.2019
