act_code: '138178'
requisite: Решение Макатского районного маслихата Атырауской области от 23 декабря 2019 года № 339-VI. Зарегистрировано Департаментом юстиции Атырауской области 9 января 2020 года № 4568
title:
  rus: О районном бюджете на 2020-2022 годы
  kaz: 2020-2022 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-12-23
approved_by:
- '156006000002'
version_date:
  kaz: 2020-09-28
  rus: 2020-09-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/138178/kaz/28.09.2020
  rus: https://zan.gov.kz/client/#!/doc/138178/rus/28.09.2020
caused_by:
  code: '147196'
  requisite: Решение Макатского районного маслихата Атырауской области от 28 сентября 2020 года № 400-VI. Зарегистрировано Департаментом юстиции Атырауской области 8 октября 2020 года № 4750
  title:
    rus: О внесении изменений в решение районного маслихата от 23 декабря 2019 года № 339-VI «О районном бюджете на 2020-2022 годы»
    kaz: Аудандық мәслихаттың 2019 жылғы 23 желтоқсандағы № 339-VI «2020-2022 жылдарға арналған аудандық бюджет туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/147196/rus
