act_code: '83736'
requisite: Решение Жылыойского районного маслихата Атырауской области от 25 сентября 2014 года № 23-7. Зарегистрировано Департаментом юстиции Атырауской области 15 октября 2014 года № 3017. Утратило силу решением Жылыойского районного маслихата Атырауской области от 20 декабря 2023 года № 10-6 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении правил проведения раздельных сходов местного сообщества и определения количества представителей жителей микрорайона, улицы, многоквартирного жилого дома для участия в сходе местного сообщества на территории города Кульсары
  kaz: Құлсары қаласы аумағында жергілікті қоғамдастықтың бөлек жиындарын өткізу және жергілікті қоғамдастық жиынына қатысу үшін шағын аудан, көше, көппәтерлі тұрғын үй тұрғындары өкілдерінің санын айқындау қағидасын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2014-09-25
approved_by:
- '156009000002'
version_date:
  kaz: 2016-09-15
  rus: 2016-09-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/83736/kaz/15.09.2016
  rus: https://zan.gov.kz/client/#!/doc/83736/rus/15.09.2016
caused_by:
  code: '106838'
  requisite: Решение Жылыойского районного маслихата Атырауской области от 15 сентября 2016 года № 5-3. Зарегистрировано Департаментом юстиции Атырауской области 6 октября 2016 года № 3630. Утратило силу решением Жылыойского районного маслихата Атырауской области от 20 декабря 2023 года № 10-6 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
  title:
    rus: О внесении изменения в решение районного маслихата от 25 сентября 2014 года №23-7 «Об утверждении правил проведения раздельных сходов местного сообщества и определения количества представителей жителей улицы, многоквартирного жилого дома для участия в сходе местного сообщества на территории города Кульсары»
    kaz: Аудандық мәслихаттың 2014 жылғы 25 қыркүйектегі №23-7 «Құлсары қаласы аумағында бөлек жергілікті қоғамдастық жиындарын өткізу және жергілікті қоғамдастық жиынына қатысу үшін көше, көппәтерлі тұрғын үй тұрғындары өкілдерінің санын айқындау қағидасын бекіту туралы» шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/106838/rus
