act_code: '146055'
requisite: Решение Исатайского районного маслихата Атырауской области от 21 августа 2020 года № 324-VI. Зарегистрировано Департаментом юстиции Атырауской области 4 сентября 2020 года № 4714. Утратило силу решением Исатайского районного маслихата Атырауской области от 27 апреля 2023 года № 11-VIII (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении регламента собраний местного сообщества Зинеденского сельского округа Исатайского района
  kaz: Исатай ауданы Зинеден ауылдық округінің жергілікті қоғамдастық жиналысының регламентін бекіту туралы
form: РЕШ
type_codes:
- РЕГЛ
- РЕШ
approved_on: 2020-08-21
approved_by:
- '156005000002'
version_date:
  kaz: 2021-10-25
  rus: 2021-10-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/146055/kaz/25.10.2021
  rus: https://zan.gov.kz/client/#!/doc/146055/rus/25.10.2021
caused_by:
  code: '159781'
  requisite: Решение Исатайского районного маслихата Атырауской области от 25 октября 2021 года № 80-VII. Утратило силу решением Исатайского районного маслихата Атырауской области от 27 апреля 2023 года № 11-VIII (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
  title:
    rus: О внесении изменений в решение Исатайского районного маслихата Атырауской области от 21 августа 2020 года № 324 "Об утверждении регламента собраний местного сообщества Зинеденского сельского округа Исатайского района"
    kaz: Атырау облысы Исатай аудандық мәслихатының 2020 жылғы 21 тамыздағы № 324 «Исатай ауданы Зинеден ауылдық округінің жергілікті қоғамдастық жиналысының регламентін бекіту туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/159781/rus
