act_code: '11913'
requisite: Решение ХV сессии Атырауского областного Маслихата второго созыва от 27 декабря 2001 года N 177-II зарегистрировано управлением юстиции Атырауской области 31 января 2002 года за N 746.  Утратило силу решением маслихата Атырауской области от 17 февраля 2016 года № 474-V
title:
  rus: О переводе делопроизводства на государственный язык в Атырауской области
  kaz: Атырау облысында iс жүргiзудi мемлекеттiк тiлге көшiру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2001-12-27
approved_by:
- '156000000002'
version_date:
  kaz: 2001-12-27
  rus: 2001-12-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/11913/kaz/27.12.2001
  rus: https://zan.gov.kz/client/#!/doc/11913/rus/27.12.2001
