act_code: '88935'
requisite: Решение Атырауского городского маслихата Атырауской области от 27 марта 2015 года № 268. Зарегистрировано Департаментом юстиции Атырауской области 16 апреля 2015 года № 3176
title:
  rus: О предоставлении права льготного проезда для обучающихся и воспитанников на общественном транспорте (кроме такси)
  kaz: Білім алушылар мен тәрбиеленушілерге қоғамдық көлікте (таксиден басқа) жеңілдікпен жол жүру құқығын беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-03-27
approved_by:
- '156002000002'
version_date:
  kaz: 2015-03-27
  rus: 2015-03-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/88935/kaz/27.03.2015
  rus: https://zan.gov.kz/client/#!/doc/88935/rus/27.03.2015
