act_code: '85671'
requisite: Решение от 25.12.2014 №26-7, Маслихат Жылыойского района. Утратило силу решением Жылыойского районного маслихата Атырауской области от 18 сентября 2015 года № 32-3.
title:
  rus: О предоставлении социальной помощи на приобретение топлива специалистам государственных  организаций социального  обеспечения, образования,  культуры, спорта и ветеринарии,проживающим и работающим в сельских населенных  пунктах  Жылыойского района
  kaz: Жылыой  ауданының  ауылдық  елді мекендерде  тұратын  және жұмыс істейтін мемлекеттік  әлеуметтік қамсыздандыру, білім беру, мәдениет,спорт  және   ветеринария   ұйымдарының мамандарына  отын  сатып  алу үшін әлеуметтік  көмек  беру  туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2014-12-25
approved_by:
- '156009000002'
version_date:
  kaz: 2014-12-25
  rus: 2014-12-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/85671/kaz/25.12.2014
  rus: https://zan.gov.kz/client/#!/doc/85671/rus/25.12.2014
