act_code: '15717'
requisite: Екінші сайланған Атырау облыстық мәслихатының кезектен тыс ХХІ сессиясының 2002 жылғы 6 желтоқсандағы № 263-II шешімі. Атырау облыстық Әділет басқармасында 2002 жылғы 25 ақпанда № 1238 болып тіркелді
title:
  rus: Атырау облысының 2003-2005 жылдарға арналған аграрлық азық-түлік бағдарламасын бекіту туралы
  kaz: Атырау облысының 2003-2005 жылдарға арналған аграрлық азық-түлік бағдарламасын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2002-12-06
approved_by:
- '156000000002'
version_date:
  kaz: 2002-12-06
source:
  kaz: https://zan.gov.kz/client/#!/doc/15717/kaz/06.12.2002
