act_code: '153634'
requisite: Решение Атырауского областного маслихата от 15 марта 2021 года № 31-VІI. Зарегистрировано Департаментом юстиции Атырауской области 19 марта 2021 года № 4899
title:
  rus: Об определении системы мер социальной поддержки медицинских и фармацевтических работников
  kaz: Медицина және фармацевтика қызметкерлерін әлеуметтік қолдау шараларының жүйесін айқындау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-03-15
approved_by:
- '156000000002'
version_date:
  kaz: 2021-03-15
  rus: 2021-03-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/153634/kaz/15.03.2021
  rus: https://zan.gov.kz/client/#!/doc/153634/rus/15.03.2021
