act_code: '43389'
requisite: Атырау облысы Жылыой аудандық мәслихатының 2008 жылғы 24 желтоқсандағы № 8-3 шешімі Жылыой аудандық Әділет басқармасында 2009 жылғы 14 қаңтарда № 4-2-106 тіркелді
title:
  rus: 2009 жылға арналған аудандық бюджет туралы
  kaz: 2009 жылға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-12-24
approved_by:
- '156009000002'
version_date:
  kaz: 2008-12-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/43389/kaz/24.12.2008
