act_code: '119539'
requisite: Решение акима Акжайыкского сельского округа Махамбетского района Атырауской области от 5 марта 2018 года № 5. Зарегистрировано Департаментом юстиции Атырауской области 16 марта 2018 года № 4073. Утратило силу решением акима Акжайыкского сельского округа Махамбетского района Атырауской области от 3 июля 2018 года № 11
title:
  rus: Об установлении ограничительных мероприятий
  kaz: Шектеу іс-шараларын белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-03-05
approved_by:
- '156004005002'
version_date:
  kaz: 2018-03-05
  rus: 2018-03-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/119539/kaz/05.03.2018
  rus: https://zan.gov.kz/client/#!/doc/119539/rus/05.03.2018
