act_code: '50227'
requisite: Атырау қалалық мәслихатының 2009 жылғы 11 желтоқсандағы № 154 шешімі. Атырау қалалық Әділет басқармасында 2010 жылғы 22 қаңтарда № 4-1-109 тіркелді. Күші жойылды - Атырау қалалық мәслихатының 2013 жылғы 26 сәуірдегі № 120 шешімімен
title:
  rus: 2010-2012 жылдарға арналған қала бюджеті туралы
  kaz: 2010-2012 жылдарға арналған қала бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-12-11
approved_by:
- '156002000002'
version_date:
  kaz: 2009-12-11
source:
  kaz: https://zan.gov.kz/client/#!/doc/50227/kaz/11.12.2009
