act_code: '129552'
requisite: Решение акима Бейбарыского сельского округа Махамбетского района Атырауской области от 11 марта 2019 года № 9. Зарегистрировано Департаментом юстиции Атырауской области 12 марта 2019 года № 4347. Утратило силу решением акима Бейбарыского сельского округа Махамбетского района Атырауской области от 29 августа 2019 года № 55 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об установлении ограничительных мероприятий
  kaz: Шектеу іс-шараларын белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-03-11
approved_by:
- '156004006002'
version_date:
  kaz: 2019-03-11
  rus: 2019-03-11
source:
  kaz: https://zan.gov.kz/client/#!/doc/129552/kaz/11.03.2019
  rus: https://zan.gov.kz/client/#!/doc/129552/rus/11.03.2019
