act_code: '17750'
requisite: III сайланған Атырау облыстық мәслихаты I сессиясының 2003 жылғы 26 қыркүйектегі № 13-II шешімі. Атырау облысының Әділет басқармасында 2003  жылғы 7 қарашада № 1703 болып тіркелді
title:
  rus: 2004 жылға қоршаған ортаны ластаудың төлем мөлшерлемелерін бекіту туралы
  kaz: 2004 жылға қоршаған ортаны ластаудың төлем мөлшерлемелерін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2003-09-25
approved_by:
- '156000000002'
version_date:
  kaz: 2003-09-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/17750/kaz/25.09.2003
