act_code: '31716'
requisite: Атырау облысы Исатай ауданы әкімінің 2006 жылғы 13 желтоқсандағы № 289 шешімі. Атырау облысының Әділет департаменті Исатай ауданының Әділет басқармасында 2006 жылғы 22 желтоқсанда № 4-4-60 болып тіркелді
title:
  rus: Исатай ауданының 1990 жылы туылған азаматтарын 2007 жылы шақыру учасклеріне тіркеу жүргізу туралы
  kaz: Исатай ауданының 1990 жылы туылған азаматтарын 2007 жылы шақыру учасклеріне тіркеу жүргізу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2006-12-13
approved_by:
- '156005000003'
version_date:
  kaz: 2006-12-13
source:
  kaz: https://zan.gov.kz/client/#!/doc/31716/kaz/13.12.2006
