act_code: '205680'
requisite: Решение Исатайского районного маслихата Атырауской области от 27 декабря 2024 года № 139-VIII
title:
  rus: Об утверждении бюджетов сельских округов Исатайского района на 2025-2027 годы
  kaz: 2025-2027 жылдарға арналған Исатай ауданының ауылдық округтерінің бюджеттерін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-12-27
approved_by:
- '156005000002'
version_date:
  kaz: 2024-12-27
  rus: 2024-12-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/205680/kaz/27.12.2024
  rus: https://zan.gov.kz/client/#!/doc/205680/rus/27.12.2024
