act_code: '190727'
requisite: Постановление акимата Махамбетского района Атырауской области от 29 декабря 2023 года № 339
title:
  rus: О мерах по совершенствованию системы управления Махамбетского района
  kaz: Махамбет ауданының мемлекеттік басқару жүйесін жетілдіру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2023-12-29
approved_by:
- '156004000001'
version_date:
  kaz: 2023-12-29
  rus: 2023-12-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/190727/kaz/29.12.2023
  rus: https://zan.gov.kz/client/#!/doc/190727/rus/29.12.2023
