act_code: '197659'
requisite: Решение Кызылкогинского районного маслихата Атырауской области от 12 июня 2024 года № 18-7. Зарегистрировано в Департаменте юстиции Атырауской области 13 июня 2024 года № 5203-06
title:
  rus: О некоторых вопросах проведения мирных собраний
  kaz: Бейбіт жиналыстар өткізудің кейбір мәселелері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-06-12
approved_by:
- '156007000002'
version_date:
  kaz: 2024-06-12
  rus: 2024-06-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/197659/kaz/12.06.2024
  rus: https://zan.gov.kz/client/#!/doc/197659/rus/12.06.2024
