act_code: '52071'
requisite: Атырау қалалық мәслихатының 2010 жылғы 9 сәуірдегі № 190 шешімі. Атырау қалалық Әділет басқармасында 2010 жылғы 27 сәуірде № 4-1-116 тіркелді. Атырау қалалық мәслихатының 2011 жылғы 18 тамыздағы № 300 шешімімен
title:
  rus: Отын сатып алу үшін бір жолғы әлеуметтік көмек көрсету туралы
  kaz: Отын сатып алу үшін бір жолғы әлеуметтік көмек көрсету туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-04-09
approved_by:
- '156002000002'
version_date:
  kaz: 2010-04-09
source:
  kaz: https://zan.gov.kz/client/#!/doc/52071/kaz/09.04.2010
